### ISSUE TITLE
Electron app can't start

### ISSUE THREAD

**Issue by brunomariani** [lovell/sharp#1009]
Hi!
Many thanks for this great sharp library!

Trying to build an Electron app for resize images using sharp...
But app throws an error during load.

Error: The module '/Users/brunomariani/luan-p1/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brunomariani/luan-p1/node_modules/sharp/lib/constructor.js:9:15)
    at Object.<anonymous> (/Users/brunomariani/luan-p1/node_modules/sharp/lib/constructor.js:234:3)

Please, could you help me pointing how to solve this?
Already tried nom rebuild, but still not working...

Best regards,

Bruno.

**Comment by lovell** [comment]
Different versions of Node are being used at `npm install` time vs runtime.

Did you see https://electron.atom.io/docs/tutorial/using-native-node-modules/ and https://github.com/electron/electron-rebuild ?

**Comment by brunomariani** [comment]
OK, it worked!
Great library and great support!
Many thanks!

This link also helped a lot: https://dev.to/onmyway133/dealing-with-nodemoduleversion-in-electron
