### ISSUE TITLE
Installation failed  node.js 8.9.1 MacOS High Sierra 10.13.1 (17B48)

### ISSUE THREAD

**Issue by ickeep** [lovell/sharp#1031]
Installation failed 

node.js 8.9.1 
MacOS High Sierra 10.13.1 (17B48)

```
[3/3] ⠐ sharp: gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp
[-/3] ⠐ waiting...
error /www/rsstu.com/node.rsstu.com/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /www/rsstu.com/node.rsstu.com/node_modules/sharp
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/www/rsstu.com/node.rsstu.com/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/keep/.node-gyp/8.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/keep/.node-gyp/8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/keep/.node-gyp/8.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/www/rsstu.com/node.rsstu.com/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17/rbconfig.rb:214: warning: Insecure world writable dir /www in PATH, mode 040777
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /www/rsstu.com/node.rsstu.com/node_modules/sharp
```

**Comment by lovell** [comment]
Hello, is xcode installed and working correctly? Could another dependency of `node.rsstu.com` be overriding the `which` command? Perhaps see https://github.com/Automattic/node-canvas/issues/630#issuecomment-173862077

**Comment by niftylettuce** [comment]
I also have same issue.  @lovell I constantly get install errors on stock Ubuntu and Mac platforms.  Happened on Node v7.x, 8.x, and now 9.x.  XCode was installed and all other requirements were installed.  There is also a ton of confusion for Mac still https://github.com/lovell/sharp/issues/939.  Overall, sharp is not stable and this should be put as a notice in the root of repo.  I will be using alternative until this is stable... I appreciate your work though

**Comment by lovell** [comment]
Native modules, such as sharp, often expose problems with mis-configured or conflicting local development environments. I'm always happy to try to help as best I can. >90% of the issues reported here relate to easily-fixable local environment problems.

This problem looks like an unrelated dependency is overriding the OS `which` command.

The problem reported by the only other commenter on #939 turned out to be an already-fixed libvips problem, please see #937.

For Node 9 support please see #1008.

**Comment by lovell** [comment]
@ickeep To help diagnose this problem, are you able to share the response of running `npm ls which` ?

**Comment by ickeep** [comment]
I am very sorry, reply now

**Comment by ickeep** [comment]
I am very sorry, reply now
I am upgrading the system
Causes Command Line Tools to fail
run:  xcode-select --install 
is ok
