### ISSUE TITLE
Failed at the sharp@0.18.4 install script.

### ISSUE THREAD

**Issue by iamdubx** [lovell/sharp#1055]
Hi. I can't install `sharp` on Xubuntu

```
make: Entering directory '/home/ssss/CODE/cryptomag.online/api-cms-server/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
make: g++: Command not found
sharp.target.mk:119: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 127
make: Leaving directory '/home/ssss/CODE/cryptomag.online/api-cms-server/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.10.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ssss/CODE/cryptomag.online/api-cms-server/node_modules/sharp
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN api-cms-server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ssss/.npm/_logs/2017-12-07T16_39_32_377Z-debug.log
```
I tried to run with `--unsafe-perm`, didn't help.

node v8.9.2

**Comment by lovell** [comment]
Please ensure the [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) are installed. `g++: Command not found` suggests you need to run `sudo apt-get install build-essential`.
