### ISSUE TITLE
Error npm installing on Node 4.3.0

### ISSUE THREAD

**Issue by patriciali** [lovell/sharp#1074]
I'm getting the following error when I try to npm install:

```
$ npm install sharp
WARN engine sharp@0.18.4: wanted: {"node":">=4.5.0"} (current: {"node":"4.3.0","npm":"2.14.12"})
WARN engine tar@3.2.1: wanted: {"node":">=4.5"} (current: {"node":"4.3.0","npm":"2.14.12"})
-
> sharp@0.18.4 install /Users/patricia/dev/HelloTest/node_modules/sharp
> node-gyp rebuild

/Users/patricia/dev/HelloTest/node_modules/sharp/node_modules/tar/lib/pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/Users/patricia/dev/HelloTest/node_modules/sharp/node_modules/tar/lib/pack.js:32:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/patricia/dev/HelloTest/node_modules/sharp/node_modules/tar/lib/create.js:6:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
gyp: Call to 'GLOBAL_VIPS_VERSION="" node -e "require('./binding').use_global_vips()"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patricia/dev/HelloTest/node_modules/sharp
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/patricia/dev/HelloTest/npm-debug.log
```

I have also attached the contents of npm-debug.log:
[npm-debug.log](https://github.com/lovell/sharp/files/1580431/npm-debug.log)

From the error message, I'm guessing the issue is that I'm on Node 4.3.0, and [Buffer.alloc](https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe) was added in v6. Is there a workaround for the issue? (Other than upgrading to a more recent version of Node. Unfortunately, that decision is above my paygrade.)

**Comment by lovell** [comment]
Hello, `Buffer.alloc` was added in Node 4.5.0 so this is the minimum required version. 
```
WARN engine sharp@0.18.4: wanted: {"node":">=4.5.0"} (current: {"node":"4.3.0","npm":"2.14.12"})
```
I recommend you upgrade to at least the latest on the 4 line of releases, currently 4.8.7.

By insisting on Node 4.3.0, the people a pay grade above you are exposing your organisation to a number of high severity vulnerabilities, for example:

https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/
https://nodejs.org/en/blog/vulnerability/oct-2017-dos/
https://nodejs.org/en/blog/vulnerability/september-2016-security-releases/
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

Feel free to show them this - good luck! :)

**Comment by patriciali** [comment]
We've since upgraded to Node 8, but no longer need to use sharp. C'est la vie...
