### ISSUE TITLE
"Latin extended"-character in node-gyp path

### ISSUE THREAD

**Issue by alestrunda** [lovell/sharp#1083]
`LINK : fatal error LNK1181: cannot open input file 'C:\Users\Ale?\.node-gyp\9.3.0\x64\node.lib' [D:\Web\bakery\node_modules\sharp\build\libvips-cpp.vcxproj]
`

I have "š" in my username so path 'C:\Users\Ale?\' does not exist, it should be 'C:\Users\Aleš\'

I was trying to install _gatsby-remark-images_, but `node-gyp rebuild` is what's failing and it seems to me it's _sharp_ issue - `npm install sharp --save` fails exactly the same way

```
npm install --save gatsby-remark-images

> sharp@0.17.3 install D:\Web\bakery\node_modules\sharp
> node-gyp rebuild


D:\Web\bakery\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1181: cannot open input file 'C:\Users\Ale?\.node-gyp\9.3.0\x64\node.lib' [D:\Web\bakery\node_modules\sharp\build\libvips-cpp.vcxproj
]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Web\bakery\node_modules\sharp
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script.
```

Thanks

**Comment by lovell** [comment]
Hello, sadly this is a long-standing gyp problem that affects native modules - see https://github.com/nodejs/node-gyp/pull/1203 for the latest discussion.

Please also see #1008 for forthcoming Node 9 support.
