### ISSUE TITLE
Module version mismatch. Expected 48, got 59

### ISSUE THREAD

**Issue by molipha** [lovell/sharp#1102]
Hi. I applied the regular software (ubuntu) updates today and now my program is broken with the above message. Here is the stack trace...
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 59.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/michael/Development/ Current Project/httplistener/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

The sharp reinstall shows sharp@0.19.0
nodejs -v: 6.12.3

Doing all the usual stuff like uninstalling and reinstalling doesn't seem to help me.

**Comment by lovell** [comment]
Hello, `npm rebuild` will recompile all native modules for the new major version of Node you're now using.

If this doesn't work, please see the previous reports - https://github.com/lovell/sharp/search?utf8=%E2%9C%93&q=%22Module+version+mismatch%22&type=Issues
