### ISSUE TITLE
Error building sharp

### ISSUE THREAD

**Issue by coffeebite** [lovell/sharp#1112]
I'm getting the following error while trying to build in a docker container:

```
error /app/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /app/node_modules/sharp
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack   File "/usr/lib/python2.7/site.py", line 1
gyp ERR! stack SyntaxError: Non-ASCII character '\xa7' in file /usr/lib/python2.7/site.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/nodejs/bin/node" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by lovell** [comment]
Hello, the error is:

> SyntaxError: Non-ASCII character '\xa7' in file /usr/lib/python2.7/site.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

...which suggests file encodings are somehow incorrect within the Python installation itself.

This is very unlikely to be a sharp problem and much more likely to be specific to your linuxkit-aufs environment so StackOverflow is your friend here. Good luck!
