### ISSUE TITLE
ld: can't map file, errno=22 file '/usr/local/opt/libffi/lib' for architecture x86_64

### ISSUE THREAD

**Issue by woss** [lovell/sharp#1133]
Hi,

This is the error I get when I try to install `sharp`.  
I'm really not sure WHY  it's failing. I've been googling but no luck with this error.

Longer error output:
```
┌─( ~/P/S/f/s/publish )─────────────────────────────────────────────────────────────────────────────────( @woss-io )─┐
(sync-photos) └─❱❱❱ yarn add sharp                                                                    +10464 18:47 ❰─┘
yarn add v1.3.2
warning package.json: No license field
warning ../../package.json: No license field
warning sensio-service@1.0.0: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > simple-progress-webpack-plugin@1.0.4" has incorrect peer dependency "webpack@>=2.0.0 <3.0.0".
[4/4] 📃  Building fresh packages...
[1/5] ⡀ fsevents: ok
[-/5] ⡀ waiting...
[5/5] ⡀ serverless
[4/5] ⡀ sharp: CXX(target) Release/obj.target/sharp/src/utilities.o
error /Users/danijel/Projects/SyncPhotos/faas/services/publish/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/danijel/Projects/SyncPhotos/faas/services/publish/node_modules/sharp
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.10.3 | darwin | x64
gyp info spawn /Users/danijel/anaconda3/envs/sync-photos/bin/python2
gyp info spawn args [ '/Users/danijel/n/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/danijel/Projects/SyncPhotos/faas/services/publish/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/danijel/n/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/danijel/.node-gyp/6.10.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/danijel/.node-gyp/6.10.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/danijel/n/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/danijel/Projects/SyncPhotos/faas/services/publish/node_modules/sharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/sharp.node
ld: can't map file, errno=22 file '/usr/local/opt/libffi/lib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/sharp.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/danijel/n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/danijel/n/bin/node" "/Users/danijel/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/danijel/Projects/SyncPhotos/faas/services/publish/node_modules/sharp
```

And for tree of the directory in question is:

```
(sync-photos) └─❱❱❱ tree /usr/local/opt/libffi/lib                                               1 ⏎  +10468 18:51 ❰─┘
/usr/local/opt/libffi/lib
├── libffi-3.2.1
│   └── include
│       ├── ffi.h
│       └── ffitarget.h
├── libffi.6.dylib
├── libffi.a
├── libffi.dylib -> libffi.6.dylib
└── pkgconfig
    └── libffi.pc

3 directories, 6 files
```

I hope someone can help me because i'd really like to use this package over GM or IM.

Thanks in advance,
D

**Comment by lovell** [comment]
Hello, is vips installed via homebrew? Does `brew update && brew upgrade` fix this?

**Comment by woss** [comment]
Hello @lovell, unfortunately not. 
I remember reading somewhere on github you posted that question, something related to, maybe photoBooth??? In any case, I've updated/upgraded packages and still having the same issue. worth mentioning I did `rm -rf node_modules` just to be sure :)
In case you are interested in `brew info libffi`

```
libffi: stable 3.2.1 (bottled), HEAD [keg-only]
Portable Foreign Function Interface library
https://sourceware.org/libffi/
/usr/local/Cellar/libffi/3.0.13 (15 files, 374.7KB)
  Poured from bottle on 2016-09-13 at 16:49:45
/usr/local/Cellar/libffi/3.2.1 (16 files, 297.0KB)
  Poured from bottle on 2017-05-21 at 17:17:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libffi.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/libffi/lib
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/libffi/lib/pkgconfig
```

**Comment by lovell** [comment]
Thanks, my best guess would be that there's a bad path being passed to pkg-config via the logic [here](https://github.com/lovell/sharp/blob/master/binding.gyp#L59).

What is `PKG_CONFIG_PATH` set to, if anything?
What does `brew --env` report as the value for `PKG_CONFIG_LIBDIR`, if anything?
What does running `pkg-config --libs vips-cpp` produce?

**Comment by woss** [comment]
```
└─❱❱❱ echo $PKG_CONFIG_PATH
/usr/local/opt/libffi/lib/pkgconfig
```

```
└─❱❱❱ brew --env 
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin
```
```
└─❱❱❱ pkg-config --libs vips-cpp
-L/usr/local/Cellar/vips/8.6.2/lib -L/usr/local/Cellar/glib/2.54.3/lib -L/usr/local/opt/gettext/lib -lvips-cpp -lvips -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
```
I hope you dont mind me pasting it like this, it's well structured IMHO

**Comment by lovell** [comment]
Thanks, that all seems fairly sensible.

Please can you provide the command the linker is using at `npm install` time, which you should be able to see by running something like:
```sh
npm install --verbose sharp 2>/dev/null | grep "sharp.node"
```

**Comment by woss** [comment]
`c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.7 -arch x86_64 -L./Release -stdlib=libc++ /usr/local/opt/libffi/lib -o Release/sharp.node Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/sharp.o Release/obj.target/sharp/src/utilities.o -L/usr/local/Cellar/vips/8.6.2/lib -L/usr/local/Cellar/glib/2.54.3/lib -L/usr/local/opt/gettext/lib -lvips-cpp -lvips -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation`

**Comment by lovell** [comment]
Whatever is putting `/usr/local/opt/libffi/lib` in there is causing the problem, `LD_FLAGS` perhaps?

**Comment by woss** [comment]
Good that you entioned that, here is my part of  `.zshrc`
```
export LDFLAGS="/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

I forgot why I put it but for sure something else was crashing, since I don't write software that needs compiling :)

**Comment by lovell** [comment]
That's an invalid LDFLAGS value and will be the reason for this error.

**Comment by woss** [comment]
Right, so for other people visiting this UNSET `LDFLAGS`and `PKG_CONFIG_PATH` and it will work.
Thank you so much @lovell
