### ISSUE TITLE
sharp.node is not a valid Win32 application

### ISSUE THREAD

**Issue by missbruni** [lovell/sharp#1189]
Hi there, I am trying to run sharp on a windows app service running on 64 bit and I am getting the below error. I have then tried running on a 32-bit OS and the error remains. Any ideas of what this can be caused by?

```
Error: \\?\D:\home\site\wwwroot\node_modules\sharp\build\Release\sharp.node is not a valid Win32 application\\?\D:\home\site\wwwroot\node_modules\sharp\build\Release\sharp.node
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sharp\lib\constructor.js:10:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

**Comment by missbruni** [comment]
I made sure the app service is running on node iis 64 binary, and I am using linux to create the artifacts. So my linux agent runs yarn install, creates the artefacts, zips it and deploys it to a windows web app.

**Comment by lovell** [comment]
The `yarn install` command must be run on Windows if the resultant `node_modules` is to be used on Windows at runtime.

**Comment by missbruni** [comment]
I tried running straight from the hosting machine and now I am getting another error:
```
sharp Intel Architecture 32-bit systems require manual installation of libvips >= 8.6.1
```

**Comment by lovell** [comment]
Are you sure this Windows machine is running x64 (64-bit) `node.exe`? The presence of x86 (32-bit) in `D:\\Program Files (x86)\\...` suggests otherwise.

**Comment by lovell** [comment]
@missbruni Were you able to make any progress with ensuring 64-bit host and executables are being used?

**Comment by felipemengatto** [comment]
@lovell, I have this same problem on windows, is there any solution for compiling it ?!
I'm using ubuntu.

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to re-open if this problem persists on 64-bit Windows.

**Comment by gaoryrt** [comment]
same error, I am using mac to generate the .exe file and runs it at win64

**Comment by simeyla** [comment]
@lovell I spent several hours trying to get this working last night but Azure functions seems to be locked to 32 bit Node. If you're running a full Azure App Service plan with IIS you can configure which Node it runs (with a nodeProcessCommandLine parameter), but that doesn't seem possible in the slimmer 'Azure Functions' environment.

For me it was more an academic exercise (to essentially make a microservice with what would amount to pennies running cost), but I had to give up in the end. I still have a full VM running that I can do whatever I want on so there's no issue.

Perhaps if you could maintain some kind of 'definitely supported' and 'definitely not supported' page, with brief explanations of why something isn't possible that would be really helpful.

**Comment by lovell** [comment]
Please see #379 for more context.

**Comment by JohannBlake** [comment]
I have the same issue. I'm running this on Windows 10 with 64 bit.
