### ISSUE TITLE
Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by OualidYousfi** [lovell/sharp#1210]
I have two Electron projects using sharp. I have a small testing project for testing sharp but it gave me an initialization DLL error at first. The commands I used were these and it got fixed.

```
npm install --save-dev electron-rebuild
npm install sharp
.\node_modules\.bin\electron-rebuild.cmd
```
I can use sharp now and tested it with some code which generated cropped output from the original image.

```
sharp('input.jpg')
  .resize(300, 200)
  .toFile('output.jpg', function(err) {
  });
```

The bigger project (electron-builder/yarn) where I want to implement sharp gives me this error. 
```
Error: The specified procedure could not be found.
  \\?\C:\Users\Noblesse\Documents\GitHub\desktop-gen-electron - kopie\node_modules\sharp\build\Release\sharp.node
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
      at Object.Module._extensions..node (module.js:598:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (C:\Users\Noblesse\Documents\GitHub\desktop-gen-electron - kopie\node_modules\sharp\lib\constructor.js:10:15)
      at Object.<anonymous> (C:\Users\Noblesse\Documents\GitHub\desktop-gen-electron - kopie\node_modules\sharp\lib\constructor.js:256:3)
```

I use the yarn way in this one but it doesn't work. There certainly is sharp.node in sharp/build/release/.
```
yarn add --dev electron-rebuild
yarn add sharp
.\node_modules\.bin\electron-rebuild.cmd
```

**Comment by lovell** [comment]
Does the "bigger project" include `node-canvas` as a dependency? If so, please see #1157

**Comment by OualidYousfi** [comment]
It did, actually. As well as `text2png` which required `node-canvas`. Removed the two as they weren't essential to the project. Got no errors anymore. I implemented the .tiff() method to be sure (because JIMP doesn't seem to have an option for reducing the file size for TIFFs) and all my images are ~50 KB now instead of ~5 MB.

Thanks for the quick tip!
