### ISSUE TITLE
Drop Node 4 support in v0.21.0

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1212]
As it will reach "end of life" on the 30th April 2018.

https://github.com/nodejs/Release#release-schedule

**Comment by nypinstripes** [comment]
Hey @lovell , first, fantastic lib just started using, switching over from imgmagik & it's doing wonders. 

It seems this release, while it builds & compiles just fine in Node 9.x it broke our (aws) docker containers' build. After upgrading node locally & our docker node image from 9.5.0 to 10.0.0 everything's kosher on v0.21.0 & 22. Just wanted to mention in case anyone else ran into the issue.

Docker output building v0.20.2 on node v9.5.0:

```
npm info lifecycle sharp@0.20.2~install: sharp@0.20.2

> sharp@0.20.2 install /app/code/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 2.5.3
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.20.2-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-lovell-sharp-releases-download-v0.20.2-sharp-v0.20.2-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.20.2/sharp-v0.20.2-node-v59-linux-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.20.2/sharp-v0.20.2-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.5.0 runtime=node arch=x64 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v9.5.0/node-v9.5.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v9.5.0/node-v9.5.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v9.5.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v9.5.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/code/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/9.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/9.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/9.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/code/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Linux 4.9.87-linuxkit-aufs
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/code/node_modules/sharp
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by billouboq** [comment]
If you drop node 4 maybe it's better to do it in a major version don't you think ?

**Comment by lovell** [comment]
@billouboq sharp has yet to reach v1.0.0 so semver allows for "breaking" changes with a minor version increment.

By way of example, support for Node 0.10 and 0.12, present in sharp v0.16.2, was [dropped in v0.17.0](http://sharp.pixelplumbing.com/en/stable/changelog/#v0170-11th-december-2016). This was discussed in #610.

**Comment by lovell** [comment]
v0.21.0 now available with this change.
