### ISSUE TITLE
Failing when installed via yarn (and using yarns workspaces feature)

### ISSUE THREAD

**Issue by ctrlplusb** [lovell/sharp#1227]
Yarn's workspaces supports monorepos and supports hoisting of dependencies to the monorepo root. I was wondering if this was causing issues with `sharp` so I specifically set Yarn to not hoist `sharp`.

When I try to run my project however I get the following error:

```
Error: /mymonorepo/packages/server-media/node_modules/sharp/build/Release/sharp.node: invalidELF header
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/monorepo/root/packages/server-media/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mymonorepo/packages/server-media/node_modules/sharp/lib/index.js:3
```

**Comment by ctrlplusb** [comment]
Just seen this: https://github.com/lovell/sharp/issues/800

It applies. Thanks.
