### ISSUE TITLE
sharp.node Exec format error

### ISSUE THREAD

**Issue by andyr** [lovell/sharp#1240]
Trying to run my app in **alpine-linux** with **node 10.2.1** in Docker.  I get the following error, where the relevant problem seems to be: 

```Error: Error loading shared library /usr/src/app/api/node_modules/sharp/build/Release/sharp.node: Exec format error```

Also, I used this guide: http://sharp.dimens.io/en/stable/install/#alpine-linux to ensure I am adding vips-dev as a system wide package in my image.  However, when the container starts, my app crashes with this.  Is there something wrong with the node version?  Any insight you could provide me as to why it errs when loading `sharp.node` ?

```[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
internal/modules/cjs/loader.js:731
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error loading shared library /usr/src/app/api/node_modules/sharp/build/Release/sharp.node: Exec format error
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/src/app/api/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
[nodemon] app crashed - waiting for file changes before starting...```

**Comment by lovell** [comment]
Hello, please see #988 and #1096
