### ISSUE TITLE
Build fail due to Python error

### ISSUE THREAD

**Issue by David-OConnor** [lovell/sharp#1245]
Note that I have Python 3.6 on the System path. The bin is located where the error lists as well, although with a lowercase .exe.

```error C:\Users\david\code\dimensions\frontend\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: C:\Users\david\code\dimensions\frontend\node_modules\sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating C:\Users\david\code\dimensions\frontend\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\david\code\dimensions\frontend\node_modules\sharp\vendor\lib to C:\Users\david\code\dimensions\frontend\node_modules\sharp\build\Relea
se
prebuild-install WARN install No prebuilt binaries found (target=9.11.1 runtime=node arch=x64 platform=win32)

C:\Users\david\code\dimensions\frontend\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.11.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\david\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\david\code\dimensions\frontend\node_modules\sharp
```

**Comment by lovell** [comment]
Hello, please see http://sharp.pixelplumbing.com/en/stable/install/ specifically the dependencies of `node-gyp` that include Python 2.7 but not 3.x.

I'd recommend using node 8 or 10 if possible as pre-compiled binaries are provided for these versions.

**Comment by David-OConnor** [comment]
Thanks!
