### ISSUE TITLE
Invalid non-string/buffer chunk during processing/output of PNG->WEBP image

### ISSUE THREAD

**Issue by CapnSpellcheck** [lovell/sharp#1249]
sharp has served me well when the inputs are JPEG or WEBP, but this one PNG repeatedly yields an error during the sharp operations. Image source file is attached. The error stack is:
```
[05/31/2018 03:21:23.383] Error -- stack: TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (_stream_readable.js:395:10)
    at readableAddChunk (_stream_readable.js:150:12)
    at Sharp.Readable.push (_stream_readable.js:136:10)
    at /usr/lib/node_modules/TwinkleAPI/node_modules/sharp/lib/output.js:470:16
```
And right before this stack is printed, I have some console logging, this ties into the code following
```
[05/31/2018 03:21:23.219] newPhoto: megapixels: 1.048576 rotate: 0 metadata: {"format":"webp","width":1024,"height":1024,"space":"srgb","channels":4,"depth":"uchar","hasProfile":false,"hasAlpha":true,"exif":null}
[05/31/2018 03:21:23.381] uploadPhoto: stream info: null
```
And the code is: (fairly gross, yes)
```
            const sharp = this.Sharp(fileLocation, {failOnError: true})
            return sharp.metadata()
            .catch(err => {
                if (err.stack && err.stack.indexOf("unsupported image format") > 0)
                    return this.error("bad_image", err)
                throw err
            })
            .then( metadata => {
                const megapixels = ( metadata.height * metadata.width ) / 1000000,
                    name = this.Uuid(),
                    rotate = Number.parseInt(this.query.rotate || '0')
                // kill metadata.exif
                metadata.exif = null
                console.log('newPhoto: megapixels: ' + megapixels + ` rotate: ${this.query.rotate} metadata: ${JSON.stringify(metadata)}`)
                
                if (this.isIrregularShape(metadata)) {
                    console.log('returning irregular_shape')
                    return this.badRequest('irregular_shape')
                }
                let oScale = null
                
                sharp.rotate(rotate)
                    .withMetadata({orientation: 1})
                    .webp({force: false})
                // it doesn't matter if this is before or after rotate, if rotate == 90 or 270, the scaledown is wrong (too big)
                // so if rotate is 90 or 270, we calc based on metadata.height instead (and still pass width)
                if (megapixels > 4) {
                    let srcDimen = (rotate == 90 || rotate == 270) ? metadata.height : metadata.width
                    oScale = {scale: Math.sqrt(4 / megapixels)}
                    sharp.resize(Math.floor(oScale.scale * srcDimen), null, {fastShrinkOnLoad: false})
                }
                
                return this.uploadPhoto(sharp, name, metadata)
                .then( ( { w, h } ) => {
                ... some more stuff is done after the upload
            ....
    uploadPhoto( sharp, name, metadata ) {
        // console.log('movePhoto')
        let info = {}
        sharp.on('info', info_ => {
            info = info_
            console.log('uploadPhoto: stream info: ' + JSON.stringify(info))
        })
        return this.GoogleCloudStorage.POST( name, sharp, this.getMIMEType(metadata) )
        .catch(err => this.error('failed_to_upload', err) )
        .then( () => Promise.resolve( {w: info.width, h: info.height} ))
    },
```
The error seems to happen during or after the pipeline, and the pipeline output is piped into a post request. As you can see, I access the stream info during the output phase, and in this case, the event is received as null. This works great with every JPEG/WEBP I've thrown as input. Sharp deployed is v0.19.x; does this look like an issue that may be fixed recently? I don't see a changelog for the releases.

![facebook icon](https://user-images.githubusercontent.com/512016/40882125-76ec4f38-668d-11e8-956e-bb85e1cbb2f4.png)

**Comment by lovell** [comment]
Hello, the error is from the output side rather than the input side so please can you add further the code that is, I think, piping data from a sharp instance.

Without seeing more code, my best guess would be that this code should listen for the `close` event on `writeStream` rather than `finish` to ensure the filesystem is fully in sync.

```diff
- writeStream.on( 'finish', () => { resolve() } )
+ writeStream.on( 'close', () => { resolve() } )
```

The changelog is at http://sharp.pixelplumbing.com/en/stable/changelog/

**Comment by CapnSpellcheck** [comment]
Hi,

I had this realization last night and, since I saw there was no feedback yet, I revamped the initial report up top. Since you replied roughly the same time, please check and see if the code up top is more relevant. I added uploadPhoto and mentioned of the info event being null. Finally, so you can see how the output is sent, it uses coud-storage: here's the code
```
    POST( name, stream, contentType ) {
        const metadata = Object.assign(
            {contentType},
            {cacheControl: "public, max-age=9999999"}
        )
        const upstream = this.Storage.bucket(process.env.GOOGLE_BUCKET).file(name).createWriteStream({
            public: true,
            resumable: false,
            metadata,
        })
        return new Promise( (resolve, reject) => {
            stream.pipe(upstream)
            upstream.on('error', reject)
            stream.on('error', reject)
            upstream.on('finish', resolve)
        })
    }
```

**Comment by lovell** [comment]
Thanks for the update, the use of `webp` and `withMetadata` leads me to believe you've run into #1242

**Comment by lovell** [comment]
Please subscribe to #1242 for updates.
