### ISSUE TITLE
installing sharp module provides an error

### ISSUE THREAD

**Issue by mrvkv** [lovell/sharp#1348]
```
npm i sharp
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> sharp@0.20.7 install /home/vivek/office/delgatedriver/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/vivek/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
sh: 1: prebuild-install: not found
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.15.0-32-generic
gyp ERR! command "/home/vivek/.nvm/versions/node/v8.11.4/bin/node" "/home/vivek/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vivek/office/delgatedriver/node_modules/sharp
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.7 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vivek/.npm/_logs/2018-08-22T06_30_00_939Z-debug.log

```

**Comment by lovell** [comment]
Hello, the error `prebuild-install: not found` suggests something went wrong during `npm install` prior to the log shown here, perhaps a temporary networking problem?

**Comment by mrvkv** [comment]
Thanks.
I have run the below command and sharp installed properly...
`sudo npm install sharp`

**Comment by publitas-revolution** [comment]
@lovell , I am getting the same error :

> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
sh: 1: prebuild-install: not found

Running on Ubuntu 16.04 Node v10.16 and npm 6.9
