### ISSUE TITLE
Error installing Sharp on Elastic Beanstalk AWS 

### ISSUE THREAD

**Issue by evilkels** [lovell/sharp#1368]
Hi, 
I have an express app, that gets deployed using gitlab-ci scripts and executes them on AWS EC2 instance with Elastic Beanstalk. 
It all deployed well, but one day it started to fail and exit the script with error. Looking in EB logs there is written, that there might be a problem with sharp. That is why i'm looking for help here!

Can You please help me figure out what could cause this issue?

/////////////////////////////

**This is a failed deploy script log output:** 

```
93923 verbose stack Error: sharp@0.20.7 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
93923 verbose stack Exit status 1
93923 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
93923 verbose stack     at emitTwo (events.js:106:13)
93923 verbose stack     at EventEmitter.emit (events.js:191:7)
93923 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
93923 verbose stack     at emitTwo (events.js:106:13)
93923 verbose stack     at ChildProcess.emit (events.js:191:7)
93923 verbose stack     at maybeClose (internal/child_process.js:891:16)
93923 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
93924 verbose pkgid sharp@0.20.7
93925 verbose cwd /tmp/deployment/application
93926 error Linux 4.9.43-17.38.amzn1.x86_64
93927 error argv "/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/npm" "--production" "install"
93928 error node v6.11.1
93929 error npm  v3.10.10
93930 error code ELIFECYCLE
93931 error sharp@0.20.7 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
93931 error Exit status 1
93932 error Failed at the sharp@0.20.7 install script '(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)'.
93932 error Make sure you have the latest version of node.js and npm installed.
93932 error If you do, this is most likely a problem with the sharp package,
93932 error not with npm itself.
93932 error Tell the author that this fails on your system:
93932 error     (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
93932 error You can get information on how to open an issue for this project with:
93932 error     npm bugs sharp
93932 error Or if that isn't available, you can get their info via:
93932 error     npm owner ls sharp
93932 error There is likely additional logging output above.
93933 verbose exit [ 1, true ]
```

**And this is the last successful deploy script log output:** 

```
> bcrypt@1.0.3 install /tmp/deployment/application/node_modules/bcrypt
  > node-pre-gyp install --fallback-to-build

  [bcrypt] Success: "/tmp/deployment/application/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
  
  > node-sass@4.9.3 install /tmp/deployment/application/node_modules/node-sass
  > node scripts/install.js
  
  Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-48_binding.node
  Download complete
  Binary saved to /tmp/deployment/application/node_modules/node-sass/vendor/linux-x64-48/binding.node
  Caching binary to /tmp/.npm/node-sass/4.9.3/linux-x64-48_binding.node
  Failed to cache binary: { Error: EACCES: permission denied, open '/tmp/.npm/node-sass/4.9.3/linux-x64-48_binding.node'
      at Error (native)
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/.npm/node-sass/4.9.3/linux-x64-48_binding.node' }
  
  > sharp@0.20.5 install /tmp/deployment/application/node_modules/sharp
  > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
  
  info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
  prebuild-install WARN install EACCES: permission denied, access '/tmp/.npm'
  make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
    TOUCH Release/obj.target/libvips-cpp.stamp
    CXX(target) Release/obj.target/sharp/src/common.o
    CXX(target) Release/obj.target/sharp/src/metadata.o
    CXX(target) Release/obj.target/sharp/src/stats.o
    CXX(target) Release/obj.target/sharp/src/operations.o
    CXX(target) Release/obj.target/sharp/src/pipeline.o
    CXX(target) Release/obj.target/sharp/src/sharp.o
    CXX(target) Release/obj.target/sharp/src/utilities.o
    SOLINK_MODULE(target) Release/obj.target/sharp.node
    COPY Release/sharp.node
  make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
  
  > node-sass@4.9.3 postinstall /tmp/deployment/application/node_modules/node-sass
  > node scripts/build.js
 ```

**Comment by lovell** [comment]
Hello, this is an Elastic Beanstalk permissions problem, please see #373
