### ISSUE TITLE
Updated node.js to v10.9.0

### ISSUE THREAD

**Issue by David-Carty** [lovell/sharp#1371]
sitespeed.io no longer works since upgrading to node v10.9.0 on Windows OS.
Error:
build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing

1. Tried npm rebuild and npm install
2. I do not have any node version conflicts as node -v matches console.log(process.version)
3. reinstalled sharp, sitespeed.io
4. No joy

All other code works as it did, just an issue with sitespeed.io and sharp.  Any help appreciated.

**Comment by David-Carty** [comment]
Removing node_modules then node install did not help I'm afraid.  Here is the output:
sitespeed.io https://www.net-a-porter.com/gb/en/ --outputFolder C:/Dev/MowziProjects/mowzi/src-v1/DevAdmin/reports/sitespeed
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\david\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\sharp\build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\sharp\lib\constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by lovell** [comment]
It looks like `sitespeed.io` was installed globally. Are you sure the globally-installed `C:\Users\david\AppData\Roaming\npm\node_modules\sitespeed.io` directory was removed, and not just the local one?

**Comment by David-Carty** [comment]
Sorry Lovell, you identified the cause of my woes.  Been a busy day.  Thanks, all good now.
