### ISSUE TITLE
No prebuilt binaries found

### ISSUE THREAD

**Issue by localnet** [lovell/sharp#1464]
I am getting the next error when I try install sharp:

```
$ npm install --save-dev sharp

> sharp@0.21.0 install /home/user/Proyectos/name/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.2.0 runtime=node arch=x64 platform=linux)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Linux 4.19.1-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Proyectos/name/app/node_modules/sharp
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

```
$ uname -a
Linux desktop 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux
```

I prefer use pre-build. Isn't it possible on Linux x64?

**Comment by lovell** [comment]
Hello, it looks like Node 11 is being used here.

"Pre-compiled binaries for sharp are provided for use with Node versions 6, 8 and 10 on 64-bit Windows, OS X and Linux platforms."

http://sharp.pixelplumbing.com/en/stable/install/

**Comment by localnet** [comment]
You are right, my fault.

I understand there aren't plans to build precompiled binaries for Node.js 11, for now. True?

**Comment by localnet** [comment]
Ok, I will change to LTS version.

Thanks you, and great work.
