### ISSUE TITLE
FreeBSD fatal error: 'vips/vips8' file not found

### ISSUE THREAD

**Issue by ctag** [lovell/sharp#1492]
Hi,

I've manually installed vips per http://sharp.pixelplumbing.com/en/stable/install/#freebsd. 
`pkg install -y pkgconf vips`

But installing sharp still fails:
```sudo -H -u peertube npm install sharp
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN rm not removing /var/www/peertube/versions/peertube-v1.1.0/node_modules/.bin/semver as it wasn't installed by /var/www/peertube/versions/peertube-v1.1.0/node_modules/semver
npm WARN rm not removing /var/www/peertube/versions/peertube-v1.1.0/node_modules/.bin/nopt as it wasn't installed by /var/www/peertube/versions/peertube-v1.1.0/node_modules/nopt

> deasync@0.1.14 install /var/www/peertube/versions/peertube-v1.1.0/node_modules/deasync
> node ./build.js

gmake: Entering directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
  SOLINK_MODULE(target) Release/obj.target/deasync.node
  COPY Release/deasync.node
gmake: Leaving directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/deasync/build'
Installed in `/var/www/peertube/versions/peertube-v1.1.0/node_modules/deasync/bin/freebsd-x64-node-10/deasync.node`

> bufferutil@4.0.0 install /var/www/peertube/versions/peertube-v1.1.0/node_modules/bufferutil
> node-gyp-build

gmake: Entering directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
cc: error: unable to execute command: Segmentation fault
cc: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
cc: note: diagnostic msg: PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
cc: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
cc: note: diagnostic msg: /tmp/bufferutil-ab6b9a.c
cc: note: diagnostic msg: /tmp/bufferutil-ab6b9a.sh
cc: note: diagnostic msg: 

********************
gmake: *** [bufferutil.target.mk:95: Release/obj.target/bufferutil/src/bufferutil.o] Error 254
gmake: Leaving directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System FreeBSD 11.1-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/peertube/versions/peertube-v1.1.0/node_modules/bufferutil
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> rdf-canonize@0.2.5 install /var/www/peertube/versions/peertube-v1.1.0/node_modules/rdf-canonize
> node-gyp rebuild

gmake: Entering directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/rdf-canonize/build'
  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
  CXX(target) Release/obj.target/urdna2015/lib/native/MessageDigest.o
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
  CXX(target) Release/obj.target/urdna2015/lib/native/NQuads.o
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
  CXX(target) Release/obj.target/urdna2015/lib/native/addon.o
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
../lib/native/addon.cc:64:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1655:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
2 warnings generated.
  CXX(target) Release/obj.target/urdna2015/lib/native/urdna2015.o
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/urdna2015.node
  COPY Release/urdna2015.node
gmake: Leaving directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/rdf-canonize/build'

> utf-8-validate@5.0.1 install /var/www/peertube/versions/peertube-v1.1.0/node_modules/utf-8-validate
> node-gyp-build

gmake: Entering directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/utf-8-validate/build'
  CC(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
gmake: Leaving directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/utf-8-validate/build'

> sharp@0.21.0 install /var/www/peertube/versions/peertube-v1.1.0/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp FreeBSD systems require manual installation of libvips >= 8.7.0
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
gmake: Entering directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
gmake: *** [sharp.target.mk:118: Release/obj.target/sharp/src/common.o] Error 1
gmake: Leaving directory '/var/www/peertube/versions/peertube-v1.1.0/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System FreeBSD 11.1-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/peertube/versions/peertube-v1.1.0/node_modules/sharp
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.0 (node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.0 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.21.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2018-12-04T17_27_37_745Z-debug.log
```

**Comment by gegeweb** [comment]
You must update libvps port to 8.7.1.

**Comment by gegeweb** [comment]
@lovell You have closed the bug, it's OK ?
I've succefully upgrded to Peertube 1.1.0 after upgrading my system (host and jail) to 11.2-RELEASE and using ports from latest repository.
The quaterly repository is not up to date about vips.

I've pushed a pull request wich update the startup script, stoping service doesn't work now if procname is not specified.

**Comment by lovell** [comment]
@gegeweb To use sharp v0.21.0+ on FreeBSD you'll need to upgrade libvips to at least v8.7.0.

http://sharp.pixelplumbing.com/en/stable/changelog/
http://sharp.pixelplumbing.com/en/stable/install/#freebsd

It looks like libvips v8.7.1 is available via ports.

https://www.freshports.org/graphics/vips/

**Comment by gegeweb** [comment]
@lovell Yes, I know. ;)
