### ISSUE TITLE
Module initialization error on using Sharp in AWS lambda functions

### ISSUE THREAD

**Issue by wobeng** [lovell/sharp#1517]
Hi,

I'm using node 8.10.0 in docker to build my packages for aws lambda. After build I get

```
module initialization error: Error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/var/task/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
In my docker config file

```
FROM amazonlinux:2

# Install dependencies
RUN yum update -y
RUN yum install -y gcc gcc-c++ make wget yum-utils groupinstall development 
RUN yum install -y zlib-devel libffi-devel python-devel openssl-devel git zip jq
RUN yum install -y unzip which gettext epel-release tar dbus-glib amazon-efs-utils

# Install NodeJs
RUN wget https://nodejs.org/dist/v8.10.0/node-v8.10.0.tar.gz
RUN tar -xvf node-v8.10.0.tar.gz && rm node-v8.10.0.tar.gz
RUN cd node-v8.10.0 && ./configure && make && make install

```
The command I use is 
```
npm install --production

```
My package.json is

```
{
  "name": "ca-images",
  "version": "0.0.1",
  "dependencies": {
    "jimp": "latest",
    "sharp": "latest",
    "imagemagick": "latest",
    "uuid": "latest",
    "get-folder-size": "latest",
    "mime-types": "latest"
  },
  "devDependencies": {
    "aws-sdk": "latest"
  }
}
```

I have looked at similar issues on here but no luck

**Comment by lovell** [comment]
Hello, did you see the section about AWS Lambda in the sharp docs?

http://sharp.pixelplumbing.com/en/stable/install/#aws-lambda

**Comment by lovell** [comment]
@wobeng Were you able to make any progress with this?

**Comment by demisx** [comment]
I've followed instructions on http://sharp.pixelplumbing.com/en/stable/install/#aws-lambda, but still getting this error: 😞 

```sh
module initialization error: Error
at Object.Module._extensions..node (module.js:681:18)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at bindings (/var/task/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:34)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
```
