### ISSUE TITLE
When I load shark in the work Thread, no matter how I rebuild, the following error occurs repeatedly.

### ISSUE THREAD

**Issue by tangboCHN** [lovell/sharp#1523]
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

const sharp = require('sharp')   // error 
const {  parentPort ,threadId, workerData} = require('worker_threads');
.....

node version : 11.5.0

**Comment by lovell** [comment]
Native modules such as sharp do not work with Node's Worker Threads - please see https://github.com/lovell/sharp/issues/1297
