### ISSUE TITLE
ubuntu 16.04 install fails - vips tarball 

### ISSUE THREAD

**Issue by rowntreerob** [lovell/sharp#1527]
npm install sharp

```
> sharp@0.21.1 install /home/rob/src/web-spch-v2/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/rob/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz
ERR! sharp zlib: Cannot read property 'length' of null
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/rob/src/web-spch-v2/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
compilation terminated.
sharp.target.mk:128: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/rob/src/web-spch-v2/node_modules/sharp/build'

```
TRIED -

installing libvips/libvips  >8.7.1 from tarball and that produced same error  "... zlib ..." 

-- tail of the log

```
1386 silly saveTree ├── workbox-sw@3.5.0
1386 silly saveTree └── workbox-webpack-plugin@3.5.0
1387 warn ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
1388 warn babelify@8.0.0 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none is installed. You must install peer dependencies yourself.
1389 warn eslint-config-google@0.3.0 requires a peer of eslint@>=1.8.0 but none is installed. You must install peer dependencies yourself.
1390 warn eslint-config-xo@0.7.1 requires a peer of eslint@>=1.7.3 but none is installed. You must install peer dependencies yourself.
1391 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
1392 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1393 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1393 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1393 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1393 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1394 verbose stack Error: sharp@0.21.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
1394 verbose stack Exit status 1
1394 verbose stack     at EventEmitter.<anonymous> (/home/rob/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
1394 verbose stack     at emitTwo (events.js:135:13)
1394 verbose stack     at EventEmitter.emit (events.js:224:7)
1394 verbose stack     at ChildProcess.<anonymous> (/home/rob/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1394 verbose stack     at emitTwo (events.js:135:13)
1394 verbose stack     at ChildProcess.emit (events.js:224:7)
1394 verbose stack     at maybeClose (internal/child_process.js:943:16)
1394 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
1395 verbose pkgid sharp@0.21.1
1396 verbose cwd /home/rob/src/web-spch-v2
1397 verbose Linux 4.4.0-140-generic
1398 verbose argv "/home/rob/.nvm/versions/node/v9.0.0/bin/node" "/home/rob/.nvm/versions/node/v9.0.0/bin/npm" "install" "sharp"
1399 verbose node v9.0.0
1400 verbose npm  v6.3.0
1401 error code ELIFECYCLE
1402 error errno 1
1403 error sharp@0.21.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
1403 error Exit status 1
1404 error Failed at the sharp@0.21.1 install script.

```

**Comment by rowntreerob** [comment]
manually get the vips-8.7.2  tarball  running ./configure  && make   on it and that is fine in my system

**Comment by lovell** [comment]
Node 9 reached end-of-life about 6 months ago, plus early versions of it had a zlib handling bug that this might be related to. If you're able to use either Node 8 or 10 then you'll get the benefit of pre-compiled binaries.
