### ISSUE TITLE
Error when using Electron and Sharp

### ISSUE THREAD

**Issue by groboter** [lovell/sharp#1530]
I'm trying to build an app using Electron and Sharp but I'm always getting an error message as soon as I add the line `const sharp = require('sharp')` to my code. Without this line everything is working. I've also tried it on different windows computers with the same result.

Here is my code (it is just the electron example code):
```javascript
const { app, BrowserWindow } = require('electron')
const sharp = require('sharp');

// Behalten Sie eine globale Referenz auf das Fensterobjekt. 
// Wenn Sie dies nicht tun, wird das Fenster automatisch geschlossen, 
// sobald das Objekt dem JavaScript-Garbagekollektor übergeben wird.

let win

function createWindow () {
  // Erstellen des Browser-Fensters.
  win = new BrowserWindow({ width: 800, height: 600 })

  // und Laden der index.html der App.
  win.loadFile('index.html')

  // Öffnen der DevTools.
  win.webContents.openDevTools()

  // Ausgegeben, wenn das Fenster geschlossen wird.
  win.on('closed', () => {
    // Dereferenzieren des Fensterobjekts, normalerweise würden Sie Fenster
    // in einem Array speichern, falls Ihre App mehrere Fenster unterstützt. 
    // Das ist der Zeitpunkt, an dem Sie das zugehörige Element löschen sollten.
    win = null
  })
}

// Diese Methode wird aufgerufen, wenn Electron mit der
// Initialisierung fertig ist und Browserfenster erschaffen kann.
// Einige APIs können nur nach dem Auftreten dieses Events genutzt werden.
app.on('ready', createWindow)

// Verlassen, wenn alle Fenster geschlossen sind.
app.on('window-all-closed', () => {
  // Unter macOS ist es üblich für Apps und ihre Menu Bar
  // aktiv zu bleiben bis der Nutzer explizit mit Cmd + Q die App beendet.
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // Unter macOS ist es üblich ein neues Fenster der App zu erstellen, wenn
  // das Dock Icon angeklickt wird und keine anderen Fenster offen sind.
  if (win === null) {
    createWindow()
  }
})
```

This is the log output:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle test1@1.0.0~prestart: test1@1.0.0
6 info lifecycle test1@1.0.0~start: test1@1.0.0
7 verbose lifecycle test1@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle test1@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\temp\test1\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\STMicroelectronics\st_toolset\asm;C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion;C:\Program Files\scicoslab-4.4.1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files\Intel\DMIX;C:\Program Files (x86)\Intel\Services\IPT\;C:\Cadence\SPB_16.3\tools\pcb\bin;C:\Cadence\SPB_16.3\tools\specctra\bin;C:\Cadence\SPB_16.3\tools\fet\bin;C:\Cadence\SPB_16.3\tools\PSpice;C:\Cadence\SPB_16.3\tools\PSpice\Library;C:\Cadence\SPB_16.3\tools\Capture;C:\Cadence\SPB_16.3\tools\bin;C:\Cadence\SPB_16.3\OpenAccess\bin\win32\opt;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Pico Technology\PicoScope6\;C:\Program Files (x86)\Pico Technology\Pico Full\;C:\Program Files\doxygen\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\rl\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\STMicroelectronics\STM32 ST-LINK Utility\ST-LINK Utility;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\IDM Computer Solutions\UltraEdit\;C:\Program Files (x86)\IDM Computer Solutions\UltraCompare\;C:\Users\rl\AppData\Local\Microsoft\WindowsApps;C:\Users\rl\AppData\Local\Programs\Fiddler;C:\Program Files\Microsoft VS Code\bin;C:\Users\rl\AppData\Local\Microsoft\WindowsApps;C:\Users\rl\AppData\Roaming\npm
9 verbose lifecycle test1@1.0.0~start: CWD: C:\temp\test1
10 silly lifecycle test1@1.0.0~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle test1@1.0.0~start: Returned: code: 3228369023  signal: null
12 info lifecycle test1@1.0.0~start: Failed to exec start script
13 verbose stack Error: test1@1.0.0 start: `electron .`
13 verbose stack Exit status 3228369023
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid test1@1.0.0
15 verbose cwd C:\temp\test1
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3228369023
22 error test1@1.0.0 start: `electron .`
22 error Exit status 3228369023
23 error Failed at the test1@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3228369023, true ]
```

If I just use a simple http server demo **without electron** I do not get the error message:
```javascript
var http = require('http');
const sharp = require('sharp');

http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World!!!');
}).listen(8080);
```

Because I'm new to both NodeJS and Electron I'm not sure if I'm doing something wrong?

Thanks!

**Comment by lovell** [comment]
Hello, did you see https://electronjs.org/docs/tutorial/using-native-node-modules ?

**Comment by groboter** [comment]
Hello, I've checked it and run the following commands:

```
npm install --save-dev electron-rebuild

./node_modules/.bin/electron-rebuild
```
Executing the command ends with: **√ Rebuild Complete**
But now I'm getting this error after `NPM start`
```
App threw an error during load
Error: Das angegebene Modul wurde nicht gefunden. 
english translation ==> Error: Module not found
\\?\C:\temp\test1\node_modules\sharp\build\Release\sharp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (C:\temp\test1\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (C:\temp\test1\node_modules\sharp\lib\constructor.js:10:34)
```
For me it seems that compilation has not worked? Do I have to manually build for electron according to your link?

**Comment by lovell** [comment]
If you're using Electron 4, please see #1522

**Comment by groboter** [comment]
Yes I've got exactly the same error. But as I understand there is no solution yet?

**Comment by lovell** [comment]
Thanks, let's track this at #1522
