### ISSUE TITLE
building sharp with react-native

### ISSUE THREAD

**Issue by mandric** [lovell/sharp#1569]
Hello I'm trying to bundle sharp with react-native and could use a tip for getting sharp to build libvips for android arm architecture.  

I'm including an error below from the build but you can see fully here: https://circleci.com/gh/mandric/nodejs-mobile-sharp/25

I think all that needs to be done is for the libvips download process to use 'linux' instead of 'android' during android builds?  

Please let me know if you think that would work or if there's a better solution, also happy to file a PR if you think a patch is in order.

Thank you!

```
npm info lifecycle sharp@0.20.8~install: sharp@0.20.8

> sharp@0.20.8 install /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-android-armv6.tar.gz
/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/install/libvips.js:79
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 404
    at /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/install/libvips.js:79:17
    at f (/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/once/once.js:25:25)
    at ClientRequest.<anonymous> (/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/simple-get/index.js:74:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:558:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/home/circleci/src/node_modules/nodejs-mobile-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@0.2.1
gyp info using node@8.15.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir compiling against specified --nodedir dev files: /home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/
gyp verb build dir attempting to create "build" dir: /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/circleci/src/node_modules/nodejs-mobile-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make-android',
gyp info spawn args   '-I',
gyp info spawn args   '/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/circleci/src/node_modules/nodejs-mobile-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/',
gyp info spawn args   '-Dnode_gyp_dir=/home/circleci/src/node_modules/nodejs-mobile-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory '/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  /home/circleci/src/android/build/standalone-toolchains/arm-linux-androideabi/bin/arm-linux-androideabi-clang++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_ENGINE="v8"' '-DNODE_ENGINE_V8' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' '-D_GLIBCXX_USE_C99_MATH' -I/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/include/node -I/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/src -I/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/deps/uv/include -I/home/circleci/src/node_modules/nodejs-mobile-react-native/android/libnode/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
sharp.target.mk:120: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make[1]: Leaving directory '/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/build'
make[1]: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/circleci/src/node_modules/nodejs-mobile-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command "/usr/local/bin/node" "/home/circleci/src/node_modules/nodejs-mobile-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v0.2.1
gyp ERR! not ok 
npm verb lifecycle sharp@0.20.8~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.20.8~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp/node_modules/.bin:/home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/.bin:/home/circleci/src/android/../nodejs-assets/nodejs-project/node_modules/.bin:/opt/android/sdk/emulator:/opt/android/sdk/tools:/opt/android/sdk/tools/bin:/opt/android/sdk/platform-tools:/home/circleci/.rubies/ruby-2.4.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.20.8~install: CWD: /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project/node_modules/sharp
npm info lifecycle sharp@0.20.8~install: Failed to exec install script
npm verb stack Error: sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:915:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid sharp@0.20.8
npm verb cwd /home/circleci/src/android/build/nodejs-native-assets-temp-build/nodejs-native-assets-armeabi-v7a/nodejs-project
npm verb Linux 4.10.0-35-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "--verbose" "rebuild" "--build-from-source"
npm verb node v8.15.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 3449ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-02-06T23_04_45_694Z-debug.log
:nodejs-mobile-react-native:BuildNpmModulesarmeabi-v7a FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nodejs-mobile-react-native:BuildNpmModulesarmeabi-v7a'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.662 secs
make: *** [android/app/build/outputs/apk/app-debug.apk] Error 1
Makefile:13: recipe for target 'android/app/build/outputs/apk/app-debug.apk' failed
Exited with code 2
```

**Comment by lovell** [comment]
Hello, you can override the platform and arch at install time, plus if you want libvips binaries for ARMv7 (rather than ARMv6) there's a flag for that too:
```sh
$ npm install sharp --platform=linux --arch=arm --armv=7
```
Please make sure you're using the latest version v0.21.3.

(The experimental/undocumented `--armv` flag is being renamed `--arm-version` in the next version - see commit 7788430.)

**Comment by mandric** [comment]
I'm new to RN and I'm wondering if this project should "just work", it's a nodejs-mobie project that has sharp as a dependency and that's about it.  Running `npm install` and then `npx react-native run android` should just work right?  I believe this fails because the system that I'm running npm install on is `x86_64` while the target arch is `armv7` and `x86` per ndk config in `android/app/build.gradle`:
```
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
```

This is where it gets a little tricky because now there's several systems trying to figure out how to compile npm modules and I'm not sure how to communicate to the sharp npm package what the target architecture is.  It seems to happily compile against the x86 library even though the target is arm. It's a minor thing that can be fixed with a hack but I'm curious if there is a right way before I go down the hack route.

**Comment by lovell** [comment]
If you need to compile native modules targetting ARMv7 using an x64 machine then you'll need to set it up for cross-compilation. This is not a sharp-specific thing so StackOverflow is your friend here - good luck!

**Comment by mandric** [comment]
Android NDK is a cross compilation system being used by nodejs-mobile and I think the way sharp downloads libvips pre-built libraries breaks that on that build system, I guess I'm wondering what is the standard way to tell node-gyp what architecture to target and maybe use that to determine which architecture to build/install? This is out of my realm of expertise but I think there is a limitation there that can be fixed.

**Comment by mandric** [comment]
I think the solution is to tell the nodejs-mobile `BuildNpmModules` gradle task https://github.com/janeasystems/nodejs-mobile-react-native/blob/9df1a5362fcb30c2321c39a3e21f3fdcb8376e15/android/build.gradle#L306-L341 to tell sharp to build libvips using the right arch(or download the right pre-built) through the node gyp bindings https://github.com/lovell/sharp/blob/master/binding.gyp
