### ISSUE TITLE
Build error under io.js 1.1.0

### ISSUE THREAD

**Issue by ide** [lovell/sharp#159]
My setup is io.js 1.1.0 installed with nvm on OS X 10.10 using the version of node-gyp that ships with io.js. Looks like a v8 compatibility issue. Here is the error output:

```
> sharp@0.9.1 install /code/node_modules/sharp
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
In file included from ../src/utilities.cc:4:
../node_modules/nan/nan.h:1848:10: error: no matching function for call to
      'Encode'
  return node::Encode(
         ^~~~~~~~~~~~
/Users/ide/.node-gyp/1.1.0/src/node.h:257:34: note: candidate function not
      viable: cannot convert argument of incomplete type 'const void *' to
      'const char *'
NODE_EXTERN v8::Local<v8::Value> Encode(v8::Isolate* isolate,
                                 ^
/Users/ide/.node-gyp/1.1.0/src/node.h:263:34: note: candidate function not
      viable: requires 3 arguments, but 4 were provided
NODE_EXTERN v8::Local<v8::Value> Encode(v8::Isolate* isolate,
                                 ^
/Users/ide/.node-gyp/1.1.0/src/node.h:268:45: note: candidate function not
      viable: requires at most 3 arguments, but 4 were provided
                inline v8::Local<v8::Value> Encode(
                                            ^
/Users/ide/.node-gyp/1.1.0/src/node.h:43:53: note: expanded from macro
      'NODE_DEPRECATED'
#define NODE_DEPRECATED(msg, fn) V8_DEPRECATED(msg, fn)
                                                    ^
/Users/ide/.node-gyp/1.1.0/deps/v8/include/v8config.h:332:45: note: expanded from
      macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message, declarator) declarator
                                            ^
1 error generated.
make: *** [Release/obj.target/sharp/src/utilities.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ide/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/ide/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /code/node_modules/sharp
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/ide/.nvm/versions/io.js/v1.1.0/bin/iojs" "/Users/ide/.nvm/versions/io.js/v1.1.0/bin/npm" "install" "sharp"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
```

**Comment by ide** [comment]
This looks like a problem with nan instead of sharp I guess...

**Comment by lovell** [comment]
Hi James, is this with nan 1.5.x? sharp v0.9.1 contains @jonathanong's [rewind](https://github.com/lovell/sharp/commit/512a2819862f8d3b6cfdc6fbfadde345836225bd) of nan from 1.6.x to 1.5.x to temporarily remove this problem.

https://github.com/rvagg/nan/pull/265 will fix this.

Travis CI adds support for iojs in <5 hour's time according to http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/ so I will add it to the build/test matrix soon after.

**Comment by ide** [comment]
I was using 1.6.1 because npm pulled it in automatically. I tested locally with 1.5.3 and it builds without issue. I'll close this out. You're really on top of things!
