### ISSUE TITLE
Error while building meteor project

### ISSUE THREAD

**Issue by gsunit** [lovell/sharp#1610]
I am trying to build `Rocket Chat` from source in my new machine (Ubuntu 18.04) using `meteor npm install`. However, I am getting the following error. The error seems to be while installing `sharp`, so I thought maybe you guys can help. I tried installing `sharp` separately. But I am still getting similar errors (will post them if required). Please help me out here.

```npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> sharp@0.21.3 install /home/gsunit/Documents/my-projects/Rocket.Chat/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/gsunit/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
make: Entering directory '/home/gsunit/Documents/my-projects/Rocket.Chat/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
sharp.target.mk:128: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/gsunit/Documents/my-projects/Rocket.Chat/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gsunit/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.0-16-generic
gyp ERR! command "/home/gsunit/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/gsunit/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gsunit/Documents/my-projects/Rocket.Chat/node_modules/sharp
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN @accounts/mongo@0.0.12 requires a peer of @accounts/common@^0.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN @accounts/mongo@0.0.12 requires a peer of @accounts/server@^0.0.10 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gsunit/.npm/_logs/2019-03-17T19_30_48_426Z-debug.log

**Comment by lovell** [comment]
Hello, the salient part of this error message is:
```
info sharp Using cached /home/gsunit/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
```
It looks like the `/home/gsunit/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz` file is corrupt, most likely due to a temporary network error. Please delete that file and try again.

**Comment by gsunit** [comment]
I had tried deleting `libvips-8.7.0-linux-x64.tar.gz` earlier but to no avail. However, this time I deleted the `_libvips' folder and tried again and it worked! Thanks anyways for the quick response! :)

**Comment by umeshv12** [comment]
same error
