### ISSUE TITLE
npm install with proxy: unable to get local issuer certificate

### ISSUE THREAD

**Issue by yanniks** [lovell/sharp#1618]
Hi,
unfortunately, I'm currently running into problems while downloading libvips from GitHub. The corporate proxy does SSL interception, that's why I already configured our Root CA inside the `.npmrc` file. Downloading the dependencies works fine, just the connection to GitHub fails. That's how my config file looks like:

```
ca="-----BEGIN CERTIFICATE-----\nOURCERTIFICATE\n-----END CERTIFICATE-----"
https-proxy="http://ourproxy:8080"
proxy="http://ourproxy:8080"
strict-ssl=false
```

That's the PowerShell output:
```
PS C:\Users\myuser\Desktop\myproject> npm install

> sharp@0.22.0 install C:\Users\myuser\Desktop\myproject\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-win32-x64.tar.gz
C:\Users\myuser\Desktop\myproject\node_modules\sharp\install\libvips.js:83
          throw err;
          ^

Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)

C:\Users\myuser\Desktop\myproject\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\myuser\Desktop\myproject\node_modules\sharp
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ma-app-odata@1.0.0 No description
npm WARN ma-app-odata@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2019-03-22T00_45_40_738Z-debug.log
PS C:\Users\myuser\Desktop\myproject>
```

Any ideas on what could cause that issue?

Thanks,
Yannik

**Comment by lovell** [comment]
Set the [NODE_EXTRA_CA_CERTS](https://nodejs.org/docs/latest-v8.x/api/cli.html#cli_node_extra_ca_certs_file) environment variable to point to a file containing your custom certificate.

**Comment by yanniks** [comment]
Thanks, that did the trick. I guess, the best way would be getting the npm config and checking whether any of the CA properties are set, afterwards it should be possible to pass them into `simple-get`. But since this way works, it's nothing too important 👍

**Comment by gigajoules** [comment]
> Set the [NODE_EXTRA_CA_CERTS](https://nodejs.org/docs/latest-v8.x/api/cli.html#cli_node_extra_ca_certs_file) environment variable to point to a file containing your custom certificate.

Noob question but how do I do this?
