### ISSUE TITLE
40r error when installing via npm with jenkins

### ISSUE THREAD

**Issue by Rody-Kirwan** [lovell/sharp#1633]
Node v10.13.0
NPM v6.4

CI installation breaks with 403 error when attempting to install 
`https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz`

```
> sharp@0.21.3 install /build/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

[91minfo[0m[91m sharp[0m[91m Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
[0m[91m/build/node_modules/sharp/install/libvips.js:81
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 403
    at /build/node_modules/sharp/install/libvips.js:81:17
    at f (/build/node_modules/once/once.js:25:25)
    at ClientRequest.protocol.request.res (/build/node_modules/simple-get/index.js:63:5)
```
Actually this is maybe not an issue with sharp but I wanted to make sure no-one else was having the same issue

**Comment by jaredh159** [comment]
I'm having the exact same issue on circle ci.

**Comment by jstayton** [comment]
This seems to be the same issue as https://github.com/lovell/sharp/issues/1632.

**Comment by lovell** [comment]
#1632
