### ISSUE TITLE
Cross Compile Sharp

### ISSUE THREAD

**Issue by neophob** [lovell/sharp#1715]
Hi

Thanks for the sharp lib! I need to cross compile sharp / libvips on my own and cannot rely on the existing binaries. I saw that in the `binding.gyp` file are references to most of the libvips deps:

```
            'libraries': [
              '../vendor/lib/libvips-cpp.so',
              '../vendor/lib/libvips.so',
              '../vendor/lib/libglib-2.0.so',
              '../vendor/lib/libgobject-2.0.so',
              # Dependencies of dependencies, included for openSUSE support
              '../vendor/lib/libcairo.so',
              '../vendor/lib/libcroco-0.6.so',
              '../vendor/lib/libexif.so',
              '../vendor/lib/libexpat.so',
              '../vendor/lib/libffi.so',
              '../vendor/lib/libfontconfig.so',
              '../vendor/lib/libfreetype.so',
              '../vendor/lib/libfribidi.so',
              '../vendor/lib/libgdk_pixbuf-2.0.so',
              '../vendor/lib/libgif.so',
              '../vendor/lib/libgio-2.0.so',
              '../vendor/lib/libgmodule-2.0.so',
              '../vendor/lib/libgsf-1.so',
              '../vendor/lib/libgthread-2.0.so',
              '../vendor/lib/libharfbuzz.so',
              '../vendor/lib/libjpeg.so',
              '../vendor/lib/liblcms2.so',
              '../vendor/lib/liborc-0.4.so',
              '../vendor/lib/libpango-1.0.so',
              '../vendor/lib/libpangocairo-1.0.so',
              '../vendor/lib/libpangoft2-1.0.so',
              '../vendor/lib/libpixman-1.so',
              '../vendor/lib/libpng.so',
              '../vendor/lib/librsvg-2.so',
              '../vendor/lib/libtiff.so',
              '../vendor/lib/libwebp.so',
              '../vendor/lib/libwebpdemux.so',
              '../vendor/lib/libwebpmux.so',
              '../vendor/lib/libxml2.so',
              '../vendor/lib/libz.so',
              # Ensure runtime linking is relative to sharp.node
              '-Wl,--disable-new-dtags -Wl,-rpath=\'$${ORIGIN}/../../vendor/lib\''
            ]
```
The question is - are those deps there because of libvips or are there there because sharp use those features?
My libvips installation for example does not include webp, svg and pango - so afaik i could remove those deps from the binding file. is that correct?

**Comment by lovell** [comment]
Hi, that list of shared libraries is used only when compiling sharp from source against the precompiled libvips binaries (which depend upon and include the listed dependencies).

If you're compiling sharp from source against a globally-installed libvips then that part of the binding.gyp file is ignored.

**Comment by neophob** [comment]
thanks @lovell, that make sense. its weird because the compilation failed when it tried to use exact those libs. ill dig deeper tomorrow and will paste some logs if it fails to compile

**Comment by neophob** [comment]
So I retried it, it looks like this:

```
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp Intel Architecture 32-bit systems require manual installation of libvips >= 8.6.1
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
make[1]: Entering directory '/home/foo/src/imageservice/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
i586-control4-linux-gnu-g++: error: ../vendor/lib/libvips-cpp.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libvips.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libglib-2.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgobject-2.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libcairo.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libcroco-0.6.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libexif.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libffi.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libfontconfig.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libfreetype.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgdk_pixbuf-2.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgif.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgio-2.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgmodule-2.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgsf-1.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libgthread-2.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libharfbuzz.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libjpeg.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/liblcms2.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libpng.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libtiff.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libwebp.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libxml2.so: No such file or directory
i586-control4-linux-gnu-g++: error: ../vendor/lib/libz.so: No such file or directory
sharp.target.mk:176: recipe for target 'Release/obj.target/sharp.node' failed
make[1]: *** [Release/obj.target/sharp.node] Error 1
make[1]: Leaving directory '/home/foo/src/imageservice/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by neophob** [comment]
I checked out this repo on the build machine and tried to compile from source using this command: `node-gyp clean configure build --verbose --arch=ia32`.

This failed with the same error:

```
parallels@parallels-Parallels-Virtual-Platform:home/foo/sharp-master$ PKG_CONFIG_PATH=/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/sysroot/lib/pkgconfig PKG_CONFIG_LIBDIR=/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib CPPFLAGS="-I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0" CC="i586-custom-linux-gnu-gcc  -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0 " LD="i586-custom-linux-gnu-ld " CXX="i586-custom-linux-gnu-g++ " CPP="i586-custom-linux-gnu-gcc -E -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0 " SHARP_IGNORE_GLOBAL_LIBVIPS=false ./node_modules/.bin/node-gyp clean configure build --verbose --arch=ia32
gyp info it worked if it ends with ok
gyp verb cli [ '/home/parallels/.nodenv/versions/6.10.3/bin/node',
gyp verb cli   '/home/foo/sharp-master/node_modules/.bin/node-gyp',
gyp verb cli   'clean',
gyp verb cli   'configure',
gyp verb cli   'build',
gyp verb cli   '--verbose',
gyp verb cli   '--arch=ia32' ]
gyp info using node-gyp@3.8.0
gyp info using node@6.10.3 | linux | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 6.10.3
gyp verb command install [ '6.10.3' ]
gyp verb install input version string "6.10.3"
gyp verb install installing version: 6.10.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.10.3
gyp verb build dir attempting to create "build" dir: /home/foo/sharp-master/build
gyp verb build dir "build" dir needed to be created? /home/foo/sharp-master/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/foo/sharp-master/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/foo/sharp-master/config.gypi
gyp verb common.gypi checking for gypi file: /home/foo/sharp-master/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/foo/sharp-master/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/foo/sharp-master/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/foo/sharp-master/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/parallels/.node-gyp/6.10.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/parallels/.node-gyp/6.10.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/foo/sharp-master/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/parallels/.node-gyp/6.10.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/foo/sharp-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir /home/parallels/.node-gyp/6.10.3
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/foo/sharp-master/build'
  touch Release/obj.target/libvips-cpp.stamp
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/metadata.o ../src/metadata.cc
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/stats.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/stats.o ../src/stats.cc
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/operations.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/operations.o ../src/operations.cc
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/pipeline.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/pipeline.o ../src/pipeline.cc
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/sharp.o ../src/sharp.cc
  i586-custom-linux-gnu-g++  '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/parallels/.node-gyp/6.10.3/include/node -I/home/parallels/.node-gyp/6.10.3/src -I/home/parallels/.node-gyp/6.10.3/deps/openssl/config -I/home/parallels/.node-gyp/6.10.3/deps/openssl/openssl/include -I/home/parallels/.node-gyp/6.10.3/deps/uv/include -I/home/parallels/.node-gyp/6.10.3/deps/zlib -I/home/parallels/.node-gyp/6.10.3/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/lib/glib-2.0/include -I/opt/x-tools/gcc-4.8.3-glibc-2.19/i586-custom-linux-gnu/i586-custom-linux-gnu/include/glib-2.0  -c -o Release/obj.target/sharp/src/utilities.o ../src/utilities.cc
  i586-custom-linux-gnu-g++  -shared -pthread -rdynamic -m32  -Wl,-soname=sharp.node -o Release/obj.target/sharp.node -Wl,--start-group Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/sharp.o Release/obj.target/sharp/src/utilities.o -Wl,--end-group ../vendor/lib/libvips-cpp.so ../vendor/lib/libvips.so ../vendor/lib/libglib-2.0.so ../vendor/lib/libgobject-2.0.so ../vendor/lib/libcairo.so ../vendor/lib/libcroco-0.6.so ../vendor/lib/libexif.so ../vendor/lib/libexpat.so ../vendor/lib/libffi.so ../vendor/lib/libfontconfig.so ../vendor/lib/libfreetype.so ../vendor/lib/libfribidi.so ../vendor/lib/libgdk_pixbuf-2.0.so ../vendor/lib/libgif.so ../vendor/lib/libgio-2.0.so ../vendor/lib/libgmodule-2.0.so ../vendor/lib/libgsf-1.so ../vendor/lib/libgthread-2.0.so ../vendor/lib/libharfbuzz.so ../vendor/lib/libjpeg.so ../vendor/lib/liblcms2.so ../vendor/lib/liborc-0.4.so ../vendor/lib/libpango-1.0.so ../vendor/lib/libpangocairo-1.0.so ../vendor/lib/libpangoft2-1.0.so ../vendor/lib/libpixman-1.so ../vendor/lib/libpng.so ../vendor/lib/librsvg-2.so ../vendor/lib/libtiff.so ../vendor/lib/libwebp.so ../vendor/lib/libwebpdemux.so ../vendor/lib/libwebpmux.so ../vendor/lib/libxml2.so ../vendor/lib/libz.so -Wl,--disable-new-dtags -Wl,-rpath='${ORIGIN}/../../vendor/lib'
i586-custom-linux-gnu-g++: error: ../vendor/lib/libvips-cpp.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libvips.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libglib-2.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgobject-2.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libcairo.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libcroco-0.6.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libexif.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libexpat.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libffi.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libfontconfig.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libfreetype.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libfribidi.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgdk_pixbuf-2.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgif.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgio-2.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgmodule-2.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgsf-1.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libgthread-2.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libharfbuzz.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libjpeg.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/liblcms2.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libpng.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libtiff.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libwebp.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libwebpdemux.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libwebpmux.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libxml2.so: No such file or directory
i586-custom-linux-gnu-g++: error: ../vendor/lib/libz.so: No such file or directory
sharp.target.mk:188: recipe for target 'Release/obj.target/sharp.node' failed
make: *** [Release/obj.target/sharp.node] Error 1
make: Leaving directory '/home/foo/sharp-master/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/foo/sharp-master/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-47-generic
```

**Comment by neophob** [comment]
> If you're compiling sharp from source against a globally-installed libvips then that part of the binding.gyp file is ignored.

So as I still see the `../vendor/lib/lib` references this means my globally-installed libvips is not detected , correct?

**Comment by neophob** [comment]
One thing which is definitive fishy is `SHARP_IGNORE_GLOBAL_LIBVIPS=false node -e "console.log(Boolean(require('./lib/libvips').useGlobalLibvips()).toString())"` -> which interprets false as true....

**Comment by lovell** [comment]
You'll need to remove/unset `SHARP_IGNORE_GLOBAL_LIBVIPS` if you want sharp to search for and use a globally-installed libvips.

Searching for and using a globally-installed libvips is the default behaviour; the mere presence of a environment variable named `SHARP_IGNORE_GLOBAL_LIBVIPS` prevents this.

https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries

**Comment by neophob** [comment]
It looks like that env parsing was the only issue here.

**Comment by lovell** [comment]
Glad you got it sorted - are you proposing a change to the docs?

**Comment by neophob** [comment]
not to the docs but if the env variable is set to false or 0 then evaluate it correctly

**Comment by lovell** [comment]
Great, thank you, parsing that env var via the `Boolean()` function should work.

**Comment by lovell** [comment]
I checked and the value of `SHARP_IGNORE_GLOBAL_LIBVIPS` is already parsed by `Boolean` - see https://github.com/lovell/sharp/blob/master/lib/libvips.js#L79 - is this still a problem?

**Comment by neophob** [comment]
argh, sorry forgot this, LGTM! Thanks
