### ISSUE TITLE
Input file is missing : Installation wrong or Path wrong ?

### ISSUE THREAD

**Issue by ThomasDelap** [lovell/sharp#1781]
**What is the output of running `npm install --verbose sharp`?**
No errors.

**What is the output of running `npx envinfo --binaries --languages --system --utilities`?**
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 1.26 GB / 7.95 GB
  Binaries:
    Yarn: 1.16.0 - C:\Users\Thomas\Documents\GitHub\CycloneIO\node_modules\.bin\yarn.CMD
    npm: 6.9.0 - C:\Users\Thomas\Documents\GitHub\CycloneIO\node_modules\.bin\npm.CMD
  Languages:
    Python: 3.7.3 - C:\Users\Thomas\AppData\Local\Programs\Python\Python37-32\python.EXE
```

I'm not sure if the error come from my input path or due to an error in installation or something else.

```
sharp('advanced_1.png').resize( 100 )
   .toFile( 'test-100.png', function ( error ) {
         // here I get the error
         console.log( error );
    });`` 

The error : **[Error: Input file is missing]**

Thanks.

**Comment by ThomasDelap** [comment]
OK, I tried with an blank project and now i have the error:

```
npm install sharp

> sharp@0.17.3 install C:\Users\Thomas\Documents\GitHub\example-sharp-master\node_modules\sharp
> node-gyp rebuild


C:\Users\Thomas\Documents\GitHub\example-sharp-master\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Thomas\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Thomas\Documents\GitHub\example-sharp-master\node_modules\sharp
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1```

I think that's due to Python 3

**Comment by lovell** [comment]
Node.js 12 support was added in v0.22.1.

https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019
