### ISSUE TITLE
` ERROR  Cannot find module 'sharp'`

### ISSUE THREAD

**Issue by OladutemuEben** [lovell/sharp#1845]
Been getting this error for a while now and it's frustrating.
Tried install the peer dependencies, same error.
Please help.
This is what I got when I ran `npm install --verbose sharp`

```
> `npm info it worked if it ends with ok
> 
> npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> npm verb cli   'C:\\Users\\E-ben\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> npm verb cli   'install',
> npm verb cli   '--verbose',
> npm verb cli   'sharp' ]
> npm info using npm@6.11.2
> npm info using node@v10.16.3
> npm verb npm-session a0a1ea22e4269d38
> npm http fetch GET 200 https://registry.npmjs.org/sharp 614ms
> npm timing stage:loadCurrentTree Completed in 8048ms
> npm timing stage:loadIdealTree:cloneCurrentTree Completed in 64ms
> npm timing stage:loadIdealTree:loadShrinkwrap Completed in 3150ms
> npm http fetch GET 304 https://registry.npmjs.org/detect-libc 2757ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/fs-copy-file-sync 2760ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 3839ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/tar 4123ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/simple-get 4618ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 4832ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/minimist 4939ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/github-from-package 4947ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 4946ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/noop-logger 4950ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/node-abi 5016ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/expand-template 5762ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/pump 6760ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/tar-fs 6899ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/semver 2561ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/decompress-response 3612ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/simple-concat 4393ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/mimic-response 350ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/tar-stream 257ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/buffer-alloc 307ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/fs-constants 405ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/to-buffer 516ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/bl 554ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/buffer-alloc-unsafe 318ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/buffer-fill 428ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/minizlib 235ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 256ms (from cache)
> npm http fetch GET 304 https://registry.npmjs.org/minipass 401ms (from cache)
> npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 31082ms
> npm timing stage:loadIdealTree Completed in 35573ms
> npm timing stage:generateActionsToTake Completed in 488ms
> npm verb correctMkdir C:\Users\E-ben\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
> npm verb makeCacheDir UID & GID are irrelevant on win32
> npm verb lock using C:\Users\E-ben\AppData\Roaming\npm-cache\_locks\staging-7e1d6a0558344c87.lock for C:\wamp64\www\BQA-Blog\node_modules\.staging
> npm timing audit submit Completed in 3382ms
> npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 3385ms
> npm timing audit body Completed in 17ms
> npm timing action:extract Completed in 13566ms
> npm timing action:finalize Completed in 3638ms
> npm timing action:refresh-package-json Completed in 16815ms
> npm info lifecycle bl@1.2.2~preinstall: bl@1.2.2
> npm info lifecycle buffer-alloc-unsafe@1.1.0~preinstall: buffer-alloc-unsafe@1.1.0
> npm info lifecycle buffer-fill@1.0.0~preinstall: buffer-fill@1.0.0
> npm info lifecycle buffer-alloc@1.2.0~preinstall: buffer-alloc@1.2.0
> npm info lifecycle detect-libc@1.0.3~preinstall: detect-libc@1.0.3
> npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
> npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
> npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
> npm info lifecycle mimic-response@1.0.1~preinstall: mimic-response@1.0.1
> npm info lifecycle decompress-response@3.3.0~preinstall: decompress-response@3.3.0
> npm info lifecycle minipass@2.4.0~preinstall: minipass@2.4.0
> npm info lifecycle fs-minipass@1.2.6~preinstall: fs-minipass@1.2.6
> npm info lifecycle minizlib@1.2.1~preinstall: minizlib@1.2.1
> npm info lifecycle napi-build-utils@1.0.1~preinstall: napi-build-utils@1.0.1
> npm info lifecycle semver@5.7.1~preinstall: semver@5.7.1
> npm info lifecycle node-abi@2.11.0~preinstall: node-abi@2.11.0
> npm info lifecycle noop-logger@0.1.1~preinstall: noop-logger@0.1.1
> npm info lifecycle minimist@1.2.0~preinstall: minimist@1.2.0
> npm info lifecycle pump@2.0.1~preinstall: pump@2.0.1
> npm info lifecycle simple-concat@1.0.0~preinstall: simple-concat@1.0.0
> npm info lifecycle simple-get@2.8.1~preinstall: simple-get@2.8.1
> npm info lifecycle pump@1.0.3~preinstall: pump@1.0.3
> npm info lifecycle to-buffer@1.1.1~preinstall: to-buffer@1.1.1
> npm info lifecycle tar-stream@1.6.2~preinstall: tar-stream@1.6.2
> npm info lifecycle tar-fs@1.16.3~preinstall: tar-fs@1.16.3
> npm info lifecycle which-pm-runs@1.0.0~preinstall: which-pm-runs@1.0.0
> npm info lifecycle fs-copy-file-sync@1.1.1~preinstall: fs-copy-file-sync@1.1.1
> npm info lifecycle prebuild-install@5.3.0~preinstall: prebuild-install@5.3.0
> npm info lifecycle tar@4.4.10~preinstall: tar@4.4.10
> npm info lifecycle simple-get@3.0.3~preinstall: simple-get@3.0.3
> npm info lifecycle sharp@0.22.1~preinstall: sharp@0.22.1
> npm timing action:preinstall Completed in 127ms
> npm info linkStuff bl@1.2.2
> npm info linkStuff buffer-alloc-unsafe@1.1.0
> npm info linkStuff buffer-fill@1.0.0
> npm info linkStuff buffer-alloc@1.2.0
> npm info linkStuff detect-libc@1.0.3
> npm verb linkBins [ { 'detect-libc': './bin/detect-libc.js' },
> npm verb linkBins   'C:\\wamp64\\www\\BQA-Blog\\node_modules\\.bin',
> npm verb linkBins   false ]
> npm info linkStuff expand-template@2.0.3
> npm info linkStuff fs-constants@1.0.0
> npm info linkStuff github-from-package@0.0.0
> npm info linkStuff mimic-response@1.0.1
> npm info linkStuff decompress-response@3.3.0
> npm info linkStuff minipass@2.4.0
> npm info linkStuff fs-minipass@1.2.6
> npm info linkStuff minizlib@1.2.1
> npm info linkStuff napi-build-utils@1.0.1
> npm info linkStuff semver@5.7.1
> npm verb linkBins [ { semver: './bin/semver' },
> npm verb linkBins   'C:\\wamp64\\www\\BQA-Blog\\node_modules\\node-abi\\node_modules\\.bin',
> npm verb linkBins   false ]
> npm info linkStuff node-abi@2.11.0
> npm info linkStuff noop-logger@0.1.1
> npm info linkStuff minimist@1.2.0
> npm info linkStuff pump@2.0.1
> npm info linkStuff simple-concat@1.0.0
> npm info linkStuff simple-get@2.8.1
> npm info linkStuff pump@1.0.3
> npm info linkStuff to-buffer@1.1.1
> npm info linkStuff tar-stream@1.6.2
> npm info linkStuff tar-fs@1.16.3
> npm info linkStuff which-pm-runs@1.0.0
> npm info linkStuff fs-copy-file-sync@1.1.1
> npm info linkStuff prebuild-install@5.3.0
> npm verb linkBins [ { 'prebuild-install': './bin.js' },
> npm verb linkBins   'C:\\wamp64\\www\\BQA-Blog\\node_modules\\.bin',
> npm verb linkBins   false ]
> npm info linkStuff tar@4.4.10
> npm info linkStuff simple-get@3.0.3
> npm info linkStuff sharp@0.22.1
> npm timing action:build Completed in 1091ms
> npm info lifecycle bl@1.2.2~install: bl@1.2.2
> npm info lifecycle buffer-alloc-unsafe@1.1.0~install: buffer-alloc-unsafe@1.1.0
> npm info lifecycle buffer-fill@1.0.0~install: buffer-fill@1.0.0
> npm info lifecycle buffer-alloc@1.2.0~install: buffer-alloc@1.2.0
> npm info lifecycle detect-libc@1.0.3~install: detect-libc@1.0.3
> npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
> npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
> npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
> npm info lifecycle mimic-response@1.0.1~install: mimic-response@1.0.1
> npm info lifecycle decompress-response@3.3.0~install: decompress-response@3.3.0
> npm info lifecycle minipass@2.4.0~install: minipass@2.4.0
> npm info lifecycle fs-minipass@1.2.6~install: fs-minipass@1.2.6
> npm info lifecycle minizlib@1.2.1~install: minizlib@1.2.1
> npm info lifecycle napi-build-utils@1.0.1~install: napi-build-utils@1.0.1
> npm info lifecycle semver@5.7.1~install: semver@5.7.1
> npm info lifecycle node-abi@2.11.0~install: node-abi@2.11.0
> npm info lifecycle noop-logger@0.1.1~install: noop-logger@0.1.1
> npm info lifecycle minimist@1.2.0~install: minimist@1.2.0
> npm info lifecycle pump@2.0.1~install: pump@2.0.1
> npm info lifecycle simple-concat@1.0.0~install: simple-concat@1.0.0
> npm info lifecycle simple-get@2.8.1~install: simple-get@2.8.1
> npm info lifecycle pump@1.0.3~install: pump@1.0.3
> npm info lifecycle to-buffer@1.1.1~install: to-buffer@1.1.1
> npm info lifecycle tar-stream@1.6.2~install: tar-stream@1.6.2
> npm info lifecycle tar-fs@1.16.3~install: tar-fs@1.16.3
> npm info lifecycle which-pm-runs@1.0.0~install: which-pm-runs@1.0.0
> npm info lifecycle fs-copy-file-sync@1.1.1~install: fs-copy-file-sync@1.1.1
> npm info lifecycle prebuild-install@5.3.0~install: prebuild-install@5.3.0
> npm info lifecycle tar@4.4.10~install: tar@4.4.10
> npm info lifecycle simple-get@3.0.3~install: simple-get@3.0.3
> npm info lifecycle sharp@0.22.1~install: sharp@0.22.1
> 
> > sharp@0.22.1 install C:\wamp64\www\BQA-Blog\node_modules\sharp
> > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> 
> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-win32-x64.tar.gz
> C:\wamp64\www\BQA-Blog\node_modules\sharp\install\libvips.js:83
>           throw err;
>           ^
> 
> Error: tunneling socket could not be established, statusCode=405
>     at ClientRequest.onConnect (C:\wamp64\www\BQA-Blog\node_modules\tunnel-agent\index.js:166:19)
>     at Object.onceWrapper (events.js:286:20)
>     at ClientRequest.emit (events.js:198:13)
>     at Socket.socketOnData (_http_client.js:475:11)
>     at Socket.emit (events.js:198:13)
>     at addChunk (_stream_readable.js:288:12)
>     at readableAddChunk (_stream_readable.js:269:11)
>     at Socket.Readable.push (_stream_readable.js:224:10)
>     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> 
> C:\wamp64\www\BQA-Blog\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\E-ben\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\E-ben\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp info it worked if it ends with ok
> gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'C:\\Users\\E-ben\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild' ]
> gyp info using node-gyp@5.0.3
> gyp info using node@10.16.3 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb find Python Python is not set from command line or npm configuration
> gyp verb find Python Python is not set from environment variable PYTHON
> gyp verb find Python checking if "python" can be used
> gyp verb find Python - executing "python" to get executable path
> gyp verb find Python - "python" is not in PATH or produced an error
> gyp verb find Python checking if "python2" can be used
> gyp verb find Python - executing "python2" to get executable path
> gyp verb find Python - "python2" is not in PATH or produced an error
> gyp verb find Python checking if the py launcher can be used to find Python 2
> gyp verb find Python - executing "py.exe" to get Python 2 executable path
> gyp verb find Python - "py.exe" is not in PATH or produced an error
> gyp verb find Python checking if Python is C:\Python27\python.exe
> gyp verb find Python - executing "C:\Python27\python.exe" to get version
> gyp verb find Python - version is "2.7.0"
> gyp info find Python using Python version 2.7.0 found at "C:\Python27\python.exe"
> gyp verb get node dir no --target version specified, falling back to host node version: 10.16.3
> gyp verb command install [ '10.16.3' ]
> gyp verb install input version string "10.16.3"
> gyp verb install installing version: 10.16.3
> gyp verb install --ensure was passed, so won't reinstall if already installed
> gyp verb install version not already installed, continuing with install 10.16.3
> gyp verb ensuring nodedir is created C:\Users\E-ben\AppData\Local\node-gyp\Cache\10.16.3
> gyp verb created nodedir C:\Users\E-ben\AppData\Local\node-gyp\Cache\10.16.3
> gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
> gyp WARN download ignoring invalid "proxy" config setting: "composer create-project symfony/website-skeleton startsym"
> gyp WARN install got an error, rolling back install
> gyp verb command remove [ '10.16.3' ]
> gyp verb remove using node-gyp dir: C:\Users\E-ben\AppData\Local\node-gyp\Cache
> gyp verb remove removing target version: 10.16.3
> gyp verb remove removing development files for version: 10.16.3
> gyp ERR! configure error
> gyp ERR! stack Error: tunneling socket could not be established, statusCode=405
> gyp ERR! stack     at ClientRequest.onConnect (C:\Users\E-ben\AppData\Roaming\npm\node_modules\npm\node_modules\tunnel-agent\index.js:166:19)
> gyp ERR! stack     at Object.onceWrapper (events.js:286:20)
> gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
> gyp ERR! stack     at Socket.socketOnData (_http_client.js:475:11)
> gyp ERR! stack     at Socket.emit (events.js:198:13)
> gyp ERR! stack     at addChunk (_stream_readable.js:288:12)
> gyp ERR! stack     at readableAddChunk (_stream_readable.js:269:11)
> gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:224:10)
> gyp ERR! stack     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\E-ben\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\wamp64\www\BQA-Blog\node_modules\sharp
> gyp ERR! node -v v10.16.3
> gyp ERR! node-gyp -v v5.0.3
> gyp ERR! not ok
> npm verb lifecycle sharp@0.22.1~install: unsafe-perm in lifecycle true
> npm verb lifecycle sharp@0.22.1~install: PATH: C:\Users\E-ben\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\wamp64\www\BQA-Blog\node_modules\sharp\node_modules\.bin;C:\wamp64\www\BQA-Blog\node_modules\.bin;C:\Program Files (x86)\Common
> Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\ComposerSetup\bin;C:\wamp64\bin\php\php7.2.4;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Symfony;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Users\E-ben\AppData\Roaming\Composer\vendor\bin;C:\Users\E-ben\AppData\Local\Microsoft\WindowsApps;;C:\Users\E-ben\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\E-ben\AppData\Roaming\npm;C:\Program Files\JetBrains\WebStorm 2019.1.3\bin;;C:\Program Files\heroku\bin
> npm verb lifecycle sharp@0.22.1~install: CWD: C:\wamp64\www\BQA-Blog\node_modules\sharp
> npm info lifecycle sharp@0.22.1~install: Failed to exec install script
> npm timing action:install Completed in 24519ms
> npm verb unlock done using C:\Users\E-ben\AppData\Roaming\npm-cache\_locks\staging-7e1d6a0558344c87.lock for C:\wamp64\www\BQA-Blog\node_modules\.staging
> npm timing stage:rollbackFailedOptional Completed in 2065ms
> npm timing stage:runTopLevelLifecycles Completed in 107020ms
> npm WARN react-redux@4.4.10 requires a peer of redux@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN slate-edit-list@0.11.3 requires a peer of slate@^0.32.0 but none is installed. You must install peer dependencies yourself.
> npm WARN slate-edit-table@0.15.2 requires a peer of slate@^0.33.3 but none is installed. You must install peer dependencies yourself.
> npm WARN nuxtlify@1.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\nodemon\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
> npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> 
> npm verb stack Error: sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
> npm verb stack Exit status 1
> npm verb stack     at EventEmitter.<anonymous> (C:\Users\E-ben\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> npm verb stack     at EventEmitter.emit (events.js:198:13)
> npm verb stack     at ChildProcess.<anonymous> (C:\Users\E-ben\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> npm verb stack     at ChildProcess.emit (events.js:198:13)
> npm verb stack     at maybeClose (internal/child_process.js:982:16)
> npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> npm verb pkgid sharp@0.22.1
> npm verb cwd C:\wamp64\www\BQA-Blog
> npm verb Windows_NT 10.0.17763
> npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\E-ben\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
> npm verb node v10.16.3
> npm verb npm  v6.11.2
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sharp@0.22.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm verb exit [ 1, true ]
> npm timing npm Completed in 112419ms
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\E-ben\AppData\Roaming\npm-cache\_logs\2019-08-24T00_33_07_925Z-debug.log`
```

**Comment by lovell** [comment]
The salient part of this error is:
```
Error: tunneling socket could not be established, statusCode=405
```
This suggests you're using a web proxy via one of the environment variables listed in https://github.com/lovell/sharp/blob/69fe21a7ec45df526461c4bf308332344112169a/lib/agent.js#L8-L15
so perhaps check it is configured correctly.
