### ISSUE TITLE
Module initialization error on using Sharp in AWS lambda functions.

### ISSUE THREAD

**Issue by FrozenIce0617** [lovell/sharp#1853]
I create a Lambda function with NodeJS 8.10 Runtime environment.

Basically, I'm trying to resize and convert file format from the existing file on S3 bucket and upload it again to another bucket.
I choose Sharp for image manipulation.

```
async.waterfall(
    [
      function download(next) {
        // Download the image from S3 into a buffer.
        s3
          .getObject({
            Bucket: srcBucket,
            Key: srcKey
          })
          .promise()
          .then(data => sharp(data.Body).toFormat('png').toBuffer())
          .then(buffer => s3.putObject({
            Bucket: dstBucket,
            Key: dstKey,
            Body: buffer,
            ContentType: ''
          }));
      },
      function transform(response, next) {
        console.log(`HERE IS RESPONSE: ${response}`);
        console.log(`HERE IS RESPONSE BODY: ${response.Body}`);
        sharp(response.Body)
          .toFormat('png')
          .toBuffer()
          .then(data => next(null, response.ContentType, data))
          .catch(err => next(err));
      },
      function upload(contentType, data, next) {
        // Stream the transformed image to a different S3 bucket.
        console.log(`HERE IS data: ${data}, contentType: ${contentType}`);
        s3.putObject(
          {
            Bucket: dstBucket,
            Key: dstKey,
            Body: data,
            ContentType: contentType
          },
          next
        );
      }
    ],
    ...
```

Btw, I got an error like this:

```
module initialization error: Error
at Object.hasVendoredLibvips (/var/task/node_modules/sharp/lib/libvips.js:67:13)
at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:8:22)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/sharp/lib/index.js:3:15)
```

Here's my log of install the sharp:
```
npm install --arch=x64 --platform=linux --target=10.15.0 sharp
```

Any suggestion is appreciated.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/install/#aws-lambda

The use of `--target=10.15.0` at install time refers to the use of Node.js 10 at runtime. These need to match, so if you're using Node.js 8 at runtime change this as appropriate at install time.

**Comment by lovell** [comment]
Hope this helped, please reopen with more details if not.
