### ISSUE TITLE
install on musl-based Raspberry Pi arch64 fail 

### ISSUE THREAD

**Issue by unwenliu** [lovell/sharp#1893]
```
> sharp@0.23.1 install /app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linuxmusl-arm64v8.tar.gz
/app/node_modules/sharp/install/libvips.js:85
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 404
    at /app/node_modules/sharp/install/libvips.js:85:17
    at f (/app/node_modules/once/once.js:25:25)
    at ClientRequest.protocol.request.res (/app/node_modules/simple-get/index.js:63:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
```

**Comment by lovell** [comment]
Hi, prebuilt libvips binaries are not provided for musl-based Linux on ARM64.

If you're using Alpine then see https://sharp.pixelplumbing.com/en/stable/install/#alpine-linux
