### ISSUE TITLE
preinstall.sh and libjpeg-turbo8-dev

### ISSUE THREAD

**Issue by Zewy** [lovell/sharp#190]
Sems that libjpeg-turbo8-dev have bin renamed to libjpeg-dev?

preinstall.sh don't work on my Debian 7 get this error:
E: unable to locate package libjpeg-turbo8-dev

**Comment by lovell** [comment]
Good spot, thanks @Zewy. Are you able to test the fixed version on the judgement branch?
```sh
curl -s https://github.com/lovell/sharp/blob/judgement/preinstall.sh | sudo bash -
```

**Comment by Zewy** [comment]
The install worked now but if I use "webp()" I get this error "VipsOperation: class "webpsave_buffer" not found" at /home/node/node_modules/sharp/index.js:566:30

> Installed libvips 7.42.3
> root@sharp:/home/node# npm install sharp
> sharp@0.9.3 install /home/node/node_modules/sharp
> node-gyp rebuild

**Comment by lovell** [comment]
The version of libwebp-dev on Debian 7 (0.1.x?) is too old for libvips to use (IIRC it doesn't support an alpha channel). The preinstall script tries to add a PPA from which to upgrade libwebp but this step will fail on Debian.

Are you able to manually install libwebp-dev >= 0.4.0 before running the preinstall script? You may need to run `sudo make uninstall` from the vips-7.42.3 directory first.

**Comment by Zewy** [comment]
Can you point me to a guide how to install that libwebp-dev? 

wheezy-backports only have Version: 0.1.3-3+nmu1 of libwebp-dev

**Comment by lovell** [comment]
Follow https://developers.google.com/speed/webp/docs/compiling#building then run `sudo ldconfig`.

**Comment by Zewy** [comment]
Same problem tryed this on a clean install of debian 7
```
aptitude -t wheezy-backports install libjpeg-dev libpng-dev libtiff-dev libgif-dev

wget http://downloads.webmproject.org/releases/webp/libwebp-0.4.3.tar.gz

tar xvzf libwebp-0.4.3.tar.gz

 cd libwebp-0.4.3
 ./configure
 make
 make install
 
 ldconfig
 
 
 aptitude -t wheezy-backports install nodejs curl pkg-config
 
 curl -s https://raw.githubusercontent.com/lovell/sharp/judgement/preinstall.sh | bash -

**Comment by lovell** [comment]
When running preinstall.sh did the output include lines starting with `checking for LIBWEBP` or `file import/export with libwebp`? If so, what did they say?

**Comment by Zewy** [comment]
```
root@sharp:/home/user#  curl -s https://raw.githubusercontent.com/lovell/sharp/judgement/preinstall.sh | bash -
bash: line 269: add-apt-repository: command not found
libwebp-dev is already the newest version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6762k  100 6762k    0     0  2279k      0  0:00:02  0:00:02 --:--:-- 2342k
configure: WARNING: unrecognized options: --enable-cxx
configure: WARNING: libgsf-1 not found; disabling dzsave support
configure: WARNING: OpenSlide >= 3.3.0 not found; disabling virtual slide support
configure: WARNING: matio not found; disabling matio support
configure: WARNING: cfitsio not found; disabling cfitsio support
configure: WARNING: libwebp not found; disabling libwebp support
configure: WARNING: pangoft2 not found; disabling pangoft2 support
configure: WARNING: pygobject-3.0 not found; disabling vips8 python support
configure: WARNING: unrecognized options: --enable-cxx
file import/export with libwebp:        no

**Comment by lovell** [comment]
Please can you check that pkg-config, upon which libvips [relies](https://github.com/jcupitt/libvips/blob/master/configure.ac#L594), is aware of libwebp by running:
```sh
pkg-config --modversion libwebp
```
(Perhaps pkg-config needs to be installed before libwebp?)

**Comment by Zewy** [comment]
What OS will this work flawless on? seems like Debian 7 is't ready for all of Sharp's awesome features!
Do you have time to try the install on a clean Debian 7? tryed 5 times from a clean install with out any luck to get webp to work. I got the other image formats to work and made a nice http image quarry to work as I liked it to thanks to sharp just this thing left to fix.
```
root@sharp:/home/user/libwebp-0.4.3# pkg-config --modversion libwebp
Package libwebp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libwebp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libwebp' found
root@sharp:/home/user/libwebp-0.4.3#

**Comment by Zewy** [comment]
Finally got it to work now with webp is there a script in Sharp I can run to test that all features are working?
I did run make install one more time and I got this result and now it works, weird that I had to run it two times.
```
root@sharp:/home/user/libwebp-0.4.3# pkg-config --modversion libwebp
0.4.3

**Comment by lovell** [comment]
Great to hear you got it working. Looks like it was a pkg-config vs libwebp thing.

The following will checkout the latest code from git, compile and run all functional  tests.
```sh
cd /tmp
git clone https://github.com/lovell/sharp
cd sharp
git checkout judgement
npm i
npm t
```

**Comment by Zewy** [comment]
Now I got a working install for Debian7 here is how I did it.
note that in Debian8 add-apt-repository is in software-properties-common not in python-software-properties
```
aptitude -t wheezy-backports install nodejs curl pkg-config python-software-properties build-essential

curl -O http://downloads.webmproject.org/releases/webp/libwebp-0.4.3.tar.gz
tar xvzf libwebp-0.4.3.tar.gz
cd libwebp-0.4.3
./configure
make
make install
ldconfig
pkg-config --modversion libwebp

curl -s https://raw.githubusercontent.com/lovell/sharp/judgement/preinstall.sh | bash -

**Comment by Zewy** [comment]
This is what I got. with npm i and npm t
```
root@sharp:/tmp/sharp# npm i
npm WARN cannot run in wd sharp@0.10.0 node-gyp rebuild (wd=/tmp/sharp)
async@0.9.0 node_modules/async

nan@1.7.0 node_modules/nan

semver@4.3.3 node_modules/semver

....

root@sharp:/tmp/sharp# npm t

> sharp@0.10.0 test /tmp/sharp
> VIPS_WARNING=0 node ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- --slow=5000 --timeout=10000 ./test/unit/*.js

=============================================================================
Writing coverage object [/tmp/sharp/coverage/coverage.json]
Writing coverage reports at [/tmp/sharp/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 2.72% ( 8/294 )
Branches     : 0% ( 0/233 )
Functions    : 0% ( 0/59 )
Lines        : 2.72% ( 8/294 )
================================================================================

module.js:340
    throw err;
          ^
Error: Cannot find module './build/Release/sharp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/sharp/index.js:9:519)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions.(anonymous function) [as .js] (/tmp/sharp/node_modules/istanbul/lib/hook.js:105:24)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/sharp/test/unit/alpha.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/tmp/sharp/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /tmp/sharp/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/tmp/sharp/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/tmp/sharp/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/tmp/sharp/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/tmp/sharp/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (/tmp/sharp/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /tmp/sharp/node_modules/istanbul/lib/command/common/run-with-cover.js:248:17
    at /tmp/sharp/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /tmp/sharp/node_modules/async/lib/async.js:254:17
    at done (/tmp/sharp/node_modules/async/lib/async.js:135:19)
    at /tmp/sharp/node_modules/async/lib/async.js:32:16
    at /tmp/sharp/node_modules/async/lib/async.js:251:21
    at LOOP (fs.js:1367:14)
    at process._tickCallback (node.js:419:13)
npm ERR! Test failed.  See above for more details.

**Comment by lovell** [comment]
Perhaps try without being root - see also http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

**Comment by Zewy** [comment]
I logged in as user instead and it worked with out any problems.
here is the report did see only green checks on all tests so all is okej then?
```
=============================== Coverage summary ===============================
Statements   : 97.28% ( 286/294 )
Branches     : 96.14% ( 224/233 )
Functions    : 100% ( 59/59 )
Lines        : 97.28% ( 286/294 )
================================================================================

**Comment by lovell** [comment]
Yes, all green tests = success, that's great news.

**Comment by Zewy** [comment]
You are awesome! Thanks for all the help @lovell now I'm ready to replace my PHP image script with your Sharp nodejs instead :)

**Comment by lovell** [comment]
No probs. If you're able to share details publicly, #35 awaits you.
