### ISSUE TITLE
Instaling with node 13.0.1 fails

### ISSUE THREAD

**Issue by josegl** [lovell/sharp#1935]
O.S. = GNU/Linux Distro Manjaro 18 KDE 64bits
Kernel = 5.3.6
Node version = 13.0.1

Doing `npm install sharp` outputs
```
> npm i sharp

> sharp@0.22.1 install /home/jgl/dev/canalcar/mapp/mapi/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/jgl/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.0.1 runtime=node arch=x64 libc= platform=linux)
make: se entra en el directorio 'project_dir/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: En la función miembro ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
  130 |         channels->Set(i, channelStat);
      |                                     ^
In file included from /home/jgl/.cache/node-gyp/13.0.1/include/node/node.h:63,
                 from ../src/stats.cc:19:
/home/jgl/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: nota: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3416 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/jgl/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: nota:   el candidato espera 3 argumentos, se proporcionaron 2
/home/jgl/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: nota: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3419 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/jgl/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: nota:   el candidato espera 3 argumentos, se proporcionaron 2
make: *** [sharp.target.mk:136: Release/obj.target/sharp/src/stats.o] Error 1
make: se sale del directorio '/home/jgl/dev/canalcar/mapp/mapi/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.6-1-MANJARO
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jgl/dev/canalcar/mapp/mapi/node_modules/sharp
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN acorn-jsx@5.0.2 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jgl/.npm/_logs/2019-10-24T09_27_02_950Z-debug.log
```

**Comment by faradaytrs** [comment]
Worked for me
