### ISSUE TITLE
node 0.12 self register error

### ISSUE THREAD

**Issue by ali-bugdayci** [lovell/sharp#196]
Getting "Error: Module did not self-register." on node 0.12.2

Using sharp from the grunt-sharp module. Sharp version: "sharp": "~0.9.3". 
https://github.com/unindented/grunt-sharp/issues/3

But after your comment I ran the grunt task verbose, and as you have said the cause might be sharp module:

```
Registering "grunt-sharp" local Npm module tasks.
Reading /home/bor/sunucu/mdm-server/node_modules/grunt-sharp/package.json...OK
Parsing /home/bor/sunucu/mdm-server/node_modules/grunt-sharp/package.json...OK
Loading "sharp.js" tasks...ERROR
>> Error: Module did not self-register.
>>     at Error (native)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/home/bor/sunucu/mdm-server/node_modules/grunt-sharp/node_modules/sharp/index.js:11:13)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.module.exports (/home/bor/sunucu/mdm-server/node_modules/grunt-sharp/tasks/sharp.js:8:15)
>>     at loadTask (/home/bor/sunucu/mdm-server/node_modules/grunt/lib/grunt/task.js:325:10)
>>     at /home/bor/sunucu/mdm-server/node_modules/grunt/lib/grunt/task.js:361:7
>>     at Array.forEach (native)
```

**Comment by lovell** [comment]
The version of Node.js used at compile time, that is when `npm install` is run, needs to be the same as the version of Node.js used at runtime.

Perhaps you've recently upgraded Node.js version? If so, try running `npm rebuild` to recompile against that new version.

**Comment by lovell** [comment]
@ali-bugdayci Were you able to make any progress with this problem?

**Comment by ali-bugdayci** [comment]
Yeah, sorry.

You were right about it. Thanks for the fast response. Closing it
