### ISSUE TITLE
Problems installing Sharp on production Linux Red Hat server

### ISSUE THREAD

**Issue by ZeldOcarina** [lovell/sharp#1988]
Hello!

I am trying to install sharp into a production VPS with pm2 but it won't install and I get a 404 on NGINX.

This is my log:

```
> node-pty@0.9.0 install /home/Mattia/casalugano-test/node_modules/node-pty
> node scripts/install.js

make: Entering directory `/home/Mattia/casalugano-test/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: execvp: g++: Permission denied
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory `/home/Mattia/casalugano-test/node_modules/node-pty/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Mattia/casalugano-test/node_modules/node-pty
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

> sharp@0.23.3 install /home/Mattia/casalugano-test/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/Mattia/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
npm WARN multer-sharp-s3@0.1.0 requires a peer of sharp@>=0.170 <= 0.20.8 but none is installed. You must install peer dependencies yourself.
npm WARN casa-lugano@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/ndb/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pty@0.9.0 (node_modules/node-pty):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pty@0.9.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ sharp@0.23.3
updated 1 package and audited 11752 packages in 9.038s
found 0 vulnerabilities
```

Node Version: 10.17.0
npm Version: 6.11.3

I have tried everything, it works smoothly on localhost of my machine, I can install and coded the features needed but now it crashes my production server and I've had to revert to previous version to get the app back up.

Any suggestions?

**Comment by lovell** [comment]
The error in this log is from the [node-pty](https://github.com/microsoft/node-pty) module so you'll need to ask there.
