### ISSUE TITLE
Heroku deploy node js throws an exception while upload

### ISSUE THREAD

**Issue by agnoam** [lovell/sharp#1989]
I'm trying to upload my node js project to Heroku dyno, but it throws an exception:
```
error /tmp/build_755631c88ee4f6fb1fc1224ca742cb81/node_modules/sharp: Command failed.
remote:        Exit code: 1
remote:        Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
remote:        Arguments:
remote:        Directory: /tmp/build_755631c88ee4f6fb1fc1224ca742cb81/node_modules/sharp
remote:        Output:
remote:        info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
remote:        make: Entering directory '/tmp/build_755631c88ee4f6fb1fc1224ca742cb81/node_modules/sharp/build'
remote:          TOUCH Release/obj.target/libvips-cpp.stamp
remote:          CXX(target) Release/obj.target/sharp/src/common.o
remote:        In file included from ../src/common.cc:27:0:
remote:        ../src/common.h:82:20: error: ‘Handle’ is not a member of ‘v8’
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
remote:                            ^~~~~~
remote:        ../src/common.h:82:37: error: expected primary-expression before ‘>’ token
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                             ^
remote:        ../src/common.h:82:39: error: ‘obj’ was not declared in this scope
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                               ^~~
remote:        ../src/common.h:82:56: error: expected primary-expression before ‘attr’
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                                                ^~~~
remote:        ../src/common.h:82:60: error: expression list treated as compound expression in initializer [-fpermissive]
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                                                    ^
remote:        ../src/common.h:83:29: error: ‘Handle’ is not a member of ‘v8’
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                     ^~~~~~
remote:        ../src/common.h:83:46: error: expected primary-expression before ‘>’ token
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                                      ^
remote:        ../src/common.h:83:48: error: ‘obj’ was not declared in this scope
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                                        ^~~
remote:        ../src/common.h:83:65: error: expected primary-expression before ‘attr’
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
remote:                                                                         ^~~~
remote:        ../src/common.h:84:48: error: ‘Handle’ is not a member of ‘v8’
remote:           template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                        ^~~~~~
remote:        ../src/common.h:84:65: error: expected primary-expression before ‘>’ token
remote:           template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                         ^
remote:        ../src/common.h:84:67: error: ‘obj’ was not declared in this scope
remote:           template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                           ^~~
remote:        ../src/common.h:84:84: error: expected primary-expression before ‘attr’
remote:           template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                                            ^~~~
remote:        ../src/common.h:84:37: warning: variable templates only available with -std=c++14 or -std=gnu++14
remote:           template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                             ^~~~~~
remote:        ../src/common.h:84:90: error: expected ‘;’ before ‘{’ token
remote:           template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                                                  ^
remote:        ../src/common.h:87:37: error: ‘Handle’ is not a member of ‘v8’
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                             ^~~~~~
remote:        ../src/common.h:87:54: error: expected primary-expression before ‘>’ token
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                              ^
remote:        ../src/common.h:87:56: error: ‘obj’ was not declared in this scope
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                ^~~
remote:        ../src/common.h:87:73: error: expected primary-expression before ‘attr’
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                                 ^~~~
remote:        ../src/common.h:87:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                  ^~~~~~
remote:        ../src/common.h:87:79: error: expected ‘;’ before ‘{’ token
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                                       ^
remote:        ../src/common.h:90:37: error: ‘Handle’ is not a member of ‘v8’
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
remote:                                             ^~~~~~
remote:        ../src/common.h:90:54: error: expected primary-expression before ‘>’ token
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
remote:                                                              ^
remote:        ../src/common.h:90:56: error: ‘obj’ was not declared in this scope
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
remote:                                                                ^~~
remote:        ../src/common.h:90:61: error: expected primary-expression before ‘int’
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
remote:                                                                     ^~~
remote:        ../src/common.h:87:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                  ^~~~~~
remote:        ../src/common.h:90:71: error: expected ‘;’ before ‘{’ token
remote:           template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
remote:                                                                               ^
remote:        ../src/common.h:96:9: error: ‘Handle’ is not a member of ‘v8’
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                 ^~~~~~
remote:        ../src/common.h:96:26: error: expected primary-expression before ‘>’ token
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                                  ^
remote:        ../src/common.h:96:28: error: ‘input’ was not declared in this scope
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                                    ^~~~~
remote:        ../src/common.h:96:28: note: suggested alternative: ‘ino_t’
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                                    ^~~~~
remote:                                    ino_t
remote:        ../src/common.h:96:70: error: expected primary-expression before ‘&’ token
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                                                                              ^
remote:        ../src/common.h:96:71: error: ‘buffersToPersist’ was not declared in this scope
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                                                                               ^~~~~~~~~~~~~~~~
remote:        ../src/common.h:96:87: error: expression list treated as compound expression in initializer [-fpermissive]
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
remote:                                                                                               ^
remote:        ../src/common.cc:34:20: error: redefinition of ‘bool sharp::HasAttr’
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                            ^~~~~~
remote:        In file included from ../src/common.cc:27:0:
remote:        ../src/common.h:82:8: note: ‘bool sharp::HasAttr’ previously defined here
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
remote:                ^~~~~~~
remote:        ../src/common.cc:34:20: error: ‘Handle’ is not a member of ‘v8’
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                            ^~~~~~
remote:        ../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                             ^
remote:        ../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                               ^~~
remote:        ../src/common.cc:34:56: error: expected primary-expression before ‘attr’
remote:           bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                ^~~~
remote:        ../src/common.cc:37:29: error: redefinition of ‘std::string sharp::AttrAsStr’
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                     ^~~~~~
remote:        In file included from ../src/common.cc:27:0:
remote:        ../src/common.h:83:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
remote:                       ^~~~~~~~~
remote:        ../src/common.cc:37:29: error: ‘Handle’ is not a member of ‘v8’
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                     ^~~~~~
remote:        ../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                      ^
remote:        ../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                        ^~~
remote:        ../src/common.cc:37:65: error: expected primary-expression before ‘attr’
remote:           std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
remote:                                                                         ^~~~
remote:        ../src/common.cc:43:9: error: redefinition of ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                 ^~~~~~
remote:        In file included from ../src/common.cc:27:0:
remote:        ../src/common.h:95:20: note: ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’ previously defined here
remote:           InputDescriptor* CreateInputDescriptor(
remote:                            ^~~~~~~~~~~~~~~~~~~~~
remote:        ../src/common.cc:43:9: error: ‘Handle’ is not a member of ‘v8’
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                 ^~~~~~
remote:        ../src/common.cc:43:26: error: expected primary-expression before ‘>’ token
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                                  ^
remote:        ../src/common.cc:43:28: error: ‘input’ was not declared in this scope
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                                    ^~~~~
remote:        ../src/common.cc:43:28: note: suggested alternative: ‘ino_t’
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                                    ^~~~~
remote:                                    ino_t
remote:        ../src/common.cc:43:70: error: expected primary-expression before ‘&’ token
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                                                                              ^
remote:        ../src/common.cc:43:71: error: ‘buffersToPersist’ was not declared in this scope
remote:             v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
remote:                                                                               ^~~~~~~~~~~~~~~~
remote:        sharp.target.mk:134: recipe for target 'Release/obj.target/sharp/src/common.o' failed
remote:        make: Leaving directory '/tmp/build_755631c88ee4f6fb1fc1224ca742cb81/node_modules/sharp/build'
remote:        make: *** [Release/obj.target/sharp/src/common.o] Error 1
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_755631c88ee4f6fb1fc1224ca742cb81/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)   
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
remote:        gyp ERR! System Linux 4.4.0-1048-aws
remote:        gyp ERR! command "/tmp/build_755631c88ee4f6fb1fc1224ca742cb81/.heroku/node/bin/node" "/tmp/build_755631c88ee4f6fb1fc1224ca742cb81/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_755631c88ee4f6fb1fc1224ca742cb81/node_modules/sharp
remote:        gyp ERR! node -v v12.13.1
remote:        gyp ERR! node-gyp -v v5.0.5
remote:        gyp ERR! not ok
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote: 
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
```

What do I need to do ?

**Comment by lovell** [comment]
Node.js 12 support was added in sharp v0.22.1

https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019

**Comment by agnoam** [comment]
Thanks a lot for your help, I tried to update to the latest version of sharp. But it still throws this exception.

I found something that very strange here. Because I don't use sharp at all.
Here all the dependencies that I use for my project:
```
  "dependencies": {
    "body-parser": "1.18.3",
    "cloudinary": "1.11.0",
    "exif": "0.6.0",
    "express": "4.16.2",
    "firebase-admin": "7.3.0",
    "folder-zip": "0.0.5",
    "jsonwebtoken": "8.5.1",
    "md5": "2.2.1",
    "multer": "1.3.0",
    "rimraf": "2.6.2",
    "socket.io": "2.0.4"
  },
  "devDependencies": {
    "@types/express": "4.16.1",
    "@types/jest": "24.0.12",
    "@types/md5": "2.1.33",
    "@types/multer": "1.3.7",
    "@types/nock": "10.0.1",
    "@types/node": "12.0.0",
    "@types/rimraf": "2.0.2",
    "@types/socket.io": "2.1.2",
    "@types/socket.io-client": "1.4.32",
    "jest": "24.7.1",
    "nock": "10.0.6",
    "socket.io-client": "2.2.0",
    "ts-jest": "24.0.2",
    "ts-loader": "6.0.4",
    "ts-node": "^8.5.2",
    "tslint": "5.16.0",
    "typescript": "3.5.3",
    "webpack": "^4.41.2",
    "webpack-cli": "3.3.2",
    "webpack-node-externals": "1.7.2"
  }
```

So where did this exception come from ?
More thing, on my workstation (runs Windows 10) this exception doesn't exist.

**Comment by alma765** [comment]
i am experiencing the same issue!
