### ISSUE TITLE
Azure installation error.

### ISSUE THREAD

**Issue by osvald0** [lovell/sharp#2001]
When I try to deploy a node js to azure web app I get the following error:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 10 -i /tmp/8d779da98bb1aae -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20191105.2, Commit: 67e159d71419415435cb5d10c05a0f0758ee8809, ReleaseTagName: 20191105.2
Build Operation ID: |cxMo9rHsEEE=.a39964ac_
Repository Commit : 2729c7872142773072a449ffc8648d197e64fd7a

Warning: An outdated version of node was detected (10.17.0). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx

Using intermediate directory '/tmp/8d779da98bb1aae'.

Copying files to the intermediate directory...
Done in 1 sec(s).

Source directory     : /tmp/8d779da98bb1aae
Destination directory: /home/site/wwwroot


Using Node version:
v10.17.0

Using Yarn version:
1.17.3

Configuring Yarn cache folder...
yarn config v1.17.3
success Set "cache-folder" to "/usr/local/share/yarn-cache".
Done in 0.07s.

Running 'yarn install --prefer-offline'...

yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /tmp/8d779da98bb1aae/node_modules/sharp: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /tmp/8d779da98bb1aae/node_modules/sharp
Output:
ERR! sharp EACCES: permission denied, mkdir '/opt/Kudu/local/npm-cache'
info sharp Are you trying to install as a root or sudo user? Try again with the --unsafe-perm flag
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.17.0 | linux | x64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "/opt/python/latest/bin/python"
gyp ERR! find Python - version is "3.8.0"
gyp ERR! find Python - version is 3.8.0 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:175:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "/opt/nodejs/10.17.0/bin/node" "/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/8d779da98bb1aae/node_modules/sharp
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
error /tmp/8d779da98bb1aae/node_modules/sharp: Command failed.\nExit code: 1\nCommand: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)\nArguments: \nDirectory: /tmp/8d779da98bb1aae/node_modules/sharp\nOutput:\nERR! sharp EACCES: permission denied, mkdir '/opt/Kudu/local/npm-cache'\ninfo sharp Are you trying to install as a root or sudo user? Try again with the --unsafe-perm flag\ninfo sharp Attempting to build from source via node-gyp but this may fail due to the above error\ninfo sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies\ngyp info it worked if it ends with ok\ngyp info using node-gyp@5.0.3\ngyp info using node@10.17.0 | linux | x64\ngyp ERR! find Python \ngyp ERR! find Python Python is not set from command line or npm configuration\ngyp ERR! find Python Python is not set from environment variable PYTHON\ngyp ERR! find Python checking if "python" can be used\ngyp ERR! find Python - executable path is "/opt/python/latest/bin/python"\ngyp ERR! find Python - version is "3.8.0"\ngyp ERR! find Python - version is 3.8.0 - should be >=2.6.0 <3.0.0\ngyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED\ngyp ERR! find Python checking if "python2" can be used\ngyp ERR! find Python - "python2" is not in PATH or produced an error\ngyp ERR! find Python \ngyp ERR! find Python **********************************************************\ngyp ERR! find Python You need to install the latest version of Python 2.7.\ngyp ERR! find Python Node-gyp should be able to find and use Python. If not,\ngyp ERR! find Python you can try one of the following options:\ngyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"\ngyp ERR! find Python   (accepted by both node-gyp and npm)\ngyp ERR! find Python - Set the environment variable PYTHON\ngyp ERR! find Python - Set the npm configuration variable python:\ngyp ERR! find Python   npm config set python "/path/to/pythonexecutable"\ngyp ERR! find Python For more information consult the documentation at:\ngyp ERR! find Python https://github.com/nodejs/node-gyp#installation\ngyp ERR! find Python **********************************************************\ngyp ERR! find Python \ngyp ERR! configure error \ngyp ERR! stack Error: Could not find any Python installation to use\ngyp ERR! stack     at PythonFinder.fail (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:303:47)\ngyp ERR! stack     at PythonFinder.runChecks (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:132:21)\ngyp ERR! stack     at PythonFinder.<anonymous> (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:175:16)\ngyp ERR! stack     at PythonFinder.execFileCallback (/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:267:16)\ngyp ERR! stack     at exithandler (child_process.js:301:5)\ngyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)\ngyp ERR! stack     at ChildProcess.emit (events.js:198:13)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)\ngyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)\ngyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)\ngyp ERR! System Linux 4.4.0-128-generic\ngyp ERR! command "/opt/nodejs/10.17.0/bin/node" "/opt/nodejs/10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"\ngyp ERR! cwd /tmp/8d779da98bb1aae/node_modules/sharp\ngyp ERR! node -v v10.17.0\ngyp ERR! node-gyp -v v5.0.3\ngyp ERR! not ok\n/opt/Kudu/Scripts/starter.sh oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 10 -i /tmp/8d779da98bb1aae -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log ```

**Comment by lovell** [comment]
Hello, the salient part of this log is:

> ERR! sharp EACCES: permission denied, mkdir '/opt/Kudu/local/npm-cache'
> info sharp Are you trying to install as a root or sudo user? Try again with the --unsafe-perm flag
> info sharp Attempting to build from source via node-gyp but this may fail due to the above error

so you should find your answer in your question ;)

The installation issue template that you deleted/ignored asked:

> If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

Did you see this question? If not, what could have made it clearer?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
