### ISSUE TITLE
Adding prebuilt versions for the common OS flavours?

### ISSUE THREAD

**Issue by Pomax** [lovell/sharp#2014]
Sharp ends up hitting `node-gyp` during install, which is the biggest Node-related headache you've ever seen on Windows. Thankfully, `node-pre-gyp` exists, which turns "compiling things" into "grabbing the prebuilt binary": can `sharp` be given the node-pre-gyp treatment so that folks don't need gigabytes of Visual Studio/C++/WinSDK etc. installed just to install this package? =(

```
info sharp Using cached C:\Users\Mike\AppData\Roaming\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz
info sharp Creating J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp\build\Release
info sharp Copying DLLs from J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp\vendor\lib to J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=13.3.0 runtime=node arch=x64 libc= platform=win32)
```

**Comment by Pomax** [comment]
Related, the build solution seems to target Windows 8.1 SDK, even on Windows 10, which is a bit of a problem because the current VStudio installer doesn't even offer 8.1 targetting anymore. Only the Windows 10 SDKs are available.

So what should be a simple `npm install sharp` becomes a full day of work.

```
c:\Users\Mike\Documents\git\projects\lightroom-catalog-helper\node_modules\sharp>if not defined npm_config_node_gyp (node "J:\Junctions\Users\Mike\AppData\Roaming\nvm\v13.3.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "J:\Junctions\Users\Mike\AppData\Roaming\nvm\v13.3.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Wind
ows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [c:\Users\Mike\Documents\git\projects\lightroom-catalog-helper\node_modules
\sharp\build\libvips-cpp.vcxproj]
```

**Comment by lovell** [comment]
Prebuilt binaries are provided for Windows, OS X and Linux.

> prebuild-install WARN install No prebuilt binaries found (target=13.3.0 runtime=node arch=x64 libc= platform=win32)

Node.js 13 support was added in v0.23.2.
https://sharp.pixelplumbing.com/en/stable/changelog/#v0232-28th-october-2019

**Comment by Pomax** [comment]
Hm, that's very odd, because if I use Node 13, installing sharp leads to the above errors, whereas if I downgrade node to 12, it installs fine.

**Comment by Pomax** [comment]
package.json reports `"sharp": "^0.23.4"` so that _should_ work... but the install attempt yields the following:
```
C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper>nvm use 13.3
13.3.0
Now using node v13.3.0 (64-bit)

C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper>npm install sharp

> sharp@0.23.4 install C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\Mike\AppData\Roaming\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz
info sharp Creating J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp\build\Release
info sharp Copying DLLs from J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp\vendor\lib to J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sharp\build\Release

> sqlite3@4.1.0 install C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v79-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@13.3.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and se
lecting "Retarget solution". [C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (J:\Junctions\Users\Mike\AppData\Roaming\nvm\v13.3.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "J:\\Junctions\\Users\\Mike\\AppData\\Roaming\\nvm\\v13.3.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Mike\\Documents\\Git\\projects\\lightroom-catalog-helper\\node_modules\\sqlite3\\lib\\binding\\node-v79-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Mike\\Documents\\Git\\projects\\lightroom-catalog-helper\\node_modules\\sqlite3\\lib\\binding\\node-v79-win32-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe J:\Junctions\Users\Mike\AppData\Roaming\nvm\v13.3.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3\lib\binding\node-v79-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3\lib\binding\node-v79-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (J:\Junctions\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1027:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mike\\Documents\\Git\\projects\\lightroom-catalog-helper\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3
node-pre-gyp ERR! node -v v13.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe J:\Junctions\Users\Mike\AppData\Roaming\nvm\v13.3.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3\lib\binding\node-v79-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Mike\Documents\Git\projects\lightroom-catalog-helper\node_modules\sqlite3\lib\binding\node-v79-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm WARN lightroom-catalog-helper@1.0.0 No description
npm WARN lightroom-catalog-helper@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Pomax** [comment]
Hm, looking at this a bit closer, it seems that even if sharp itself is Node 13 compatible, it's reliant on a version of sqlite3 that might not be?

**Comment by lovell** [comment]
The error above is from sqlite3. sharp is not dependent on sqlite3:
```
$ npm install sharp
...
+ sharp@0.23.4
added 71 packages from 105 contributors and audited 161 packages in 2.898s
found 0 vulnerabilities

$ npm ls sqlite3
/tmp
└── (empty)
```

You can run the command `npm ls sqlite3` in the `C:\\Users\\Mike\\Documents\\Git\\projects\\lightroom-catalog-helper` directory on your machine to find out what is dependent upon it.

**Comment by Pomax** [comment]
Hm, but why would `npm` do anything with sqlite3 when I'm explicitly only calling `npm install sharp`? That's probably something completely unrelated, and no reason to keep this issue open over, but if you happen to know: great. Because I have no idea why it would try to install anything that's mentioned in package.json or is in node_modules when the instruction is specifically only to install `sharp`.

**Comment by lovell** [comment]
My best guess would be that `sqlite3` previously failed to install (due to it not yet supporting Node.js 13) and running `npm install anything` triggered a consistency check and therefore another attempt to install it.

**Comment by Pomax** [comment]
ah, cheers
