### ISSUE TITLE
azure install: `ERR! sharp Windows x86 (32-bit) node.exe is not supported`

### ISSUE THREAD

**Issue by mahesh2000** [lovell/sharp#2028]
hi, i'm getting the error `ERR! sharp Windows x86 (32-bit) node.exe is not supported` when i try installing on azure. also, is there any dependency on canvas (won't install either) or chromium (super slow)? thanks!

```
D:\home\site\wwwroot\IoTHub_EventHub2> npm install sharp
ERR! sharp Windows x86 (32-bit) node.exe is not supported
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\6.4.1\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\10.14.1\\node.exe" "D:\\Program Files (x86)\\npm\\6.4.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\site\wwwroot\IoTHub_EventHub2\node_modules\sharp
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN rollback Rolling back minimist@1.2.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\home\site\wwwroot\IoTHub_EventHub2\node_modules\rc\node_modules'
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN IoTHub_EventHub2 No description
npm WARN IoTHub_EventHub2 No repository field.
npm WARN IoTHub_EventHub2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2020-01-09T19_27_15_694Z-debug.log

D:\home\site\wwwroot\IoTHub_EventHub2> npm install save-svg-as-png
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN IoTHub_EventHub2 No description
npm WARN IoTHub_EventHub2 No repository field.
npm WARN IoTHub_EventHub2 No license field.

```

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/en/stable/install/)?

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/en/stable/install/#windows-x64

> Only 64-bit (x64) node.exe is supported.

**Comment by mahesh2000** [comment]
is there no way to run it as an azure function app? i did find the following for running sharp (specifically) on azure web app, but i don't think those options are available for the function app. see https://devblogs.microsoft.com/premier-developer/configure-azure-app-service-for-64-bit-platform-and-node-js/

**Comment by lovell** [comment]
Please see https://github.com/Azure/azure-functions-nodejs-worker/issues/158

**Comment by mahesh2000** [comment]
yes, that worked, thank you, specifically this answer: https://github.com/Azure/azure-functions-nodejs-worker/issues/158#issuecomment-540232863
