### ISSUE TITLE
Experiment: unpack prebuilt libvips to versioned vendor subdirectory

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#2046]
It looks like macOS doesn't expand `@loader_path` to the actual filesystem path before checking if the rpath of a dylib file has already been loaded. This means that different versions of sharp at different filesystem locations loaded in the same process can conflict when an earlier version is loaded before a later version.

To attempt to deal with this, we can experiment with unpacking prebuilt libvips binaries into versioned directory under `vendor`, e.g. `node_modules/sharp/vendor/8.9.0/lib/...`, which should then ensure the rpath includes the version number.

**Comment by kleisauke** [comment]
I had a quick go: https://github.com/kleisauke/sharp/commit/b4c86bbe6379f96d621ed5b400e1ad5c29d3bc1f. The unit tests on Travis CI passes ([relevant build](https://travis-ci.org/kleisauke/sharp/builds/639925253)) and `otool -l` reports:
```
Load command 14
          cmd LC_RPATH
      cmdsize 48
         path @loader_path/../../vendor/8.9.0/lib (offset 12)
```

So it seems to work. But it should be tested on a physical macOS machine with different versions of sharp, just to be sure:
```bash
npm install kleisauke/sharp#issue-2046
```

Could someone verify whether this works? I don't have the necessary hardware to test it on, unfortunately.

**Comment by lovell** [comment]
@sapkra Are you able to help test this?

**Comment by sapkra** [comment]
Doesn't seem like it's working. I've tested it with my example repository and still getting the same error.

https://github.com/sapkra/sharp-issue-2029
using: `"sharp": "github:kleisauke/sharp#issue-2046"`

```
$ node src/index.js
/Users/sapkra/Documents/test/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

dlopen(/Users/sapkra/Documents/test/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /Users/sapkra/Documents/test/node_modules/sharp/build/Release/sharp.node
  Reason: Incompatible library version: sharp.node requires version 55.0.0 or later, but libvips-cpp.42.dylib provides version 54.0.0

- Run "brew update && brew upgrade vips"
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/sapkra/Documents/test/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/sapkra/Documents/test/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kleisauke** [comment]
Thanks for testing! I'm able to reproduce this in a private Travis container. I'll have a look.

fwiw, running the example repo from @sapkra in a Linux container doesn't work either:
```bash
node: symbol lookup error: /home/travis/build/kleisauke/sharp-issue-2029/node_modules/sharp/build/Release/sharp.node: undefined symbol: vips_foreign_heif_compression_get_type
```

It looks like the `sharp.node` binary (version 0.24.0 - linked with libvips v8.9.0) is trying to lookup a vips 8.9 symbol within libvips v8.8.1 (sharp v0.23.4). I tried to swap `${ORIGIN}` with `$ORIGIN` in https://github.com/kleisauke/sharp/commit/80c85f3081f81e73057beffa1fcf95af1e86099d but the same problem persists.

**Comment by lovell** [comment]
Perhaps we could try modifying the shared libraries in the prebuilt tarballs to include the libvips version in their soname/id, something like:

https://github.com/lovell/package-libvips-darwin/blob/master/package.sh
```diff
- install_name_tool -id @rpath/$base_dep $dest_dir/$base_dep
+ install_name_tool -id @rpath/8.9.0/lib/$base_dep $dest_dir/$base_dep
```

https://github.com/lovell/sharp-libvips/blob/master/build/lin.sh
```diff
- patchelf --set-rpath '\$ORIGIN' --force-rpath {}
+ patchelf --set-rpath '\$ORIGIN' --force-rpath --set-soname '8.9.0/lib/{}' {}
```

**Comment by kleisauke** [comment]
I managed to get the macOS build working with that example repo. Modifying the "install name" to include the versioned subdirectory indeed seems to work.

It only gives this warning at runtime:
```
objc[3932]: Class GNotificationCenterDelegate is implemented in both /Users/travis/build/kleisauke/sharp-issue-2029/node_modules/@fiahfy/icns-convert/node_modules/sharp/vendor/lib/libgio-2.0.0.dylib (0x106a31578) and /Users/travis/build/kleisauke/sharp-issue-2029/node_modules/sharp/vendor/8.9.0/lib/libgio-2.0.0.dylib (0x107ff6598). One of the two will be used. Which one is undefined.
```

Which can be safely(?) ignored.

Fixing the Linux glibc build is a little harder (I don't think the soname can contain paths). I tried to bump the soname of libvips (and the C++ binding) to ensure the dynamic linker will attempt to load the latest version. Unfortunately this doesn't work:
```
(sharp:4541): GLib-GObject-WARNING **: 21:45:41.191: cannot register existing type 'VipsObject'
(sharp:4541): GLib-CRITICAL **: 21:45:41.191: g_once_init_leave: assertion 'result != 0' failed
(sharp:4541): GLib-GObject-CRITICAL **: 21:45:41.191: g_type_register_static: assertion 'parent_type > 0' failed
(sharp:4541): GLib-CRITICAL **: 21:45:41.191: g_once_init_leave: assertion 'result != 0' failed
```
<sup>(https://github.com/libvips/libvips/blob/b2334d8d620ba3e042b19478cabf21742caf3817/libvips/iofuncs/object.c#L2974-L2984)</sup>

On musl I get another error:
```
Error relocating /mnt/sharp/node_modules/sharp/build/Release/../../vendor/8.9.0/lib/libvips.so.52: g_date_time_format_iso8601: symbol not found
```

Perhaps bumping the soname of `libglib-2.0.so.0` and `libgobject-2.0.so.0` might fix this, but that's something I want to avoid.

Static linking of all dependencies to `sharp.node` can resolve these issues (I think). As long as we provide everything to allow the user to relink the application (i.e. the `sharp-libvips` build system) it will not violate the LGPL license (IANAL). Shall I try this? I did a similar thing with NetVips as experiment, see:
https://github.com/kleisauke/libvips-packaging/commit/982f59e7d2f5a2de516aa78b6584eda8aeed4baf
(that's a semi-static build, only `libgobject-2.0.so.0` and `libvips.so.42` are packaged)

Here are the relevant changes so far:
https://github.com/lovell/sharp/compare/master...kleisauke:issue-2046
https://github.com/lovell/sharp-libvips/compare/master...kleisauke:issue-2046
https://github.com/lovell/package-libvips-darwin/compare/master...kleisauke:issue-2046

**Comment by lovell** [comment]
@kleisauke Thank you very much for all of your research on this so far! It looks like building libvips and its dependencies as static libraries, which then form part of the `sharp.node` dynamic library, is worth investigating as a possible solution to this.

I do need to think about the licensing impact, as statically-linked LGPLv2.1+ dependencies would implicitly make all of the Apache 2.0 sharp code LGPLv3. Anything that uses sharp would not be impacted as Node.js native modules are always shared libraries.

**Comment by lovell** [comment]
@kleisauke I've just re-read what you wrote and I might have originally misunderstood. Are you suggesting we link libvips with its dependencies statically and bundle them all into one big shared library file, that is then dynamically linked with `sharp.node` (which is then dynamically linked to `node` itself)? If so, that definitely makes sense and is worth continuing with, especially as licensing would remain pretty much as-is.
