### ISSUE TITLE
Sharp won't run on macOS... linux-x64' binaries cannot be used on the 'darwin-x64

### ISSUE THREAD

**Issue by soosgyul** [lovell/sharp#2052]
I think now I've tried everything.... so my issue.
I have a lambda that uses the sharp libraries. Normally at deploy I delete the sharp folder and forcefully download the linux binaries as per documentation.

The problem now is to actually have the thing running on my mac.
No matter what I do I get the error:
`generate-logos-lambda/dist/node_modules/sharp/lib/libvips.js:61
      throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.`);
      ^

Error: 'linux-x64' binaries cannot be used on the 'darwin-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
    at Object.hasVendoredLibvips (/Users/gyula/workspace/radioplayer/generate-logos-lambda/dist/node_modules/sharp/lib/libvips.js:61:13)
    at Object.<anonymous> (/Users/gyula/workspace/radioplayer/generate-logos-lambda/dist/node_modules/sharp/lib/constructor.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gyula/workspace/radioplayer/generate-logos-lambda/dist/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)`

So far I've tried - and between each step I'm deleting the node_modules/sharp folder:
npm install sharp
yarn add sharp
deleted caches of both package managers and re-tried.
downloaded the latest from https://github.com/lovell/sharp/releases and copied to my node_modules folder...
nothing. Everything throws the error as above.

If I try to run the same code inside a docker container, it works, but:
1. It shouldn't, because as far as I know I've installed the macOs libraries
2. I could use docker only for development, however tsc and/or tsc --watch is unususably slow.

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
No error message

What is the output of running `npx envinfo --binaries --languages --system --utilities`?
`System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 761.84 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.22.0 - /usr/local/bin/git
    Clang: 1100.0.33.17 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.13.4 - /usr/local/bin/go
    Java: 12.0.1 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.9 - /usr/bin/php
    Python: 3.7.6 - /usr/local/bin/python
    Python3: 3.7.6 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby`

**Comment by soosgyul** [comment]
Leaving this report got me thinking, that maybe I'm not deleting the right stuff. Turns out, that even though I was deleting the node_modules, I wasn't overwriting anything that ended up in my dist folder where the whole thing ran... so... it's not you, it's me. :)
