### ISSUE TITLE
Compositing 101

### ISSUE THREAD

**Issue by soosgyul** [lovell/sharp#2055]
What are you trying to achieve?
Want to put an image, in the center of a blank new image of a given size.

Have you searched for similar questions? Yes. 

Here is what I got:
```
const blankImage = await sharp({
            create: {
                width: 600,
                height: 600,
                channels: 4,
                background: "rgba(255, 255, 255, 0)",
            },
        })
            .png()
            .toBuffer();

const overlay = await sharp(inputImage);

const composite = sharp(blankImage)
            .composite([{ input: overlay }])
            .png()
            .toBuffer();

return composite;
```

This throws me a 
```(node:56302) UnhandledPromiseRejectionWarning: Error: Expected width, height and channels for raw pixel input
    at Sharp._createInputDescriptor (/Users/gyula/workspace/radioplayer/generate-logos-lambda/node_modules/sharp/lib/input.js:61:15)
    at /Users/gyula/workspace/radioplayer/generate-logos-lambda/node_modules/sharp/lib/composite.js:105:19
    at Array.map (<anonymous>)
    at Sharp.composite (/Users/gyula/workspace/radioplayer/generate-logos-lambda/node_modules/sharp/lib/composite.js:98:35)```

What am I douing wrong? Could you please provide an example to solve this?

**Comment by lovell** [comment]
To composite `inputImage` over a blank image, try something like the following:

```javascript
const composited = await sharp({
  create: {
    width: 600,
    height: 600,
    channels: 4,
    background: "rgba(255, 255, 255, 0)"
  }
})
  .composite([{ input: inputImage }])
  .png()
  .toBuffer();
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
