### ISSUE TITLE
Problem installing sharp on Lambda

### ISSUE THREAD

**Issue by angelvega93** [lovell/sharp#2096]
Hi, i followed the guide to install Lambda, but i cant get it running.

docker run -v C:\MyProject:/var/task lambci/lambda:build-nodejs10.x npm install sharp
```
> sharp@0.24.1 install /var/task/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.0/libvips-8.9.0-linux-x64.tar.gz
npm WARN saveError ENOENT: no such file or directory, open '/var/task/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/var/task/package.json'
npm WARN task No description
npm WARN task No repository field.
npm WARN task No README data
npm WARN task No license field.

+ sharp@0.24.1
added 72 packages from 106 contributors and audited 160 packages in 18.247s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

My project just contains 1 file:

app.js
```javascript
const Sharp = require("sharp");

exports.handler = async (event, context) => {
  return { success: true };
};
```
Lambda Error
```
START RequestId: c670e029-8cca-4bf1-b7ec-ef6092ca15a6 Version: $LATEST
2020-02-23T08:03:23.570Z	undefined	ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"\nSomething went wrong installing the \"sharp\" module\n\n/var/task/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: invalid ELF header\n\n- Ensure \"linux\" is used at install time as well as runtime\n- Consult the installation documentation at https://sharp.pixelplumbing.com/install\n- Search for this error at https://github.com/lovell/sharp/issues\n","stack":["Error: ","Something went wrong installing the \"sharp\" module","","/var/task/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: invalid ELF header","","- Ensure \"linux\" is used at install time as well as runtime","- Consult the installation documentation at https://sharp.pixelplumbing.com/install","- Search for this error at https://github.com/lovell/sharp/issues","","    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:34:9)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Module.require (internal/modules/cjs/loader.js:692:17)","    at require (internal/modules/cjs/helpers.js:25:18)","    at Object.<anonymous> (/var/task/node_modules/sharp/lib/index.js:3:15)","    at Module._compile (internal/modules/cjs/loader.js:778:30)"]}
END RequestId: c670e029-8cca-4bf1-b7ec-ef6092ca15a6
REPORT RequestId: c670e029-8cca-4bf1-b7ec-ef6092ca15a6	Duration: 2390.27 ms	Billed Duration: 2400 ms	Memory Size: 128 MB	Max Memory Used: 25 MB	
Unknown application error occurred
Error
```

I tried everything even install sharp using Amazon Linux 2.
When i run it using AWS SAM it works fine, what am i doing wrong?

**Comment by angelvega93** [comment]
I don't know why but i copied this from AWS Example package.json

```
    "scripts": {
        "build:init": "rm -rf package-lock.json && rm -rf dist && rm -rf node_modules",
        "build:zip": "zip -rq image-handler.zip .",
        "build:dist": "mkdir dist && mv image-handler.zip dist/",
        "build": "npm run build:init && npm install --arch=x64 --platform=linux --production && npm run build:zip && npm run build:dist"
    },
```

And then run:
```
docker run -v C:\MyProject:/var/task lambci/lambda:build-nodejs12.x npm run build
```

And it worked just fine.

**Comment by alvincrisuy** [comment]
how do i make this work in nodejs 18x and arm64? using serverless deployment

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/install#aws-lambda
