### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by averri** [lovell/sharp#2109]
When I installed other library (joi-password-complexity) the following error is happening when starting Node:

```bash
/home/alex/dev/src/other/strenux/strenux-api/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/home/alex/dev/src/other/strenux/strenux-api/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alex/dev/src/other/strenux/strenux-api/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
Waiting for the debugger to disconnect...
```

How to clear this?! I cannot run the project anymore!

Versions:
- Node: 12.16.0
- sharp: 0.24.1
- Ubuntu 18

**Comment by averri** [comment]
The only way to solve was to demove `node_modules` folder an `yarn.lock` and then `yarn install` again.

**Comment by lovell** [comment]
Does this mean that your previous issue at https://github.com/lovell/sharp/issues/2084 can be closed also?

**Comment by rob88** [comment]
Another solution is that you need to  either run npm install sharp  or yarn install sharp . Deleting node_module takes waste of time

**Comment by manel00** [comment]
Hello, having the same issue, anyone knows how to solve it? Thank you

**Comment by lovell** [comment]
@manel00 Please open a new issue and answer all of the questions - https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
