### ISSUE TITLE
electron build  failed  for win32 on mac

### ISSUE THREAD

**Issue by DiamondYuan** [lovell/sharp#2126]
sharp version sharp

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
yes
Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?
yes

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 8.24 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
```

## use electron-builder build --win --x64 to build

```
yarn run v1.19.1
$ electron-builder build --win --x64
  • electron-builder  version=22.3.2 os=19.3.0
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=/Users/diamondyuan/projj/github.com/DiamondYuan/web-clipper-electron/dist
  ⨯ /Users/diamondyuan/.nvm/versions/node/v12.14.1/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:

Error output:
warning package.json: No license field
warning ../package.json: No license field
warning web-clipper@0.0.1: No license field
warning " > routing-controllers@0.8.1-alpha.2" has incorrect peer dependency "class-validator@0.10.1".
error /Users/diamondyuan/projj/github.com/DiamondYuan/web-clipper-electron/dist/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/diamondyuan/projj/github.com/DiamondYuan/web-clipper-electron/dist/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-win32-x64.tar.gz
prebuild-install WARN This package does not support N-API version 7.1.1 
prebuild-install WARN install No prebuilt binaries found (target=7.1.1 runtime=napi arch=x64 libc= platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.14.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/diamondyuan/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/diamondyuan/projj/github.com/DiamondYuan/web-clipper-electron/dist/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/diamondyuan/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/diamondyuan/.electron-gyp/7.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/diamondyuan/.electron-gyp/7.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/diamondyuan/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/diamondyuan/.electron-gyp/7.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/diamondyuan/projj/github.com/DiamondYuan/web-clipper-electron/dist/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:50:
In file included from ../vendor/include/glib-2.0/glib/ghash.h:33:
In file included from ../vendor/include/glib-2.0/glib/glist.h:32:
../vendor/include/glib-2.0/glib/gmem.h:382:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR gboolean g_mem_gc_friendly;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:50:
In file included from ../vendor/include/glib-2.0/glib/ghash.h:33:
In file included from ../vendor/include/glib-2.0/glib/glist.h:32:
../vendor/include/glib-2.0/glib/gmem.h:386:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR GMemVTable     *glib_mem_profiler_table;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:54:
In file included from ../vendor/include/glib-2.0/glib/giochannel.h:33:
../vendor/include/glib-2.0/glib/gmain.h:783:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR GSourceFuncs g_timeout_funcs;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:54:
In file included from ../vendor/include/glib-2.0/glib/giochannel.h:33:
../vendor/include/glib-2.0/glib/gmain.h:784:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR GSourceFuncs g_child_watch_funcs;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:54:
In file included from ../vendor/include/glib-2.0/glib/giochannel.h:33:
../vendor/include/glib-2.0/glib/gmain.h:785:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR GSourceFuncs g_idle_funcs;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:54:
In file included from ../vendor/include/glib-2.0/glib/giochannel.h:34:
In file included from ../vendor/include/glib-2.0/glib/gstring.h:33:
../vendor/include/glib-2.0/glib/gunicode.h:745:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const gchar * const g_utf8_skip;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:54:
../vendor/include/glib-2.0/glib/giochannel.h:327:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR GSourceFuncs g_io_watch_funcs;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:82:
../vendor/include/glib-2.0/glib/gstrfuncs.h:54:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const guint16 * const g_ascii_table;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:85:
../vendor/include/glib-2.0/glib/gtestutils.h:505:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const GTestConfig * const g_test_config_vars;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:99:
../vendor/include/glib-2.0/glib/gversion.h:36:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const guint glib_major_version;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:99:
../vendor/include/glib-2.0/glib/gversion.h:37:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const guint glib_minor_version;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:99:
../vendor/include/glib-2.0/glib/gversion.h:38:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const guint glib_micro_version;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:99:
../vendor/include/glib-2.0/glib/gversion.h:39:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const guint glib_interface_age;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:99:
../vendor/include/glib-2.0/glib/gversion.h:40:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR const guint glib_binary_age;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:111:
../vendor/include/glib-2.0/glib/deprecated/gthread.h:94:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR GThreadFunctions       g_thread_functions_for_glib_use;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:111:
../vendor/include/glib-2.0/glib/deprecated/gthread.h:95:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR gboolean               g_thread_use_default_impl;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:111:
../vendor/include/glib-2.0/glib/deprecated/gthread.h:97:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR guint64   (*g_thread_gettime) (void);
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:22:
In file included from ../vendor/include/glib-2.0/gobject/gbinding.h:28:
In file included from ../vendor/include/glib-2.0/glib.h:111:
../vendor/include/glib-2.0/glib/deprecated/gthread.h:268:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GLIB_VAR gboolean g_threads_got_initialized;
^
../vendor/include/glib-2.0/glib/gtypes.h:573:33: note: expanded from macro 'GLIB_VAR'
#        define GLIB_VAR extern __declspec(dllimport)
                                ^
In file included from ../src/common.cc:23:
In file included from ../vendor/include/vips/vips8:35:
In file included from ../vendor/include/glib-2.0/glib-object.h:28:
../vendor/include/glib-2.0/gobject/gparamspecs.h:1166:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
GOBJECT_VAR GType *g_param_spec_types;
^
../vendor/include/glib-2.0/gobject/gparamspecs.h:1158:36: note: expanded from macro 'GOBJECT_VAR'
#        define GOBJECT_VAR extern __declspec(dllimport)
                                   ^
19 errors generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/diamondyuan/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/diamondyuan/.nvm/versions/node/v12.14.1/bin/node" "/Users/diamondyuan/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/diamondyuan/projj/github.com/DiamondYuan/web-clipper-electron/dist/node_modules/sharp
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

**Comment by lovell** [comment]
Hi, did you see the documentation relating to Electron installation, specifically the use of `electron-rebuild`?

https://sharp.pixelplumbing.com/install#electron

**Comment by DiamondYuan** [comment]
> Hi, did you see the documentation relating to Electron installation, specifically the use of `electron-rebuild`?
> 
> https://sharp.pixelplumbing.com/install#electron

yes,I use electron-builder to build.
Work for mac and not work for windows.

**Comment by lovell** [comment]
Although they have confusingly-similar names, please note that [electron-rebuild](https://github.com/electron/electron-rebuild) is not the same as `electron-builder`.
