### ISSUE TITLE
Installation problem for specific sharp version after MacOS update

### ISSUE THREAD

**Issue by AngeloGulina** [lovell/sharp#2131]
Having trouble installing `v0.20.5` - unfortunately I need this precise version and cannot do differently.
After the Catalina update, I get this errors, running `npm install --verbose sharp`?
```
> sharp@0.20.5 install /Users/a.gulina/code/shop/image-transformer/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-darwin-x64.tar.gz
prebuild-install info begin Prebuild-install version 4.0.0
prebuild-install info looking for cached prebuild @ /Users/a.gulina/.npm/_prebuilds/20e891-sharp-v0.20.5-node-v72-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.20.5/sharp-v0.20.5-node-v72-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.20.5/sharp-v0.20.5-node-v72-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=x64 platform=darwin)
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/a.gulina/.nvm/versions/node/v12.16.1/bin/node',
gyp verb cli   '/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.0.5
gyp info using node@12.16.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/local/opt/python@2/bin/python2.7"
gyp verb find Python - executing "/usr/local/opt/python@2/bin/python2.7" to get version
gyp verb find Python - version is "2.7.17"
gyp info find Python using Python version 2.7.17 found at "/usr/local/opt/python@2/bin/python2.7"
gyp verb get node dir no --target version specified, falling back to host node version: 12.16.1
gyp verb command install [ '12.16.1' ]
gyp verb install input version string "12.16.1"
gyp verb install installing version: 12.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.16.1
gyp verb build dir attempting to create "build" dir: /Users/a.gulina/code/shop/image-transformer/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /Users/a.gulina/code/shop/image-transformer/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/a.gulina/code/shop/image-transformer/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/a.gulina/code/shop/image-transformer/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /Users/a.gulina/code/shop/image-transformer/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/a.gulina/code/shop/image-transformer/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/a.gulina/Library/Caches/node-gyp/12.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/a.gulina/Library/Caches/node-gyp/12.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/a.gulina/Library/Caches/node-gyp/12.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/a.gulina/code/shop/image-transformer/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/a.gulina/Library/Caches/node-gyp/12.16.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  touch Release/obj.target/libvips-cpp.stamp
  c++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/include/node -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/src -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/deps/openssl/config -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/deps/openssl/openssl/include -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/deps/uv/include -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/deps/zlib -I/Users/a.gulina/Library/Caches/node-gyp/12.16.1/deps/v8/include -I../../nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fexceptions -Wall -O3 -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
In file included from ../src/common.cc:27:
../src/common.h:82:20: error: no member named 'Handle' in namespace 'v8'
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
               ~~~~^
../src/common.h:82:37: error: expected '(' for function-style cast or type construction
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                          ~~~~~~~~~~^
../src/common.h:82:39: error: use of undeclared identifier 'obj'
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                      ^
../src/common.h:82:56: error: expected '(' for function-style cast or type construction
  bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                           ~~~~~~~~~~~ ^
../src/common.h:83:29: error: no member named 'Handle' in namespace 'v8'
  std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                        ~~~~^
../src/common.h:83:46: error: expected '(' for function-style cast or type construction
  std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                   ~~~~~~~~~~^
../src/common.h:83:48: error: use of undeclared identifier 'obj'
  std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                               ^
../src/common.h:83:65: error: expected '(' for function-style cast or type construction
  std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                    ~~~~~~~~~~~ ^
../src/common.h:84:37: warning: variable templates are a C++14 extension [-Wc++14-extensions]
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                    ^
../src/common.h:84:48: error: no member named 'Handle' in namespace 'v8'
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                           ~~~~^
../src/common.h:84:65: error: expected '(' for function-style cast or type construction
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                      ~~~~~~~~~~^
../src/common.h:84:67: error: use of undeclared identifier 'obj'
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                  ^
../src/common.h:84:84: error: expected '(' for function-style cast or type construction
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                       ~~~~~~~~~~~ ^
../src/common.h:84:89: error: expected ';' at end of declaration
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                        ^
                                                                                        ;
../src/common.h:84:90: error: expected unqualified-id
  template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                         ^
../src/common.h:87:26: warning: variable templates are a C++14 extension [-Wc++14-extensions]
  template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                         ^
../src/common.h:87:37: error: no member named 'Handle' in namespace 'v8'
  template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                ~~~~^
../src/common.h:87:54: error: expected '(' for function-style cast or type construction
  template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                           ~~~~~~~~~~^
../src/common.h:87:56: error: use of undeclared identifier 'obj'
  template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                       ^
../src/common.h:87:73: error: expected '(' for function-style cast or type construction
  template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                            ~~~~~~~~~~~ ^
../src/common.h:87:78: error: expected ';' at end of declaration
  template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                             ^
                                                                             ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/a.gulina/.nvm/versions/node/v12.16.1/bin/node" "/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/a.gulina/code/shop/image-transformer/node_modules/sharp
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm verb lifecycle sharp@0.20.5~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.20.5~install: PATH: /Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/a.gulina/code/shop/image-transformer/node_modules/sharp/node_modules/.bin:/Users/a.gulina/code/shop/image-transformer/node_modules/.bin:/Users/a.gulina/.nvm/versions/node/v12.16.1/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
npm verb lifecycle sharp@0.20.5~install: CWD: /Users/a.gulina/code/shop/image-transformer/node_modules/sharp
npm http fetch POST 400 http://npm-registry.wwdus.local/repository/npm/-/npm/v1/security/audits/quick 1421ms
npm info lifecycle sharp@0.20.5~install: Failed to exec install script
npm timing action:install Completed in 22512ms
npm verb unlock done using /Users/a.gulina/.npm/_locks/staging-411c3be815a7327f.lock for /Users/a.gulina/code/shop/image-transformer/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 141ms
npm timing stage:runTopLevelLifecycles Completed in 72943ms

...

npm verb stack Error: sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:311:20)
npm verb stack     at ChildProcess.<anonymous> (/Users/a.gulina/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:311:20)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm verb pkgid sharp@0.20.5
npm verb cwd /Users/a.gulina/code/shop/image-transformer
npm verb Darwin 19.3.0
npm verb argv "/Users/a.gulina/.nvm/versions/node/v12.16.1/bin/node" "/Users/a.gulina/.nvm/versions/node/v12.16.1/bin/npm" "i" "-S" "--verbose" "sharp@0.20.5"
npm verb node v12.16.1
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.20.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```
The output of running `npx envinfo --binaries --system`:
```sh
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.72 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.2 - ~/code/shop/image-transformer/node_modules/.bin/npm
```

**Comment by lovell** [comment]
Support for Node.js 12 was added in sharp v0.22.1.

https://sharp.pixelplumbing.com/changelog#v0221---25supthsup-april-2019

**Comment by AngeloGulina** [comment]
@lovell I see. I will downgrade my version. Thanks for the reply, I will close this.
