### ISSUE TITLE
Something went wrong installing the "sharp" module, preventing peertube service to start

### ISSUE THREAD

**Issue by stemy2** [lovell/sharp#2142]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
yes
Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?
yes
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes
If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
yes
What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@6.14.4
npm info using node@v10.19.0
npm verb config Skipping project config: /root/.npmrc. (matches userconfig)
npm verb npm-session e8f0e40d3600ec36
npm http fetch GET 304 https://registry.npmjs.org/sharp 407ms (from cache)
npm timing stage:loadCurrentTree Completed in 873ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 203ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 249ms
npm timing stage:loadIdealTree Completed in 569ms
npm timing stage:generateActionsToTake Completed in 19ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-4b9e621e77c1ced6.lock for /root/node_modules/.staging
npm timing action:extract Completed in 72ms
npm info lifecycle sharp@0.25.2~preuninstall: sharp@0.25.2
npm info lifecycle sharp@0.25.2~uninstall: sharp@0.25.2
npm verb unbuild rmStuff sharp@0.25.2 from /root/node_modules
npm info lifecycle sharp@0.25.2~postuninstall: sharp@0.25.2
npm timing action:unbuild Completed in 6ms
npm timing action:remove Completed in 204ms
npm timing action:finalize Completed in 3ms
npm timing action:refresh-package-json Completed in 11ms
npm info lifecycle sharp@0.25.2~preinstall: sharp@0.25.2
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.25.2
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.25.2~install: sharp@0.25.2

> sharp@0.25.2 install /root/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /root/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/ba3ce8-sharp-v0.25.2-napi-v3-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /root/.npm/_prebuilds/ba3ce8-sharp-v0.25.2-napi-v3-linux-x64.tar.gz
prebuild-install info unpack resolved to /root/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.25.2~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.25.2~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/node_modules/sharp/node_modules/.bin:/root/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.25.2~install: CWD: /root/node_modules/sharp
npm timing audit submit Completed in 361ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 361ms
npm timing audit body Completed in 0ms
npm timing action:install Completed in 1896ms
npm info lifecycle sharp@0.25.2~postinstall: sharp@0.25.2
npm timing action:postinstall Completed in 2ms
npm verb unlock done using /root/.npm/_locks/staging-4b9e621e77c1ced6.lock for /root/node_modules/.staging
npm timing stage:executeActions Completed in 2224ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 3762ms
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ sharp@0.25.2
updated 1 package and audited 524 packages in 3.93s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 5533ms
npm info ok
```
What is the output of running `npx envinfo --binaries --system`?
```
npx: installed 1 in 2.562s

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz
    Memory: 1.86 GB / 6.82 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
```

Hello,

I have a peertube instance on my server, but it give me a error 502 bad gateway and the said service refuses to start. According [journalctl](https://zerobin.stemy.me/?27280362bc6b0744#v64VtKUBZOnc+yimMZBEpjUmvqFtrn/NWgmoSxU1cRY=), the problem is that "something went wrong with installing the sharp module". So i tried to install it with npm following the instruction here above, but nothing changed. What did i missed ?

Thanks

**Comment by lovell** [comment]
Hi, it looks like `peertube` depends on `^0.24.0` according to https://github.com/Chocobozzz/PeerTube/blob/develop/package.json#L136 so will not be using the latest version of sharp.

Please can you provide the complete output of running the following:

```sh
cd /root
rm -rf node_modules
npm install --verbose peertube
```

**Comment by stemy2** [comment]
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'peertube' ]
npm info using npm@6.14.4
npm info using node@v10.19.0
npm verb config Skipping project config: /root/.npmrc. (matches userconfig)
npm verb npm-session db3c808c59fd70bf
npm http fetch GET 404 https://registry.npmjs.org/peertube 1200ms
npm http fetch GET 404 https://registry.npmjs.org/peertube 752ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 2113ms
npm verb stack Error: 404 Not Found - GET https://registry.npmjs.org/peertube - Not found
npm verb stack     at res.buffer.catch.then.body (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:68:7)
npm verb statusCode 404
npm verb pkgid peertube@latest
npm verb cwd /root
npm verb Linux 4.9.0-12-amd64
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose" "peertube"
npm verb node v10.19.0
npm verb npm  v6.14.4
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/peertube - Not found
npm ERR! 404 
npm ERR! 404  'peertube@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]
npm timing npm Completed in 5128ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-28T08_47_17_911Z-debug.log
```

**Comment by stemy2** [comment]
I forgot to mention: i usually install apps from a specific repository.

https://github.com/YunoHost-Apps/peertube_ynh

**Comment by lovell** [comment]
Oh, peertube isn't published to npm. I'll need a verbose installation log of the `npm install` step of however it is usually installed to be able to help further.

**Comment by stemy2** [comment]
Strangely, peertube was able to start this morning at 6:30 AM, and i didn't had to succeed to install sharp.

**Comment by lovell** [comment]
@stemy2 Is this still a problem?

**Comment by stemy2** [comment]
It's complicated. The problem is not permanent and randomly (dis)appears without any apparent reason.

**Comment by lovell** [comment]
Thanks for the update. I'll close for now, but if you're able to provide a verbose log of the installation failure then I'm happy to help further.

**Comment by stemy2** [comment]
It seems to have disappeard permanently. I'm a bit frustrated because i have no idea of the origin of the problem, nor why it was not permanent nor why it vanished.
