### ISSUE TITLE
cannot deploy to firebase due to sharp.node

### ISSUE THREAD

**Issue by eng-dibo** [lovell/sharp#2147]
I'm trying to deploy my project to firebase, but it faild due to sharp.
I got the following error:
```
Cannot open node_modules/sharp/build/Release/sharp.node: 

Error: node_modules/sharp/build/Release/sharp.node: cannot open shared object file: No such file or directory

  at Object.<anonymous> (/github/workspace/dist/server.js:4756:551664)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:4756:550687)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:4756:549989)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:3247:71093)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:3009:1755)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at /github/workspace/dist/server.js:1:1224
    at Object.<anonymous> (/github/workspace/dist/server.js:1:1271)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

you can see the full details from here
https://github.com/goblins-tech/almogtama3/runs/540656778?check_suite_focus=true

**Comment by lovell** [comment]
Does the file referenced in the error message exist in the files you are deploying? Has webpack been configured to include it, e.g. by adding sharp to [externals](https://webpack.js.org/configuration/externals/)?

**Comment by eng-dibo** [comment]
@lovell 

Does the file referenced in the error message exist in the files you are deploying?
do you mean `dist/server.js`? if so, yes 


Has webpack been configured to include it, e.g. by adding sharp to externals?
No, what exactly should I include in `externals`?

currently webpack Externals looks like:
```
externals: {
    "./dist/server/main": 'require("./server/main")'
  }
```

**Comment by lovell** [comment]
https://webpack.js.org/configuration/externals/
```
  externals: {
    'sharp': 'commonjs2 sharp'
  }
```

**Comment by eng-dibo** [comment]
I already tried this solution but got `Error parsing triggers: Cannot find module 'sharp'`

@lovell

**Comment by lovell** [comment]
Does the file referenced in the error message, specifically `node_modules/sharp/build/Release/sharp.node`, exist in the file(s) you are deploying? Make sure you're not (implicitly?) excluding `node_modules` from your deployment.

**Comment by eng-dibo** [comment]
I don't execlude `node_modules`, firebase automatically install all modules from `package.json`.

**Comment by eng-dibo** [comment]
Now I got this error

```
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/github/workspace/dist/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by luisarbezerra** [comment]
same error here.

**Comment by eng-dibo** [comment]
@luisarbezerra  

what I did until now:

I added the following to the webpack
```
externals: {
    'sharp': 'commonjs2 sharp'
  }

module : {
  rules: [
     {
        test: /\.node$/,
        use: "node-loader"
      }   
  ]
}
```

then I installed sharp inside `firebase` dir.
but now I got the following error: `Module did not self-register.` as [mentioned here ](https://github.com/lovell/sharp/issues/2147#issuecomment-611167380)

**Comment by lovell** [comment]
Are you able to remove the use of webpack to help eliminate its (mis)configuration being a possible source of these problems?

**Comment by eng-dibo** [comment]
as I understood you want me to remove the webpack file, but I cannot because it is required by Angular.

-> I use Sharp in nodejs (not the front-end).

**Comment by eng-dibo** [comment]
any updates? @lovell

**Comment by lovell** [comment]
This is probably a question for either Firebase [support](https://firebase.google.com/support) or [community](https://firebase.community/) - good luck!

**Comment by eng-dibo** [comment]
updating sharp to the latest version fixed the issue.
thank you for your great efforts @lovell .
