### ISSUE TITLE
Something went wrong installing the "sharp" module (5424)

### ISSUE THREAD

**Issue by Schimi1983** [lovell/sharp#2169]
Hi,

somebody have the same issue?

`

iot.0 | 2020-04-18 11:13:00.775 | info | (5424) Connection changed: connect
-- | -- | -- | --
iot.0 | 2020-04-18 11:13:00.432 | info | (5424) Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
iot.0 | 2020-04-18 11:13:00.432 | warn |  
iot.0 | 2020-04-18 11:13:00.432 | warn | - Search for this error at https://github.com/lovell/sharp/issues
iot.0 | 2020-04-18 11:13:00.432 | warn | - Consult the installation documentation at https://sharp.pixelplumbing.com/install
iot.0 | 2020-04-18 11:13:00.432 | warn | "npm install --ignore-scripts=false --verbose" and look for errors
iot.0 | 2020-04-18 11:13:00.432 | warn | - Remove the "node_modules/sharp" directory then run
iot.0 | 2020-04-18 11:13:00.432 | warn | \\?\C:\Program Files\iobroker\SmartHome\node_modules\iobroker.iot\node_modules\sharp\build\Release\sharp.node
iot.0 | 2020-04-18 11:13:00.432 | warn | Die angegebene Prozedur wurde nicht gefunden.
iot.0 | 2020-04-18 11:13:00.432 | warn | Something went wrong installing the "sharp" module
iot.0 | 2020-04-18 11:13:00.432 | warn | (5424) Cannot initialize getImage: Error:
iot.0 | 2020-04-18 11:12:58.681 | info | (5424) starting. Version 1.4.6 in C:/Program Files/iobroker/SmartHome/node_modules/iobroker.iot, node: v10.17.0

`

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by iamzhanghao** [comment]
I have the same issue:

Using sharp 0.25.2
```
/home/app/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
        ^
Error:
Something went wrong installing the "sharp" module

Error loading shared library /home/app/node_modules/sharp/build/Release/sharp.node: Exec format error

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/home/app/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/app/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

ENV INFO:

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 159.04 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by iamzhanghao** [comment]
Just to update, I found out `node_modules/sharp/vendor` folder doesn't exist after install.
I ran `brew uninstall vips` then it works.
Root cause is platform miss match, my global install used `darwin-x64` but docker container needs `linuxmusl`

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.
