### ISSUE TITLE
PDF support on Heroku

### ISSUE THREAD

**Issue by adamhayek1** [lovell/sharp#2173]
Hey guys,

first of all amazing library, thanks for all the work. I'm having an issue getting PDF support to work when deploying to Heroku. I found this buildpack: https://github.com/brandoncc/heroku-buildpack-vips but when trying to deploy I get the following error:

```
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > sharp@0.18.4 install /tmp/build_18d25bdc43869ba65636dd4f72369cf6/node_modules/express-sharp/node_modules/sharp
       > node-gyp rebuild
       
       readelf: Error: '/usr/src/vips/lib/libvips-cpp.so': No such file
       gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
       gyp ERR! configure error 
       gyp ERR! stack Error: `gyp` failed with exit code: 1
       gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_18d25bdc43869ba65636dd4f72369cf6/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
       gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
       gyp ERR! System Linux 4.4.0-1062-aws
       gyp ERR! command "/tmp/build_18d25bdc43869ba65636dd4f72369cf6/.heroku/node/bin/node" "/tmp/build_18d25bdc43869ba65636dd4f72369cf6/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_18d25bdc43869ba65636dd4f72369cf6/node_modules/express-sharp/node_modules/sharp
       gyp ERR! node -v v11.15.0
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the sharp@0.18.4 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.nswFG/_logs/2020-04-19T18_59_22_146Z-debug.log
-----> Build failed
```

Any idea what I'm missing? Or is there a better way to get PDF support to work on Heroku.

Thanks

**Comment by lovell** [comment]
Hi, please can you upgrade to the latest sharp, currently v0.25.2, as the version you are trying to use is from September 2017. You might also want to upgrade Node.js as version 11 reached end of life in June 2019.

**Comment by adamhayek1** [comment]
Thanks for the reply. I did what you suggested and upgraded to Node 12. I also found an unused npm package that was installing an old sharp verion. However I still get the same (or very similar) error.

I will include the full log, buildpacks and Aptfile here:
Buildpacks:
- https://github.com/heroku/heroku-buildpack-apt
- https://github.com/brandoncc/heroku-buildpack-vips
- heroku/nodejs

Aptfile:
`libglib2.0-0
libglib2.0-dev
libpoppler-glib8`

Log:
```-----> Apt app detected
-----> Detected Aptfile or Stack changes, flushing cache
-----> Adding custom repositories
-----> Updating apt caches
       Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
       Get:2 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
       Get:3 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [71.5 kB]
       Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
       Get:5 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [903 kB]
       Get:6 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [843 kB]
       Get:7 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [297 kB]
       Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,205 kB]
       Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,376 kB]
       Fetched 4,873 kB in 1s (3,300 kB/s)
       Reading package lists...
-----> Fetching .debs for libglib2.0-0
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 27 not upgraded.
       Need to get 1,171 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 libglib2.0-0 amd64 2.56.4-0ubuntu0.18.04.6 [1,171 kB]
       Fetched 1,171 kB in 1s (1,825 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libglib2.0-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 27 not upgraded.
       Need to get 1,385 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 libglib2.0-dev amd64 2.56.4-0ubuntu0.18.04.6 [1,385 kB]
       Fetched 1,385 kB in 1s (2,085 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libpoppler-glib8
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         libnspr4 libnss3 libpoppler73
       The following NEW packages will be installed:
         libnspr4 libnss3 libpoppler-glib8 libpoppler73
       0 upgraded, 4 newly installed, 0 to remove and 27 not upgraded.
       Need to get 2,155 kB of archives.
       After this operation, 7,290 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libnspr4 amd64 2:4.18-1ubuntu1 [112 kB]
       Get:2 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 libnss3 amd64 2:3.35-2ubuntu2.7 [1,135 kB]
       Get:3 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 libpoppler73 amd64 0.62.0-2ubuntu2.10 [800 kB]
       Get:4 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 libpoppler-glib8 amd64 0.62.0-2ubuntu2.10 [108 kB]
       Fetched 2,155 kB in 1s (2,666 kB/s)
       Download complete and in download only mode
-----> Installing libglib2.0-0_2.56.4-0ubuntu0.18.04.6_amd64.deb
-----> Installing libglib2.0-dev_2.56.4-0ubuntu0.18.04.6_amd64.deb
-----> Installing libnspr4_2%3a4.18-1ubuntu1_amd64.deb
-----> Installing libnss3_2%3a3.35-2ubuntu2.7_amd64.deb
-----> Installing libpoppler73_0.62.0-2ubuntu2.10_amd64.deb
-----> Installing libpoppler-glib8_0.62.0-2ubuntu2.10_amd64.deb
-----> Writing profile script
-----> Rewrite package-config files
-----> vips app detected
-----> Vendoring binaries
       Fetching /app/tmp/buildpacks/5c56f165f1b08a13858b331652401de5c6eba22bfbd00f07f7c26d8a9692b32ce622f8f797527c93bae37d37f270d3536b28ddfc828d8b9568861898bc8cbc68/build/libvips.tar.gz
-----> Configuring build environment
-----> Building runtime environment
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  12.x
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.16.3...
       Using default npm version: 6.14.4
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules
       
       > fsevents@1.2.11 install /tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/fsevents
       > node-gyp rebuild
       
       make: Entering directory '/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/fsevents/build'
         SOLINK_MODULE(target) Release/obj.target/.node
         COPY Release/.node
       make: Leaving directory '/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/fsevents/build'
       
       > canvas@2.6.1 install /tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/canvas
       > node-pre-gyp install --fallback-to-build
       
       [canvas] Success: "/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/canvas/build/Release/canvas.node" is installed via remote
       
       > sharp@0.25.2 install /tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Detected globally-installed libvips v8.9.1
       info sharp Building from source via node-gyp
       readelf: Error: '/usr/src/vips/lib/libvips-cpp.so': No such file
       gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/pkgconfig::/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/vendor/vips/lib/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
       gyp ERR! configure error 
       gyp ERR! stack Error: `gyp` failed with exit code: 1
       gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
       gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
       gyp ERR! System Linux 4.4.0-1062-aws
       gyp ERR! command "/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.heroku/node/bin/node" "/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_de8e195ae9ee65c6d0ee7803b4290341/node_modules/sharp
       gyp ERR! node -v v12.16.3
       gyp ERR! node-gyp -v v5.1.0
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! sharp@0.25.2 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the sharp@0.25.2 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.L8bFB/_logs/2020-04-29T16_21_56_604Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed```

**Comment by lovell** [comment]
The salient error is here:
```
readelf: Error: '/usr/src/vips/lib/libvips-cpp.so': No such file
gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/pkgconfig::/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/vendor/vips/lib/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
```
You'll need to ensure the referenced `libvips-cpp.so` file exists and can be found via `PKG_CONFIG_PATH` in this buildpack.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
