### ISSUE TITLE
Unable to build project with sharp

### ISSUE THREAD

**Issue by notaduck** [lovell/sharp#2182]
I have an old project which is using sharp, and I am unable to install the project with `yarn install` and `npm install` and according to the output does it looks like that `sharp` is the root of the problem.

```
[test] npx envinfo --binaries --system
npx: installed 1 in 1.294s

  System:
    OS: Linux 5.6 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 8.23 GB / 15.48 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 13.13.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
```

```
[3/13] ⠈ sharp
[4/13] ⠈ node-sass
error /home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp
Output:
info sharp Using cached /home/daniel/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.13.0 runtime=node arch=x64 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.13.0 | linux | x64
gyp info find Python using Python version 3.7.2 found at "/home/daniel/.pyenv/versions/3.7.2/bin/python3"
gyp http GET https://nodejs.org/download/release/v13.13.0/node-v13.13.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.13.0/node-v13.13.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.13.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.13.0/SHASUMS256.txt
gyp info spawn /home/daniel/.pyenv/versions/3.7.2/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/daniel/.cache/node-gyp/13.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/daniel/.cache/node-gyp/13.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/daniel/.cache/node-gyp/13.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:24:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../src/common.cc:27:
../src/common.h: At global scope:
../src/common.h:82:20: error: ‘Handle’ is not a member of ‘v8’
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                    ^~~~~~
../src/common.h:82:37: error: expected primary-expression before ‘>’ token
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                     ^
../src/common.h:82:39: error: ‘obj’ was not declared in this scope
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                       ^~~
../src/common.h:82:56: error: expected primary-expression before ‘attr’
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                        ^~~~
../src/common.h:82:60: error: expression list treated as compound expression in initializer [-fpermissive]
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                            ^
../src/common.h:83:29: error: ‘Handle’ is not a member of ‘v8’
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                             ^~~~~~
../src/common.h:83:46: error: expected primary-expression before ‘>’ token
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                                              ^
../src/common.h:83:48: error: ‘obj’ was not declared in this scope
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                ^~~
../src/common.h:83:65: error: expected primary-expression before ‘attr’
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                                 ^~~~
../src/common.h:84:48: error: ‘Handle’ is not a member of ‘v8’
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                ^~~~~~
../src/common.h:84:65: error: expected primary-expression before ‘>’ token
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                 ^
../src/common.h:84:67: error: ‘obj’ was not declared in this scope
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                   ^~~
../src/common.h:84:84: error: expected primary-expression before ‘attr’
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                                    ^~~~
../src/common.h:84:37: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                     ^~~~~~
../src/common.h:84:89: error: expected ‘;’ before ‘{’ token
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                                         ^~
      |                                                                                         ;
../src/common.h:87:37: error: ‘Handle’ is not a member of ‘v8’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                     ^~~~~~
../src/common.h:87:54: error: expected primary-expression before ‘>’ token
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                      ^
../src/common.h:87:56: error: ‘obj’ was not declared in this scope
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                        ^~~
../src/common.h:87:73: error: expected primary-expression before ‘attr’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                         ^~~~
../src/common.h:87:26: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                          ^~~~~~
../src/common.h:87:78: error: expected ‘;’ before ‘{’ token
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                              ^~
      |                                                                              ;
../src/common.h:90:37: error: ‘Handle’ is not a member of ‘v8’
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                     ^~~~~~
../src/common.h:90:54: error: expected primary-expression before ‘>’ token
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                      ^
../src/common.h:90:56: error: ‘obj’ was not declared in this scope
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                        ^~~
../src/common.h:90:61: error: expected primary-expression before ‘int’
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                             ^~~
../src/common.h:87:26: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                          ^~~~~~
../src/common.h:90:70: error: expected ‘;’ before ‘{’ token
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                                      ^~
      |                                                                      ;
../src/common.h:96:9: error: ‘Handle’ is not a member of ‘v8’
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |         ^~~~~~
../src/common.h:96:26: error: expected primary-expression before ‘>’ token
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                          ^
../src/common.h:96:28: error: ‘input’ was not declared in this scope
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                            ^~~~~
../src/common.h:96:70: error: expected primary-expression before ‘&’ token
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                                                                      ^
../src/common.h:96:71: error: ‘buffersToPersist’ was not declared in this scope
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                                                                       ^~~~~~~~~~~~~~~~
../src/common.h:96:87: error: expression list treated as compound expression in initializer [-fpermissive]
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                                                                                       ^
../src/common.cc:34:8: error: redefinition of ‘bool sharp::HasAttr’
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |        ^~~~~~~
In file included from ../src/common.cc:27:
../src/common.h:82:8: note: ‘bool sharp::HasAttr’ previously defined here
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |        ^~~~~~~
../src/common.cc:34:20: error: ‘Handle’ is not a member of ‘v8’
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                    ^~~~~~
../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                     ^
../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                       ^~~
../src/common.cc:34:56: error: expected primary-expression before ‘attr’
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                        ^~~~
../src/common.cc:37:15: error: redefinition of ‘std::string sharp::AttrAsStr’
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |               ^~~~~~~~~
In file included from ../src/common.cc:27:
../src/common.h:83:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |               ^~~~~~~~~
../src/common.cc:37:29: error: ‘Handle’ is not a member of ‘v8’
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                             ^~~~~~
../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                              ^
../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                ^~~
../src/common.cc:37:65: error: expected primary-expression before ‘attr’
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                 ^~~~
../src/common.cc:42:20: error: redefinition of ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’
   42 |   InputDescriptor* CreateInputDescriptor(
      |                    ^~~~~~~~~~~~~~~~~~~~~
In file included from ../src/common.cc:27:
../src/common.h:95:20: note: ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’ previously defined here
   95 |   InputDescriptor* CreateInputDescriptor(
      |                    ^~~~~~~~~~~~~~~~~~~~~
../src/common.cc:43:9: error: ‘Handle’ is not a member of ‘v8’
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |         ^~~~~~
../src/common.cc:43:26: error: expected primary-expression before ‘>’ token
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                          ^
../src/common.cc:43:28: error: ‘input’ was not declared in this scope
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                            ^~~~~
../src/common.cc:43:70: error: expected primary-expression before ‘&’ token
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                                                                      ^
../src/common.cc:43:71: error: ‘buffersToPersist’ was not declared in this scope
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                                                                       ^~~~~~~~~~~~~~~~
make: *** [sharp.target.mk:132: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.6.6-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/daniel/Nextcloud/Projects/personal_blog/node_modules/sharp
```

**Comment by zermatt** [comment]
hey @notaduck - the issues is because `Sharp` uses 3rd party libraries, such as `libvips` that must be compiled using particular versions of **node**. The simplest solution is to use something like `nvm` to switch to a different version and then try `yarn` or `npm` again.

For example:

```bash
nvm use v10.16.3
yarn
```

I always forget this and spend about 10 minutes complaining to myself, before I remember. 😄 

Cheers.

**Comment by lovell** [comment]
Support for Node.js 13 was added in sharp v0.23.2.

https://sharp.pixelplumbing.com/changelog#v0232---28supthsup-october-2019

I highly recommend upgrading to the latest v0.25.2 that allows you to change the major version of Node.js without re-installation.
