### ISSUE TITLE
Install sharp on Azure App Service causes error

### ISSUE THREAD

**Issue by andrewt3000** [lovell/sharp#2247]
When I deploy my node app to Azure App Service I get the error below.  Azure App Service doesn't give you much control over deploying your app. I suspect from this error that it may be using a windows machine to npm install and copying it to my Linux machine. 

Anyone gotten Sharp to deploy to Azure App Service?

```
PATH="$PATH:/home/site/wwwroot" node index.js
2020-06-07T00:53:38.189890630Z /home/site/wwwroot/node_modules/sharp/lib/libvips.js:68
2020-06-07T00:53:38.189950030Z       throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.`);
2020-06-07T00:53:38.189955629Z       ^
2020-06-07T00:53:38.189959229Z 
2020-06-07T00:53:38.189962629Z Error: 'win32-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
2020-06-07T00:53:38.189966329Z     at Object.hasVendoredLibvips (/home/site/wwwroot/node_modules/sharp/lib/libvips.js:68:13)
2020-06-07T00:53:38.189986829Z     at Object. (/home/site/wwwroot/node_modules/sharp/lib/constructor.js:7:22)
```

**Comment by lovell** [comment]
> 'win32-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.

The runtime environment, in this case Linux x64, needs to be set at `npm install` time.

```sh
rm -rf node_modules/sharp
npm install --arch=x64 --platform=linux sharp
```

https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
