### ISSUE TITLE
Installation: electron builder and errorOut=ERR! sharp 'linux-x64' binaries cannot be used on the 'linux-ia32' platform

### ISSUE THREAD

**Issue by xnerhu** [lovell/sharp#2264]
Hello!

I'm trying to build my electron app using electron-builder on github actions (Ubuntu ia32) and I get 

```bash
2020-06-18T13:14:46.0860757Z   • rebuilding native dependency  name=sharp version=0.25.4
2020-06-18T13:14:51.8297776Z   ⨯ cannot execute  cause=exit status 1
2020-06-18T13:14:51.8311067Z                     out=$ (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
2020-06-18T13:14:51.8312390Z     make: Entering directory '/home/runner/work/desktop/desktop/node_modules/sharp/build'
2020-06-18T13:14:51.8315505Z       CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
2020-06-18T13:14:51.8316562Z       AR(target) Release/obj.target/../node-addon-api/nothing.a
2020-06-18T13:14:51.8317151Z       COPY Release/nothing.a
2020-06-18T13:14:51.8355648Z       TOUCH Release/obj.target/libvips-cpp.stamp
2020-06-18T13:14:51.8356498Z       CXX(target) Release/obj.target/sharp/src/common.o
2020-06-18T13:14:51.8357337Z     sharp.target.mk:137: recipe for target 'Release/obj.target/sharp/src/common.o' failed
2020-06-18T13:14:51.8358463Z     make: Leaving directory '/home/runner/work/desktop/desktop/node_modules/sharp/build'
2020-06-18T13:14:51.8362353Z     info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-06-18T13:14:51.8362669Z     
2020-06-18T13:14:51.8363437Z                     errorOut=ERR! sharp 'linux-x64' binaries cannot be used on the 'linux-ia32' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-ia32' platform.
2020-06-18T13:14:51.8364024Z     info sharp Attempting to build from source via node-gyp but this may fail due to the above error
2020-06-18T13:14:51.8364330Z     info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
2020-06-18T13:14:51.8364614Z     gyp info it worked if it ends with ok
2020-06-18T13:14:51.8364906Z     gyp info using node-gyp@5.1.0
2020-06-18T13:14:51.8365112Z     gyp info using node@12.18.0 | linux | x64
2020-06-18T13:14:51.8365341Z     gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
2020-06-18T13:14:51.8365802Z     gyp http GET https://electronjs.org/headers/v9.0.2/node-v9.0.2-headers.tar.gz
2020-06-18T13:14:51.8366258Z     gyp http 200 https://electronjs.org/headers/v9.0.2/node-v9.0.2-headers.tar.gz
2020-06-18T13:14:51.8366558Z     gyp http GET https://electronjs.org/headers/v9.0.2/SHASUMS256.txt
2020-06-18T13:14:51.8366824Z     gyp http 200 https://electronjs.org/headers/v9.0.2/SHASUMS256.txt
2020-06-18T13:14:51.8367038Z     gyp info spawn /usr/bin/python
2020-06-18T13:14:51.8367211Z     gyp info spawn args [
2020-06-18T13:14:51.8367868Z     gyp info spawn args   '/opt/hostedtoolcache/node/12.18.0/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2020-06-18T13:14:51.8368306Z     gyp info spawn args   'binding.gyp',
2020-06-18T13:14:51.8368807Z     gyp info spawn args   '-f',
2020-06-18T13:14:51.8369124Z     gyp info spawn args   'make',
2020-06-18T13:14:51.8369457Z     gyp info spawn args   '-I',
2020-06-18T13:14:51.8369889Z     gyp info spawn args   '/home/runner/work/desktop/desktop/node_modules/sharp/build/config.gypi',
2020-06-18T13:14:51.8370210Z     gyp info spawn args   '-I',
2020-06-18T13:14:51.8370676Z     gyp info spawn args   '/opt/hostedtoolcache/node/12.18.0/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2020-06-18T13:14:51.8371013Z     gyp info spawn args   '-I',
2020-06-18T13:14:51.8371429Z     gyp info spawn args   '/home/runner/.electron-gyp/9.0.2/include/node/common.gypi',
2020-06-18T13:14:51.8371787Z     gyp info spawn args   '-Dlibrary=shared_library',
2020-06-18T13:14:51.8372134Z     gyp info spawn args   '-Dvisibility=default',
2020-06-18T13:14:51.8372554Z     gyp info spawn args   '-Dnode_root_dir=/home/runner/.electron-gyp/9.0.2',
2020-06-18T13:14:51.8373051Z     gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/12.18.0/x64/lib/node_modules/npm/node_modules/node-gyp',
2020-06-18T13:14:51.8373496Z     gyp info spawn args   '-Dnode_lib_file=/home/runner/.electron-gyp/9.0.2/<(target_arch)/node.lib',
2020-06-18T13:14:51.8373932Z     gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/desktop/desktop/node_modules/sharp',
2020-06-18T13:14:51.8374291Z     gyp info spawn args   '-Dnode_engine=v8',
2020-06-18T13:14:51.8374613Z     gyp info spawn args   '--depth=.',
2020-06-18T13:14:51.8374892Z     gyp info spawn args   '--no-parallel',
2020-06-18T13:14:51.8375363Z     gyp info spawn args   '--generator-output',
2020-06-18T13:14:51.8375684Z     gyp info spawn args   'build',
2020-06-18T13:14:51.8376049Z     gyp info spawn args   '-Goutput_dir=.'
2020-06-18T13:14:51.8376237Z     gyp info spawn args ]
2020-06-18T13:14:51.8376411Z     gyp info spawn make
2020-06-18T13:14:51.8376789Z     gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-06-18T13:14:51.8377180Z     In file included from ../vendor/lib/glib-2.0/include/glibconfig.h:9:0,
2020-06-18T13:14:51.8377577Z                      from ../vendor/include/glib-2.0/glib/gtypes.h:32,
2020-06-18T13:14:51.8377972Z                      from ../vendor/include/glib-2.0/glib/galloca.h:32,
2020-06-18T13:14:51.8378346Z                      from ../vendor/include/glib-2.0/glib.h:30,
2020-06-18T13:14:51.8378791Z                      from ../vendor/include/glib-2.0/gobject/gbinding.h:28,
2020-06-18T13:14:51.8379208Z                      from ../vendor/include/glib-2.0/glib-object.h:22,
2020-06-18T13:14:51.8379441Z                      from ../vendor/include/vips/vips8:35,
2020-06-18T13:14:51.8379661Z                      from ../src/common.cc:23:
2020-06-18T13:14:51.8380143Z     ../vendor/include/glib-2.0/glib/gtypes.h: In function ‘gboolean _GLIB_CHECKED_ADD_U64(guint64*, guint64, guint64)’:
2020-06-18T13:14:51.8380632Z     ../vendor/include/glib-2.0/glib/gmacros.h:742:31: error: static assertion failed: Expression evaluates to false
2020-06-18T13:14:51.8380887Z      #define G_STATIC_ASSERT(expr) static_assert (expr, "Expression evaluates to false")
2020-06-18T13:14:51.8381099Z                                    ^
2020-06-18T13:14:51.8381559Z     ../vendor/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
2020-06-18T13:14:51.8381800Z        G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
2020-06-18T13:14:51.8381993Z        ^~~~~~~~~~~~~~~
2020-06-18T13:14:51.8382156Z     At global scope:
2020-06-18T13:14:51.8382592Z     cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
2020-06-18T13:14:51.8382826Z     make: *** [Release/obj.target/sharp/src/common.o] Error 1
2020-06-18T13:14:51.8383235Z     gyp ERR! build error 
2020-06-18T13:14:51.8383737Z     gyp ERR! stack Error: `make` failed with exit code: 2
2020-06-18T13:14:51.8384782Z     gyp ERR! stack     at ChildProcess.onExit (/opt/hostedtoolcache/node/12.18.0/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2020-06-18T13:14:51.8385271Z     gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-06-18T13:14:51.8385581Z     gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2020-06-18T13:14:51.8386005Z     gyp ERR! System Linux 5.3.0-1028-azure
2020-06-18T13:14:51.8386679Z     gyp ERR! command "/opt/hostedtoolcache/node/12.18.0/x64/bin/node" "/opt/hostedtoolcache/node/12.18.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-06-18T13:14:51.8386977Z     gyp ERR! cwd /home/runner/work/desktop/desktop/node_modules/sharp
2020-06-18T13:14:51.8387407Z     gyp ERR! node -v v12.18.0
2020-06-18T13:14:51.8387779Z     gyp ERR! node-gyp -v v5.1.0
2020-06-18T13:14:51.8388135Z     gyp ERR! not ok 
2020-06-18T13:14:51.8416932Z     error Command failed with exit code 1.
2020-06-18T13:14:51.8417189Z     
2020-06-18T13:14:51.8417463Z                     command=/opt/hostedtoolcache/node/12.18.0/x64/bin/node /usr/share/yarn/bin/yarn.js run install
2020-06-18T13:14:51.8417729Z                     workingDir=/home/runner/work/desktop/desktop/node_modules/sharp
2020-06-18T13:14:51.8578425Z Error: Command failed: npx --no-install electron-builder --linux 
2020-06-18T13:14:51.8578721Z     at checkExecSyncError (child_process.js:630:11)
2020-06-18T13:14:51.8578919Z     at execSync (child_process.js:666:15)
2020-06-18T13:14:51.8579133Z     at run (/home/runner/work/desktop/desktop/scripts/utils.js:5:3)
2020-06-18T13:14:51.8579626Z     at /home/runner/work/desktop/desktop/scripts/ci-build.js:81:5 {
2020-06-18T13:14:51.8579991Z   status: 1,
2020-06-18T13:14:51.8580144Z   signal: null,
2020-06-18T13:14:51.8580308Z   output: [ null, null, null ],
2020-06-18T13:14:51.8580469Z   pid: 6028,
2020-06-18T13:14:51.8580627Z   stdout: null,
2020-06-18T13:14:51.8580782Z   stderr: null
2020-06-18T13:14:51.8580940Z }
2020-06-18T13:14:51.8847030Z error Command failed with exit code 1.
2020-06-18T13:14:51.8850938Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-06-18T13:14:51.8995161Z ##[error]Process completed with exit code 1.
2020-06-18T13:14:51.9056013Z Post job cleanup.
2020-06-18T13:14:52.0327970Z [command]/usr/bin/git version
2020-06-18T13:14:52.0391327Z git version 2.27.0
2020-06-18T13:14:52.0436876Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-06-18T13:14:52.0482558Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-06-18T13:14:52.0752526Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-06-18T13:14:52.0781871Z http.https://github.com/.extraheader
2020-06-18T13:14:52.0792882Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-06-18T13:14:52.0830801Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-06-18T13:14:52.1179653Z Cleaning up orphan processes
2020-06-18T13:14:52.1575434Z Terminate orphan process: pid (6049) (node)
2020-06-18T13:14:52.1600832Z Terminate orphan process: pid (6071) (sh)
2020-06-18T13:14:52.1620988Z Terminate orphan process: pid (6105) (node)
2020-06-18T13:14:52.1642238Z Terminate orphan process: pid (6245) (sh)
2020-06-18T13:14:52.1660851Z Terminate orphan process: pid (6246) (sh)
2020-06-18T13:14:52.1679500Z Terminate orphan process: pid (6247) (node-gyp)
2020-06-18T13:14:52.1700034Z Terminate orphan process: pid (6296) (make)
2020-06-18T13:14:52.1723482Z Terminate orphan process: pid (6394) (cc)
2020-06-18T13:14:52.1742660Z Terminate orphan process: pid (6402) (cc1)
```

Node: 12
Electron: 9.0.2
Electron-Builder: 22.7.0

**Comment by lovell** [comment]
Prebuilt binaries are not provided for 32-bit (x86, ia32) Linux.

https://sharp.pixelplumbing.com/install#prebuilt-binaries

The log above mentions 64-bit (x64) so you may want to check your build environment:

> 2020-06-18T13:14:51.8365112Z     gyp info using node@12.18.0 | linux | x64

**Comment by sentialx** [comment]
@lovell Is there a way to build for 32-bit on a Linux 64-bit machine? I had similar problem with building better-sqlite3 but it was enough to just install g++-multilib.

**Comment by lovell** [comment]
If you're cross-compiling then libvips and its dependencies will be required too, plus you'll need to work out how to bundle all these shared libraries with electron (e.g. you might need to compile it from source also).

This is not going to be a straightforward task - good luck!

**Comment by xnerhu** [comment]
Thanks for your help @lovell.
