### ISSUE TITLE
can't install sharp on ubuntu server

### ISSUE THREAD

**Issue by Leccho** [lovell/sharp#2313]
I'm using node 12.18.3 on Ubuntu 16.04LTS and I'm trying to install dependencies for sharp with the `npm install`. I've been using sharp with nestjs to work with images and I'm now at the deploy stage. So sharp work on my dev environment wich was on Windows. On my server thought sharp dosen't install.

```
> sharp@0.25.4 install /var/www/inspection-rest-api/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/var/www/inspection-rest-api/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp`?

**Comment by Leccho** [comment]
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose', 'sharp' ]
npm info using npm@6.14.6
npm info using node@v12.18.3
npm verb npm-session 73ae9e92b78c224f
npm http fetch GET 304 https://registry.npmjs.org/sharp 177ms (from cache)
npm timing stage:loadCurrentTree Completed in 3930ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 49ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2388ms
npm http fetch GET 304 https://registry.npmjs.org/color 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 125ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 143ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 147ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 155ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 155ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 159ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 163ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 84ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 102ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 119ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 128ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ini 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 72ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 76ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 86ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 86ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5591ms
npm timing stage:loadIdealTree Completed in 8988ms
npm timing stage:generateActionsToTake Completed in 254ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-724ba7b227fe397a.lock for /var/www/inspection-rest-api/node_modules/.staging
npm timing action:extract Completed in 240ms
npm timing action:finalize Completed in 50ms
npm timing action:refresh-package-json Completed in 45ms
npm info lifecycle yallist@4.0.0~preinstall: yallist@4.0.0
npm info lifecycle minipass@3.1.3~preinstall: minipass@3.1.3
npm info lifecycle fs-minipass@2.1.0~preinstall: fs-minipass@2.1.0
npm info lifecycle yallist@4.0.0~preinstall: yallist@4.0.0
npm info lifecycle minizlib@2.1.0~preinstall: minizlib@2.1.0
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle chownr@2.0.0~preinstall: chownr@2.0.0
npm info lifecycle mkdirp@1.0.4~preinstall: mkdirp@1.0.4
npm info lifecycle yallist@4.0.0~preinstall: yallist@4.0.0
npm info lifecycle node-addon-api@3.0.0~preinstall: node-addon-api@3.0.0
npm info lifecycle semver@7.3.2~preinstall: semver@7.3.2
npm info lifecycle tar@6.0.2~preinstall: tar@6.0.2
npm info lifecycle sharp@0.25.4~preinstall: sharp@0.25.4
npm timing action:preinstall Completed in 8ms
npm info linkStuff yallist@4.0.0
npm info linkStuff minipass@3.1.3
npm info linkStuff fs-minipass@2.1.0
npm info linkStuff yallist@4.0.0
npm info linkStuff minizlib@2.1.0
npm info linkStuff simple-concat@1.0.1
npm info linkStuff chownr@2.0.0
npm info linkStuff mkdirp@1.0.4
npm verb linkBins [
npm verb linkBins   { mkdirp: 'bin/cmd.js' },
npm verb linkBins   '/var/www/inspection-rest-api/node_modules/tar/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff yallist@4.0.0
npm info linkStuff node-addon-api@3.0.0
npm info linkStuff semver@7.3.2
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   '/var/www/inspection-rest-api/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff tar@6.0.2
npm info linkStuff sharp@0.25.4
npm timing action:build Completed in 20ms
npm info lifecycle yallist@4.0.0~install: yallist@4.0.0
npm info lifecycle minipass@3.1.3~install: minipass@3.1.3
npm info lifecycle fs-minipass@2.1.0~install: fs-minipass@2.1.0
npm info lifecycle yallist@4.0.0~install: yallist@4.0.0
npm info lifecycle minizlib@2.1.0~install: minizlib@2.1.0
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle chownr@2.0.0~install: chownr@2.0.0
npm info lifecycle mkdirp@1.0.4~install: mkdirp@1.0.4
npm info lifecycle yallist@4.0.0~install: yallist@4.0.0
npm info lifecycle node-addon-api@3.0.0~install: node-addon-api@3.0.0
npm info lifecycle semver@7.3.2~install: semver@7.3.2
npm info lifecycle tar@6.0.2~install: tar@6.0.2
npm info lifecycle sharp@0.25.4~install: sharp@0.25.4

> sharp@0.25.4 install /var/www/inspection-rest-api/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/var/www/inspection-rest-api/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@12.18.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, unlink 'build'
gyp ERR! System Linux 4.4.0-186-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/inspection-rest-api/node_modules/sharp
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm verb lifecycle sharp@0.25.4~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.25.4~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/inspection-rest-api/node_modules/sharp/node_modules/.bin:/var/www/inspection-rest-api/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
npm verb lifecycle sharp@0.25.4~install: CWD: /var/www/inspection-rest-api/node_modules/sharp
npm info lifecycle sharp@0.25.4~install: Failed to exec install script
npm timing action:install Completed in 245ms
npm verb unlock done using /root/.npm/_locks/staging-724ba7b227fe397a.lock for /var/www/inspection-rest-api/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 33ms
npm timing stage:runTopLevelLifecycles Completed in 14796ms
npm WARN ts-jest@26.1.3 requires a peer of jest@>=26 <27 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm verb pkgid sharp@0.25.4
npm verb cwd /var/www/inspection-rest-api
npm verb Linux 4.4.0-186-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose" "sharp"
npm verb node v12.18.3
npm verb npm  v6.14.6
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.25.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing audit submit Completed in 2202ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 2201ms
npm timing audit body Completed in 1ms
npm timing npm Completed in 16878ms

```

**Comment by Leccho** [comment]
Well I just tried `npm install --unsafe-perm` and it did the trick. I would still like to understand what `--unsafe-perm` means thought.

**Comment by lovell** [comment]
It's an `npm` flag - https://docs.npmjs.com/misc/config#unsafe-perm - if you're running `npm install` as root then it ensures any child commands are also run as root. It's best to avoid running as root if possible.

**Comment by Leccho** [comment]
Thanks alot!
