### ISSUE TITLE
Problem during launch "not be found C:\laragon\www\Puppeteer_bossweb\node_modules\sharp\build\Release\sharp.node"

### ISSUE THREAD

**Issue by lucasHam** [lovell/sharp#2319]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

yes, version : 0.25.4

What is the output of running `npx envinfo --binaries --system`?

Binaries:
    Node: 12.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD

when launching my code, this error appears and blocks me.
I tried to find existing solutions on google but nothing.
sorry for my bad english
Thanks for your help

```
C:\laragon\www\Puppeteer_bossweb\node_modules\sharp\lib\constructor.js:34
  throw new Error(error);
  ^

Error:
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\laragon\www\Puppeteer_bossweb\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\laragon\www\Puppeteer_bossweb\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\laragon\www\Puppeteer_bossweb\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**Comment by lovell** [comment]
Does the repo at `C:\laragon\www\Puppeteer_bossweb` also have `canvas` as a dependency? If so, please see #2125 specifically #2125 (comment)

**Comment by lucasHam** [comment]
yes, I just noticed that I have another module that has a node-canvas dependency but I can't do without it for my project

**Comment by lovell** [comment]
Thanks for confirming, please see https://github.com/lovell/sharp/issues/2125#issuecomment-653783908
