### ISSUE TITLE
Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by Dajamante** [lovell/sharp#2331]
Thank you for the additional information, the problem is revealed here:
```
npm info lifecycle sharp@0.23.4~install: ignored because ignore-scripts is set to true
```
You'll need to reset `ignore-scripts` to its default value of `false`.

https://docs.npmjs.com/misc/config#ignore-scripts

_Originally posted by @lovell in https://github.com/lovell/sharp/issues/2026#issuecomment-572948829_

Hi! I set the param to false and it did not solve it for me.

blog2 on  master [!?] is 📦 v0.1.0 via ⬢ v10.16.0 via 🅒 base
➜ npm config set ignore-script false

blog2 on  master [!?] is 📦 v0.1.0 via ⬢ v10.16.0 via 🅒 base
➜ npm config get ignore-script
false

What is the next step?

**Comment by lovell** [comment]
```diff
- npm config set ignore-script false
+ npm config set ignore-scripts false
```

**Comment by Dajamante** [comment]
It is not possible to uninstall sharp or oniguruma. Both tries give me the following errors:


```
blog2 on  master [✘!?] is 📦 v0.1.0 via ⬢ v10.16.0 via 🅒 base
➜ npm uninstall sharp

> fsevents@1.2.10 install /Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.10/fse-v1.2.10-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.10 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/aissata/blog2/node_modules/babel-plugin-add-module-exports/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> oniguruma@7.2.1 install /Users/aissata/blog2/node_modules/oniguruma
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aissata/blog2/node_modules/oniguruma
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.10 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.10 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@7.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aissata/.npm/_logs/2020-08-23T18_09_28_166Z-debug.log

```

**Comment by lovell** [comment]
When you uninstall a package, npm attempts to re-install any other missing dependencies, which is what is happening here. Your repo requires the `babel-plugin-add-module-exports` module which requires `fsevents` but that must be compiled from source. You'll probably need to install xcode for this.

I'd like to reiterate that this is not a sharp error but is instead other dependencies preventing `npm install` from completing for all dependencies.

**Comment by Dajamante** [comment]
Thank you, I will try to find a solution.
