### ISSUE TITLE
Windows Error on require()

### ISSUE THREAD

**Issue by sirsavary** [lovell/sharp#234]
I am using 64 bit Windows 8.1, with Visual Studio 2013 and 32 bit iojs version 2.3.0. libvips version is 7.42.3 and I can compile sharp properly, issues only arise when I try to require it:

```
module.js:343
        ' for module ' + JSON.stringify(this.id));
                       ^
Error: The specified procedure could not be found.
C:\Users\Jesse\Development\Projects\modmtn\node_modules\sharp\build\Release\sharp.node
    at Error (native)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jesse\Development\Projects\modmtn\node_modules\sharp\index.js:12:13)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
```

**Comment by lovell** [comment]
Hello, it looks like sharp may have been compiled against one version of io.js and is being run against another. Perhaps the version of io.js was recently upgraded on this machine?

You can force recompilation of your project's dependencies by removing the existing `node_modules` directory and running `npm i` again.

**Comment by oliversalzburg** [comment]
I think I'm having the same or a similar issue:

```
$ node .build/splashscreen.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: error: 193C:\…\node_modules\sharp\build\Release\sharp.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\…\node_modules\sharp\index.js:12:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\…\.build\splashscreen.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I removed all npm modules and reinstalled them with `npm install --arch=ia32 --msvs_version=2013`. Makes no difference.

I'm using 64bit NodeJS 0.12.3

**Comment by lovell** [comment]
Hello @oliversalzburg, the 64-bit `node.exe` is currently [unsupported](https://github.com/lovell/sharp#windows) by this module - see #224 if you're able to help get it working.

As an aside, I believe 64-bit node.exe won't work with any C++ addons compiled using the `--arch=ia32` flag. Specifying it can help `node-gyp` determine which arch to compile for e.g. in the event of 32 and 64 both being present.

**Comment by oliversalzburg** [comment]
@lovell Ah, I see. Thanks for the information.

**Comment by sirsavary** [comment]
@lovell I purged any excess versions of node and iojs before compiling. I got the same error on node, too.

**Comment by lovell** [comment]
@sirsavary Is `VIPS_HOME` also set/available at runtime? Does [$(VIPS_HOME)/lib](https://github.com/lovell/sharp/blob/master/binding.gyp#L14) exist at runtime?

Are you able to try a more recent version of libvips e.g. the [8.x series](http://www.vips.ecs.soton.ac.uk/supported/current/win32/)?

**Comment by sirsavary** [comment]
@lovell ```VIPS_HOME``` is available, I will try a version in the 8.x series.

**Comment by TheThing** [comment]
I'm having same problem.

```
D:\my\project>node
> require('sharp');
Error: The specified procedure could not be found.
D:\my\project\node_modules\sharp\build\Release\sharp.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\my\project\node_modules\sharp\index.js:12:13)
```

I've tried rebuilding for both the 8.0.2 and 7.42.3 and neither work.
And yes I have configured VIPS_HOME correctly:

```
D:\my\project>vips --version
vips-8.0.2-Tue May  5 15:46:00 BST 2015

D:\my\project>ECHO %VIPS_HOME%
D:\NFP\vips-dev-8.0.2

D:\my\project>dir /B %VIPS_HOME%\lib
expat.lib
fontconfig.def
fontconfig.lib
...etc...
```

**Comment by lovell** [comment]
Assuming `vips-dev-8.0.2\bin` [has been added](http://sharp.dimens.io/en/stable/install/#windows) to `PATH`, the next step here might be to try loading the `build/Release/sharp.node` file with a tool like [Dependency Walker](http://www.dependencywalker.com/) to see what could be causing the `specified procedure could not be found` error.

**Comment by TheThing** [comment]
As you can see, the vips command is working fine, meaning `vips-dev-8.0.2\bin` has been added to `PATH`. And yes I had already tried taking Dependency Walker through it and it also looked okay.

I have tried doing a lot of googling relating to this error message, hence why I'm stuck now and posting on this issue thread.

**Comment by TheThing** [comment]
And I finally figured out the problem \o/

Using Dependancy Walker again I went deeper into it. Deep inside I found some tiny red marks on `ZLIB1.DLL` and `INTL.DLL`. As it turns out, my zend server actually had older version of those program and zend server bin folder was __ahead__ in the `PATH` list. I moved the `vips-dev-8.0.2\bin` ahead of zend server bin in the `PATH` environment variable and it finally works now \o/

Thank you lovell!

**Comment by eloops** [comment]
I'm having a similar issue. I'm running Win8.1 64-bit, with nodejs 0.12.7 x86. I compiled okay with vs2013 (npm install sharp worked without issue), however when I require it throws an error:

````
E:\node\rb>node
> require('sharp')
Error: error: 127E:\node\rb\node_modules\sharp\build\Release\sharp.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\node\rb\node_modules\sharp\index.js:12:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
````
I tried re-compiling using vs2015, I was able to successfully get it to compile, however it continues to throw the same error when I try to load it. I can have a look at it with dependancy walker but I really don't know what I'm looking for.

**Comment by lovell** [comment]
Hi @eloops, has `vips-dev-x.y.z\bin` been added to the `PATH` environment variable?http://sharp.dimens.io/en/stable/install/#windows

**Comment by eloops** [comment]
Hi @lovell, yes it's been added to the path. I took the liberty of doing what @TheThing has done, and put the entry further up the PATH list. I previously had it at the end of the user %PATH% variable, now it is at the start of the system %PATH% variable.

When opening a nodejs command prompt in Windows it also adds a few extra entries to it. It seems to be loading now, I'll perform some actual tests later in the week. Thanks for your help, apologies for not looking more closely at the PATH var initially.

**Comment by lovell** [comment]
Looks like everyone here has solved their problems, but please feel free to re-open if not.

**Comment by kjsagre** [comment]
install it 20 time  and it will work
