### ISSUE TITLE
Error when loading sharp module on Electron (win10)

### ISSUE THREAD

**Issue by darron1217** [lovell/sharp#2352]
It seems similar issue with #1530

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
`version 0.26.0`

What are the steps to reproduce?
1. install strapi
2. add `electron`, `electron-rebuild` package to project
3. rebuild electron and run
4. Works well on MacOS (Catalina), but not working on Windows 10(64bit)

What is the expected behaviour?
show contents on electron

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
my *main.js*

```js
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')
const strapi = require('strapi/lib/Strapi')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    maximizable: true,
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // and load the index.html of the app.
  strapi({
    autoReload: true,
    serveAdminPanel: true,
  }).start().then(() => {
    mainWindow.loadURL('http://127.0.0.1:1337/');
  }).catch((e) => {
    console.log(e);
  });

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

```

Are you able to provide a sample image that helps explain the problem?
```
C:\Users\darron\Desktop\electron-strapi>electron .

Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Users\darron\Desktop\electron-strapi\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\Users\darron\Desktop\electron-strapi\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\darron\Desktop\electron-strapi\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
[2020-09-04T07:05:17.538Z] debug ?뷂툘 Server wasn't able to start properly.
```

What is the output of running `npx envinfo --binaries --system`?
Windows on Pararells VM
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (3) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 3.08 GB / 5.87 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
What's the output of running `npm install --verbose sharp`? Are there any other native dependencies that could be conflicting e.g. `canvas`?

**Comment by darron1217** [comment]
I'm using yarn to handle dependencies.
I tried `yarn add --verbose sharp` stdout is too verbose (every file's directory is being printed)

example
```
yarn add v1.22.5
verbose 0.188838401 Checking for configuration file "C:\\Users\\darron\\Desktop\\electron-strapi\\.npmrc".
verbose 0.189633501 Checking for configuration file "C:\\Users\\darron\\.npmrc".
verbose 0.190216501 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.1907702 Found configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.1916112 Checking for configuration file "C:\\Users\\darron\\Desktop\\electron-strapi\\.npmrc".
verbose 0.192392901 Checking for configuration file "C:\\Users\\darron\\Desktop\\.npmrc".
verbose 0.193182501 Checking for configuration file "C:\\Users\\darron\\.npmrc".
verbose 0.1938966 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.1966139 Checking for configuration file "C:\\Users\\darron\\Desktop\\electron-strapi\\.yarnrc".
verbose 0.1982743 Checking for configuration file "C:\\Users\\darron\\.yarnrc".
verbose 0.199544401 Found configuration file "C:\\Users\\darron\\.yarnrc".
verbose 0.200851001 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\yarnrc".
verbose 0.2015781 Checking for configuration file "C:\\Users\\darron\\Desktop\\electron-strapi\\.yarnrc".
verbose 0.202200901 Checking for configuration file "C:\\Users\\darron\\Desktop\\.yarnrc".
verbose 0.202631001 Checking for configuration file "C:\\Users\\darron\\.yarnrc".
verbose 0.203026001 Found configuration file "C:\\Users\\darron\\.yarnrc".
verbose 0.203628001 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.2086363 current time: 2020-09-04T08:02:43.934Z
[1/5] Validating package.json...
[2/5] Resolving packages...
verbose 0.844858101 Performing "GET" request to "https://registry.yarnpkg.com/sharp".
verbose 0.912915201 Request "https://registry.yarnpkg.com/sharp" finished with status code 200.
[3/5] Fetching packages...
-----
skip
----
verbose 65.986647601 Removing extraneous file "C:\\Users\\darron\\Desktop\\electron-strapi\\node_modules\\webpack-dev-server\\node_modules\\.bin".
verbose 65.9888086 Removing extraneous file "C:\\Users\\darron\\Desktop\\electron-strapi\\node_modules\\webpack-log\\node_modules\\.bin".
verbose 65.9894403 Removing extraneous file "C:\\Users\\darron\\Desktop\\electron-strapi\\node_modules\\webpackbar\\node_modules\\.bin".
verbose 65.990701701 Removing extraneous file "C:\\Users\\darron\\Desktop\\electron-strapi\\node_modules\\worker-farm\\node_modules\\.bin".
verbose 65.991215401 Removing extraneous file "C:\\Users\\darron\\Desktop\\electron-strapi\\node_modules\\sqlite3\\lib\\binding".
verbose 65.9929707 Removing extraneous file "C:\\Users\\darron\\Desktop\\electron-strapi\\node_modules\\sqlite3\\lib\\binding\\napi-v3-win32-x64".
[5/5] Building fresh packages...
[1/7] ⡀ sqlite3
[2/7] ⡀ strapi
[1/7] ⢀ sqlite3
[-/7] ⢀ waiting...
[6/7] ⢀ sharp
[4/7] ⢀ core-js
verbose 69.8205202 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
[1/7] ⡀ sqlite3
[-/7] ⡀ waiting...
[6/7] ⡀ sharp
[7/7] ⢀ electron
verbose 72.273731401 node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.18.3 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\darron\Desktop\electron-strapi\node_modules\sqlite3\lib\binding\napi-v3-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-win32-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-win32-x64.tar.gz
[-/7] ⢀ waiting...
[-/7] ⠄ waiting...
[-/7] ⠄ waiting...
[6/7] ⠄ sharp
[-/7] ⠄ waiting...
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
[6/7] ⠂ sharp
success Saved 1 new dependency.
info Direct dependencies
└─ sharp@0.26.0
info All dependencies
└─ sharp@0.26.0
Done in 82.61s.
```

**Comment by darron1217** [comment]
This is my package.json

```json
{
  "name": "electron-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "main": "main.js",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "app": "electron .",
    "build:win": "electron-builder --win"
  },
  "devDependencies": {
    "electron": "^10.1.1",
    "electron-builder": "^22.8.0",
    "electron-rebuild": "^2.0.1"
  },
  "dependencies": {
    "knex": "<0.20.0",
    "sharp": "^0.26.0",
    "sqlite3": "latest",
    "strapi": "3.1.4",
    "strapi-admin": "3.1.4",
    "strapi-connector-bookshelf": "3.1.4",
    "strapi-plugin-content-manager": "3.1.4",
    "strapi-plugin-content-type-builder": "3.1.4",
    "strapi-plugin-email": "3.1.4",
    "strapi-plugin-upload": "3.1.4",
    "strapi-plugin-users-permissions": "3.1.4",
    "strapi-utils": "3.1.4"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "09fd85c4-0649-4097-80fd-4fe5dbc7faf0"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT",
  "build": {
    "appId": "com.strapi",
    "mac": {
      "category": "public.app-category.productivity"
    },
    "win": {
      "target": "portable"
    },
    "npmRebuild": false
  }
}

```

**Comment by darron1217** [comment]
I've reinstalled it, then error message slightly changed (Error is pointing another sharp folder)
```
C:\Users\darron\Desktop\electron-strapi>electron .

Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Users\darron\Desktop\electron-strapi\node_modules\strapi-plugin-upload\node_modules\sharp\build\Release\sharp.node

```

**Comment by lovell** [comment]
I think you'll need to get `strapi-plugin-upload` to upgrade to v0.26.0 too - see https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/package.json#L32

**Comment by darron1217** [comment]
https://github.com/darron1217/strapi-plugin-upload

I've created fork of the plugin, and replaced it.
Now it works well!

Thanks @lovell
