### ISSUE TITLE
Async/await `toBuffer()` throws an syntax error

### ISSUE THREAD

**Issue by mati0090** [lovell/sharp#2355]
My node version is most recent - `14.9.0`

What are you trying to achieve?
`const resizedFile = await sharp(file).resize(200).png().toBuffer();`

What I am getting?
```
const resizedFile = await sharp(file).resize(200).png().toBuffer();
                    ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:991:16)
    at Module._compile (internal/modules/cjs/loader.js:1039:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

Do I need to use any `babel` plugins to have functions returning promises handles that `await`?

**Comment by mati0090** [comment]
I was calling `const resizedFile = await sharp(file).resize(200).png().toBuffer();` in context of non-async function. Closing.
