### ISSUE TITLE
Stack Error: `make` failed

### ISSUE THREAD

**Issue by bpatrik** [lovell/sharp#2366]
Hi, 

I would like to increase awareness of a possible bug:
Updating sharp from ["0.23.4" to  "0.26.0"](https://github.com/bpatrik/pigallery2/commit/004948cdc2b718db0ab5f57c019bcc3d8d99285e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

Resulted in a ` Error: `make` failed with exit code: 2` error, during building docker container with `node -v v12.18.3`, `node-gyp -v v5.1.0`.:

```
#30 [linux/arm64 builder 5/6] RUN npm install --unsafe-perm
#30 111.3 make: Entering directory '/app/node_modules/sharp/build'
#30 111.3   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
#30 111.9   AR(target) Release/obj.target/../node-addon-api/nothing.a
#30 112.0   COPY Release/nothing.a
#30 112.2   TOUCH Release/obj.target/libvips-cpp.stamp
#30 112.2   CXX(target) Release/obj.target/sharp/src/common.o
#30 112.9 In file included from ../src/common.cc:24:
#30 112.9 /usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
#30 112.9    35 | #include <glib-object.h>
#30 112.9       |          ^~~~~~~~~~~~~~~
#30 112.9 compilation terminated.
#30 112.9 make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
#30 112.9 make: Leaving directory '/app/node_modules/sharp/build'
#30 112.9 gyp ERR! build error 
#30 112.9 gyp ERR! stack Error: `make` failed with exit code: 2
#30 112.9 gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
#30 112.9 gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
#30 112.9 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
#30 112.9 gyp ERR! System Linux 5.4.0-1023-azure
#30 112.9 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#30 112.9 gyp ERR! cwd /app/node_modules/sharp
#30 112.9 gyp ERR! node -v v12.18.3
#30 112.9 gyp ERR! node-gyp -v v5.1.0
#30 112.9 gyp ERR! not ok 
#30 114.5 npm ERR! code ELIFECYCLE
#30 114.5 npm ERR! errno 1
#30 114.6 npm ERR! sharp@0.26.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
#30 114.6 npm ERR! Exit status 1
#30 114.6 npm ERR! 
#30 114.6 npm ERR! Failed at the sharp@0.26.0 install script.
#30 114.6 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#30 114.8 
#30 114.8 npm ERR! A complete log of this run can be found in:
#30 114.8 npm ERR!     /root/.npm/_logs/2020-09-13T13_25_15_401Z-debug.log
#30 ERROR: executor failed running [/bin/sh -c npm install --unsafe-perm]: buildkit-runc did not terminate successfully
```
I'm building my app on `linux/amd64,linux/arm64,linux/arm/v7` for both alpine and debian stretch linux.
Full log is [here (not sure if its available).](https://github.com/bpatrik/pigallery2/runs/1108420961?check_suite_focus=true)
Might be related to https://github.com/nodejs/node-gyp/issues/1694.

**Comment by lovell** [comment]
The log entries just before the ones pasted into this report contain the information you need.

```
#30 94.98 info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linuxmusl-arm64v8.tar.br
#30 95.44 ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for linuxmusl-arm64v8
#30 95.44 info sharp Attempting to build from source via node-gyp but this may fail due to the above error
#30 95.45 info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
```

https://sharp.pixelplumbing.com/install#prebuilt-binaries

> The following platforms require compilation of both libvips and sharp from source:
> * Linux ARM64 (glibc <= 2.28, musl)

Prebuilt binaries are not provided for musl-based Linux on ARM64.

**Comment by bpatrik** [comment]
I see. Thank you very much for the quick help.
