### ISSUE TITLE
 fatal error: glibconfig.h: No such file or directory

### ISSUE THREAD

**Issue by AldeonMoriak** [lovell/sharp#2441]
Hello, I'm trying to install sharp on Lubuntu but I got this error.

System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
    Memory: 2.59 GB / 7.72 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm

The details are:

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/local/bin/npm', 'i', 'sharp', '--verbose' ]
npm info using npm@6.13.7
npm info using node@v12.19.0
npm verb npm-session 005d64f2b441b55c
npm http fetch GET 304 https://registry.npmjs.org/sharp 703ms (from cache)
npm timing stage:loadCurrentTree Completed in 3288ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 31ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1175ms
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 212ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 490ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 515ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 524ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 538ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 181ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 197ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 191ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 253ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 264ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 269ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 279ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 579ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 580ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 156ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 173ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 156ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 161ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 175ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 207ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 212ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 183ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 187ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5820ms
npm timing stage:loadIdealTree Completed in 7534ms
npm timing stage:generateActionsToTake Completed in 139ms
npm verb correctMkdir /home/aldeon/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/aldeon/.npm/_locks/staging-da1539c6ccd55de7.lock for /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/.staging
npm timing action:extract Completed in 242ms
npm timing action:finalize Completed in 73ms
npm timing action:refresh-package-json Completed in 99ms
npm info lifecycle inherits@2.0.4~preinstall: inherits@2.0.4
npm info lifecycle string_decoder@1.3.0~preinstall: string_decoder@1.3.0
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle bl@4.0.3~preinstall: bl@4.0.3
npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
npm info lifecycle mimic-response@2.1.0~preinstall: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~preinstall: decompress-response@4.2.1
npm info lifecycle mkdirp-classic@0.5.3~preinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~preinstall: napi-build-utils@1.0.2
npm info lifecycle node-abi@2.19.1~preinstall: node-abi@2.19.1
npm info lifecycle noop-logger@0.1.1~preinstall: noop-logger@0.1.1
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle simple-get@3.1.0~preinstall: simple-get@3.1.0
npm info lifecycle mimic-response@3.1.0~preinstall: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~preinstall: decompress-response@6.0.0
npm info lifecycle is-arrayish@0.3.2~preinstall: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~preinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.4~preinstall: color-string@1.5.4
npm info lifecycle string_decoder@1.3.0~preinstall: string_decoder@1.3.0
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle tar-stream@2.1.4~preinstall: tar-stream@2.1.4
npm info lifecycle tar-fs@2.1.1~preinstall: tar-fs@2.1.1
npm info lifecycle which-pm-runs@1.0.0~preinstall: which-pm-runs@1.0.0
npm info lifecycle color@3.1.3~preinstall: color@3.1.3
npm info lifecycle prebuild-install@5.3.6~preinstall: prebuild-install@5.3.6
npm info lifecycle semver@7.3.2~preinstall: semver@7.3.2
npm info lifecycle simple-get@4.0.0~preinstall: simple-get@4.0.0
npm info lifecycle sharp@0.26.2~preinstall: sharp@0.26.2
npm timing action:preinstall Completed in 10ms
npm info linkStuff inherits@2.0.4
npm info linkStuff string_decoder@1.3.0
npm info linkStuff readable-stream@3.6.0
npm info linkStuff bl@4.0.3
npm info linkStuff expand-template@2.0.3
npm info linkStuff fs-constants@1.0.0
npm info linkStuff github-from-package@0.0.0
npm info linkStuff mimic-response@2.1.0
npm info linkStuff decompress-response@4.2.1
npm info linkStuff mkdirp-classic@0.5.3
npm info linkStuff napi-build-utils@1.0.2
npm info linkStuff node-abi@2.19.1
npm info linkStuff noop-logger@0.1.1
npm info linkStuff simple-concat@1.0.1
npm info linkStuff simple-get@3.1.0
npm info linkStuff mimic-response@3.1.0
npm info linkStuff decompress-response@6.0.0
npm info linkStuff is-arrayish@0.3.2
npm info linkStuff simple-swizzle@0.2.2
npm info linkStuff color-string@1.5.4
npm info linkStuff string_decoder@1.3.0
npm info linkStuff readable-stream@3.6.0
npm info linkStuff tar-stream@2.1.4
npm info linkStuff tar-fs@2.1.1
npm info linkStuff which-pm-runs@1.0.0
npm info linkStuff color@3.1.3
npm info linkStuff prebuild-install@5.3.6
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   '/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff semver@7.3.2
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   '/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff simple-get@4.0.0
npm info linkStuff sharp@0.26.2
npm timing action:build Completed in 16ms
npm info lifecycle inherits@2.0.4~install: inherits@2.0.4
npm info lifecycle string_decoder@1.3.0~install: string_decoder@1.3.0
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle bl@4.0.3~install: bl@4.0.3
npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
npm info lifecycle mimic-response@2.1.0~install: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~install: decompress-response@4.2.1
npm info lifecycle mkdirp-classic@0.5.3~install: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~install: napi-build-utils@1.0.2
npm info lifecycle node-abi@2.19.1~install: node-abi@2.19.1
npm info lifecycle noop-logger@0.1.1~install: noop-logger@0.1.1
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle simple-get@3.1.0~install: simple-get@3.1.0
npm info lifecycle mimic-response@3.1.0~install: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~install: decompress-response@6.0.0
npm info lifecycle is-arrayish@0.3.2~install: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~install: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.4~install: color-string@1.5.4
npm info lifecycle string_decoder@1.3.0~install: string_decoder@1.3.0
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle tar-stream@2.1.4~install: tar-stream@2.1.4
npm info lifecycle tar-fs@2.1.1~install: tar-fs@2.1.1
npm info lifecycle which-pm-runs@1.0.0~install: which-pm-runs@1.0.0
npm info lifecycle color@3.1.3~install: color@3.1.3
npm info lifecycle prebuild-install@5.3.6~install: prebuild-install@5.3.6
npm info lifecycle semver@7.3.2~install: semver@7.3.2
npm info lifecycle simple-get@4.0.0~install: simple-get@4.0.0
npm info lifecycle sharp@0.26.2~install: sharp@0.26.2

> sharp@0.26.2 install /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/aldeon/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br
ERR! sharp Please delete /home/aldeon/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br as it is not a valid tarball
ERR! sharp unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.0.7
gyp info using node@12.19.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.18"
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 12.19.0
gyp verb command install [ '12.19.0' ]
gyp verb install input version string "12.19.0"
gyp verb install installing version: 12.19.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.19.0
gyp verb build dir attempting to create "build" dir: /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aldeon/.cache/node-gyp/12.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/aldeon/.cache/node-gyp/12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/aldeon/.cache/node-gyp/12.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/aldeon/.cache/node-gyp/12.19.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/build'
  cc '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/home/aldeon/.cache/node-gyp/12.19.0/include/node -I/home/aldeon/.cache/node-gyp/12.19.0/src -I/home/aldeon/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/aldeon/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/aldeon/.cache/node-gyp/12.19.0/deps/uv/include -I/home/aldeon/.cache/node-gyp/12.19.0/deps/zlib -I/home/aldeon/.cache/node-gyp/12.19.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c
  rm -f Release/obj.target/../node-addon-api/nothing.a && ar crs Release/obj.target/../node-addon-api/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.o
  rm -rf "Release/nothing.a" && cp -af "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a"
  touch Release/obj.target/libvips-cpp.stamp
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/aldeon/.cache/node-gyp/12.19.0/include/node -I/home/aldeon/.cache/node-gyp/12.19.0/src -I/home/aldeon/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/aldeon/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/aldeon/.cache/node-gyp/12.19.0/deps/uv/include -I/home/aldeon/.cache/node-gyp/12.19.0/deps/zlib -I/home/aldeon/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include -I/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/glib-2.0 -I/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
In file included from /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/glib-2.0/glib/galloca.h:32,
                 from /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/glib-2.0/glib.h:30,
                 from /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/glib-2.0/gobject/gbinding.h:28,
                 from /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/glib-2.0/glib-object.h:22,
                 from /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/vips/vips8:35,
                 from ../src/common.cc:24:
/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/vendor/8.10.0/include/glib-2.0/glib/gtypes.h:32:10: fatal error: glibconfig.h: No such file or directory
   32 | #include <glibconfig.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-53-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm verb lifecycle sharp@0.26.2~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.26.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp/node_modules/.bin:/home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle sharp@0.26.2~install: CWD: /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/sharp
npm timing audit submit Completed in 1675ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1675ms
npm timing audit body Completed in 0ms
npm info lifecycle sharp@0.26.2~install: Failed to exec install script
npm timing action:install Completed in 2714ms
npm verb unlock done using /home/aldeon/.npm/_locks/staging-da1539c6ccd55de7.lock for /home/aldeon/Desktop/coding/nestjs/slpathBackend/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 274ms
npm timing stage:runTopLevelLifecycles Completed in 15500ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.26.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:314:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm verb pkgid sharp@0.26.2
npm verb cwd /home/aldeon/Desktop/coding/nestjs/slpathBackend
npm verb Linux 5.4.0-53-generic
npm verb argv "/usr/bin/node" "/usr/local/bin/npm" "i" "sharp" "--verbose"
npm verb node v12.19.0
npm verb npm  v6.13.7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.26.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.26.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 16855ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aldeon/.npm/_logs/2020-11-13T18_50_30_525Z-debug.log

**Comment by AldeonMoriak** [comment]
Sorry I didn't see that part. It works now. Thank you
