### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by teffanymae11** [lovell/sharp#2454]
I already do what the error said. I removed the sharp then `npm install --ignore-scripts=false --verbose` but it still doesn't work.

I also tried the:

```
    rimraf node_modules 
    rimraf yarn.lock 
    yarn
```

What might the problem here?

npm: 6.13.4

node: v10.18.0

python: 3.7.0

sharp: ^0.26.2

windows 10 pro 64-bit

```
!  Error: 
Something went wrong installing the "sharp" module      

\\?\C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\build\Release\sharp.node is not a valid Win32 application.
\\?\C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\build\Release\sharp.node     

- Remove the "node_modules/sharp" directory then run    
  "npm install --ignore-scripts=false --verbose" and look for errors

at Object.<anonymous> (C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)  
    at Object.<anonymous> (C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)  
    at Object.<anonymous> (C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\helpers\image.js:1:15)   
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
!  We were unable to load your functions code. (see above)
```

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp`?

**Comment by teffanymae11** [comment]
Hi Mr. Lovell. 
Thank you for responding to my question. 

When I run `npm install --verbose sharp`, this is the output.

```
npm verb lifecycle nodemon@2.0.6~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle nodemon@2.0.6~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\nodemon\node_modules\.bin;C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\.bin;C:\Users\ph2200009\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\mingw64\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\local\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\mingw64\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin;C:\Users\ph2200009\bin;C:\Python39\Scripts;C:\Python39;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Users\ph2200009\AppData\Local\Microsoft\WindowsApps;C:\Users\ph2200009\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\cmd;C:\Users\ph2200009\AppData\Local\Yarn\bin;C:\Users\ph2200009\AppData\Roaming\npm;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin\vendor_perl;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin\core_perl  
npm verb lifecycle nodemon@2.0.6~postinstall: CWD: C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\nodemon
npm info lifecycle prebuild-install@6.0.0~postinstall: prebuild-install@6.0.0
npm info lifecycle raw-loader@4.0.2~postinstall: raw-loader@4.0.2
npm info lifecycle request@2.88.2~postinstall: request@2.88.2
npm info lifecycle request-promise@4.2.6~postinstall: request-promise@4.2.6
npm info lifecycle array-flatten@3.0.0~postinstall: array-flatten@3.0.0
npm info lifecycle semver@7.3.2~postinstall: semver@7.3.2
npm info lifecycle simple-get@4.0.0~postinstall: simple-get@4.0.0
npm info lifecycle sharp@0.26.3~postinstall: sharp@0.26.3
npm info lifecycle validate.js@0.13.1~postinstall: validate.js@0.13.1
npm info lifecycle webpack@5.6.0~postinstall: webpack@5.6.0
npm info lifecycle webpack-cli@4.2.0~postinstall: webpack-cli@4.2.0
npm timing action:postinstall Completed in 10760ms      
npm verb unlock done using C:\Users\ph2200009\AppData\Roaming\npm-cache\_locks\staging-7f8d008093da1ef3.lock for C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\.staging
npm timing stage:executeActions Completed in 252245ms   
npm timing stage:rollbackFailedOptional Completed in 114ms
npm timing stage:runTopLevelLifecycles Completed in 272124ms
npm verb saving [ { name: 'sharp', spec: '^0.26.3', save: 'dependencies' } ]
npm info lifecycle undefined~preshrinkwrap: undefined   
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\chokidar\node_modules\fsevents):  
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})      
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: 
   darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})       
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: 
   darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

+ sharp@0.26.3
added 87 packages from 66 contributors, removed 77 packages, updated 1131 packages and audited 1227 packages in 
273.44s

52 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 277161ms
npm info ok
```

Then, when I run `npm run local`, I still get the above issue..

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp` in a new, empty directory that does not already have it installed?

**Comment by teffanymae11** [comment]
```
PS C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions> npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@6.13.4
npm info using node@v10.18.0
npm verb npm-session 876590730b4f61f0
npm http fetch GET 304 https://registry.npmjs.org/sharp 289ms (from cache)
npm timing stage:loadCurrentTree Completed in 2082ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 44ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 838ms
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 243ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 249ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/array-flatten 317ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 320ms (from cache)        
npm http fetch GET 304 https://registry.npmjs.org/semver 322ms (from cache)       
npm http fetch GET 304 https://registry.npmjs.org/color-string 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 133ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 110ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 121ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 126ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 125ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 134ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 96ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 74ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 1043ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3807ms
npm timing stage:loadIdealTree Completed in 5065ms
npm timing stage:generateActionsToTake Completed in 130ms
npm verb correctMkdir C:\Users\ph2200009\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\ph2200009\AppData\Roaming\npm-cache\_locks\staging-7f8d008093da1ef3.lock for C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\.staging
npm timing action:extract Completed in 80ms
npm info lifecycle sharp@0.26.3~preuninstall: sharp@0.26.3
npm info lifecycle sharp@0.26.3~uninstall: sharp@0.26.3
npm verb unbuild rmStuff sharp@0.26.3 from C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules
npm info lifecycle sharp@0.26.3~postuninstall: sharp@0.26.3
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined 'from' 'C:\\Users\\ph2200009\\Desktop\\TM\\cplus_incident_mgnt\\functions\\node_modules'
npm verb unbuild rmStuff in C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\@grpc\grpc-js\node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined 'from' 'C:\\Users\\ph2200009\\Desktop\\TM\\cplus_incident_mgnt\\functions\\node_modules'
npm info lifecycle undefined~postuninstall: undefined
npm timing action:unbuild Completed in 130ms
npm timing action:remove Completed in 231ms
npm timing action:finalize Completed in 27ms
npm timing action:refresh-package-json Completed in 43ms
npm info lifecycle sharp@0.26.3~preinstall: sharp@0.26.3
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.26.3
npm timing action:build Completed in 2ms
npm info lifecycle sharp@0.26.3~install: sharp@0.26.3

> sharp@0.26.3 install C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\ph2200009\AppData\Roaming\npm-cache\_libvips\libvips-8.10.0-win32-x64.tar.br
info sharp Creating C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\vendor\8.10.0\lib to C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 6.0.0
prebuild-install info looking for cached prebuild @ C:\Users\ph2200009\AppData\Roaming\npm-cache\_prebuilds\6b1ede-sharp-v0.26.3-napi-v3-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\ph2200009\AppData\Roaming\npm-cache\_prebuilds\6b1ede-sharp-v0.26.3-napi-v3-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\build\Release\sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.26.3~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.26.3~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp\node_modules\.bin;C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\.bin;C:\Users\ph2200009\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\mingw64\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\local\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\mingw64\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin;C:\Users\ph2200009\bin;C:\Python39\Scripts;C:\Python39;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Users\ph2200009\AppData\Local\Microsoft\WindowsApps;C:\Users\ph2200009\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\ph2200009\AppData\Local\Programs\Git\cmd;C:\Users\ph2200009\AppData\Local\Yarn\bin;C:\Users\ph2200009\AppData\Roaming\npm;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin\vendor_perl;C:\Users\ph2200009\AppData\Local\Programs\Git\usr\bin\core_perl
npm verb lifecycle sharp@0.26.3~install: CWD: C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\sharp
npm timing audit submit Completed in 1689ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1689ms
npm timing audit body Completed in 0ms
npm timing action:install Completed in 3302ms
npm info lifecycle sharp@0.26.3~postinstall: sharp@0.26.3
npm timing action:postinstall Completed in 24ms
npm verb unlock done using C:\Users\ph2200009\AppData\Roaming\npm-cache\_locks\staging-7f8d008093da1ef3.lock for C:\Users\ph2200009\Desktop\TM\cplus_incident_mgnt\functions\node_modules\.staging
npm timing stage:executeActions Completed in 3903ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 11495ms
npm verb saving [ { name: 'sharp', spec: '^0.26.3', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
+ sharp@0.26.3
removed 2 packages, updated 1 package and audited 1244 packages in 12.262s

49 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 13516ms
npm info ok
```

It's now working! Thank you very much. 

What I did is to 

`npm i bcrypt@^4.0.1` 
`npm i @firebase-util` 

Then, delete
`C:\Users\ph2200009\AppData\Roaming\npm-cache\_libvips\libvips-8.10.0-win32-x64.tar.br`

Finaly, run `npm install --verbose sharp`.
