### ISSUE TITLE
MacOS: is --runtime_link=static still working? results in: no such file or directory: 'ApplicationServices'

### ISSUE THREAD

**Issue by gpetrov** [lovell/sharp#2467]
Finally got the libvips to compile and install as global library on the new Apple Silicon M1 ARM64.
Now I can also install sharp nicely and it uses the global vips. Congratulations it works!

However when I want to compile it with static libraries, so everything gets included.
But when I try to install with: npm install sharp --runtime_link=static
an error occurs:
clang: error: no such file or directory: 'ApplicationServices'

last c++ command looks a bit weird, I've shorten it a bit:

c++ -bundle **-undefined** dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=11 -arch arm64 -L./Release -stdlib=libc++  -o Release/sharp.node Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/sharp.o Release/obj.target/sharp/src/utilities.o -lIexMath-2_5 -lIlmThread-2_5 -lheif -lstdc++ -lopenslide -lcfitsio -lwebpmux -lwebpdemux -lwebp -D_THREAD_SAFE -pthread -lpangoft2-1.0 **-framework CoreFoundation ApplicationServices** -lpango-1.0 -lgio-2.0 -Wl,-framework,CoreFoundation -Wl,-framework,Carbon -Wl,-framework,Foundation -Wl,-framework,AppKit -lresolv -lgmodule-2.0 -lfribidi -lcairo -lpixman-1 -lharfbuzz -lgraphite2 -lfontconfig -lexpat -ltiff -ljpeg -lspng -lpng16 -limagequant -lexif -lgobject-2.0 -lffi -liconv -lpcre

full last part of the output is:

```
  c++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_REVERSE_JSARGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DV8_COMPRESS_POINTERS' '-DV8_31BIT_SMIS_ON_64BIT_ARCH' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' '-DBUILDING_NODE_EXTENSION' -I/Users/george/.nw-gyp/0.50.1/include/node -I/Users/george/.nw-gyp/0.50.1/src -I/Users/george/.nw-gyp/0.50.1/deps/uv/include -I/Users/george/.nw-gyp/0.50.1/deps/v8/include -I../../nan -I/opt/homebrew/Cellar/libffi/3.3/include -I/usr/local/include -I/opt/homebrew/Cellar/vips/8.10.2_4/include -I/opt/homebrew/Cellar/glib/2.66.2_1/include -I/opt/homebrew/Cellar/libgsf/1.14.47/include/libgsf-1 -I/opt/homebrew/Cellar/imagemagick/7.0.10-44/include/ImageMagick-7 -I/opt/homebrew/Cellar/orc/0.4.32/include/orc-0.4 -I/opt/homebrew/Cellar/little-cms2/2.11/include -I/opt/homebrew/Cellar/openexr/2.5.3/include/OpenEXR -I/opt/homebrew/Cellar/ilmbase/2.5.3/include -I/opt/homebrew/Cellar/ilmbase/2.5.3/include/OpenEXR -I/opt/homebrew/Cellar/libheif/1.9.1/include -I/opt/homebrew/Cellar/openslide/3.4.1_5/include/openslide -I/opt/homebrew/Cellar/cfitsio/3.490/include -I/opt/homebrew/Cellar/webp/1.1.0/include -I/opt/homebrew/Cellar/pango/1.48.0/include/pango-1.0 -I/opt/homebrew/Cellar/fribidi/1.0.10/include/fribidi -I/opt/homebrew/Cellar/cairo/1.16.0_3/include/cairo -I/opt/homebrew/Cellar/pixman/0.40.0/include/pixman-1 -I/opt/homebrew/Cellar/harfbuzz/2.7.2/include/harfbuzz -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/fontconfig/2.13.1/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/libtiff/4.1.0_1/include -I/opt/homebrew/Cellar/libspng/0.6.1/include -I/opt/homebrew/Cellar/libpng/1.6.37/include/libpng16 -I/opt/homebrew/Cellar/libimagequant/2.13.1/include -I/opt/homebrew/Cellar/jpeg/9d/include -I/opt/homebrew/Cellar/libexif/0.6.22/include -I/opt/homebrew/Cellar/glib/2.66.2_1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.66.2_1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include  -O3 -gdwarf-2 -mmacosx-version-min=11 -arch arm64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++14 -stdlib=libc++ -fexceptions -Wall -O3 -std=c++14 -stdlib=libc++ -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw   -c -o Release/obj.target/sharp/src/sharp.o ../src/sharp.cc
  c++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_REVERSE_JSARGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DV8_COMPRESS_POINTERS' '-DV8_31BIT_SMIS_ON_64BIT_ARCH' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' '-DBUILDING_NODE_EXTENSION' -I/Users/george/.nw-gyp/0.50.1/include/node -I/Users/george/.nw-gyp/0.50.1/src -I/Users/george/.nw-gyp/0.50.1/deps/uv/include -I/Users/george/.nw-gyp/0.50.1/deps/v8/include -I../../nan -I/opt/homebrew/Cellar/libffi/3.3/include -I/usr/local/include -I/opt/homebrew/Cellar/vips/8.10.2_4/include -I/opt/homebrew/Cellar/glib/2.66.2_1/include -I/opt/homebrew/Cellar/libgsf/1.14.47/include/libgsf-1 -I/opt/homebrew/Cellar/imagemagick/7.0.10-44/include/ImageMagick-7 -I/opt/homebrew/Cellar/orc/0.4.32/include/orc-0.4 -I/opt/homebrew/Cellar/little-cms2/2.11/include -I/opt/homebrew/Cellar/openexr/2.5.3/include/OpenEXR -I/opt/homebrew/Cellar/ilmbase/2.5.3/include -I/opt/homebrew/Cellar/ilmbase/2.5.3/include/OpenEXR -I/opt/homebrew/Cellar/libheif/1.9.1/include -I/opt/homebrew/Cellar/openslide/3.4.1_5/include/openslide -I/opt/homebrew/Cellar/cfitsio/3.490/include -I/opt/homebrew/Cellar/webp/1.1.0/include -I/opt/homebrew/Cellar/pango/1.48.0/include/pango-1.0 -I/opt/homebrew/Cellar/fribidi/1.0.10/include/fribidi -I/opt/homebrew/Cellar/cairo/1.16.0_3/include/cairo -I/opt/homebrew/Cellar/pixman/0.40.0/include/pixman-1 -I/opt/homebrew/Cellar/harfbuzz/2.7.2/include/harfbuzz -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/fontconfig/2.13.1/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/libtiff/4.1.0_1/include -I/opt/homebrew/Cellar/libspng/0.6.1/include -I/opt/homebrew/Cellar/libpng/1.6.37/include/libpng16 -I/opt/homebrew/Cellar/libimagequant/2.13.1/include -I/opt/homebrew/Cellar/jpeg/9d/include -I/opt/homebrew/Cellar/libexif/0.6.22/include -I/opt/homebrew/Cellar/glib/2.66.2_1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.66.2_1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include  -O3 -gdwarf-2 -mmacosx-version-min=11 -arch arm64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++14 -stdlib=libc++ -fexceptions -Wall -O3 -std=c++14 -stdlib=libc++ -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw   -c -o Release/obj.target/sharp/src/utilities.o ../src/utilities.cc
  c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=11 -arch arm64 -L./Release -stdlib=libc++  -o Release/sharp.node Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/sharp.o Release/obj.target/sharp/src/utilities.o -L/opt/homebrew/Cellar/libffi/3.3/lib -L/opt/homebrew/Cellar/vips/8.10.2_4/lib -L/opt/homebrew/Cellar/libgsf/1.14.47/lib -L/opt/homebrew/Cellar/imagemagick/7.0.10-44/lib -L/opt/homebrew/Cellar/little-cms2/2.11/lib -L/opt/homebrew/opt/freetype/lib -L/opt/homebrew/Cellar/glib/2.66.2_1/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/Cellar/xz/5.2.5/lib -L/opt/homebrew/Cellar/orc/0.4.32/lib -L/opt/homebrew/Cellar/openexr/2.5.3/lib -L/opt/homebrew/Cellar/ilmbase/2.5.3/lib -L/opt/homebrew/Cellar/libheif/1.9.1/lib -L/opt/homebrew/Cellar/openslide/3.4.1_5/lib -L/opt/homebrew/Cellar/cfitsio/3.490/lib -L/opt/homebrew/Cellar/webp/1.1.0/lib -L/opt/homebrew/Cellar/pango/1.48.0/lib -L/opt/homebrew/Cellar/fribidi/1.0.10/lib -L/opt/homebrew/Cellar/cairo/1.16.0_3/lib -L/opt/homebrew/Cellar/pixman/0.40.0/lib -L/opt/homebrew/Cellar/harfbuzz/2.7.2/lib -L/opt/homebrew/Cellar/graphite2/1.3.14/lib -L/opt/homebrew/Cellar/fontconfig/2.13.1/lib -L/opt/homebrew/Cellar/libtiff/4.1.0_1/lib -L/opt/homebrew/Cellar/libspng/0.6.1/lib -L/opt/homebrew/Cellar/libpng/1.6.37/lib -L/opt/homebrew/Cellar/libimagequant/2.13.1/lib -L/opt/homebrew/Cellar/jpeg/9d/lib -L/opt/homebrew/Cellar/libexif/0.6.22/lib -lvips-cpp -lvips -lgsf-1 -lxml2 -lz -lpthread -licucore -lm -lMagickCore-7.Q16HDRI -llcms2 -lfreetype -llqr-1 -lglib-2.0 -lintl -llzma -lbz2 -lltdl -lorc-0.4 -lIlmImf-2_5 -lImath-2_5 -lHalf-2_5 -lIex-2_5 -lIexMath-2_5 -lIlmThread-2_5 -lheif -lstdc++ -lopenslide -lcfitsio -lwebpmux -lwebpdemux -lwebp -D_THREAD_SAFE -pthread -lpangoft2-1.0 -framework CoreFoundation ApplicationServices -lpango-1.0 -lgio-2.0 -Wl,-framework,CoreFoundation -Wl,-framework,Carbon -Wl,-framework,Foundation -Wl,-framework,AppKit -lresolv -lgmodule-2.0 -lfribidi -lcairo -lpixman-1 -lharfbuzz -lgraphite2 -lfontconfig -lexpat -ltiff -ljpeg -lspng -lpng16 -limagequant -lexif -lgobject-2.0 -lffi -liconv -lpcre
clang: error: no such file or directory: 'ApplicationServices'
make: *** [Release/sharp.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:261:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "rebuild"
gyp ERR! cwd /Users/george/Documents/SVN/Wappler_Native_Modules/node_modules/sharp
gyp ERR! node -v v14.15.1
gyp ERR! nw-gyp -v v3.6.2
gyp ERR! not ok 
npm verb lifecycle sharp@0.23.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.23.4~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/george/Documents/SVN/Wappler_Native_Modules/node_modules/sharp/node_modules/.bin:/Users/george/Documents/SVN/Wappler_Native_Modules/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/Library/Apple/usr/bin
npm verb lifecycle sharp@0.23.4~install: CWD: /Users/george/Documents/SVN/Wappler_Native_Modules/node_modules/sharp
npm info lifecycle sharp@0.23.4~install: Failed to exec install script
npm verb stack Error: sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.23.4
npm verb cwd /Users/george/Documents/SVN/Wappler_Native_Modules
npm verb Darwin 20.1.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "sharp" "--runtime_link=static" "--production" "--no-optional" "-verbose" "--build-from-source" "--fallback-to-build"
npm verb node v14.15.1
npm verb npm  v6.14.8
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 17533ms
```

**Comment by lovell** [comment]
I think this is a bug in meson, as used by pango - see https://github.com/mesonbuild/meson/issues/5202

(Does this mean we can close #2460 ?)

**Comment by kenips** [comment]
@gpetrov mind posting a gist on how to compile libvips on M1? Thank you.

**Comment by kenips** [comment]
Whoops. Never mind. Was stuck getting `brew` to install vips. Compiling from source and installing globally works.

**Comment by lovell** [comment]
@gpetrov I hope this information helped. Please feel free to re-open with more details if further assistance is required.
