### ISSUE TITLE
[Release/obj.target/sharp/src/stats.o] Error 1 

### ISSUE THREAD

**Issue by Dumpinator** [lovell/sharp#2472]
Hello there,

I recently changed my node version to v15 and made the error of rebuild... Looking for a little bit, I quickly changed to node V14.13.0.

I deleted the node_modules folder, emptied the npm cache and launched npm install but I still have this installation error...

```
Runtours git:(master) ✗ npm install                         

> sharp@0.22.1 install /Users/jonathan/Desktop/Runtours/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/jonathan/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.15.0 runtime=node arch=x64 libc= platform=darwin)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/jonathan/Library/Caches/node-gyp/14.15.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/jonathan/Library/Caches/node-gyp/14.15.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jonathan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/jonathan/.nvm/versions/node/v14.15.0/bin/node" "/Users/jonathan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jonathan/Desktop/Runtours/node_modules/sharp
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathan/.npm/_logs/2020-12-04T14_26_50_277Z-debug.log

```

**Comment by lovell** [comment]
> sharp@0.22.1 install /Users/jonathan/Desktop/Runtours/node_modules/sharp
> prebuild-install WARN install No prebuilt binaries found (target=14.15.0 runtime=node arch=x64 libc= platform=darwin)

Please upgrade sharp - the latest is v0.26.3.

**Comment by Dumpinator** [comment]
Worked for me !!! Thank you for mutch !

**Comment by davidhellmann** [comment]
Same problem. Try to install npm i sharp and this installed sharp 0.26 but afterwards when I run `npm i` same error as above.

**Comment by lovell** [comment]
@davidhellmann If you're still having problems, please open a new installation issue and answer all the questions. https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
