### ISSUE TITLE
require('sharp') throws error in linux alpine docker

### ISSUE THREAD

**Issue by Svarto** [lovell/sharp#2509]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Yes.

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

yes

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

Tried this no change

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

Yes I have checked it, here it is, install seems successful:

```
/usr/src/app # npm install --unsafe-perm --ignore-scripts=false --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--unsafe-perm',
npm verb cli   '--ignore-scripts=false',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v14.15.1
npm verb npm-session b07c924bdeddf93d
npm http fetch GET 304 https://registry.npmjs.org/sharp 251ms (from cache)
npm timing stage:loadCurrentTree Completed in 829ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 102ms
npm http fetch GET 304 https://registry.npmjs.org/semver 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/array-flatten 127ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fsevents 54ms (from cache)
npm WARN deprecated fsevents@2.1.3: Please update to v 2.2.x
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 488ms
npm timing stage:loadIdealTree Completed in 672ms
npm timing stage:generateActionsToTake Completed in 29ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-af89dff005e44f9e.lock for /usr/src/app/node_modules/.staging
npm timing action:extract Completed in 90ms
npm timing action:finalize Completed in 16ms
npm timing action:refresh-package-json Completed in 15ms
npm info lifecycle array-flatten@3.0.0~preinstall: array-flatten@3.0.0
npm info lifecycle semver@7.3.4~preinstall: semver@7.3.4
npm info lifecycle sharp@0.27.0~preinstall: sharp@0.27.0
npm timing action:preinstall Completed in 4ms
npm info linkStuff array-flatten@3.0.0
npm info linkStuff semver@7.3.4
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   '/usr/src/app/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff sharp@0.27.0
npm timing action:build Completed in 10ms
npm info lifecycle array-flatten@3.0.0~install: array-flatten@3.0.0
npm info lifecycle semver@7.3.4~install: semver@7.3.4
npm info lifecycle sharp@0.27.0~install: sharp@0.27.0

> sharp@0.27.0 install /usr/src/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /root/.npm/_libvips/libvips-8.10.5-linuxmusl-x64.tar.br
prebuild-install info begin Prebuild-install version 6.0.0
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/f6dade-sharp-v0.27.0-napi-v3-linuxmusl-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /root/.npm/_prebuilds/f6dade-sharp-v0.27.0-napi-v3-linuxmusl-x64.tar.gz
prebuild-install info unpack resolved to /usr/src/app/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.27.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.27.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/sharp/node_modules/.bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.27.0~install: CWD: /usr/src/app/node_modules/sharp
npm timing audit submit Completed in 379ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 379ms
npm timing audit body Completed in 1ms
npm timing action:install Completed in 2446ms
npm info lifecycle array-flatten@3.0.0~postinstall: array-flatten@3.0.0
npm info lifecycle semver@7.3.4~postinstall: semver@7.3.4
npm info lifecycle sharp@0.27.0~postinstall: sharp@0.27.0
npm timing action:postinstall Completed in 2ms
npm verb unlock done using /root/.npm/_locks/staging-af89dff005e44f9e.lock for /usr/src/app/node_modules/.staging
npm timing stage:executeActions Completed in 2608ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 4222ms
npm verb saving [ { name: 'sharp', spec: '^0.27.0', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle api@1.0.0~shrinkwrap: api@1.0.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm info lifecycle api@1.0.0~postshrinkwrap: api@1.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN api@1.0.0 No description
npm WARN api@1.0.0 No repository field.

+ sharp@0.27.0
added 3 packages from 69 contributors and audited 265 packages in 4.372s
```

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 272.79 MB / 1.94 GB
    Container: Yes
    Shell: 1.30.1 - /bin/ash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
```

The error message is the below, it happens when I try to const sharp = require('sharp'):
```

/usr/src/app/node_modules/sharp/lib/constructor.js:34

throw new Error(error);



^

Error:

Something went wrong installing the "sharp" module


Error relocating /usr/src/app/node_modules/sharp/build/Release/../../vendor/8.10.5/lib/libvips.so.42: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found


- Remove the "node_modules/sharp" directory then run

"npm install --ignore-scripts=false --verbose" and look for errors

- Consult the installation documentation at https://sharp.pixelplumbing.com/install

- Search for this error at https://github.com/lovell/sharp/issues


at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:34:9)

at Module._compile (internal/modules/cjs/loader.js:1063:30)

at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

at Object.require.extensions.<computed> [as .js] (/usr/src/app/node_modules/ts-node/src/index.ts:1045:43)

at Module.load (internal/modules/cjs/loader.js:928:32)

at Function.Module._load (internal/modules/cjs/loader.js:769:14)

at Module.require (internal/modules/cjs/loader.js:952:19)

at require (internal/modules/cjs/helpers.js:88:18)

at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/index.js:3:15)

at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

Any ideas what might go wrong? The docker image is node:14.15.1-alpine3.10

**Comment by lovell** [comment]
> The docker image is node:14.15.1-alpine3.10

Alpine 3.10 provides musl 1.1.22 but the musl-based prebuilt binaries require 1.1.24+

https://sharp.pixelplumbing.com/install#prebuilt-binaries

**Comment by Svarto** [comment]
@lovell thank you! works with alpine3.12
