### ISSUE TITLE
Express Sharp install via Docker issue

### ISSUE THREAD

**Issue by kvlknctk** [lovell/sharp#2526]
Hi, 
I need to use [sharp][1]. Its work fine on my workspace but if I deploymeny via docker then I get error. I am implementation [all steps][1]. 

```
Error: 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linuxmusl-x64' platform.
```

I think sharp is prebuilt when first install. It uses the architecture of my computer(darwin, arm) But when it runs on the docker, although it gets built again, the work talks about the architecture of my computer. 

My Dockerfile:
```
FROM node:alpine

RUN mkdir -p /usr/src/node-app && chown -R node:node /usr/src/node-app

WORKDIR /usr/src/node-app

COPY package.json yarn.lock ./

USER node

RUN npm install --pure-lockfile
RUN npm install sharp --ignore-scripts=false

COPY --chown=node:node . .

EXPOSE 3050

```

My .dockerignore. 
```
node_modules
**/node_modules
npm-debug.log
Dockerfile
.dockerignore
.git
.gitignore

```

```docker build . ```
When I do it, I see that sharp for my server is loaded among the docker logs.

```
found 11 vulnerabilities (6 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container e5ad8008eebd
 ---> 906e268b6fc3
Step 7/9 : RUN npm install sharp --ignore-scripts=false
 ---> Running in 933338813b5d

> sharp@0.27.0 install /usr/src/node-app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/node/.npm/_libvips/libvips-8.10.5-linuxmusl-x64.tar.br
npm WARN @apidevtools/swagger-parser@10.0.2 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.19.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ sharp@0.27.0
updated 1 package and audited 1348 packages in 20.689s

84 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (6 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 933338813b5d
 ---> 838713a4cebb
Step 8/9 : COPY --chown=node:node . .
 ---> eb755fc2589e
Step 9/9 : EXPOSE 3050
 ---> Running in bf0a5c9e96c6
Removing intermediate container bf0a5c9e96c6
 ---> 347f113598fd
Successfully built 347f113598fd
```

My Docker-compose up log 
```
mongodb_1   | 2021-01-09T19:31:15.802+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=a8281f9d01ef
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] db version v4.2.1
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] git version: edf6d45851c0b9ee15548f0f847df141764a317e
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] modules: none
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] build environment:
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten]     distarch: x86_64
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
mongodb_1   | 2021-01-09T19:31:15.815+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "0.0.0.0", port: 27017 }, security: { authorization: "enabled" }, storage: { dbPath: "/data/db" } }
mongodb_1   | 2021-01-09T19:31:15.816+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongodb_1   | 2021-01-09T19:31:15.816+0000 I  STORAGE  [initandlisten] 
mongodb_1   | 2021-01-09T19:31:15.816+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongodb_1   | 2021-01-09T19:31:15.816+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongodb_1   | 2021-01-09T19:31:15.816+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=457M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
mongodb_1   | 2021-01-09T19:31:17.154+0000 I  STORAGE  [initandlisten] WiredTiger message [1610220677:154424][1:0x7f96e9f8db00], txn-recover: Recovering log 194 through 195
api_node-app_1 exited with code 0
mongodb_1   | 2021-01-09T19:31:17.389+0000 I  STORAGE  [initandlisten] WiredTiger message [1610220677:389583][1:0x7f96e9f8db00], txn-recover: Recovering log 195 through 195
mongodb_1   | 2021-01-09T19:31:17.527+0000 I  STORAGE  [initandlisten] WiredTiger message [1610220677:527496][1:0x7f96e9f8db00], txn-recover: Main recovery loop: starting at 194/6016 to 195/256
mongodb_1   | 2021-01-09T19:31:17.643+0000 I  STORAGE  [initandlisten] WiredTiger message [1610220677:643739][1:0x7f96e9f8db00], txn-recover: Recovering log 194 through 195
mongodb_1   | 2021-01-09T19:31:17.722+0000 I  STORAGE  [initandlisten] WiredTiger message [1610220677:722144][1:0x7f96e9f8db00], txn-recover: Recovering log 195 through 195
mongodb_1   | 2021-01-09T19:31:17.784+0000 I  STORAGE  [initandlisten] WiredTiger message [1610220677:784868][1:0x7f96e9f8db00], txn-recover: Set global recovery timestamp: (0,0)
mongodb_1   | 2021-01-09T19:31:17.812+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongodb_1   | 2021-01-09T19:31:17.825+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongodb_1   | 2021-01-09T19:31:17.827+0000 I  CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
mongodb_1   | 2021-01-09T19:31:17.828+0000 I  CONTROL  [initandlisten] 
mongodb_1   | 2021-01-09T19:31:17.844+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
mongodb_1   | 2021-01-09T19:31:17.847+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongodb_1   | 2021-01-09T19:31:17.848+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
mongodb_1   | 2021-01-09T19:31:17.849+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
mongodb_1   | 2021-01-09T19:31:17.850+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
mongodb_1   | 2021-01-09T19:31:17.851+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongodb_1   | 2021-01-09T19:31:17.855+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
mongodb_1   | 2021-01-09T19:31:17.856+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
mongodb_1   | 2021-01-09T19:31:17.857+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
mongodb_1   | 2021-01-09T19:31:17.857+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
mongodb_1   | 2021-01-09T19:31:17.858+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
mongodb_1   | 2021-01-09T19:31:18.004+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
```
I think, I need to install sharp on docker for pre-built proccess.
I didn't understand how docker works very well. it has to do with my amateurishness that I live with.

Relation Issue :
https://stackoverflow.com/questions/57932529/linux-x64-binaries-cannot-be-used-on-the-linuxmusl-x64-platform-error

  [1]: https://sharp.pixelplumbing.com/install#prerequisites

**Comment by lovell** [comment]
The message "Error: 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform." means that `npm install` is being run on a glibc-based Linux such as Ubuntu but at runtime a musl-based Linux such as Alpine is being used. You'll need to find where that is happening, for example ensure you are not copying files or mapping volumes that could conflict.

**Comment by kvlknctk** [comment]
There is no problem when I use the buster package. but this time the mongodb connection is causing a problem. I had to go back to alpine again. Do you have a docker package for me?

**Comment by kvlknctk** [comment]
Do I have anything to do with the setup of this?
https://github.com/sgerrand/alpine-pkg-glibc

**Comment by kvlknctk** [comment]
I am trying with unsafeperm flag

```
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! ERR! sharp EACCES: permission denied, mkdir '/root/.npm'
npm ERR! info sharp Are you trying to install as a root or sudo user? Try again with the --unsafe-perm flag
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.2.1 | linux | x64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python2" can be used
npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:302:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:316:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:328:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:329:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:467:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
npm ERR! gyp ERR! System Linux 5.4.0-54-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/src/node-app/node_modules/sharp
npm ERR! gyp ERR! node -v v15.2.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-10T09_44_13_666Z-debug.log
```

**Comment by lovell** [comment]
> npm ERR! ERR! sharp EACCES: permission denied, mkdir '/root/.npm'

It looks like you're using Node.js 15, which ships with npm 7 and had a breaking change as the `--unsafe-perm` flag was removed.

If you're running `npm install` as root, make sure the directory you're running it in is also owned by root.

For example, here's what the sharp CI jobs have to do to workaround this:

https://github.com/lovell/sharp/blob/138e60adb3ff260fcbc6a127a47bffc3073839e0/.github/workflows/ci.yml#L69-L71

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
