### ISSUE TITLE
[cordova-res] /opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/lib/constructor.js:34 throw new Error(error); ^ Error: Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by manel00** [lovell/sharp#2566]
Running on Macbook M1, Ionic 5, when I run "ionic cordova resources"

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)? Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime? Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? Yes

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? Yes

If you are using npm v7, does the user running `npm install` own the directory it is run in? Yes

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag? Yes

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```
> cordova-res
[cordova-res] /opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/lib/constructor.js:34
[cordova-res]   throw new Error(error);
[cordova-res]   ^
[cordova-res] 
[cordova-res] Error: 
[cordova-res] Something went wrong installing the "sharp" module
[cordova-res] 
[cordova-res] dlopen(/opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/build/Release/sharp.node, 1): Symbol not found: __ZTVN4vips7VOptionE
[cordova-res]   Referenced from: /opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/build/Release/sharp.node
[cordova-res]   Expected in: flat namespace
[cordova-res]  in /opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/build/Release/sharp.node
[cordova-res] 
[cordova-res] - Remove the "node_modules/sharp" directory then run
[cordova-res]   "npm install --ignore-scripts=false --verbose" and look for errors
[cordova-res] - Consult the installation documentation at https://sharp.pixelplumbing.com/install
[cordova-res] - Search for this error at https://github.com/lovell/sharp/issues
[cordova-res] 
[cordova-res]     at Object.<anonymous> (/opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/lib/constructor.js:34:9)
[cordova-res]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[cordova-res]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[cordova-res]     at Module.load (internal/modules/cjs/loader.js:928:32)
[cordova-res]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[cordova-res]     at Module.require (internal/modules/cjs/loader.js:952:19)
[cordova-res]     at require (internal/modules/cjs/helpers.js:88:18)
[cordova-res]     at Object.<anonymous> (/opt/homebrew/lib/node_modules/cordova-res/node_modules/sharp/lib/index.js:3:15)
[cordova-res]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[cordova-res]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

What is the output of running `npx envinfo --binaries --system`?
```
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/opt/homebrew/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:90:19)
    at new <anonymous> (/opt/homebrew/lib/node_modules/npm/lib/npm.js:74:19)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/npm/lib/npm.js:59:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/install#apple-m1 and #2460. You may also need to run `brew update && brew upgrade`.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by ramfattah** [comment]
Hello, 
I am running on Macbook M1, Ionic 5 and tried to install cordova-res but I was having this same exact problem.
I was able to solve this error by following the links mentioned by @lovell and then running ``` brew install vips ```
Hope this helps.
