### ISSUE TITLE
CI Installation of Sharp gives Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by gita-v** [lovell/sharp#2600]
I am using CircleCI and am having issues with sharp when using `mocha` testing. I am restoring the node cache but everytime it says that `Cannot find module '../build/Release/sharp.node`
I can see inside my CI build that there is no build directory inside of sharp 
`
root@530a942a86fe:~/project# ls node_modules/sharp/
LICENSE       binding.gyp   lib/          package.json  
README.md     install/      node_modules/ src/ 
`
And so I have to rebuild the module in order to get the `sharp.node`.

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes:  0.27.2

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?
not npm 7

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
not using ignore-scripts

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
```
root@8345342dfdc9:~/project# npm rebuild --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'rebuild',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.10
npm info using node@v14.15.4
npm info readInstalled object
npm verb rebuild path, id [ '/root/project/node_modules/sharp', 'sharp@0.27.2' ]
npm info build /root/project/node_modules/sharp
npm info lifecycle sharp@0.27.2~preinstall: sharp@0.27.2
npm info linkStuff sharp@0.27.2
npm verb rebuildBundles [ '.bin', 'array-flatten', 'semver' ]
npm info lifecycle sharp@0.27.2~install: sharp@0.27.2

> sharp@0.27.2 install /root/project/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linux-x64.tar.br
prebuild-install info begin Prebuild-install version 6.0.1
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/dd31c0-sharp-v0.27.2-napi-v3-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.27.2/sharp-v0.27.2-napi-v3-linux-x64.tar.gz
prebuild-install http 200 https://github.com/lovell/sharp/releases/download/v0.27.2/sharp-v0.27.2-napi-v3-linux-x64.tar.gz
prebuild-install info downloading to @ /root/.npm/_prebuilds/dd31c0-sharp-v0.27.2-napi-v3-linux-x64.tar.gz.4457-815a2b5d389eb.tmp
prebuild-install info renaming to @ /root/.npm/_prebuilds/dd31c0-sharp-v0.27.2-napi-v3-linux-x64.tar.gz
prebuild-install info unpacking @ /root/.npm/_prebuilds/dd31c0-sharp-v0.27.2-napi-v3-linux-x64.tar.gz
prebuild-install info unpack resolved to /root/project/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.27.2~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.27.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/project/node_modules/sharp/node_modules/.bin:/root/project/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.27.2~install: CWD: /root/project/node_modules/sharp
npm info lifecycle sharp@0.27.2~postinstall: sharp@0.27.2
sharp@0.27.2 /root/project/node_modules/sharp
npm verb exit [ 0, true ]
npm timing npm Completed in 4761ms
npm info ok 
```
What is the output of running `npx envinfo --binaries --system`?
```

  System:
    OS: Linux 4.15 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Memory: 16.65 GB / 68.69 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
```

This is the full error:
```
[DaCoda] Mocha output: Error:
[DaCoda] Mocha output: Something went wrong installing the "sharp" module
[DaCoda] Mocha output: 
[DaCoda] Mocha output: Cannot find module '../build/Release/sharp.node'
[DaCoda] Mocha output: Require stack:
[DaCoda] Mocha output: - /root/project/node_modules/sharp/lib/constructor.js
[DaCoda] Mocha output: - /root/project/node_modules/sharp/lib/index.js
[DaCoda] Mocha output: - /root/project/modules/server/workflows/ingest_blob.ts
[DaCoda] Mocha output: - /root/project/modules/server/workflows/index.ts
[DaCoda] Mocha output: - /root/project/modules/server/utils/test_helper.ts
[DaCoda] Mocha output: - /root/project/modules/server/metrics-reporter/test_helper.ts
[DaCoda] Mocha output: - /root/project/modules/server/metrics-reporter/test/metrics_reporter_test.ts
[DaCoda] Mocha output: - /root/project/node_modules/mocha/lib/esm-utils.js
[DaCoda] Mocha output: - /root/project/node_modules/mocha/lib/mocha.js
[DaCoda] Mocha output: - /root/project/node_modules/mocha/lib/cli/one-and-dones.js
[DaCoda] Mocha output: - /root/project/node_modules/mocha/lib/cli/options.js
[DaCoda] Mocha output: - /root/project/node_modules/mocha/lib/cli/cli.js
[DaCoda] Mocha output: 
[DaCoda] Mocha output: - Run "npm rebuild --verbose sharp" and look for errors
[DaCoda] Mocha output: - Consult the installation documentation at https://sharp.pixelplumbing.com/install
[DaCoda] Mocha output: - Search for this error at https://github.com/lovell/sharp/issues
[DaCoda] Mocha output: 
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/node_modules/sharp/lib/constructor.js:34:9)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .js] (/root/project/node_modules/ts-node/src/index.ts:431:14)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/node_modules/sharp/lib/index.js:3:15)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .js] (/root/project/node_modules/ts-node/src/index.ts:431:14)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/modules/server/workflows/ingest_blob.ts:33:1)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module.m._compile (/root/project/node_modules/ts-node/src/index.ts:439:23)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .ts] (/root/project/node_modules/ts-node/src/index.ts:442:12)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/modules/server/workflows/index.ts:29:1)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module.m._compile (/root/project/node_modules/ts-node/src/index.ts:439:23)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .ts] (/root/project/node_modules/ts-node/src/index.ts:442:12)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/modules/server/utils/test_helper.ts:69:1)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module.m._compile (/root/project/node_modules/ts-node/src/index.ts:439:23)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .ts] (/root/project/node_modules/ts-node/src/index.ts:442:12)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/modules/server/metrics-reporter/test_helper.ts:1:1)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module.m._compile (/root/project/node_modules/ts-node/src/index.ts:439:23)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .ts] (/root/project/node_modules/ts-node/src/index.ts:442:12)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.<anonymous> (/root/project/modules/server/metrics-reporter/test/metrics_reporter_test.ts:1:1)
[DaCoda] Mocha output:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[DaCoda] Mocha output:     at Module.m._compile (/root/project/node_modules/ts-node/src/index.ts:439:23)
[DaCoda] Mocha output:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[DaCoda] Mocha output:     at Object.require.extensions.<computed> [as .ts] (/root/project/node_modules/ts-node/src/index.ts:442:12)
[DaCoda] Mocha output:     at Module.load (internal/modules/cjs/loader.js:928:32)
[DaCoda] Mocha output:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[DaCoda] Mocha output:     at Module.require (internal/modules/cjs/loader.js:952:19)
[DaCoda] Mocha output:     at require (internal/modules/cjs/helpers.js:88:18)
[DaCoda] Mocha output:     at Object.exports.requireOrImport (/root/project/node_modules/mocha/lib/esm-utils.js:42:12)
[DaCoda] Mocha output:     at Object.exports.loadFilesAsync (/root/project/node_modules/mocha/lib/esm-utils.js:55:34)
[DaCoda] Mocha output:     at Mocha.loadFilesAsync (/root/project/node_modules/mocha/lib/mocha.js:431:19)
[DaCoda] Mocha output:     at singleRun (/root/project/node_modules/mocha/lib/cli/run-helpers.js:125:15)
[DaCoda] Mocha output:     at exports.runMocha (/root/project/node_modules/mocha/lib/cli/run-helpers.js:190:10)
[DaCoda] Mocha output:     at Object.exports.handler (/root/project/node_modules/mocha/lib/cli/run.js:362:11)
[DaCoda] Mocha output:     at /root/project/node_modules/yargs/build/index.cjs:443:71
Mocha returned a non-zero exit code: 1

```

**Comment by lovell** [comment]
What command are you using to populate `node_modules`, e.g. is it `npm install --unsafe-perm` or something else?

**Comment by gita-v** [comment]
I have a cache folder I restore with CI using yarn.lock checksum and store that cache in 
 `/root/project/node_modules` and `/root/.yarncache`
and then I install that yarncache
`
yarn config set cache-folder ~/.yarncache
yarn install
`

**Comment by gita-v** [comment]
After I generated a new node_modules cache and saved that it seems to be working fine 🤔 Not sure what caused the issue of a bad saved cahce

**Comment by lovell** [comment]
Glad you worked it out. Perhaps check that your CI script isn't able to fail silently (e.g. when there are temporary network problems) leaving behind an invalid cache. There is also a known issue with yarn silently failing - see https://github.com/yarnpkg/yarn/issues/5476
