### ISSUE TITLE
"pkg-config --modversion vips-cpp" reports "8.10.5" but still can't install

### ISSUE THREAD

**Issue by Alex-EEE** [lovell/sharp#2616]
Hi,

I had to manually build vips b/c I have to run an older version of ubuntu on an nVidia Tegra.  The build looked successful, and it looks good according to these commands:
```
pkg-config --modversion vips-cpp
8.10.5

alex@jetson1:/usr/local$ find -name "vips8"
./vips-8.10.5/cplusplus/include/vips/vips8
```

But I'm still getting a failure when trying to install sharp
```
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
```

Can you give me any further things to try to debug?  Here are the answers to the other questions:

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
```
sudo npm install sharp --unsafe-perm=true -g --verbose
...
npm info lifecycle sharp@0.27.2~install: sharp@0.27.2

> sharp@0.27.2 install /usr/local/lib/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp Use with glibc 2.27 requires manual installation of libvips >= 8.10.5
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.17"
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 12.13.0
gyp verb command install [ '12.13.0' ]
gyp verb install input version string "12.13.0"
gyp verb install installing version: 12.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.13.0
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /usr/local/lib/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/local/lib/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/local/lib/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /usr/local/lib/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/alex/.cache/node-gyp/12.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/alex/.cache/node-gyp/12.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/alex/.cache/node-gyp/12.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm64
gyp verb node dev dir /home/alex/.cache/node-gyp/12.13.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/local/lib/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  cc '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' -I/home/alex/.cache/node-gyp/12.13.0/include/node -I/home/alex/.cache/node-gyp/12.13.0/src -I/home/alex/.cache/node-gyp/12.13.0/deps/openssl/config -I/home/alex/.cache/node-gyp/12.13.0/deps/openssl/openssl/include -I/home/alex/.cache/node-gyp/12.13.0/deps/uv/include -I/home/alex/.cache/node-gyp/12.13.0/deps/zlib -I/home/alex/.cache/node-gyp/12.13.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/node_modules/node-addon-api/nothing.o.d.raw   -c -o Release/obj.target/nothing/node_modules/node-addon-api/nothing.o ../node_modules/node-addon-api/nothing.c
  rm -f Release/obj.target/node_modules/node-addon-api/nothing.a && ar crs Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  rm -rf "Release/nothing.a" && cp -af "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a"
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/alex/.cache/node-gyp/12.13.0/include/node -I/home/alex/.cache/node-gyp/12.13.0/src -I/home/alex/.cache/node-gyp/12.13.0/deps/openssl/config -I/home/alex/.cache/node-gyp/12.13.0/deps/openssl/openssl/include -I/home/alex/.cache/node-gyp/12.13.0/deps/uv/include -I/home/alex/.cache/node-gyp/12.13.0/deps/zlib -I/home/alex/.cache/node-gyp/12.13.0/deps/v8/include -I../node_modules/node-addon-api -I/usr/local/lib/node_modules/sharp/vendor/8.10.5/include -I/usr/local/lib/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/usr/local/lib/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
sharp.target.mk:137: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.201-tegra
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sharp
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

What is the output of running `npx envinfo --binaries --system`?
```
alex@jetson1:/usr/local$ sudo npx envinfo --binaries --system
npx: installed 1 in 2.262s

  System:
    OS: Linux 4.9 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) arm64 unknown
    Memory: 1.76 GB / 3.87 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
```

Here's the other output from the install prior to the error:
```
alex@jetson1:/usr/local/lib/node_modules$ sudo npm install sharp --unsafe-perrue -g
[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] / rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] - rollbackFailedOptional: verb npm-session 14325d0f860eb[..................] \ fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] \ fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] - fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] - fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] - fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] - fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] - fetchMetadata: sill resolveWithNewModule sharp@0.27.2 [..................] / fetchMetadata: sill resolveWithNewModule npmlog@4.1.2 [..................] / fetchMetadata: sill resolveWithNewModule npmlog@4.1.2 [..................] / fetchMetadata: sill resolveWithNewModule npmlog@4.1.2 [..................] \ fetchMetadata: sill resolveWithNewModule color-convert[..................] - fetchMetadata: sill resolveWithNewModule color-name@1.[..................] - fetchMetadata: sill resolveWithNewModule color-name@1.[..................] / fetchMetadata: sill resolveWithNewModule simple-swizzl[..................] - fetchMetadata: sill resolveWithNewModule simple-swizzl[ .................] | fetchMetadata: sill resolveWithNewModule is-arrayish@0[ .................] | fetchMetadata: sill resolveWithNewModule is-arrayish@0[ .................] \ fetchMetadata: sill resolveWithNewModule is-arrayish@0[ .................] | fetchMetadata: sill resolveWithNewModule are-we-there-[ .................] | fetchMetadata: sill resolveWithNewModule are-we-there-[ .................] - fetchMetadata: sill resolveWithNewModule readable-stre[ .................] - fetchMetadata: sill resolveWithNewModule readable-stre[ .................] - fetchMetadata: sill resolveWithNewModule readable-stre[ .................] - fetchMetadata: sill resolveWithNewModule readable-stre[ .................] \ fetchMetadata: sill resolveWithNewModule util-deprecat[ .................] \ fetchMetadata: sill resolveWithNewModule util-deprecat[ .................] \ fetchMetadata: sill resolveWithNewModule util-deprecat[ .................] \ fetchMetadata: sill resolveWithNewModule util-deprecat[ .................] | fetchMetadata: sill resolveWithNewModule util-deprecat[ .................] | loadDep:strip-ansi: sill resolveWithNewModule strip-an[ .................] | loadDep:strip-ansi: sill resolveWithNewModule strip-an[ .................] - fetchMetadata: sill resolveWithNewModule code-point-at[ .................] - fetchMetadata: sill resolveWithNewModule code-point-at[ .................] / fetchMetadata: sill resolveWithNewModule number-is-nan[  ................] | fetchMetadata: sill resolveWithNewModule ansi-regex@2.[  ................] - fetchMetadata: sill resolveWithNewModule ansi-regex@2.[  ................] - fetchMetadata: sill resolveWithNewModule ansi-regex@2.[  ................] - fetchMetadata: sill resolveWithNewModule ansi-regex@2.[  ................] - fetchMetadata: sill resolveWithNewModule ansi-regex@2.[  ................] | fetchMetadata: sill resolveWithNewModule ansi-regex@2.[  ................] - fetchMetadata: sill resolveWithNewModule semver@5.7.1 [  ................] - fetchMetadata: sill resolveWithNewModule semver@5.7.1 [  ................] | fetchMetadata: sill resolveWithNewModule once@1.4.0 ch[  ................] \ fetchMetadata: sill resolveWithNewModule wrappy@1.0.2 [  ................] \ fetchMetadata: sill resolveWithNewModule wrappy@1.0.2 [  ................] | fetchMetadata: sill resolveWithNewModule wrappy@1.0.2 [  ................] | fetchMetadata: sill resolveWithNewModule ini@1.3.8 che[  ................] \ fetchMetadata: sill resolveWithNewModule ini@1.3.8 che[  ................] - fetchMetadata: sill resolveWithNewModule simple-concat[  ................] / fetchMetadata: sill resolveWithNewModule mimic-respons[  ................] - fetchMetadata: sill resolveWithNewModule mimic-respons[  ................] / fetchMetadata: sill resolveWithNewModule tar-stream@2.[  ................] / fetchMetadata: sill resolveWithNewModule tar-stream@2.[  ................] / fetchMetadata: sill resolveWithNewModule bl@4.1.0 chec[  ................] | fetchMetadata: sill resolveWithNewModule buffer@5.7.1 [  ................] | fetchMetadata: sill resolveWithNewModule buffer@5.7.1 [  ................] - fetchMetadata: sill resolveWithNewModule base64-js@1.5[  ................] - fetchMetadata: sill resolveWithNewModule base64-js@1.5[  ................] / fetchMetadata: sill resolveWithNewModule lru-cache@6.0[  ................] - fetchMetadata: sill resolveWithNewModule decompress-re[       ...........] / extract:sharp: verb lock using /home/alex/.npm/_locks/[       ...........] \ extract:sharp: verb lock using /home/alex/.npm/_locks/[       ...........] \ extract:sharp: verb lock using /home/alex/.npm/_locks/[       ...........] \ extract:sharp: verb lock using /home/alex/.npm/_locks/[       ...........] \ extract:sharp: verb lock using /home/alex/.npm/_locks/[       ...........] \ extract:sharp: verb lock using /home/alex/.npm/_locks/[        ..........] | extract:strip-json-comments: sill extract end-of-strea[         .........] | extract:napi-build-utils: sill extract isarray@~1.0.0 [         .........] - extract:napi-build-utils: sill extract isarray@~1.0.0 [          ........] \ extract:detect-libc: sill extract noop-logger@^0.1.1 e[          ........] / extract:buffer: sill extract github-from-package@0.0.0[           .......] / extract:minimist: sill extract minimist@^1.2.3 extract[            ......] \ extract:gauge: sill extract gauge@~2.7.3 extracted to [            ......] | extract:sharp: sill extract sharp@latest extracted to [            ......] / finalize:color-name: sill finalize /usr/local/lib/node[            ......] \ finalize:semver: sill finalize /usr/local/lib/node_mod[            ......] / finalize:readable-stream: sill finalize /usr/local/lib[            ......] | finalize:simple-get: sill finalize /usr/local/lib/node[            ......] | refresh-package-json:sharp: timing action:finalize Com[            ......] | refresh-package-json:sharp: timing action:finalize Com[            ......] | refresh-package-json:sharp: timing action:finalize Com[            ......] | refresh-package-json:semver: sill refresh-package-json[            ......] | refresh-package-json:semver: sill refresh-package-json[            ......] - preinstall:sharp: timing action:refresh-package-json C[            ......] / build:delegates: sill linkStuff delegates@1.0.0 is ins
> sharp@0.27.2 install /usr/local/lib/node_modules/sharp
```

**Comment by Alex-EEE** [comment]
hold tight, I may have gotten the vips install wrong...will report back

**Comment by Alex-EEE** [comment]
False alarm.  To anyone reading this later, be sure to run "which vips" after your install to make sure it succeeded.  I didn't see any errors the first time, but something must have went wrong.  Didn't do anything to fix it...just went from which vips returning nothing, to which vips showing a path
