### ISSUE TITLE
"libvips" and "windows-build-tools" are **additional install or runtime dependencies**, please design to remove that build process.

### ISSUE THREAD

**Issue by lyne408** [lovell/sharp#2628]
> Most modern macOS, Windows and Linux systems running Node.js v10+ do not require any additional install or runtime dependencies.

We all prefer **starter**, instead of **config**, **error caused by additional dependencies**.

## How to avoid actually additional requirements?

Let's see the **7zip** of **Node ecosystem**.

A package may be named `7z-bin` provides a **cross-platform binary** 7Zip.
A package `node-7z` provides *a 7Zip object* can extract, compress, check...

And  `node-7z` doesn't provides any 7Zip binary, so it add a dependency `7z-bin`.

So only add `node-7z` as dependency, you can use 7Zip. No additional binaries, no additional build process.

This is a **STARTER**.

**Comment by lyne408** [comment]
## Network Issue showcase

```bat
$>npm install sharp

> sharp@0.27.2 install D:\Workspaces\lyne\image-size-reducer\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-win32-x64.tar.brERR! sharp read ECONNRESET
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies

D:\Workspaces\lyne\image-size-reducer\node_modules\sharp>if not defined npm_config_node_gyp (node "D:\Program_Files\Node_14\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program_Files\Node_14\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  VError.cpp
  VConnection.cpp
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VConnection.cpp(34,10): fatal error C108
3: Cannot open include file: 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modul
es\sharp\build\libvips-cpp.vcxproj]
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VError.cpp(33,10): fatal error C1083: Ca
nnot open include file: 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modules\sh
arp\build\libvips-cpp.vcxproj]
  VInterpolate.cpp
  VImage.cpp
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VInterpolate.cpp(34,10): fatal error C10
83: Cannot open include file: 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modu
les\sharp\build\libvips-cpp.vcxproj]
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VImage.cpp(41,10): fatal error C1083: Ca
nnot open include file: 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modules\sh
arp\build\libvips-cpp.vcxproj]
  win_delay_load_hook.cc
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\build\Release\\nothing.lib
gyp ERR! build error
gyp ERR! stack Error: `D:\Program_Files\Visual_Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program_Files\Node_14\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\Program_Files\\Node_14\\node.exe" "D:\\Program_Files\\Node_14\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Workspaces\lyne\image-size-reducer\node_modules\sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN image-size-reducer@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.27.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.27.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program_Data\Customizable\Node\node_cache\_logs\2021-03-20T07_33_09_521Z-debug.log

D:\Workspaces\lyne\image-size-reducer>npm install sharp

> sharp@0.27.2 install D:\Workspaces\lyne\image-size-reducer\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-win32-x64.tar.br
ERR! sharp connect ETIMEDOUT 13.229.188.59:443
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies

D:\Workspaces\lyne\image-size-reducer\node_modules\sharp>if not defined npm_config_node_gyp (node "D:\Program_Files\Node_14\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program_Files\Node_14\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  VError.cpp
  VConnection.cpp
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VConnection.cpp(34,10): fatal error C1083: Cannot open include
file: 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\build\libvips-cpp.vcxproj]
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VError.cpp(33,10): fatal error C1083: Cannot open include file:
 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\build\libvips-cpp.vcxproj]
  VInterpolate.cpp
  VImage.cpp
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VInterpolate.cpp(34,10): fatal error C1083: Cannot open include
 file: 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\build\libvips-cpp.vcxproj]
D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\src\libvips\cplusplus\VImage.cpp(41,10): fatal error C1083: Cannot open include file:
 'vips/intl.h': No such file or directory [D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\build\libvips-cpp.vcxproj]
  win_delay_load_hook.cc
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> D:\Workspaces\lyne\image-size-reducer\node_modules\sharp\build\Release\\nothing.lib
gyp ERR! build error
gyp ERR! stack Error: `D:\Program_Files\Visual_Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program_Files\Node_14\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\Program_Files\\Node_14\\node.exe" "D:\\Program_Files\\Node_14\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Workspaces\lyne\image-size-reducer\node_modules\sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN image-size-reducer@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.27.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.27.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program_Data\Customizable\Node\node_cache\_logs\2021-03-20T07_52_32_053Z-debug.log
```

## Build Error show case

**Comment by lovell** [comment]
Hello, in both of these examples there are networking errors during installation.

> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-win32-x64.tar.br
> ERR! sharp read ECONNRESET
> info sharp Attempting to build from source via node-gyp but this may fail due to the above error

> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-win32-x64.tar.br
> ERR! sharp connect ETIMEDOUT 13.229.188.59:443
> info sharp Attempting to build from source via node-gyp but this may fail due to the above error

Both of these error messages are relatively clear that there has been a networking error *and* that the next step is likely to fail because of it.

On Windows machines this next step will almost always fail as there is no mechanism for finding a globally-installed libvips (unlike pkg-config on Linux and macOS machines).

To slightly improve the situation, we could trap common networking errors and provide further help for these to Windows users.

If you're based in China then I recommend the use of the mirror hosted there - see https://sharp.pixelplumbing.com/install#chinese-mirror
