### ISSUE TITLE
 Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp

### ISSUE THREAD

**Issue by arvi** [lovell/sharp#2695]
I am unable to install sharp in a project. Here's the verbose install log `ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-darwin-x64.tar.gz status code 403`

```
npm info it worked if it ends with ok
npm verb cli [ '/Users/me/.nvm/versions/node/v10.15.3/bin/node',
npm verb cli   '/Users/me/.nvm/versions/node/v10.15.3/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@6.4.1
npm info using node@v10.15.3
npm verb npm-session b64166a0550b5001
npm http fetch GET 304 https://registry.npmjs.org/sharp 1017ms (from cache)
npm timing stage:loadCurrentTree Completed in 2495ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 693ms
npm http fetch GET 304 https://registry.npmjs.org/caw 302ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 820ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 826ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 828ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 831ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/get-proxy 273ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isurl 277ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 283ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/url-to-options 286ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npm-conf 261ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/config-chain 253ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pify 255ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/ini 8ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/proto-list 258ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-object 255ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-to-string-tag-x 297ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-symbol-support-x 260ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 260ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 288ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 359ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 261ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 268ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 268ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 269ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 261ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 280ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 281ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 288ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 290ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6159ms
npm timing stage:loadIdealTree Completed in 7066ms
npm timing stage:generateActionsToTake Completed in 92ms
npm verb correctMkdir /Users/me/.npm/_locks correctMkdir not in flight; initializing
npm timing audit compress Completed in 6ms
npm info audit Submitting payload of 34690bytes
npm timing audit submit Completed in 1872ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1872ms
npm timing audit body Completed in 2ms
npm verb lock using /Users/me/.npm/_locks/staging-38290f1fa815b5dd.lock for /Users/me/code/aaapp/node_modules/.staging
npm timing action:extract Completed in 1762ms
npm timing action:finalize Completed in 99ms
npm timing action:refresh-package-json Completed in 155ms
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle color-name@1.1.3~preinstall: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~preinstall: color-convert@1.9.3
npm info lifecycle has-symbol-support-x@1.4.2~preinstall: has-symbol-support-x@1.4.2
npm info lifecycle has-to-string-tag-x@1.4.1~preinstall: has-to-string-tag-x@1.4.1
npm info lifecycle ini@1.3.8~preinstall: ini@1.3.8
npm info lifecycle is-arrayish@0.3.2~preinstall: is-arrayish@0.3.2
npm info lifecycle is-object@1.0.2~preinstall: is-object@1.0.2
npm info lifecycle isurl@1.0.0~preinstall: isurl@1.0.0
npm info lifecycle mimic-response@1.0.1~preinstall: mimic-response@1.0.1
npm info lifecycle decompress-response@3.3.0~preinstall: decompress-response@3.3.0
npm info lifecycle pify@3.0.0~preinstall: pify@3.0.0
npm info lifecycle proto-list@1.2.4~preinstall: proto-list@1.2.4
npm info lifecycle config-chain@1.1.12~preinstall: config-chain@1.1.12
npm info lifecycle npm-conf@1.1.3~preinstall: npm-conf@1.1.3
npm info lifecycle get-proxy@2.1.0~preinstall: get-proxy@2.1.0
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle simple-swizzle@0.2.2~preinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~preinstall: color-string@1.5.5
npm info lifecycle tunnel-agent@0.6.0~preinstall: tunnel-agent@0.6.0
npm info lifecycle url-to-options@1.0.1~preinstall: url-to-options@1.0.1
npm info lifecycle yallist@3.1.1~preinstall: yallist@3.1.1
npm info lifecycle minipass@2.9.0~preinstall: minipass@2.9.0
npm info lifecycle minizlib@1.3.3~preinstall: minizlib@1.3.3
npm info lifecycle caw@2.0.1~preinstall: caw@2.0.1
npm info lifecycle color@2.0.1~preinstall: color@2.0.1
npm info lifecycle detect-libc@0.2.0~preinstall: detect-libc@0.2.0
npm info lifecycle simple-get@2.8.1~preinstall: simple-get@2.8.1
npm info lifecycle tar@3.2.1~preinstall: tar@3.2.1
npm info lifecycle sharp@0.18.4~preinstall: sharp@0.18.4
npm timing action:preinstall Completed in 11ms
npm info linkStuff chownr@1.1.4
npm info linkStuff color-name@1.1.3
npm info linkStuff color-convert@1.9.3
npm info linkStuff has-symbol-support-x@1.4.2
npm info linkStuff has-to-string-tag-x@1.4.1
npm info linkStuff ini@1.3.8
npm info linkStuff is-arrayish@0.3.2
npm info linkStuff is-object@1.0.2
npm info linkStuff isurl@1.0.0
npm info linkStuff mimic-response@1.0.1
npm info linkStuff decompress-response@3.3.0
npm info linkStuff pify@3.0.0
npm info linkStuff proto-list@1.2.4
npm info linkStuff config-chain@1.1.12
npm info linkStuff npm-conf@1.1.3
npm info linkStuff get-proxy@2.1.0
npm info linkStuff simple-concat@1.0.1
npm info linkStuff simple-swizzle@0.2.2
npm info linkStuff color-string@1.5.5
npm info linkStuff tunnel-agent@0.6.0
npm info linkStuff url-to-options@1.0.1
npm info linkStuff yallist@3.1.1
npm info linkStuff minipass@2.9.0
npm info linkStuff minizlib@1.3.3
npm info linkStuff caw@2.0.1
npm info linkStuff color@2.0.1
npm info linkStuff detect-libc@0.2.0
npm verb linkBins [ { 'detect-libc': './bin/detect-libc.js' },
npm verb linkBins   '/Users/me/code/aaapp/node_modules/.bin',
npm verb linkBins   false ]
npm info linkStuff simple-get@2.8.1
npm info linkStuff tar@3.2.1
npm info linkStuff sharp@0.18.4
npm timing action:build Completed in 29ms
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle color-name@1.1.3~install: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~install: color-convert@1.9.3
npm info lifecycle has-symbol-support-x@1.4.2~install: has-symbol-support-x@1.4.2
npm info lifecycle has-to-string-tag-x@1.4.1~install: has-to-string-tag-x@1.4.1
npm info lifecycle ini@1.3.8~install: ini@1.3.8
npm info lifecycle is-arrayish@0.3.2~install: is-arrayish@0.3.2
npm info lifecycle is-object@1.0.2~install: is-object@1.0.2
npm info lifecycle isurl@1.0.0~install: isurl@1.0.0
npm info lifecycle mimic-response@1.0.1~install: mimic-response@1.0.1
npm info lifecycle decompress-response@3.3.0~install: decompress-response@3.3.0
npm info lifecycle pify@3.0.0~install: pify@3.0.0
npm info lifecycle proto-list@1.2.4~install: proto-list@1.2.4
npm info lifecycle config-chain@1.1.12~install: config-chain@1.1.12
npm info lifecycle npm-conf@1.1.3~install: npm-conf@1.1.3
npm info lifecycle get-proxy@2.1.0~install: get-proxy@2.1.0
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle simple-swizzle@0.2.2~install: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~install: color-string@1.5.5
npm info lifecycle tunnel-agent@0.6.0~install: tunnel-agent@0.6.0
npm info lifecycle url-to-options@1.0.1~install: url-to-options@1.0.1
npm info lifecycle yallist@3.1.1~install: yallist@3.1.1
npm info lifecycle minipass@2.9.0~install: minipass@2.9.0
npm info lifecycle minizlib@1.3.3~install: minizlib@1.3.3
npm info lifecycle caw@2.0.1~install: caw@2.0.1
npm info lifecycle color@2.0.1~install: color@2.0.1
npm info lifecycle detect-libc@0.2.0~install: detect-libc@0.2.0
npm info lifecycle simple-get@2.8.1~install: simple-get@2.8.1
npm info lifecycle tar@3.2.1~install: tar@3.2.1
npm info lifecycle sharp@0.18.4~install: sharp@0.18.4

> sharp@0.18.4 install /Users/me/code/aaapp/node_modules/sharp
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/Users/me/.nvm/versions/node/v10.15.3/bin/node',
gyp verb cli   '/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.3
gyp verb command install [ '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.15.3
gyp verb build dir attempting to create "build" dir: /Users/me/code/aaapp/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /Users/me/code/aaapp/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/me/code/aaapp/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/me/code/aaapp/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /Users/me/code/aaapp/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/me/code/aaapp/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/me/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/me/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/me/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/me/code/aaapp/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-darwin-x64.tar.gz status code 403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/me/.nvm/versions/node/v10.15.3/bin/node" "/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/code/aaapp/node_modules/sharp
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm verb lifecycle sharp@0.18.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.18.4~install: PATH: /Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/me/code/aaapp/node_modules/sharp/node_modules/.bin:/Users/me/code/aaapp/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/opt/php@7.2/sbin:/usr/local/opt/php@7.2/bin:/usr/local/mysql/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/me/.composer/vendor/bin:/usr/local/opt/mongodb-community@4.2/bin:/usr/local/opt/mongodb-community@4.2/bin:/usr/local/opt/mongodb-community@4.2/bin:/Users/me/.yarn/bin:/Users/me/.config/yarn/global/node_modules/.bin:/Users/me/.yvm/versions/v1.13.0/bin:/Users/me/Library/Android/sdk/emulator:/Users/me/Library/Android/sdk/tools:/Users/me/Documents/dev-installs/flutter/bin:/Users/me/.nvm/versions/node/v10.15.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
npm verb lifecycle sharp@0.18.4~install: CWD: /Users/me/code/aaapp/node_modules/sharp
npm info lifecycle sharp@0.18.4~install: Failed to exec install script
npm timing action:install Completed in 5708ms
npm verb unlock done using /Users/me/.npm/_locks/staging-38290f1fa815b5dd.lock for /Users/me/code/aaapp/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 100ms
npm timing stage:runTopLevelLifecycles Completed in 54631ms
npm WARN pdfjs-dist@2.2.228 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@2.0.0 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN aaapp@1.0.0 No repository field.

npm verb stack Error: sharp@0.18.4 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid sharp@0.18.4
npm verb cwd /Users/me/code/aaapp
npm verb Darwin 19.6.0
npm verb argv "/Users/me/.nvm/versions/node/v10.15.3/bin/node" "/Users/me/.nvm/versions/node/v10.15.3/bin/npm" "install" "--verbose" "sharp"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 55573ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2021-05-05T08_35_30_113Z-debug.log
```

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/2574
