### ISSUE TITLE
Fatal install bug

### ISSUE THREAD

**Issue by sandorvasas** [lovell/sharp#2699]
For almost a day, I'm constantly getting this, it's driving me mad:
```
npm WARN invalid config cache=false set in command line options
npm WARN invalid config Must be valid filesystem path
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/s/.nvm/versions/node/v13.7.0/bin/node /home/s/.nvm/versions/node/v13.7.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/s/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/s/.npm/_cacache/tmp/git-clone-b9bef8e8/node_modules/sharp
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! npm ERR! make: Entering directory '/home/s/.npm/_cacache/tmp/git-clone-b9bef8e8/node_modules/sharp/build'
npm ERR! npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR! npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! npm ERR!   CXX(target) Release/obj.target/sharp/src/metadata.o
npm ERR! npm ERR!   CXX(target) Release/obj.target/sharp/src/stats.o
npm ERR! npm ERR! make: Leaving directory '/home/s/.npm/_cacache/tmp/git-clone-b9bef8e8/node_modules/sharp/build'
npm ERR! npm ERR! info sharp Using cached /home/s/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@7.1.2
npm ERR! npm ERR! gyp info using node@13.7.0 | linux | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.8.2 found at "/home/s/anaconda3/envs/cliniko/bin/python3"
npm ERR! npm ERR! gyp info spawn /home/s/anaconda3/envs/cliniko/bin/python3
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   '/home/s/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'make',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/home/s/.npm/_cacache/tmp/git-clone-b9bef8e8/node_modules/sharp/build/config.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/home/s/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/home/s/.cache/node-gyp/13.7.0/include/node/common.gypi',
npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/s/.cache/node-gyp/13.7.0',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/s/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/s/.cache/node-gyp/13.7.0/<(target_arch)/node.lib',
npm ERR! npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/s/.npm/_cacache/tmp/git-clone-b9bef8e8/node_modules/sharp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! npm ERR! gyp info spawn args   '--depth=.',
npm ERR! npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! npm ERR! gyp info spawn args   '--generator-output',
npm ERR! npm ERR! gyp info spawn args   'build',
npm ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp info spawn make
npm ERR! npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! npm ERR! ../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
npm ERR! npm ERR! ../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
npm ERR! npm ERR!   130 |         channels->Set(i, channelStat);
npm ERR! npm ERR!       |                                     ^
npm ERR! npm ERR! In file included from /home/s/.cache/node-gyp/13.7.0/include/node/node.h:63,
npm ERR! npm ERR!                  from ../src/stats.cc:19:
npm ERR! npm ERR! /home/s/.cache/node-gyp/13.7.0/include/node/v8.h:3547:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
npm ERR! npm ERR!  3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR! npm ERR!       |                                     ^~~
npm ERR! npm ERR! /home/s/.cache/node-gyp/13.7.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! npm ERR! /home/s/.cache/node-gyp/13.7.0/include/node/v8.h:3550:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
npm ERR! npm ERR!  3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR! npm ERR!       |                                     ^~~
npm ERR! npm ERR! /home/s/.cache/node-gyp/13.7.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! npm ERR! make: *** [sharp.target.mk:138: Release/obj.target/sharp/src/stats.o] Error 1
npm ERR! npm ERR! gyp ERR! build error 
npm ERR! npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/s/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! npm ERR! gyp ERR! System Linux 5.8.0-50-generic
npm ERR! npm ERR! gyp ERR! command "/home/s/.nvm/versions/node/v13.7.0/bin/node" "/home/s/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! npm ERR! gyp ERR! cwd /home/s/.npm/_cacache/tmp/git-clone-b9bef8e8/node_modules/sharp
npm ERR! npm ERR! gyp ERR! node -v v13.7.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! npm ERR! gyp ERR! not ok
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/s/.npm/_logs/2021-05-06T16_58_14_848Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/s/.npm/_logs/2021-05-06T16_58_19_631Z-debug.log
```

The worst part is that my project does not even have any reference to sharp! It's a frontend React application, not using any kind of image resizing. I don't get how even sharp comes into the picture, or what the heck is fetching it from where. I tried node 13.7, node 14.7, npm rebuild, deleted the /home/s/.npm, installed with --no-cache, explicitly ran npm uninstall sharp; npm uninstall -g sharp just to be 110% sure there is no sharp at all. Searching for 'sharp' keyword in my project directory yields nothing. no sharp in package-lock.json, no sharp in package.json, no sharp in node_modules anywhere. Why does npm want to install and build sharp, and more importantly how to fix this bug? I had started debugging a totally unrelated problem and now this idiocy is halting me from resuming work

**Comment by lovell** [comment]
This log suggests there is a (transitive) dependency on sharp v0.22.x (April 2019). Support for Node.js 13 was added in v0.23.2.

https://sharp.pixelplumbing.com/changelog

Node.js 13 reached end-of-life in June 2020. 

What is the output of running `npm ls sharp` and `npm ls -g sharp` when run in the directory containing the project?

As an aside, please don't take out your frustrations ("this idiocy is halting me from resuming work") on open source maintainers that volunteer their time when you are requesting unpaid help from them.

**Comment by sandorvasas** [comment]
```
$ npm ls sharp
XXXX REDACTED PATH XXXXXXXXX
└── (empty)

$ npm ls -g sharp
XXXX REDACTED PATH XXXXXXXXX
└── (empty)
```
As I said, there is no sharp in the project, nor globally. I do not want to use sharp, as I don't need it for this project.

**Comment by sandorvasas** [comment]
Found sharp "hidden" in a dependency which was npm installed by its github repo url.
