### ISSUE TITLE
 error C2661: "v8::Object::Set": No overloaded function accepts 2 Arguments

### ISSUE THREAD

**Issue by Link451** [lovell/sharp#2706]
I have the error mentioned in the title whenever I try to install sharp via npm.

I have tried the --unsafe-perm and the --ignore-scripts=false flag with no luck.

The output of npx envinfo --binaries --system is:

```System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
```
and the output of npm ls sharp 
```
+-- UNMET DEPENDENCY gatsby-plugin-favicon@3.1.6
| `-- UNMET DEPENDENCY favicons-webpack-plugin@git+https://github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf
|   `-- UNMET DEPENDENCY favicons@5.4.1
|     `-- UNMET DEPENDENCY sharp@0.22.1
+-- gatsby-plugin-manifest@2.4.9
| `-- sharp@0.25.3
+-- gatsby-plugin-sharp@2.6.9
| `-- sharp@0.25.3
`-- gatsby-transformer-sharp@2.5.3
  `-- sharp@0.25.3

npm ERR! missing: gatsby-plugin-favicon@3.1.6, required by it-factum-website@1.0.0
npm ERR! missing: favicons-webpack-plugin@git+https://github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf, required by gatsby-plugin-favicon@3.1.6
npm ERR! missing: favicons@5.4.1, required by favicons-webpack-plugin@git+https://github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf
npm ERR! missing: sharp@0.22.1, required by favicons@5.4.1
```
while npm view sharp dist-tags.latest returns 0.28.2. Could that be the problem? I am new to React and Node and the project I am building is not created by me, but it`s odd to me, that there are two different versions (0.22 and 0.35), none of which matches with the latest version.

Output of npm install --verbose sharp (shortened to error and warning messages):
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.12
npm info using node@v14.16.1
(...)
npm info lifecycle sharp@0.28.2~preuninstall: sharp@0.28.2
npm info lifecycle sharp@0.28.2~uninstall: sharp@0.28.2
npm verb unbuild rmStuff sharp@0.28.2 from C:\Users\username\source\repos\website\node_modules
npm info lifecycle sharp@0.28.2~postuninstall: sharp@0.28.2
(...)
npm info lifecycle sharp@0.22.1~preinstall: sharp@0.22.1
npm info lifecycle favicons@5.4.1~preinstall: favicons@5.4.1
npm info lifecycle favicons-webpack-plugin@git+https://github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf~preinstall: favicons-webpack-plugin@git+https://github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf
npm info lifecycle gatsby-plugin-favicon@3.1.6~preinstall: gatsby-plugin-favicon@3.1.6
npm info lifecycle sharp@0.28.2~preinstall: sharp@0.28.2
(...)
npm info lifecycle sharp@0.22.1~install: sharp@0.22.1

> sharp@0.22.1 install C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\username\AppData\Roaming\npm-cache\_libvips\libvips-8.7.4-win32-x64.tar.gz
info sharp Creating C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\vendor\lib to C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ C:\Users\username\AppData\Roaming\npm-cache\_prebuilds\aa520d-sharp-v0.22.1-node-v83-win32-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v83-win32-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v83-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.16.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.16.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "C:\Python39\python.exe"
gyp verb find Python - executing "C:\Python39\python.exe" to get version
gyp verb find Python - version is "3.9.5"
gyp info find Python using Python version 3.9.5 found at "C:\Python39\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 14.16.1
gyp verb command install [ '14.16.1' ]
gyp verb install input version string "14.16.1"
gyp verb install installing version: 14.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.16.1
gyp verb build dir attempting to create "build" dir: C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build
gyp verb build dir "build" dir needed to be created? C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2019 (16.9.31205.134) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp verb find VS - "Visual Studio C++ core features" missing
gyp verb find VS checking VS2017 (15.9.28307.1500) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp info find VS using VS2017 (15.9.28307.1500) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build\config.gypigyp verb config.gypi checking for gypi file: C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python39\python.exe
...
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\username\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\username\\source\\repos\\website\\node_modules\\favicons\\node_modules\\sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\username\\source\\repos\website\\node_modules\\favicons\\node_modules\\sharp\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
←[37;40mgyp←[0m ←[0m←[34;40mverb←[0m ←[0m←[35mcommand←[0m build []
←[0m←[37;40mgyp←[0m ←[0m←[34;40mverb←[0m ←[0m←[35mbuild type←[0m Release
←[0m←[37;40mgyp←[0m ←[0m←[34;40mverb←[0m ←[0m←[35marchitecture←[0m x64
←[0m←[37;40mgyp←[0m ←[0m←[34;40mverb←[0m ←[0m←[35mnode dev dir←[0m C:\Users\Stefanie Schaller\AppData\Local\node-gyp\Cache\14.16.1
←[0m←[37;40mgyp←[0m ←[0m←[34;40mverb←[0m ←[0m←[35mfound first Solution file←[0m build/binding.sln
←[0m←[37;40mgyp←[0m ←[0m←[34;40mverb←[0m ←[0m←[35musing MSBuild:←[0m C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn←[0m C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m [
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   'build/binding.sln',
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   '/nologo',
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   '/p:Configuration=Release;Platform=x64'
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m ]
←[0mDie Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
Der Buildvorgang wurde am 11.05.2021 09:31:20 gestartet.
Projekt "C:\Users\username\source\repos\website\node_modules\fav
icons\node_modules\sharp\build\binding.sln" auf Knoten "1" (Standardziele).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Release|x64" wird erstellt.
Das Projekt "C:\Users\username\source\repos\website\node_modules
\favicons\node_modules\sharp\build\binding.sln" (1) erstellt "C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build
\libvips-cpp.vcxproj" (2) auf Knoten "1" (Standardziele).
PrepareForBuild:
  Das Verzeichnis "Release\obj\libvips-cpp\" wird erstellt.
  Das Verzeichnis "Release\obj\libvips-cpp\libvips-cpp.tlog\" wird erstellt.
InitializeBuildStatus:
  "Release\obj\libvips-cpp\libvips-cpp.tlog\unsuccessfulbuild" wird erstellt, da "A
  lwaysCreate" angegeben wurde.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.1
  6.27023\bin\HostX64\x64\CL.exe /c /I"C:\Users\username\AppData\Local\nod
  e-gyp\Cache\14.16.1\include\node" /I"C:\Users\username\AppData\Local\nod
  e-gyp\Cache\14.16.1\src" /I"C:\Users\usernamer\AppData\Local\node-gyp\Cac
  he\14.16.1\deps\openssl\config" /I"C:\Users\username\AppData\Local\node-
  gyp\Cache\14.16.1\deps\openssl\openssl\include" /I"C:\Users\username\App
  Data\Local\node-gyp\Cache\14.16.1\deps\uv\include" /I"C:\Users\username\
  AppData\Local\node-gyp\Cache\14.16.1\deps\zlib" /I"C:\Users\username\App
  Data\Local\node-gyp\Cache\14.16.1\deps\v8\include" /I..\vendor\include /I"..\vend
  or\include\glib-2.0" /I"..\vendor\lib\glib-2.0\include" /Z7 /nologo /W3 /WX- /dia
  gnostics:classic /MP /Ox /Ob2 /Oi /Ot /Oy /D "NODE_GYP_MODULE_NAME=libvips-cpp" /
  D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D V8_DEPRE
  CATION_WARNINGS /D V8_IMMINENT_DEPRECATION_WARNINGS /D WIN32 /D _CRT_SECURE_NO_DE
  PRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D OPENSSL_NO_PINSHARED
   /D OPENSSL_THREADS /D VIPS_CPLUSPLUS_EXPORTS /D _ALLOW_KEYWORD_MACROS /D "HOST_B
  INARY=\"node.exe\"" /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t
   /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\libvips-cpp\\" /Fd"Release\obj\libv
  ips-cpp\vc141.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd426
  7 /FC /errorReport:queue ..\src\libvips\cplusplus\VError.cpp ..\src\libvips\cplus
  plus\VInterpolate.cpp ..\src\libvips\cplusplus\VImage.cpp "C:\Program Files\nodej
  s\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.1
  6.27023\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build
  \Release\libvips-cpp.dll" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib
  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib
  DelayImp.lib "C:\\Users\\username\\AppData\\Local\\node-gyp\\Cache\\14.1
  6.1\\x64\\node.lib" ..\vendor\lib\libvips.lib "..\vendor\lib\libglib-2.0.lib" "..
  \vendor\lib\libgobject-2.0.lib" Delayimp.lib /DELAYLOAD:node.exe /MANIFEST /MANIF
  ESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users
  \username\source\repos\website\node_modules\favicons\node_modu
  les\sharp\build\Release\libvips-cpp.pdb" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:
  "C:\Users\username\source\repos\website\node_modules\favicons\
  node_modules\sharp\build\Release\libvips-cpp.lib" /MACHINE:X64 /ignore:4199 /DLL
  "Release\obj\libvips-cpp\VError.obj"
  "Release\obj\libvips-cpp\VInterpolate.obj"
  "Release\obj\libvips-cpp\VImage.obj"
  "Release\obj\libvips-cpp\win_delay_load_hook.obj"
     Bibliothek "C:\Users\username\source\repos\website\node_mod
  ules\favicons\node_modules\sharp\build\Release\libvips-cpp.lib" und Objekt "C:\Us
  ers\username\source\repos\website\node_modules\favicons\node_m
  odules\sharp\build\Release\libvips-cpp.exp" werden erstellt.
  libvips-cpp.vcxproj -> C:\Users\username\source\repos-website\
  node_modules\favicons\node_modules\sharp\build\Release\\libvips-cpp.dll
FinalizeBuildStatus:
  Die Datei "Release\obj\libvips-cpp\libvips-cpp.tlog\unsuccessfulbuild" wird gelös
  cht.
  Aktualisieren des Timestamps von "Release\obj\libvips-cpp\libvips-cpp.tlog\libvip
  s-cpp.lastbuildstate".
Die Erstellung von Projekt "C:\Users\usernamer\source\repos\it-factum-websi
te\node_modules\favicons\node_modules\sharp\build\libvips-cpp.vcxproj" ist abgeschl
ossen (Standardziele).

Das Projekt "C:\Users\username\source\repos\website\node_modules
\favicons\node_modules\sharp\build\binding.sln" (1) erstellt "C:\Users\username\source\repos\website\node_modules\favicons\node_modules\sharp\build
\sharp.vcxproj.metaproj" (3) auf Knoten "1" (Standardziele).
Das Projekt "C:\Users\username\source\repos\it-factum-website\node_modules
\favicons\node_modules\sharp\build\sharp.vcxproj.metaproj" (3) erstellt "C:\Users\usernamer\source\repos\website\node_modules\favicons\node_modules\
sharp\build\sharp.vcxproj" (4) auf Knoten "1" (Standardziele).
PrepareForBuild:
  Directory "Release\obj\sharp\" 
  Directory "Release\obj\sharp\sharp.tlog\" 
InitializeBuildStatus:
  "Release\obj\sharp\sharp.tlog\unsuccessfulbuild" because of "AlwaysCreate"
  ´
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.1
  6.27023\bin\HostX64\x64\CL.exe /c /I"C:\Users\username\AppData\Local\nod
  e-gyp\Cache\14.16.1\include\node" /I"C:\Users\username\AppData\Local\nod
  e-gyp\Cache\14.16.1\src" /I"C:\Users\username\AppData\Local\node-gyp\Cac
  he\14.16.1\deps\openssl\config" /I"C:\Users\username\AppData\Local\node-
  gyp\Cache\14.16.1\deps\openssl\openssl\include" /I"C:\Users\username\App
  Data\Local\node-gyp\Cache\14.16.1\deps\uv\include" /I"C:\Users\username\
  AppData\Local\node-gyp\Cache\14.16.1\deps\zlib" /I"C:\Users\username\App
  Data\Local\node-gyp\Cache\14.16.1\deps\v8\include" /I..\..\..\..\nan /I..\vendor\
  include /I"..\vendor\include\glib-2.0" /I"..\vendor\lib\glib-2.0\include" /Z7 /no
  logo /W3 /WX- /diagnostics:classic /MP /Ox /Ob2 /Oi /Ot /Oy /D NODE_GYP_MODULE_NA
  ME=sharp /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /
  D V8_DEPRECATION_WARNINGS /D V8_IMMINENT_DEPRECATION_WARNINGS /D WIN32 /D _CRT_SE
  CURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D OPENSSL_NO
  _PINSHARED /D OPENSSL_THREADS /D _ALLOW_KEYWORD_MACROS /D BUILDING_NODE_EXTENSION
   /D "HOST_BINARY=\"node.exe\"" /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise
  /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\sharp\\" /Fd"Release\obj
  \sharp\vc141.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267
   /wd4996 /FC /errorReport:queue ..\src\common.cc ..\src\metadata.cc ..\src\stats.
  cc ..\src\operations.cc ..\src\pipeline.cc ..\src\sharp.cc ..\src\utilities.cc "C
  :\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_
  hook.cc"
  common.cc
  metadata.cc
  stats.cc
  operations.cc
c:\users\username\source\repos\project\node_modules\favicons\nod
e_modules\sharp\src\stats.cc(130): error C2661: "v8::Object::Set":No overloaded Function accepts 2 arguments [C:\Users\username\source\repos\project\node_modules\favicons\node_modules\sharp\build\sharp.vcxproj]
  pipeline.cc
  sharp.cc
  utilities.cc
  win_delay_load_hook.cc
Creating project "C:\Users\username\source\repos\project\node_modules\favicons\node_modules\sharp\build\sharp.vcxproj" finished
 (Standardziele) -- Error.

Creating project "C:\Users\username\source\repos\project\node_modules\favicons\node_modules\sharp\build\sharp.vcxproj.metaproj" finished (Standardziele) --  Error.

Creating project "C:\Users\username\source\repos\project\node_modules\favicons\node_modules\sharp\build\binding.sln" finished(
Standardziele) -- Error.


Error while Building.

"C:\Users\username\source\repos\project\node_modules\favicons\no
de_modules\sharp\build\binding.sln" (Standard) (1) ->
"C:\Users\username\source\repos\project\node_modules\favicons\no
de_modules\sharp\build\sharp.vcxproj.metaproj" (Standard) (3) ->
"C:\Users\username\source\repos\project\node_modules\favicons\no
de_modules\sharp\build\sharp.vcxproj" (Standard) (4) ->
(ClCompile Ziel) ->
  c:\users\username\source\repos\project\node_modules\favicons\n
ode_modules\sharp\src\stats.cc(130): error C2661: "v8::Object::Set": No overloaded function accepts 2 arguments [C:\Users\username\source\repo\project\node_modules\favicons\node_modules\sharp\build\sharp.vcxproj]

    0 warnings
    1 error

time 00:00:09.83
←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mbuild error←[0m
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.emit (events.js:315:20)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mSystem←[0m Windows_NT 10.0.19042
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcommand←[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcwd←[0m C:\Users\username\source\repos\project\node_modules\favicons\node_modules\sharp
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode -v←[0m v14.16.1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode-gyp -v←[0m v5.1.0
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnot ok←[0m
←[0mnpm verb lifecycle sharp@0.22.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.22.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin; (...)
npm verb lifecycle sharp@0.22.1~install: CWD: C:\Users\username\source\repos\project\node_modules\favicons\node_modules\sharp
npm info lifecycle sharp@0.22.1~install: Failed to exec install script
npm timing action:install Completed in 14196ms
npm verb unlock done using C:\Users\username\AppData\Roaming\npm-cache\_locks\staging-564117d5797403ca.lock for C:\Users\username\source\repos\project\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 695ms
npm timing stage:runTopLevelLifecycles Completed in 39872ms
npm WARN @jimp/plugin-threshold@0.10.3 requires a peer of @jimp/plugin-color@>=0.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @jimp/plugin-threshold@0.10.3 requires a peer of @jimp/plugin-resize@>=0.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.3.2 requires a peer of react-refresh@^0.8.2 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN project@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.22.1
npm verb cwd C:\Users\username\source\repos\project
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
npm verb node v14.16.1
npm verb npm  v6.14.12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 42138ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2021-05-11T07_31_33_064Z-debug.log

```

**Comment by lovell** [comment]
Hi, this is sharp v0.22.1, which won't work with Node.js 14 - please upgrade.

https://sharp.pixelplumbing.com/changelog
