### ISSUE TITLE
latest version (0.28.2) fails to install on Windows 10 npm v7 node 14 due compilation error

### ISSUE THREAD

**Issue by yarsky-tgz** [lovell/sharp#2712]
> What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```
1554 info run sharp@0.28.2 install node_modules/sharp node-gyp rebuild
1555 info run sharp@0.28.2 install { code: 1, signal: null }
1556 warn cleanup Failed to remove some directories [
1556 warn cleanup   [
1556 warn cleanup     undefined,
1556 warn cleanup     AssertionError [ERR_ASSERTION]: rimraf: missing path
1556 warn cleanup         at rimraf (C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:54:3)
1556 warn cleanup         at internal/util.js:297:30
1556 warn cleanup         at new Promise (<anonymous>)
1556 warn cleanup         at rimraf (internal/util.js:296:12)
1556 warn cleanup         at C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:452:20
1556 warn cleanup         at Array.map (<anonymous>)
1556 warn cleanup         at Arborist.[rollbackCreateSparseTree] (C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:452:8)
1556 warn cleanup         at C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:892:50
1556 warn cleanup         at processTicksAndRejections (internal/process/task_queues.js:93:5)
1556 warn cleanup         at async Arborist.[reifyPackages] (C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:212:11) {
1556 warn cleanup       generatedMessage: false,
1556 warn cleanup       code: 'ERR_ASSERTION',
1556 warn cleanup       actual: undefined,
1556 warn cleanup       expected: true,
1556 warn cleanup       operator: '=='
1556 warn cleanup     }
1556 warn cleanup   ],
1556 warn cleanup   [
1556 warn cleanup     'D:\\work\\withthegrid\\platform\\node_modules',
1556 warn cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\work\withthegrid\platform\node_modules\isolated-vm'] {
1556 warn cleanup       errno: -4082,
1556 warn cleanup       code: 'EBUSY',
1556 warn cleanup       syscall: 'rmdir',
1556 warn cleanup       path: 'D:\\work\\withthegrid\\platform\\node_modules\\isolated-vm'
1556 warn cleanup     }
1556 warn cleanup   ]
1556 warn cleanup ]
1557 timing reify:rollback:createSparse Completed in 45898ms
1558 timing reify:rollback:retireShallow Completed in 0ms
1559 timing command:install Completed in 98476ms
1560 verbose stack Error: command failed
1560 verbose stack     at ChildProcess.<anonymous> (C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
1560 verbose stack     at ChildProcess.emit (events.js:315:20)
1560 verbose stack     at maybeClose (internal/child_process.js:1048:16)
1560 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
1561 verbose pkgid sharp@0.28.2
1562 verbose cwd D:\work\withthegrid\platform
1563 verbose Windows_NT 10.0.19042
1564 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kzawo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
1565 verbose node v14.15.3
1566 verbose npm  v7.12.1
1567 error code 1
1568 error path D:\work\withthegrid\platform\node_modules\sharp
1569 error command failed
1570 error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
1571 error Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
1571 error   nothing.c
1571 error   win_delay_load_hook.cc
1571 error   nothing.vcxproj -> D:\work\withthegrid\platform\node_modules\sharp\build\Release\\nothing.lib
1571 error   VError.cpp
1571 error D:\work\withthegrid\platform\node_modules\sharp\src\libvips\cplusplus\VError.cpp(33,10): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or directory [D:\work\withthegrid\platform\node_modules\sharp\build\libvips-cpp.vcxproj]
1572 error gyp info it worked if it ends with ok
1572 error gyp info using node-gyp@7.1.2
1572 error gyp info using node@14.15.3 | win32 | x64
1572 error gyp info find Python using Python version 3.7.9 found at "C:\Users\kzawo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe"
1572 error gyp info find VS using VS2019 (16.9.31112.23) found at:
1572 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
1572 error gyp info find VS run with --verbose for detailed information
1572 error gyp info spawn C:\Users\kzawo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
1572 error gyp info spawn args [
1572 error gyp info spawn args   'C:\\Users\\kzawo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
1572 error gyp info spawn args   'binding.gyp',
1572 error gyp info spawn args   '-f',
1572 error gyp info spawn args   'msvs',
1572 error gyp info spawn args   '-I',
1572 error gyp info spawn args   'D:\\work\\withthegrid\\platform\\node_modules\\sharp\\build\\config.gypi',
1572 error gyp info spawn args   '-I',
1572 error gyp info spawn args   'C:\\Users\\kzawo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
1572 error gyp info spawn args   '-I',
1572 error gyp info spawn args   'C:\\Users\\kzawo\\AppData\\Local\\node-gyp\\Cache\\14.15.3\\include\\node\\common.gypi',
1572 error gyp info spawn args   '-Dlibrary=shared_library',
1572 error gyp info spawn args   '-Dvisibility=default',
1572 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kzawo\\AppData\\Local\\node-gyp\\Cache\\14.15.3',
1572 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\kzawo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
1572 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\kzawo\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.3\\\\<(target_arch)\\\\node.lib',
1572 error gyp info spawn args   '-Dmodule_root_dir=D:\\work\\withthegrid\\platform\\node_modules\\sharp',
1572 error gyp info spawn args   '-Dnode_engine=v8',
1572 error gyp info spawn args   '--depth=.',
1572 error gyp info spawn args   '--no-parallel',
1572 error gyp info spawn args   '--generator-output',
1572 error gyp info spawn args   'D:\\work\\withthegrid\\platform\\node_modules\\sharp\\build',
1572 error gyp info spawn args   '-Goutput_dir=.'
1572 error gyp info spawn args ]
1572 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
1572 error gyp info spawn args [
1572 error gyp info spawn args   'build/binding.sln',
1572 error gyp info spawn args   '/clp:Verbosity=minimal',
1572 error gyp info spawn args   '/nologo',
1572 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
1572 error gyp info spawn args ]
1572 error gyp ERR! build error
1572 error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
1572 error gyp ERR! stack     at ChildProcess.onExit (C:\Users\kzawo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
1572 error gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
1572 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
1572 error gyp ERR! System Windows_NT 10.0.19042
1572 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kzawo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
1572 error gyp ERR! cwd D:\work\withthegrid\platform\node_modules\sharp
1572 error gyp ERR! node -v v14.15.3
1572 error gyp ERR! node-gyp -v v7.1.2
1572 error gyp ERR! not ok
1573 verbose exit 1
```

**Comment by yarsky-tgz** [comment]
We are using npm v7.12.1

**Comment by yarsky-tgz** [comment]
![image](https://user-images.githubusercontent.com/11916002/118011134-59cc7e80-b358-11eb-90c5-e97260c57257.png)

**Comment by lovell** [comment]
> [Error: EBUSY: resource busy or locked, rmdir 'D:\work\withthegrid\platform\node_modules\isolated-vm'] {

This would appear to be the salient error. `isolated-vm` is not a dependency of sharp. Perhaps delete the `D:\work\withthegrid\platform\node_modules` directory and try again.

If you're still having problems, please include the complete output of running `npm install --verbose sharp` in an empty directory.

**Comment by yarsky-tgz** [comment]
@lovell that's not actual problem, this error message is unrelated and can be understood as warning, I think.

`1571 error D:\work\withthegrid\platform\node_modules\sharp\src\libvips\cplusplus\VError.cpp(33,10): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or directory [D:\work\withthegrid\platform\node_modules\sharp\build\libvips-cpp.vcxproj]`

here is the actual problem, which breaks build of `sharp`

**Comment by lovell** [comment]
If you're still having problems, please include the complete output of running `npm install --verbose sharp` in an empty directory.

**Comment by Mistic92** [comment]
It's not working on node 14 and node 16:/

```
npm timing command:install Completed in 12888ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.28.2
npm verb cwd <PROJECT_PATH>
npm verb Linux 4.19.84-microsoft-standard
npm verb argv "/root/.nvm/versions/node/v14.14.0/bin/node" "/root/.nvm/versions/node/v14.14.0/bin/npm" "install" "--verbose" "sharp"
npm verb node v14.14.0
npm verb npm  v7.9.0
npm ERR! code 1
npm ERR! path <PROJECT_PATH>/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '<PROJECT_PATH>/node_modules/sharp/build'
npm ERR!   cc -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/root/.cache/node-gyp/14.14.0/include/node -I/root/.cache/node-gyp/14.14.0/src -I/root/.cache/node-gyp/14.14.0/deps/openssl/config -I/root/.cache/node-gyp/14.14.0/deps/openssl/openssl/include -I/root/.cache/node-gyp/14.14.0/deps/uv/include -I/root/.cache/node-gyp/14.14.0/deps/zlib -I/root/.cache/node-gyp/14.14.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c
npm ERR!   rm -f Release/obj.target/../node-addon-api/nothing.a && ar crs Release/obj.target/../node-addon-api/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   ln -f "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a" 2>/dev/null || (rm -rf "Release/nothing.a" && cp -af "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a")
npm ERR!   touch Release/obj.target/libvips-cpp.stamp
npm ERR!   g++ -o Release/obj.target/sharp/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/root/.cache/node-gyp/14.14.0/include/node -I/root/.cache/node-gyp/14.14.0/src -I/root/.cache/node-gyp/14.14.0/deps/openssl/config -I/root/.cache/node-gyp/14.14.0/deps/openssl/openssl/include -I/root/.cache/node-gyp/14.14.0/deps/uv/include -I/root/.cache/node-gyp/14.14.0/deps/zlib -I/root/.cache/node-gyp/14.14.0/deps/v8/include -I../../node-addon-api -I<PROJECT_PATH>/node_modules/sharp/vendor/8.10.6/include -I<PROJECT_PATH>/node_modules/sharp/vendor/8.10.6/include/glib-2.0 -I<PROJECT_PATH>/node_modules/sharp/vendor/8.10.6/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c
npm ERR! make: Leaving directory '<PROJECT_PATH>/node_modules/sharp/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/root/.nvm/versions/node/v14.14.0/bin/node',
npm ERR! gyp verb cli   '/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.14.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.8.5"
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 14.14.0
npm ERR! gyp verb command install [ '14.14.0' ]
npm ERR! gyp verb install input version string "14.14.0"
npm ERR! gyp verb install installing version: 14.14.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 14.14.0
npm ERR! gyp verb build dir attempting to create "build" dir: <PROJECT_PATH>/node_modules/sharp/build
npm ERR! gyp verb build dir "build" dir needed to be created? <PROJECT_PATH>/node_modules/sharp/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: <PROJECT_PATH>/node_modules/sharp/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: <PROJECT_PATH>/node_modules/sharp/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: <PROJECT_PATH>/node_modules/sharp/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '<PROJECT_PATH>/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=<PROJECT_PATH>/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir /root/.cache/node-gyp/14.14.0
npm ERR! gyp verb `which` succeeded for `make` /usr/bin/make
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
npm ERR!    24 | #include <vips/vips8>
npm ERR!       |          ^~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 4.19.84-microsoft-standard
npm ERR! gyp ERR! command "/root/.nvm/versions/node/v14.14.0/bin/node" "/root/.nvm/versions/node/v14.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd <PROJECT_PATH>/node_modules/sharp
npm ERR! gyp ERR! node -v v14.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 13162ms
npm verb code 1
```

**Comment by lovell** [comment]
@Mistic92 Please see https://sharp.pixelplumbing.com/install#common-problems and if you're still having problems, please open a new installation issue and answer all of the questions.

**Comment by yarsky-tgz** [comment]
> It's not working on node 14 and node 16:/
> 
> ```
> npm ERR! ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
> npm ERR!    24 | #include <vips/vips8>
> npm ERR!       |          ^~~~~~~~~~~~
> npm ERR! compilation terminated.
> npm ERR! make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
> ```

I had exactly same problem with npm v7 and `0.28.1` version on Mac OS, but recently released version `0.28.2` installs there well.

This topic started with problem on Windows 10, which my colleague has. We were clearing `node_modules`, using latest version of package.

@lovell I've asked already her to launch requested command at empty directory, waiting soon with results.

**Comment by Mistic92** [comment]
Version 0.27.2 is working ok. But 0.28.x is not.

**Comment by lovell** [comment]
@Mistic92 If you're still having problems, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions.

**Comment by KZavorotna** [comment]
> npm install --verbose sharp

@yarsky-tgz @lovell
Hi!
Here's the full output:
[output.txt](https://github.com/lovell/sharp/files/6472337/output.txt)

**Comment by lovell** [comment]
@KZavorotna Thank you, this log suggests you were able to install sharp successfully, which suggests the original problem might be caused by another dependency or perhaps relate to filesystem permissions.

> sharp: Using cached C:\Users\kzawo\AppData\Roaming\npm-cache\_libvips\libvips-8.10.6-win32-x64.tar.br
sharp: Creating C:\Users\kzawo\OneDrive\Документи\ShareX\Screenshots\2021-05\New folder\node_modules\sharp\build\Release
sharp: Copying DLLs from C:\Users\kzawo\OneDrive\Документи\ShareX\Screenshots\2021-05\New folder\node_modules\sharp\vendor\8.10.6\lib to C:\Users\kzawo\OneDrive\Документи\ShareX\Screenshots\2021-05\New folder\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 6.1.2
prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.28.2-napi-v3-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\kzawo\AppData\Roaming\npm-cache\_prebuilds\510ec4-sharp-v0.28.2-napi-v3-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\kzawo\AppData\Roaming\npm-cache\_prebuilds\510ec4-sharp-v0.28.2-napi-v3-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\kzawo\OneDrive\Документи\ShareX\Screenshots\2021-05\New folder\node_modules\sharp\build\Release\sharp.node
prebuild-install info install Successfully installed prebuilt binary!

**Comment by yarsky-tgz** [comment]
@lovell Seems that problem gone away after updating npm from `7.11` to `7.12`. Everything installs without problems now
