### ISSUE TITLE
Image to composite must have same dimensions or smaller

### ISSUE THREAD

**Issue by 82318179** [lovell/sharp#2728]
err: [Error: Image to composite must have same dimensions or smaller]
err: Error: Invalid input
    at Sharp (C:\Users\12179\Desktop\elect\electron-fullpagecapture\node_modules\sharp\lib\constructor.js:158:11)
    at C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:108:11
    at async C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:107:16
    at async C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:107:16
    at async FullPageCapture.mergeImage (C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:96:20)
err: Error: Invalid input
    at Sharp (C:\Users\12179\Desktop\elect\electron-fullpagecapture\node_modules\sharp\lib\constructor.js:158:11)
    at C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:108:11
    at async C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:107:16
    at async FullPageCapture.mergeImage (C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:96:20)
(node:2848) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (fs.js:1436:5)
    at FullPageCapture.mergeImage (C:\Users\12179\Desktop\elect\electron-fullpagecapture\fullpagecapture.js:118:8)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:2848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not 
handled will terminate the Node.js process with a non-zero exit code.

**Comment by lovell** [comment]
Are you able to provide a minimal, standalone code sample that demonstrates this question?

Are you able to provide a sample image that helps explain the question?

**Comment by lovell** [comment]
@82318179 Were you able to make any progress with this? If you still require help, please can you provide the requested information.

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.
