### ISSUE TITLE
Python 3.9 build error

### ISSUE THREAD

**Issue by martadinata666** [lovell/sharp#2730]
Error at using npm install sharp on python 3.9
```
#16 299.7 npm ERR! sharp: Detected globally-installed libvips v8.10.6
#16 299.7 npm ERR! sharp: Building from source via node-gyp
#16 299.7 npm ERR! gyp info it worked if it ends with ok
#16 299.7 npm ERR! gyp info using node-gyp@3.8.0
#16 299.7 npm ERR! gyp info using node@14.16.1 | linux | x64
#16 299.7 npm ERR! gyp ERR! configure error 
#16 299.8 npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
#16 299.8 npm ERR! gyp ERR! stack   File "<string>", line 1
#16 299.8 npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
#16 299.8 npm ERR! gyp ERR! stack                       ^
#16 299.8 npm ERR! gyp ERR! stack SyntaxError: invalid syntax
#16 299.8 npm ERR! gyp ERR! stack 
#16 299.8 npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
#16 299.8 npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
#16 299.8 npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
#16 299.8 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
#16 299.8 npm ERR! gyp ERR! System Linux 4.19.78-coreos
```

Environment:
- Docker 20.10.6
- Debian Sid (Docker)
- Python 3.9

Work on python 3.8

**Comment by lovell** [comment]
> #16 299.7 npm ERR! gyp info using node-gyp@3.8.0

`node-gyp` v3.8.0 is from 2018, which predates Python 3.9.

Node.js 14 provides `node-gyp` v5.x.x, so it looks like you've explicitly chosen to use an older version.

Please can you try updating `node-gyp`.
