### ISSUE TITLE
sharp: Installation error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by vermavarun** [lovell/sharp#2751]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
NA

If you are using npm v7, does the user running `npm install` own the directory it is run in?
NA

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
Yes

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```
C:\Users\varun.verma\Desktop\test>npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.13
npm info using node@v14.17.0
npm verb npm-session 0a5e6893373ec828
npm http fetch GET 304 https://registry.npmjs.org/sharp 358ms (from cache)
npm timing stage:loadCurrentTree Completed in 2773ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 21ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 620ms
npm http fetch GET 304 https://registry.npmjs.org/color 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 147ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 231ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 233ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 245ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 243ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 245ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 73ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 92ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 137ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 142ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 146ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 153ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 220ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 111ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 120ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 130ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 131ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 112ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/has-unicode 27ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 124ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 126ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 114ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fsevents 79ms (from cache)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5802ms
npm timing stage:loadIdealTree Completed in 7112ms
npm timing stage:generateActionsToTake Completed in 130ms
npm verb correctMkdir C:\Users\varun.verma\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\varun.verma\AppData\Roaming\npm-cache\_locks\staging-9c66ff8f2804a2ba.lock for C:\Users\varun.verma\Desktop\test\node_modules\.staging
npm timing action:extract Completed in 283ms
npm timing action:finalize Completed in 170ms
npm timing action:refresh-package-json Completed in 121ms
npm info lifecycle aproba@1.2.0~preinstall: aproba@1.2.0
npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
npm info lifecycle string_decoder@1.1.1~preinstall: string_decoder@1.1.1
npm info lifecycle readable-stream@2.3.7~preinstall: readable-stream@2.3.7
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle code-point-at@1.1.0~preinstall: code-point-at@1.1.0
npm info lifecycle console-control-strings@1.1.0~preinstall: console-control-strings@1.1.0
npm info lifecycle delegates@1.0.0~preinstall: delegates@1.0.0
npm info lifecycle are-we-there-yet@1.1.5~preinstall: are-we-there-yet@1.1.5
npm info lifecycle detect-libc@1.0.3~preinstall: detect-libc@1.0.3
npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle ansi-regex@2.1.1~preinstall: ansi-regex@2.1.1
npm info lifecycle strip-ansi@3.0.1~preinstall: strip-ansi@3.0.1
npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
npm info lifecycle has-unicode@2.0.1~preinstall: has-unicode@2.0.1
npm info lifecycle mkdirp-classic@0.5.3~preinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~preinstall: napi-build-utils@1.0.2
npm info lifecycle semver@5.7.1~preinstall: semver@5.7.1
npm info lifecycle node-abi@2.30.0~preinstall: node-abi@2.30.0
npm info lifecycle number-is-nan@1.0.1~preinstall: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~preinstall: is-fullwidth-code-point@1.0.0
npm info lifecycle string-width@1.0.2~preinstall: string-width@1.0.2
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle mimic-response@2.1.0~preinstall: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~preinstall: decompress-response@4.2.1
npm info lifecycle simple-get@3.1.0~preinstall: simple-get@3.1.0
npm info lifecycle is-arrayish@0.3.2~preinstall: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~preinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~preinstall: color-string@1.5.5
npm info lifecycle tar-stream@2.2.0~preinstall: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~preinstall: tar-fs@2.1.1
npm info lifecycle tunnel-agent@0.6.0~preinstall: tunnel-agent@0.6.0
npm info lifecycle ansi-regex@3.0.0~preinstall: ansi-regex@3.0.0
npm info lifecycle is-fullwidth-code-point@2.0.0~preinstall: is-fullwidth-code-point@2.0.0
npm info lifecycle strip-ansi@4.0.0~preinstall: strip-ansi@4.0.0
npm info lifecycle string-width@2.1.1~preinstall: string-width@2.1.1
npm info lifecycle wide-align@1.1.3~preinstall: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~preinstall: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~preinstall: npmlog@4.1.2
npm info lifecycle color@3.1.3~preinstall: color@3.1.3
npm info lifecycle node-addon-api@3.2.1~preinstall: node-addon-api@3.2.1
npm info lifecycle prebuild-install@6.1.3~preinstall: prebuild-install@6.1.3
npm info lifecycle sharp@0.28.3~preinstall: sharp@0.28.3
npm timing action:preinstall Completed in 37ms
npm info linkStuff aproba@1.2.0
npm info linkStuff isarray@1.0.0
npm info linkStuff string_decoder@1.1.1
npm info linkStuff readable-stream@2.3.7
npm info linkStuff chownr@1.1.4
npm info linkStuff code-point-at@1.1.0
npm info linkStuff console-control-strings@1.1.0
npm info linkStuff delegates@1.0.0
npm info linkStuff are-we-there-yet@1.1.5
npm info linkStuff detect-libc@1.0.3
npm verb linkBins [
npm verb linkBins   { 'detect-libc': 'bin/detect-libc.js' },
npm verb linkBins   'C:\\Users\\varun.verma\\Desktop\\test\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff expand-template@2.0.3
npm info linkStuff fs-constants@1.0.0
npm info linkStuff ansi-regex@2.1.1
npm info linkStuff strip-ansi@3.0.1
npm info linkStuff github-from-package@0.0.0
npm info linkStuff has-unicode@2.0.1
npm info linkStuff mkdirp-classic@0.5.3
npm info linkStuff napi-build-utils@1.0.2
npm info linkStuff semver@5.7.1
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver' },
npm verb linkBins   'C:\\Users\\varun.verma\\Desktop\\test\\node_modules\\node-abi\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff node-abi@2.30.0
npm info linkStuff number-is-nan@1.0.1
npm info linkStuff is-fullwidth-code-point@1.0.0
npm info linkStuff string-width@1.0.2
npm info linkStuff simple-concat@1.0.1
npm info linkStuff mimic-response@2.1.0
npm info linkStuff decompress-response@4.2.1
npm info linkStuff simple-get@3.1.0
npm info linkStuff is-arrayish@0.3.2
npm info linkStuff simple-swizzle@0.2.2
npm info linkStuff color-string@1.5.5
npm info linkStuff tar-stream@2.2.0
npm info linkStuff tar-fs@2.1.1
npm info linkStuff tunnel-agent@0.6.0
npm info linkStuff ansi-regex@3.0.0
npm info linkStuff is-fullwidth-code-point@2.0.0
npm info linkStuff strip-ansi@4.0.0
npm info linkStuff string-width@2.1.1
npm info linkStuff wide-align@1.1.3
npm info linkStuff gauge@2.7.4
npm info linkStuff npmlog@4.1.2
npm info linkStuff color@3.1.3
npm info linkStuff node-addon-api@3.2.1
npm info linkStuff prebuild-install@6.1.3
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   'C:\\Users\\varun.verma\\Desktop\\test\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff sharp@0.28.3
npm timing action:build Completed in 60ms
npm info lifecycle aproba@1.2.0~install: aproba@1.2.0
npm info lifecycle isarray@1.0.0~install: isarray@1.0.0
npm info lifecycle string_decoder@1.1.1~install: string_decoder@1.1.1
npm info lifecycle readable-stream@2.3.7~install: readable-stream@2.3.7
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle code-point-at@1.1.0~install: code-point-at@1.1.0
npm info lifecycle console-control-strings@1.1.0~install: console-control-strings@1.1.0
npm info lifecycle delegates@1.0.0~install: delegates@1.0.0
npm info lifecycle are-we-there-yet@1.1.5~install: are-we-there-yet@1.1.5
npm info lifecycle detect-libc@1.0.3~install: detect-libc@1.0.3
npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle ansi-regex@2.1.1~install: ansi-regex@2.1.1
npm info lifecycle strip-ansi@3.0.1~install: strip-ansi@3.0.1
npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
npm info lifecycle has-unicode@2.0.1~install: has-unicode@2.0.1
npm info lifecycle mkdirp-classic@0.5.3~install: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~install: napi-build-utils@1.0.2
npm info lifecycle semver@5.7.1~install: semver@5.7.1
npm info lifecycle node-abi@2.30.0~install: node-abi@2.30.0
npm info lifecycle number-is-nan@1.0.1~install: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~install: is-fullwidth-code-point@1.0.0
npm info lifecycle string-width@1.0.2~install: string-width@1.0.2
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle mimic-response@2.1.0~install: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~install: decompress-response@4.2.1
npm info lifecycle simple-get@3.1.0~install: simple-get@3.1.0
npm info lifecycle is-arrayish@0.3.2~install: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~install: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~install: color-string@1.5.5
npm info lifecycle tar-stream@2.2.0~install: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~install: tar-fs@2.1.1
npm info lifecycle tunnel-agent@0.6.0~install: tunnel-agent@0.6.0
npm info lifecycle ansi-regex@3.0.0~install: ansi-regex@3.0.0
npm info lifecycle is-fullwidth-code-point@2.0.0~install: is-fullwidth-code-point@2.0.0
npm info lifecycle strip-ansi@4.0.0~install: strip-ansi@4.0.0
npm info lifecycle string-width@2.1.1~install: string-width@2.1.1
npm info lifecycle wide-align@1.1.3~install: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~install: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~install: npmlog@4.1.2
npm info lifecycle color@3.1.3~install: color@3.1.3
npm info lifecycle node-addon-api@3.2.1~install: node-addon-api@3.2.1
npm info lifecycle prebuild-install@6.1.3~install: prebuild-install@6.1.3
npm info lifecycle sharp@0.28.3~install: sharp@0.28.3

> sharp@0.28.3 install C:\Users\varun.verma\Desktop\test\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-win32-x64.tar.br
sharp: Installation error: unable to get local issuer certificate
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm verb lifecycle sharp@0.28.3~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.28.3~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\varun.verma\Desktop\test\node_modules\sharp\node_modules\.bin;C:\Users\varun.verma\Desktop\test\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\1E\Client\Extensibility\NomadBranch;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\varun.verma\AppData\Local\Microsoft\WindowsApps;C:\Users\varun.verma\AppData\Roaming\npm;C:\Users\varun.verma\.dotnet\tools
npm verb lifecycle sharp@0.28.3~install: CWD: C:\Users\varun.verma\Desktop\test\node_modules\sharp
npm timing audit submit Completed in 879ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 879ms
npm timing audit body Completed in 1ms
npm info lifecycle sharp@0.28.3~install: Failed to exec install script
npm timing action:install Completed in 669ms
npm verb unlock done using C:\Users\varun.verma\AppData\Roaming\npm-cache\_locks\staging-9c66ff8f2804a2ba.lock for C:\Users\varun.verma\Desktop\test\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 95ms
npm timing stage:runTopLevelLifecycles Completed in 11980ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN eslint-config-react-app@6.0.0 requires a peer of babel-eslint@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN express-graphql@0.9.0 requires a peer of graphql@^14.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-offline@3.10.2 requires a peer of gatsby@^2.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-react-helmet@3.10.0 requires a peer of gatsby@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-react-helmet@3.10.0 requires a peer of react-helmet@^5.1.3 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-styled-components@3.10.0 requires a peer of babel-plugin-styled-components@>1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-styled-components@3.10.0 requires a peer of gatsby@^2.0.32 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-styled-components@3.10.0 requires a peer of styled-components@>=2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-remark-autolink-headers@2.11.0 requires a peer of gatsby@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-remark-images@3.11.1 requires a peer of gatsby@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-remark-images@3.11.1 requires a peer of gatsby-plugin-sharp@^2.0.0-beta.5 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-source-filesystem@2.11.1 requires a peer of gatsby@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-transformer-remark@2.16.1 requires a peer of gatsby@^2.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-node@9.1.1 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm verb stack Error: sharp@0.28.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:376:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:376:20)
npm verb stack     at maybeClose (internal/child_process.js:1055:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.28.3
npm verb cwd C:\Users\varun.verma\Desktop\test
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
npm verb node v14.17.0
npm verb npm  v6.14.13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.28.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.28.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 13644ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\varun.verma\AppData\Roaming\npm-cache\_logs\2021-06-10T15_52_41_454Z-debug.log
```

C:\Users\varun.verma\Desktop\test>

What is the output of running `npx envinfo --binaries --system`?

C:\Users\varun.verma\Desktop\test>npx envinfo --binaries --system

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 7.72 GB / 15.78 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
Please see #1618

**Comment by vermavarun** [comment]
@lovell , Still the same issue

```
PS C:\Users\varun.verma\Desktop\test> npm i sharp
npm ERR! path C:\Users\varun.verma\Desktop\test\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\varun.verma\AppData\Local\npm-cache\_logs\2021-06-11T06_30_24_392Z-debug.log
PS C:\Users\varun.verma\Desktop\test> npm config get
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\varun.verma\\AppData\\Roaming\\npm"

; "user" config from C:\Users\varun.verma\.npmrc

cafile = "C:\\Program Files\\Git\\usr\\bin\\cert.pem"
NODE_EXTRA_CA_CERTS = "C:\\Program Files\\Git\\usr\\bin\\cert.pem"
python = "C:\\Python27\\python.exe"
registry = "https://registry.npmjs.org/"
strict-ssl = false

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\varun.verma\Desktop\test
; HOME = C:\Users\varun.verma
; Run `npm config ls -l` to show all defaults.
PS C:\Users\varun.verma\Desktop\test>
```

**Comment by vermavarun** [comment]
[https://forums.couchbase.com/t/prebuild-install-warn-install-unable-to-get-local-issuer-certificate/29681](url) worked!
We can close the issue
