### ISSUE TITLE
Error installing on darwin-arm64

### ISSUE THREAD

**Issue by controversial** [lovell/sharp#2757]
**Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?**
 Yes

**Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?**
Yes

**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**
Yes

**If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?**
N/A

**If you are using npm v7, does the user running `npm install` own the directory it is run in?**
Yes

**If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?**
N/A

**What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?**
The meaningful error I see is some kind of internal node error related to applying the libtool regular expression. [Similar](https://github.com/nodejs/node-gyp/issues/2121) [node-gyp](https://github.com/libxmljs/libxmljs/issues/469) [issues](https://stackoverflow.com/questions/52987586/if-not-libtool-re-matchline-and-not-libtool-re5-matchline-typeerror-cannot) suggest that the issue is solved by installing Python 2, but these predate Python 3 support in `node-gyp`.

```
❯ npm i sharp
npm ERR! code 1
npm ERR! path /Users/luke/Developer/project/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Using cached /Users/luke/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.3.0 | darwin | arm64
npm ERR! (node:99247) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/luke/Developer/project/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/luke/Developer/project/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/luke/Developer/project/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/luke/.node-gyp/16.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/luke/.node-gyp/16.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/luke/Developer/project/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/luke/.node-gyp/16.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/luke/Developer/project/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/luke/Developer/project/node_modules/sharp/build/./gyp-mac-tool", line 611, in <module>
npm ERR!     sys.exit(main(sys.argv[1:]))
npm ERR!   File "/Users/luke/Developer/project/node_modules/sharp/build/./gyp-mac-tool", line 28, in main
npm ERR!     exit_code = executor.Dispatch(args)
npm ERR!   File "/Users/luke/Developer/project/node_modules/sharp/build/./gyp-mac-tool", line 43, in Dispatch
npm ERR!     return getattr(self, method)(*args[1:])
npm ERR!   File "/Users/luke/Developer/project/node_modules/sharp/build/./gyp-mac-tool", line 246, in ExecFilterLibtool
npm ERR!     if not libtool_re.match(line) and not libtool_re5.match(line):
npm ERR! TypeError: cannot use a string pattern on a bytes-like object
npm ERR! make: *** [Release/nothing.a] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/luke/Developer/project/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.0.0
npm ERR! gyp ERR! command "/Users/luke/.nvm/versions/node/v16.3.0/bin/node" "/Users/luke/Developer/project/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/luke/Developer/project/node_modules/sharp
npm ERR! gyp ERR! node -v v16.3.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
```

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 12.0
    CPU: (8) arm64 Apple M1
    Memory: 162.64 MB / 16.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
```

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/install#apple-m1

> npm ERR! gyp info using node-gyp@3.8.0

It also looks like you've got a really old version of `node-gyp` installed globally; the version provided by Node.js 16 is v6.1.0.

**Comment by controversial** [comment]
That's weird, I thought I had run `npm i -g node-gyp`. Today it seems to have resolved itself after I updated xcode, node-gyp, and all the dependencies in my `package.json`. Thanks for your help!
