### ISSUE TITLE
Electron app says Sharp did not install correctly when calling methods

### ISSUE THREAD

**Issue by Eric-Gonzalez-Portfolio** [lovell/sharp#2773]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Version being used is the most recent one (both above commands match in version output): V0.28.3

What are the steps to reproduce?

In a new electron project:

1. Install Sharp with npm install sharp
2. Place provided code sample index.html
3. Create a new folder called images and place a JPEG file into it
4. Run npm start
5. Press the "Click to run Sharp test" button and check the Electron console log

What is the expected behaviour?

Image should be modified and a new output file generated. Instead, the Electron console throws an error saying that sharp did not install correctly, though the app does compile. Error message is only thrown when the button is pressed calling the Sharp methods.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

index.html:

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sharp Test</title>
    <link rel="stylesheet" href="index.css">
  </head>
  <body>
    <h1>💖</h1>
    <button id="sharp-test-button">Click to run Sharp test</button>
    <p></p>
    <div class="column" id="main-view">
      <br /><img id="main-img"><br />
    </div>

    <script>
      const fetch = require("node-fetch");
      const { v4: uuidv4 } = require('uuid');
      // https://chrisfrew.in/blog/saving-images-in-node-js-using-fetch-with-array-buffer-and-buffer/
      async function savePhotoFromURL(photo_url) {
        const response = await fetch(photo_url);
        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        return buffer;
      }

      var filename = "bigger.jpg";
      var image_path = `images/${filename}`;
      const homeDir = require('os').homedir();
      const desktopDir = `${homeDir}/Desktop`;
      async function runSharpTest() {
        console.log('(running sharp)');
        const Sharp = require('../node_modules/sharp');
        const fs = require('fs');

        //get the original image path
        var width = 6000;
        var height = 4000;

        // cover: (default) Preserving aspect ratio, ensure the image covers both provided dimensions by cropping/clipping to fit.
        //         contain: Preserving aspect ratio, contain within both provided dimensions using "letterboxing" where necessary.
        //         fill: Ignore the aspect ratio of the input and stretch to both provided dimensions.
        //         inside: Preserving aspect ratio, resize the image to be as large as possible while ensuring its dimensions are less than or equal to both those specified.
        //         outside: Preserving aspect ratio, resize the image to be as small as possible while ensuring its dimensions are greater than or equal to both those specified.
        var crop = "cover";
        var quality = 60;
        var format = "webp";
        var photo_url = "https://picsum.photos/200/300"
        var random_uuid = uuidv4();

        var obj = await savePhotoFromURL(photo_url);
        var out_file = Sharp(obj)
                // .resize(width, height, {
                //   fit: crop,
                //   position: 'right top',
                //   background: { r: 255, g: 0, b: 255, alpha: 0.5 }
                // })

                .toFormat(format, {
                  quality: parseInt(quality)
                })

                //srgb, rgb, cmyk, lab, b-w, rgb16
                // .toColourspace('b-w')

                // .raw()

                // .tile({
                //   size: 512
                // })

                .toBuffer()

                .then(data => {
                  fs.writeFileSync(`${desktopDir}/${random_uuid}.${format}`, data);
                  document.getElementById("main-img").src = `${desktopDir}/${random_uuid}.${format}`;
                })
                .catch(err => { console.log(err)});

        //   //create the stream — so basically read the path
      //   // const stream = fs.createReadStream(image_path);
      //   //transform the image based on our variable, then output using the quality
      //   const transform = Sharp().resize(width, height, {
      //     fit: crop
      //   }).toFormat(format, {
      //     quality: parseInt(quality)
      //   });
      };
      document.getElementById("main-img").src = image_path;

      var sharp_test_button = document.getElementById('sharp-test-button');
      sharp_test_button.addEventListener('click', runSharpTest);

      // const { ipcRenderer } = require('electron');
      //
      // // Some data that will be sent to the main process
      // let Data = {
      //   message: "Hi",
      //   someData: "Let's go"
      // };
      //
      // // Send information to the main process
      // // if a listener has been set, then the main process
      // // will react to the request !
      // ipcRenderer.send('request-mainprocess-action', Data);

    </script>
  </body>
</html>

Are you able to provide a sample image that helps explain the problem?

![image](https://user-images.githubusercontent.com/35201416/123845787-76515580-d8c9-11eb-9d5a-0a6f6e14ca77.png)

What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 AMD Ryzen 3 3250U with Radeon Graphics
    Memory: 1.06 GB / 5.95 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

I am working on a desktop application on Windows using Electron and Sharp. The program compiles and works correctly on OS X, but always halts operations when used on Windows after one clicks the button to alter the image. The app does appear to initially compile correctly, the only time the error message is thrown is when running the test on an image. Any assistance you can provide regarding why the program throws this error when calling Sharp would be greatly appreciated.

Error message when button is clicked to run test:

index.html:32 (running sharp)
C:\Users\Eric\Electr…b\constructor.js:32 Uncaught (in promise) Error: 
Something went wrong installing the "sharp" module

\\?\C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\build\Release\sharp.node is not a valid Win32 application.
\\?\C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\Users\Eric\Electr…b\constructor.js:32)
    at Object.<anonymous> (C:\Users\Eric\Electr…\constructor.js:394)
    at Module._compile (internal/modules/cjs/loader.js:1078)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
(anonymous)	@	C:\Users\Eric\Electr…b\constructor.js:32
(anonymous)	@	C:\Users\Eric\Electr…\constructor.js:394
Module._compile	@	internal/modules/cjs/loader.js:1078
Module._extensions..js	@	internal/modules/cjs/loader.js:1108
Module.load	@	internal/modules/cjs/loader.js:935
Module._load	@	internal/modules/cjs/loader.js:776
f._load	@	electron/js2c/asar_bundle.js:5
o._load	@	electron/js2c/renderer_init.js:33
Module.require	@	internal/modules/cjs/loader.js:959
require	@	internal/modules/cjs/helpers.js:88
(anonymous)	@	C:\Users\Eric\Electr…harp\lib\index.js:3
(anonymous)	@	C:\Users\Eric\Electr…arp\lib\index.js:15
Module._compile	@	internal/modules/cjs/loader.js:1078
Module._extensions..js	@	internal/modules/cjs/loader.js:1108
Module.load	@	internal/modules/cjs/loader.js:935
Module._load	@	internal/modules/cjs/loader.js:776
f._load	@	electron/js2c/asar_bundle.js:5
o._load	@	electron/js2c/renderer_init.js:33
Module.require	@	internal/modules/cjs/loader.js:959
require	@	internal/modules/cjs/helpers.js:88
runSharpTest	@	index.html:33

Output of npm install --verbose sharp:

npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.13
npm info using node@v14.17.1
npm verb npm-session cb5268d38db96044
npm http fetch GET 304 https://registry.npmjs.org/sharp 708ms (from cache)
npm timing stage:loadCurrentTree Completed in 2608ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 12ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 742ms
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 230ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 378ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 391ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 392ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 421ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 99ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 84ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 129ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 75ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 171ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 184ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 209ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 213ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3103ms
npm timing stage:loadIdealTree Completed in 4137ms
npm timing stage:generateActionsToTake Completed in 111ms
npm verb correctMkdir C:\Users\Eric\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\Eric\AppData\Roaming\npm-cache\_locks\staging-0f29acb211732c9f.lock for C:\Users\Eric\Electron_Projects\mysharptest\node_modules\.staging
npm timing audit submit Completed in 445ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 448ms
npm timing audit body Completed in 18ms
npm timing action:extract Completed in 770ms
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from C:\Users\Eric\Electron_Projects\mysharptest\node_modules
npm verb unbuild rmStuff in C:\Users\Eric\Electron_Projects\mysharptest\node_modules\@malept\cross-spawn-promise\node_modules
npm info lifecycle undefined~postuninstall: undefined
npm timing action:unbuild Completed in 41ms
npm timing action:remove Completed in 29ms
npm timing action:finalize Completed in 249ms
npm timing action:refresh-package-json Completed in 217ms
npm info lifecycle color-name@1.1.3~preinstall: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~preinstall: color-convert@1.9.3
npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
npm info lifecycle mkdirp-classic@0.5.3~preinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~preinstall: napi-build-utils@1.0.2
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle mimic-response@2.1.0~preinstall: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~preinstall: decompress-response@4.2.1
npm info lifecycle simple-get@3.1.0~preinstall: simple-get@3.1.0
npm info lifecycle is-arrayish@0.3.2~preinstall: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~preinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~preinstall: color-string@1.5.5
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle tar-stream@2.2.0~preinstall: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~preinstall: tar-fs@2.1.1
npm info lifecycle color@3.1.3~preinstall: color@3.1.3
npm info lifecycle prebuild-install@6.1.3~preinstall: prebuild-install@6.1.3
npm info lifecycle node-addon-api@3.2.1~preinstall: node-addon-api@3.2.1
npm info lifecycle sharp@0.28.3~preinstall: sharp@0.28.3
npm timing action:preinstall Completed in 53ms
npm info linkStuff color-name@1.1.3
npm info linkStuff color-convert@1.9.3
npm info linkStuff expand-template@2.0.3
npm info linkStuff fs-constants@1.0.0
npm info linkStuff github-from-package@0.0.0
npm info linkStuff mkdirp-classic@0.5.3
npm info linkStuff napi-build-utils@1.0.2
npm info linkStuff simple-concat@1.0.1
npm info linkStuff mimic-response@2.1.0
npm info linkStuff decompress-response@4.2.1
npm info linkStuff simple-get@3.1.0
npm info linkStuff is-arrayish@0.3.2
npm info linkStuff simple-swizzle@0.2.2
npm info linkStuff color-string@1.5.5
npm info linkStuff readable-stream@3.6.0
npm info linkStuff tar-stream@2.2.0
npm info linkStuff tar-fs@2.1.1
npm info linkStuff color@3.1.3
npm info linkStuff prebuild-install@6.1.3
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   'C:\\Users\\Eric\\Electron_Projects\\mysharptest\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff node-addon-api@3.2.1
npm info linkStuff sharp@0.28.3
npm timing action:build Completed in 91ms
npm info lifecycle color-name@1.1.3~install: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~install: color-convert@1.9.3
npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
npm info lifecycle mkdirp-classic@0.5.3~install: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~install: napi-build-utils@1.0.2
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle mimic-response@2.1.0~install: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~install: decompress-response@4.2.1
npm info lifecycle simple-get@3.1.0~install: simple-get@3.1.0
npm info lifecycle is-arrayish@0.3.2~install: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~install: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~install: color-string@1.5.5
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle tar-stream@2.2.0~install: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~install: tar-fs@2.1.1
npm info lifecycle color@3.1.3~install: color@3.1.3
npm info lifecycle prebuild-install@6.1.3~install: prebuild-install@6.1.3
npm info lifecycle node-addon-api@3.2.1~install: node-addon-api@3.2.1
npm info lifecycle sharp@0.28.3~install: sharp@0.28.3

> sharp@0.28.3 install C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached C:\Users\Eric\AppData\Roaming\npm-cache\_libvips\libvips-8.10.6-win32-x64.tar.br
sharp: Creating C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\build\Release
sharp: Copying DLLs from C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\vendor\8.10.6\lib to C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 6.1.3
prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.28.3-napi-v3-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Eric\AppData\Roaming\npm-cache\_prebuilds\da1c59-sharp-v0.28.3-napi-v3-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Eric\AppData\Roaming\npm-cache\_prebuilds\da1c59-sharp-v0.28.3-napi-v3-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\build\Release\sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.28.3~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.28.3~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp\node_modules\.bin;C:\Users\Eric\Electron_Projects\mysharptest\node_modules\.bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.11-Q16-HDRI;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Users\Eric\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\Eric\Downloads\mongodb-shell-windows-x86_64-4.4.5\mongodb-win32-x86_64-windows-4.4.5\bin;C:\Program Files\nodejs\;C:\Users\Eric\AppData\Local\Microsoft\WindowsApps;C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Eric\AppData\Local\atom\bin;C:\Users\Eric\AppData\Local\Microsoft\WindowsApps;C:\Users\Eric\.dotnet\tools;C:\Users\Eric\AppData\Local\GitHubDesktop\bin;C:\Program Files\heroku\bin;C:\Program Files\PostgreSQL\13\bin;C:\Users\Eric\AppData\Local\gitkraken\bin;C:\Users\Eric\AppData\Roaming\Composer\vendor\bin;C:\Users\Eric\AppData\Roaming\npm
npm verb lifecycle sharp@0.28.3~install: CWD: C:\Users\Eric\Electron_Projects\mysharptest\node_modules\sharp
npm timing action:install Completed in 7158ms
npm info lifecycle color-name@1.1.3~postinstall: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~postinstall: color-convert@1.9.3
npm info lifecycle expand-template@2.0.3~postinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~postinstall: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~postinstall: github-from-package@0.0.0
npm info lifecycle mkdirp-classic@0.5.3~postinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~postinstall: napi-build-utils@1.0.2
npm info lifecycle simple-concat@1.0.1~postinstall: simple-concat@1.0.1
npm info lifecycle mimic-response@2.1.0~postinstall: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~postinstall: decompress-response@4.2.1
npm info lifecycle simple-get@3.1.0~postinstall: simple-get@3.1.0
npm info lifecycle is-arrayish@0.3.2~postinstall: is-arrayish@0.3.2
npm info lifecycle simple-swizzle@0.2.2~postinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.5~postinstall: color-string@1.5.5
npm info lifecycle readable-stream@3.6.0~postinstall: readable-stream@3.6.0
npm info lifecycle tar-stream@2.2.0~postinstall: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~postinstall: tar-fs@2.1.1
npm info lifecycle color@3.1.3~postinstall: color@3.1.3
npm info lifecycle prebuild-install@6.1.3~postinstall: prebuild-install@6.1.3
npm info lifecycle node-addon-api@3.2.1~postinstall: node-addon-api@3.2.1
npm info lifecycle sharp@0.28.3~postinstall: sharp@0.28.3
npm timing action:postinstall Completed in 52ms
npm verb unlock done using C:\Users\Eric\AppData\Roaming\npm-cache\_locks\staging-0f29acb211732c9f.lock for C:\Users\Eric\Electron_Projects\mysharptest\node_modules\.staging
npm timing stage:executeActions Completed in 8739ms
npm timing stage:rollbackFailedOptional Completed in 27ms
npm timing stage:runTopLevelLifecycles Completed in 15953ms
npm verb saving [ { name: 'sharp', spec: '^0.28.3', save: 'dependencies' } ]
npm info lifecycle mysharptest@1.0.0~preshrinkwrap: mysharptest@1.0.0
npm info lifecycle mysharptest@1.0.0~shrinkwrap: mysharptest@1.0.0
npm info lifecycle mysharptest@1.0.0~postshrinkwrap: mysharptest@1.0.0
npm WARN mysharptest@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@3.1.0 (node_modules\electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin,linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@3.3.0 (node_modules\electron-installer-redhat):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@3.3.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin,linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

+ sharp@0.28.3
added 21 packages from 171 contributors, removed 1 package and audited 532 packages in 16.697s

51 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 18202ms
npm info ok

**Comment by lovell** [comment]
> is not a valid Win32 application

Are you using the x64 Electron binaries (to match the x64 Node.js used at installation time)?

**Comment by Eric-Gonzalez-Portfolio** [comment]
I tried uninstalling and reinstalling Electron to specify that it was the x64 binaries. I ran npm install --arch=x64 electron --save-dev
Would this be correct? Or would it be a different command to ensure that the binaries are properly installed to match Sharp?

Upon reinstalling, the error message changed and no longer said that sharp was not a valid win32 application, but instead just said that the path to the Electron installation was not recognized.

**Comment by lovell** [comment]
The use of `npm install --arch=x64 electron` is correct according to https://www.electronjs.org/docs/tutorial/installation#customization

**Comment by Eric-Gonzalez-Portfolio** [comment]
I tried uninstalling and running npm install --arch=x64 electron, but I get an error message and Electron won't compile. Only npm install --arch=x64 electron --save-dev seems to work, but then the system still crashes when pressing the button.

Here is the error message when trying to run npm start after npm install --arch=x64 electron:

C:\Users\Eric\Electron_Projects\mysharptest>npm start

> mysharptest@1.0.0 start C:\Users\Eric\Electron_Projects\mysharptest
> electron-forge start

✔ Checking your system
✔ Locating Application

An unhandled rejection has occurred inside Forge:
Error: Could not find any Electron packages in devDependencies
    at getElectronModuleName (C:\Users\Eric\Electron_Projects\mysharptest\node_modules\@electron-forge\core\src\util\electron-version.ts:56:11)
    at getElectronVersion (C:\Users\Eric\Electron_Projects\mysharptest\node_modules\@electron-forge\core\src\util\electron-version.ts:92:23)
    at _default (C:\Users\Eric\Electron_Projects\mysharptest\node_modules\@electron-forge\core\src\api\start.ts:49:11)
    at C:\Users\Eric\Electron_Projects\mysharptest\node_modules\@electron-forge\cli\src\electron-forge-start.ts:58:19

Electron Forge was terminated. Location:
{}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mysharptest@1.0.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mysharptest@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eric\AppData\Roaming\npm-cache\_logs\2021-07-11T04_05_12_938Z-debug.log

**Comment by Eric-Gonzalez-Portfolio** [comment]
Any recommendations/updates on how to solve this issue?

**Comment by lovell** [comment]
A web search for `"Could not find any Electron packages in devDependencies"` reveals https://github.com/electron-userland/electron-forge/issues/1071

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.
