### ISSUE TITLE
Error: Something went wrong installing the "sharp" module (Apple M1 chip)

### ISSUE THREAD

**Issue by ChenLangChen** [lovell/sharp#2794]
It looks like I can install sharp with 'npm i', but it shows errors during 'gatsby develop'.
------------------------------------------------------------------
### npm i 
```shell
> sharp@0.27.2 install /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.11.2
info sharp Building from source via node-gyp
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/sharp.node
ld: warning: ignoring file /opt/homebrew/Cellar/vips/8.11.2/lib/libvips-cpp.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/vips/8.11.2/lib/libvips.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/glib/2.68.3/lib/libgobject-2.0.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/glib/2.68.3/lib/libglib-2.0.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/gettext/lib/libintl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint-plugin-react-hooks@1.x || 2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.2.1 requires a peer of eslint@>=1.6.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-sitemap@3.3.0 requires a peer of gatsby@^3.0.0-next.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-node@9.1.1 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

added 5 packages from 73 contributors and audited 2629 packages in 594.485s

217 packages are looking for funding
  run `npm fund` for details
```

### gatsby develop
```shell
warn Plugin gatsby-plugin-sitemap is not compatible with your gatsby version 2.32.13 - It requires gatsby@^3.0.0-next.0

 ERROR 

Error in "/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js":
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/constructor.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/index.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/safe-sharp.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/index.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/customize-schema.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/services/initialize.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/services/index.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/state-machines/develop/services.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/state-machines/develop/index.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/commands/develop-process.js
- /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/.cache/tmp-39940-azClAAVaD94d

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues




  Error: Something went wrong installing the "sharp" module
  Cannot find module '../build/Release/sharp.node'
  Require stack:
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/constructor.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/index.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/safe-sharp.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/index.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/customize-schema.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/services/initialize.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/services/index.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/state-machines/develop/services.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/state-machines/develop/index.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby/dist/commands/develop-process.js
  - /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/.cache/tmp-39940-azClAAVaD94d
  - Run "npm rebuild --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
  
  - constructor.js:34 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/[sharp]/lib/constructor.js:34:9
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/[sharp]/lib/index.js:3:15
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - safe-sharp.js:127 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/safe-sharp.js:127:11
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  

not finished load plugins - 9.853s
```

### npm rebuild --verbose sharp
```shell
npm info ok 
```
### Gatsby develop
```shell
Error in "/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js":
Something went wrong installing the "sharp" module

dlopen(/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp.n
ode, 1): Symbol not found: __ZTVN4vips7VOptionE
  Referenced from:
/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp.node
  Expected in: flat namespace
 in /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues




  Error: Something went wrong installing the "sharp" module
  dlopen(/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp
  .node, 1): Symbol not found: __ZTVN4vips7VOptionE
    Referenced from: /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/R
  elease/sharp.node
    Expected in: flat namespace
   in /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp.no
  de
  - Remove the "node_modules/sharp" directory then run
    "npm install --ignore-scripts=false --verbose" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
  
  - constructor.js:34 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/[sharp]/lib/constructor.js:34:9
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/[sharp]/lib/index.js:3:15
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - safe-sharp.js:127 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/safe-sharp.js:127:11
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  

not finished load plugins - 10.084s
```

**Comment by lovell** [comment]
Hi, the salient part of the above is:

> info sharp Detected globally-installed libvips v8.11.2

> ld: warning: ignoring file /opt/homebrew/Cellar/vips/8.11.2/lib/libvips-cpp.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

It looks like you are using a globally-installed libvips that was built for Intel x64 with Node.js that was built for ARM64:

You'll either need to use x64 Node.js, or remove the x64 libvips via `brew uninstall vips`.

**Comment by ChenLangChen** [comment]
Hi, after `brew uninstall vips` and deleting node_modules, I ran `npm install --ignore-scripts=false --verbose`. It showed the following error.
```shell
55231 verbose stack Error: sharp@0.27.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
55231 verbose stack Exit status 1
55231 verbose stack     at EventEmitter.<anonymous> (/Users/langchen/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
55231 verbose stack     at EventEmitter.emit (events.js:315:20)
55231 verbose stack     at ChildProcess.<anonymous> (/Users/langchen/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
55231 verbose stack     at ChildProcess.emit (events.js:315:20)
55231 verbose stack     at maybeClose (internal/child_process.js:1021:16)
55231 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
55232 verbose pkgid sharp@0.27.2
55233 verbose cwd /Users/langchen/Documents/WebDev/Fraser/fit_gatsby
55234 verbose Darwin 20.5.0
55235 verbose argv "/Users/langchen/.nvm/versions/node/v12.18.3/bin/node" "/Users/langchen/.nvm/versions/node/v12.18.3/bin/npm" "install" "--ignore-scripts=false" "--verbose"
55236 verbose node v12.18.3
55237 verbose npm  v6.14.6
55238 error code ELIFECYCLE
55239 error errno 1
55240 error sharp@0.27.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
55240 error Exit status 1
55241 error Failed at the sharp@0.27.2 install script.
55241 error This is probably not a problem with npm. There is likely additional logging output above.
55242 verbose exit [ 1, true ]
```

**Comment by rawpixel-vincent** [comment]
try to upgrade to the latest version of the sharp library, it looks like you are using `sharp@0.27.2`
with 0.28.3 it works fine for me on M1 with the pre-built binaries,
with 0.27.2 I have to pre-install libvips to make it works

**Comment by lovell** [comment]
Yes, please upgrade - see https://sharp.pixelplumbing.com/install#apple-m1

**Comment by ChenLangChen** [comment]
> try to upgrade to the latest version of the sharp library, it looks like you are using `sharp@0.27.2`
> with 0.28.3 it works fine for me on M1 with the pre-built binaries,
> with 0.27.2 I have to pre-install libvips to make it works

Could you please share how to upgrade to the latest version of the sharp library?

**Comment by rawpixel-vincent** [comment]
`npm install sharp@0.28.3 --save` @ChenLangChen

**Comment by lovell** [comment]
It looks like you're using Gatsby, so https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/ may also be helpful.

**Comment by ChenLangChen** [comment]
In a new Gatsby-V3 project, sharp@0.28.3 was successfully installed with `npm i`.
```shell
frasers-interview@0.1.0 /Users/langchen/Documents/WebDev/Fraser/fit_gatsby
├─┬ gatsby-plugin-manifest@3.9.0
│ └── sharp@0.28.3 
├─┬ gatsby-plugin-sharp@3.9.0
│ └── sharp@0.28.3  deduped
└─┬ gatsby-transformer-sharp@3.9.0
  └── sharp@0.28.3  deduped
```
However, with `gatsby develop`, the following error poped up again.
```shell
Error in
"/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js":

Something went wrong installing the "sharp" module

dlopen(/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node, 1):
 Symbol not found: __ZTVN4vips7VOptionE
  Referenced from:
/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node
  Expected in: flat namespace
 in /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues




  Error: Something went wrong installing the "sharp" module
  dlopen(/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node, 1
  ): Symbol not found: __ZTVN4vips7VOptionE
    Referenced from: /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/s
  harp.node
    Expected in: flat namespace
   in /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node
  - Remove the "node_modules/sharp" directory then run
    "npm install --ignore-scripts=false --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
  
  - constructor.js:32 Object.<anonymous>
    [fit_gatsby]/[sharp]/lib/constructor.js:32:9
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [fit_gatsby]/[sharp]/lib/index.js:3:15
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - safe-sharp.js:127 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/safe-sharp.js:127:11
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  

not finished open and validate gatsby-configs, load plugins - 13.490s
```

**Comment by lovell** [comment]
> Symbol not found: __ZTVN4vips7VOptionE

This suggests you might still have a globally-installed libvips. Perhaps try running `brew update && brew uninstall vips && brew upgrade`.

**Comment by ChenLangChen** [comment]
After `brew update && brew uninstall vips && brew upgrade`, similar error persisted. 
```shell
The following flags were automatically enabled on your site:
- DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on
full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds. See
 umbrella issue for how to update custom webpack config.

There are 3 other flags available that you might be interested in:
- FAST_DEV · Enable all experiments aimed at improving develop server start time
- PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't
delete the downloaded files cache when changing gatsby-node.js & gatsby-config.js files.
- PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) ·
Run all source plugins at the same time instead of serially. For sites with multiple source plugins, this
can speedup sourcing and transforming considerably.

warn Plugin gatsby-plugin-react-helmet is not compatible with your gatsby version 3.9.1 - It requires
gatsby@^2.0.0
warn Plugin gatsby-source-filesystem is not compatible with your gatsby version 3.9.1 - It requires
gatsby@^2.2.0
warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.9.1 - It requires
gatsby@^2.0.0
warn Plugin gatsby-plugin-react-helmet is not compatible with your gatsby version 3.9.1 - It requires
gatsby@^2.0.0
warn Plugin gatsby-source-filesystem is not compatible with your gatsby version 3.9.1 - It requires
gatsby@^2.2.0
warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.9.1 - It requires
gatsby@^2.0.0

 ERROR 

Error in
"/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js":

Something went wrong installing the "sharp" module

dlopen(/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node, 1):
 Symbol not found: __ZTVN4vips7VOptionE
  Referenced from:
/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node
  Expected in: flat namespace
 in /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues




  Error: Something went wrong installing the "sharp" module
  dlopen(/Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node, 1
  ): Symbol not found: __ZTVN4vips7VOptionE
    Referenced from: /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/s
  harp.node
    Expected in: flat namespace
   in /Users/langchen/Documents/WebDev/Fraser/fit_gatsby/node_modules/sharp/build/Release/sharp.node
  - Remove the "node_modules/sharp" directory then run
    "npm install --ignore-scripts=false --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
  
  - constructor.js:32 Object.<anonymous>
    [fit_gatsby]/[sharp]/lib/constructor.js:32:9
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [fit_gatsby]/[sharp]/lib/index.js:3:15
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32
  
  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - v8-compile-cache.js:159 require
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - safe-sharp.js:127 Object.<anonymous>
    [fit_gatsby]/[gatsby-plugin-sharp]/safe-sharp.js:127:11
  
  - v8-compile-cache.js:192 Module._compile
    [fit_gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  

not finished open and validate gatsby-configs, load plugins - 13.462s
```

**Comment by lovell** [comment]
What's the output of running `npm ls sharp && npm ls -g sharp`?

**Comment by ChenLangChen** [comment]
`npm ls sharp `
```shell
frasers-interview@0.1.0 /Users/langchen/Documents/WebDev/Fraser/fit_gatsby
├─┬ gatsby-plugin-manifest@3.9.0
│ └── sharp@0.28.3 
├─┬ gatsby-plugin-sharp@3.9.0
│ └── sharp@0.28.3  deduped
└─┬ gatsby-transformer-sharp@3.9.0
  └── sharp@0.28.3  deduped
```

`npm ls -g sharp `
```shell
/Users/langchen/.nvm/versions/node/v12.18.3/lib
└── (empty)
```

**Comment by lovell** [comment]
Thanks, this all looks OK.

Is it possible there could be multiple, conflicting versions and/or architectures of Node.js being used? Some versions of Node.js prior to 16 use Rosetta emulation on M1, which can cause the `Symbol not found: __ZTVN4vips7VOptionE` error - see #2588 for a previous example.

**Comment by ChenLangChen** [comment]
I'm not able to detect any conflicting architecture or version of Node.js, is there anything else I should check?
```shell
$ npx envinfo --binaries --system
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 140.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
```

```shell
$ node -p 'process.arch'
arm64
$ /usr/bin/uname -p
arm
```

**Comment by ChenLangChen** [comment]
> sharp v0.29.0 is now available and provides prebuilt M1-compatible binaries for libvips and sharp. Please can you try to upgrade.

Thanks so much for the effort, now it's finally working! 🎉🎉🎉

**Comment by NeoHBz** [comment]
I'm facing the same issue and I tried following most of the steps on other available posts with no success :( can i get some help please 

### npm start
`> ielts-backend@0.1.0 start /Users/neo/Workspace/ielts/backend
> strapi start

[2021-09-19T21:43:57.714Z] debug ⛔️ Server wasn't able to start properly.
[2021-09-19T21:43:57.714Z] error Error:
Something went wrong installing the "sharp" module

dlopen(/Users/neo/Workspace/ielts/backend/node_modules/strapi-plugin-upload/node_modules/sharp/build/Release/sharp.node, 0x0001): symbol not found in flat namespace '__ZTVN4vips7VOptionE'

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/neo/Workspace/ielts/backend/node_modules/strapi-plugin-upload/node_modules/sharp/lib/constructor.js:32:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/neo/Workspace/ielts/backend/node_modules/strapi-plugin-upload/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ielts-backend@0.1.0 start: `strapi start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ielts-backend@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/neo/.npm/_logs/2021-09-19T21_43_57_720Z-debug.log`

**Comment by lovell** [comment]
@NeoHBz Please open a new installation issue and answer all of the questions. https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&template=installation.md
