### ISSUE TITLE
Install failing in WSL on Windows

### ISSUE THREAD

**Issue by chasebank** [lovell/sharp#2795]
Installing from Windows Terminal ran as admin

Here's the first sign of trouble:
```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/chase/.cache/node-gyp/14.15.4
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/home/chase/.nvm/versions/node/v14.15.4/bin/node" "/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chase/dev/price-log-website/node_modules/sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

And here's the complete `--verbose` response
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/chase/.nvm/versions/node/v14.15.4/bin/node',
npm verb cli   '/home/chase/.nvm/versions/node/v14.15.4/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v14.15.4
npm verb npm-session faf1801f18764d06
npm http fetch GET 304 https://registry.npmjs.org/sharp 160ms (from cache)
npm timing stage:loadCurrentTree Completed in 1300ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 11ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 557ms
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 137ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 156ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/rc 10ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 107ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 116ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 139ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 37ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 53ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1790ms
npm timing stage:loadIdealTree Completed in 2579ms
npm timing stage:generateActionsToTake Completed in 83ms
npm verb correctMkdir /home/chase/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/chase/.npm/_locks/staging-9f52e8166511bad8.lock for /home/chase/dev/price-log-website/node_modules/.staging
npm timing action:extract Completed in 99ms
npm timing action:finalize Completed in 16ms
npm timing action:refresh-package-json Completed in 36ms
npm info lifecycle buffer@5.7.1~preinstall: buffer@5.7.1
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle bl@4.1.0~preinstall: bl@4.1.0
npm info lifecycle deep-extend@0.6.0~preinstall: deep-extend@0.6.0
npm info lifecycle detect-libc@1.0.3~preinstall: detect-libc@1.0.3
npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
npm info lifecycle mimic-response@2.1.0~preinstall: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~preinstall: decompress-response@4.2.1
npm info lifecycle mkdirp-classic@0.5.3~preinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~preinstall: napi-build-utils@1.0.2
npm info lifecycle node-abi@2.30.0~preinstall: node-abi@2.30.0
npm info lifecycle noop-logger@0.1.1~preinstall: noop-logger@0.1.1
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle yallist@4.0.0~preinstall: yallist@4.0.0
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle simple-get@3.1.0~preinstall: simple-get@3.1.0
npm info lifecycle strip-json-comments@2.0.1~preinstall: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.8~preinstall: rc@1.2.8
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle tar-stream@2.2.0~preinstall: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~preinstall: tar-fs@2.1.1
npm info lifecycle which-pm-runs@1.0.0~preinstall: which-pm-runs@1.0.0
npm info lifecycle prebuild-install@5.3.6~preinstall: prebuild-install@5.3.6
npm info lifecycle semver@6.3.0~preinstall: semver@6.3.0
npm info lifecycle tar@5.0.5~preinstall: tar@5.0.5
npm info lifecycle sharp@0.23.4~preinstall: sharp@0.23.4
npm timing action:preinstall Completed in 5ms
npm info linkStuff buffer@5.7.1
npm info linkStuff readable-stream@3.6.0
npm info linkStuff bl@4.1.0
npm info linkStuff deep-extend@0.6.0
npm info linkStuff detect-libc@1.0.3
npm verb linkBins [
npm verb linkBins   { 'detect-libc': 'bin/detect-libc.js' },
npm verb linkBins   '/home/chase/dev/price-log-website/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff expand-template@2.0.3
npm info linkStuff fs-constants@1.0.0
npm info linkStuff github-from-package@0.0.0
npm info linkStuff mimic-response@2.1.0
npm info linkStuff decompress-response@4.2.1
npm info linkStuff mkdirp-classic@0.5.3
npm info linkStuff napi-build-utils@1.0.2
npm info linkStuff node-abi@2.30.0
npm info linkStuff noop-logger@0.1.1
npm info linkStuff chownr@1.1.4
npm info linkStuff yallist@4.0.0
npm info linkStuff simple-concat@1.0.1
npm info linkStuff simple-get@3.1.0
npm info linkStuff strip-json-comments@2.0.1
npm info linkStuff rc@1.2.8
npm verb linkBins [
npm verb linkBins   { rc: 'cli.js' },
npm verb linkBins   '/home/chase/dev/price-log-website/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff chownr@1.1.4
npm info linkStuff readable-stream@3.6.0
npm info linkStuff tar-stream@2.2.0
npm info linkStuff tar-fs@2.1.1
npm info linkStuff which-pm-runs@1.0.0
npm info linkStuff prebuild-install@5.3.6
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   '/home/chase/dev/price-log-website/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff semver@6.3.0
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   '/home/chase/dev/price-log-website/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff tar@5.0.5
npm info linkStuff sharp@0.23.4
npm timing action:build Completed in 11ms
npm info lifecycle buffer@5.7.1~install: buffer@5.7.1
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle bl@4.1.0~install: bl@4.1.0
npm info lifecycle deep-extend@0.6.0~install: deep-extend@0.6.0
npm info lifecycle detect-libc@1.0.3~install: detect-libc@1.0.3
npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
npm info lifecycle mimic-response@2.1.0~install: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~install: decompress-response@4.2.1
npm info lifecycle mkdirp-classic@0.5.3~install: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~install: napi-build-utils@1.0.2
npm info lifecycle node-abi@2.30.0~install: node-abi@2.30.0
npm info lifecycle noop-logger@0.1.1~install: noop-logger@0.1.1
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle yallist@4.0.0~install: yallist@4.0.0
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle simple-get@3.1.0~install: simple-get@3.1.0
npm info lifecycle strip-json-comments@2.0.1~install: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.8~install: rc@1.2.8
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle tar-stream@2.2.0~install: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~install: tar-fs@2.1.1
npm info lifecycle which-pm-runs@1.0.0~install: which-pm-runs@1.0.0
npm info lifecycle prebuild-install@5.3.6~install: prebuild-install@5.3.6
npm info lifecycle semver@6.3.0~install: semver@6.3.0
npm info lifecycle tar@5.0.5~install: tar@5.0.5
npm info lifecycle sharp@0.23.4~install: sharp@0.23.4

> sharp@0.23.4 install /home/chase/dev/price-log-website/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/chase/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /home/chase/.npm/_prebuilds/32e648-sharp-v0.23.4-node-v83-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.23.4/sharp-v0.23.4-node-v83-linux-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.23.4/sharp-v0.23.4-node-v83-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/chase/.nvm/versions/node/v14.15.4/bin/node',
gyp verb cli   '/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.15.4 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python checking Python explicitly set from command line or npm configuration
gyp verb find Python - "--python=" or "npm config get python" is "C:LibraryPythonPython27python.exe"
gyp verb find Python - executing "C:LibraryPythonPython27python.exe" to get executable path
gyp verb find Python - "C:LibraryPythonPython27python.exe" is not in PATH or produced an error
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.8.2"
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 14.15.4
gyp verb command install [ '14.15.4' ]
gyp verb install input version string "14.15.4"
gyp verb install installing version: 14.15.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.15.4
gyp verb build dir attempting to create "build" dir: /home/chase/dev/price-log-website/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/chase/dev/price-log-website/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/chase/dev/price-log-website/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/chase/dev/price-log-website/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/chase/dev/price-log-website/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chase/dev/price-log-website/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chase/.cache/node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/chase/.cache/node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/chase/.cache/node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/chase/dev/price-log-website/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/chase/.cache/node-gyp/14.15.4
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/home/chase/.nvm/versions/node/v14.15.4/bin/node" "/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chase/dev/price-log-website/node_modules/sharp
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm verb lifecycle sharp@0.23.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.23.4~install: PATH: /home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/chase/dev/price-log-website/node_modules/sharp/node_modules/.bin:/home/chase/dev/price-log-website/node_modules/.bin:/home/chase/.nvm/versions/node/v14.15.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/dotnet/:/mnt/c/Users/chase/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/chase/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
npm verb lifecycle sharp@0.23.4~install: CWD: /home/chase/dev/price-log-website/node_modules/sharp
npm timing audit submit Completed in 505ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 505ms
npm timing audit body Completed in 0ms
npm info lifecycle sharp@0.23.4~install: Failed to exec install script
npm timing action:install Completed in 1056ms
npm verb unlock done using /home/chase/.npm/_locks/staging-9f52e8166511bad8.lock for /home/chase/dev/price-log-website/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 69ms
npm timing stage:runTopLevelLifecycles Completed in 5432ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/home/chase/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.23.4
npm verb cwd /home/chase/dev/price-log-website
npm verb Linux 4.19.128-microsoft-standard
npm verb argv "/home/chase/.nvm/versions/node/v14.15.4/bin/node" "/home/chase/.nvm/versions/node/v14.15.4/bin/npm" "install" "--verbose" "sharp"
npm verb node v14.15.4
npm verb npm  v6.14.11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 5851ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chase/.npm/_logs/2021-07-14T17_24_55_440Z-debug.log
```
Appreciate any suggestions!

**Comment by lovell** [comment]
Please upgrade sharp for Node.js 14 support.

**Comment by chasebank** [comment]
Yep! All is well now, thanks.
