### ISSUE TITLE
Installation problems on macOS 11.4; node-gyp issue

### ISSUE THREAD

**Issue by dislick** [lovell/sharp#2806]
I'm having troubles installing sharp on macOS Big Sur 11.4. It has definitely worked before, but something on my computer has changed and it stops me from installing it. Since I can't figure it out myself I was hoping to maybe get some help here. This is the output of creating a new folder, initialising a `package.json` and finally running `npm install --verbose sharp`.

I'm thankful for any hints/solutions!

```
/tmp
❯ mkdir sharptest

/tmp
❯ cd sharptest

/tmp/sharptest
❯ npm init -y
Wrote to /private/tmp/sharptest/package.json:

{
  "name": "sharptest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



/tmp/sharptest
❯ npm install --verbose sharp
npm verb cli [
npm verb cli   '/Users/patrickmuff/.nvm/versions/node/v16.5.0/bin/node',
npm verb cli   '/Users/patrickmuff/.nvm/versions/node/v16.5.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@7.19.1
npm info using node@v16.5.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/private/tmp/sharptest/.npmrc Completed in 0ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:/Users/patrickmuff/.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/Users/patrickmuff/.nvm/versions/node/v16.5.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 13ms
npm timing npm:load:configload Completed in 13ms
npm timing npm:load:setTitle Completed in 14ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 33ms
npm timing config:load:flatten Completed in 2ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 11ms
npm timing idealTree:userRequests Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 13ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 18ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 18ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 22ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 23ms (cache hit)
npm timing idealTree:#root Completed in 43ms
npm http fetch GET 200 https://registry.npmjs.org/color-convert 37ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 36ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minimist 38ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/rc 37ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 41ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pump 38ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 40ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 42ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 42ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 39ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/chownr 38ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/npmlog 41ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 38ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 41ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 40ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/once 41ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 42ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 46ms (cache hit)
npm timing idealTree:node_modules/sharp Completed in 58ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 5ms (cache hit)
npm timing idealTree:node_modules/color Completed in 9ms
npm timing idealTree:node_modules/color-convert Completed in 1ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 3ms (cache hit)
npm timing idealTree:node_modules/color-string Completed in 4ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/gauge 20ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 21ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/are-we-there-yet 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/set-blocking 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 22ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/console-control-strings 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ini 24ms (cache hit)
npm timing idealTree:node_modules/prebuild-install Completed in 35ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/object-assign 17ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/delegates 20ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string-width 18ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/signal-exit 21ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/aproba 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/wide-align 22ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/has-unicode 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 26ms (cache hit)
npm timing idealTree:node_modules/npmlog Completed in 34ms
npm http fetch GET 200 https://registry.npmjs.org/isarray 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/inherits 17ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/process-nextick-args 17ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/core-util-is 19ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 17ms (cache hit)
npm timing idealTree:node_modules/are-we-there-yet Completed in 26ms
npm timing idealTree:node_modules/console-control-strings Completed in 0ms
npm timing idealTree:node_modules/delegates Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/code-point-at 7ms (cache hit)
npm timing idealTree:node_modules/gauge Completed in 11ms
npm timing idealTree:node_modules/aproba Completed in 0ms
npm timing idealTree:node_modules/has-unicode Completed in 0ms
npm timing idealTree:node_modules/object-assign Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 3ms (cache hit)
npm timing idealTree:node_modules/pump Completed in 4ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 0ms
npm timing idealTree:node_modules/rc Completed in 2ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 7ms
npm timing idealTree:node_modules/core-util-is Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/isarray Completed in 0ms
npm timing idealTree:node_modules/process-nextick-args Completed in 0ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 4ms (cache hit)
npm timing idealTree:node_modules/semver Completed in 11ms
npm timing idealTree:node_modules/lru-cache Completed in 1ms
npm timing idealTree:node_modules/set-blocking Completed in 0ms
npm timing idealTree:node_modules/signal-exit Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 2ms (cache hit)
npm timing idealTree:node_modules/simple-get Completed in 4ms
npm timing idealTree:node_modules/decompress-response Completed in 0ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 0ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/string_decoder Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/number-is-nan 3ms (cache hit)
npm timing idealTree:node_modules/string-width Completed in 6ms
npm timing idealTree:node_modules/code-point-at Completed in 0ms
npm timing idealTree:node_modules/is-fullwidth-code-point Completed in 1ms
npm timing idealTree:node_modules/number-is-nan Completed in 0ms
npm timing idealTree:node_modules/strip-ansi Completed in 0ms
npm timing idealTree:node_modules/ansi-regex Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/bl 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 4ms (cache hit)
npm timing idealTree:node_modules/tar-fs Completed in 7ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/buffer 3ms (cache hit)
npm timing idealTree:node_modules/tar-stream Completed in 6ms
npm http fetch GET 200 https://registry.npmjs.org/ieee754 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 12ms (cache hit)
npm timing idealTree:node_modules/bl Completed in 14ms
npm timing idealTree:node_modules/buffer Completed in 1ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wide-align Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/bl/node_modules/readable-stream Completed in 0ms
npm timing idealTree:node_modules/node-abi/node_modules/semver Completed in 0ms
npm timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
npm timing idealTree:buildDeps Completed in 297ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 312ms
npm timing reify:loadTrees Completed in 313ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 7ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/chownr Completed in 180ms
npm timing reifyNode:node_modules/ansi-regex Completed in 180ms
npm timing reifyNode:node_modules/number-is-nan Completed in 180ms
npm timing reifyNode:node_modules/code-point-at Completed in 181ms
npm timing reifyNode:node_modules/is-fullwidth-code-point Completed in 181ms
npm timing reifyNode:node_modules/process-nextick-args Completed in 180ms
npm timing reifyNode:node_modules/ini Completed in 181ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 181ms
npm timing reifyNode:node_modules/wrappy Completed in 181ms
npm timing reifyNode:node_modules/end-of-stream Completed in 180ms
npm timing reifyNode:node_modules/once Completed in 181ms
npm timing reifyNode:node_modules/wide-align Completed in 181ms
npm timing reifyNode:node_modules/strip-ansi Completed in 181ms
npm timing reifyNode:node_modules/string-width Completed in 181ms
npm timing reifyNode:node_modules/object-assign Completed in 182ms
npm timing reifyNode:node_modules/aproba Completed in 182ms
npm timing reifyNode:node_modules/has-unicode Completed in 182ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 183ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 183ms
npm timing reifyNode:node_modules/simple-get Completed in 183ms
npm timing reifyNode:node_modules/ieee754 Completed in 188ms
npm timing reifyNode:node_modules/fs-constants Completed in 188ms
npm timing reifyNode:node_modules/decompress-response Completed in 187ms
npm timing reifyNode:node_modules/mimic-response Completed in 187ms
npm timing reifyNode:node_modules/lru-cache Completed in 188ms
npm timing reifyNode:node_modules/inherits Completed in 188ms
npm timing reifyNode:node_modules/console-control-strings Completed in 187ms
npm timing reifyNode:node_modules/set-blocking Completed in 187ms
npm timing reifyNode:node_modules/color-string Completed in 187ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 187ms
npm timing reifyNode:node_modules/color Completed in 187ms
npm timing reifyNode:node_modules/base64-js Completed in 191ms
npm timing reifyNode:node_modules/util-deprecate Completed in 190ms
npm timing reifyNode:node_modules/yallist Completed in 190ms
npm timing reifyNode:node_modules/signal-exit Completed in 189ms
npm timing reifyNode:node_modules/expand-template Completed in 189ms
npm timing reifyNode:node_modules/simple-concat Completed in 192ms
npm timing reifyNode:node_modules/deep-extend Completed in 192ms
npm timing reifyNode:node_modules/string_decoder Completed in 192ms
npm timing reifyNode:node_modules/safe-buffer Completed in 192ms
npm timing reifyNode:node_modules/pump Completed in 192ms
npm timing reifyNode:node_modules/npmlog Completed in 192ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 192ms
npm timing reifyNode:node_modules/color-name Completed in 191ms
npm timing reifyNode:node_modules/is-arrayish Completed in 194ms
npm timing reifyNode:node_modules/isarray Completed in 194ms
npm timing reifyNode:node_modules/delegates Completed in 194ms
npm timing reifyNode:node_modules/core-util-is Completed in 195ms
npm timing reifyNode:node_modules/color-convert Completed in 194ms
npm timing reifyNode:node_modules/detect-libc Completed in 195ms
npm timing reifyNode:node_modules/tar-stream Completed in 199ms
npm timing reifyNode:node_modules/are-we-there-yet Completed in 197ms
npm timing reifyNode:node_modules/node-abi/node_modules/semver Completed in 197ms
npm timing reifyNode:node_modules/buffer Completed in 201ms
npm timing reifyNode:node_modules/github-from-package Completed in 201ms
npm timing reifyNode:node_modules/rc Completed in 202ms
npm timing reifyNode:node_modules/bl Completed in 204ms
npm timing reifyNode:node_modules/prebuild-install Completed in 202ms
npm timing reifyNode:node_modules/node-abi Completed in 204ms
npm timing reifyNode:node_modules/gauge Completed in 207ms
npm timing reifyNode:node_modules/minimist Completed in 207ms
npm timing reifyNode:node_modules/readable-stream Completed in 213ms
npm timing reifyNode:node_modules/bl/node_modules/readable-stream Completed in 216ms
npm timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 216ms
npm timing reifyNode:node_modules/tar-fs Completed in 215ms
npm timing reifyNode:node_modules/node-addon-api Completed in 215ms
npm timing reifyNode:node_modules/semver Completed in 217ms
npm timing reifyNode:node_modules/sharp Completed in 220ms
npm timing reify:unpack Completed in 223ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 3ms
npm timing build:link:node_modules/detect-libc Completed in 3ms
npm timing build:link:node_modules/node-abi/node_modules/semver Completed in 3ms
npm timing build:link:node_modules/prebuild-install Completed in 3ms
npm timing build:link:node_modules/rc Completed in 4ms
npm timing build:link:node_modules/semver Completed in 4ms
npm timing build:link Completed in 5ms
npm info run sharp@0.28.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 387ms
npm timing auditReport:getReport Completed in 389ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 389ms
npm info run sharp@0.28.3 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 54ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 8403ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:394:28)
npm verb stack     at maybeClose (node:internal/child_process:1067:16)
npm verb stack     at Socket.<anonymous> (node:internal/child_process:453:11)
npm verb stack     at Socket.emit (node:events:394:28)
npm verb stack     at Pipe.<anonymous> (node:net:672:12)
npm verb pkgid sharp@0.28.3
npm verb cwd /private/tmp/sharptest
npm verb Darwin 20.5.0
npm verb argv "/Users/patrickmuff/.nvm/versions/node/v16.5.0/bin/node" "/Users/patrickmuff/.nvm/versions/node/v16.5.0/bin/npm" "install" "--verbose" "sharp"
npm verb node v16.5.0
npm verb npm  v7.19.1
npm ERR! code 1
npm ERR! path /private/tmp/sharptest/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Detected globally-installed libvips v8.11.2
npm ERR! sharp: Building from source via node-gyp
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/patrickmuff/.nvm/versions/node/v16.5.0/bin/node',
npm ERR! gyp verb cli   '/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.5.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp verb find Python - executing "/usr/local/opt/python@3.9/bin/python3.9" to get version
npm ERR! gyp verb find Python - version is "3.9.6"
npm ERR! gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.5.0
npm ERR! gyp verb command install [ '16.5.0' ]
npm ERR! gyp verb install input version string "16.5.0"
npm ERR! gyp verb install installing version: 16.5.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.5.0
npm ERR! gyp verb build dir attempting to create "build" dir: /private/tmp/sharptest/node_modules/sharp/build
npm ERR! gyp verb build dir "build" dir needed to be created? /private/tmp/sharptest/node_modules/sharp/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /private/tmp/sharptest/node_modules/sharp/build/config.gypi
npm ERR! (node:30612) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /private/tmp/sharptest/node_modules/sharp/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /private/tmp/sharptest/node_modules/sharp/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/private/tmp/sharptest/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/patrickmuff/Library/Caches/node-gyp/16.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/patrickmuff/Library/Caches/node-gyp/16.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/patrickmuff/Library/Caches/node-gyp/16.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/private/tmp/sharptest/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Package Imath was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `Imath.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! Package 'Imath', required by 'OpenEXR', not found
npm ERR! gyp: Call to 'PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags-only-I vips-cpp vips glib-2.0 | sed s\/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/Users/patrickmuff/.nvm/versions/node/v16.5.0/bin/node" "/Users/patrickmuff/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /private/tmp/sharptest/node_modules/sharp
npm ERR! gyp ERR! node -v v16.5.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 8647ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrickmuff/.npm/_logs/2021-07-20T09_50_06_232Z-debug.log

/tmp/sharptest 9s
```

```
/tmp/sharptest
❯ node -v
v16.5.0

/tmp/sharptest
❯ npm -v
7.19.1
```

**Comment by lovell** [comment]
It looks like you're using a globally-installed libvips, most likely via Homebrew:

> npm ERR! sharp: Detected globally-installed libvips v8.11.2
> npm ERR! sharp: Building from source via node-gyp

But there's a problem with the dependencies:

> npm ERR! Package 'Imath', required by 'OpenEXR', not found

Please can you run `brew update && brew upgrade` to fix your Homebrew installation.

**Comment by dislick** [comment]
There was indeed an issue with the dependencies. `brew update && brew upgrade` didn't fix the problem though, I eventually completely [uninstalled and reinstalled Homebrew](https://github.com/homebrew/install#uninstall-homebrew). The error is gone now, thank you so much!
