### ISSUE TITLE
Termux install fails, missing xproto.pc, despite globally installed libvips

### ISSUE THREAD

**Issue by Leif-W** [lovell/sharp#2807]
* Android 11 / Aarch64 / ARMv8
* Termux 0.117
* node 14.15.4
* libvips 8.11.0
* node-gyp 8.1.0
* python 3.9.6

Note: npm v7 is horribly broken in Termux right now.  npm v6 mostly works, as does yarn v1.  yarn v2 mostly works, yarn v3 not at all.  And pnpm seems to work quite well, but has no `--platform` option.  My project uses pnpm.

What I am wondering is, if libvips is compiled, installed globally, and detected already, then why is sharp trying to build anything?  And why is it looking for X-Window protocol stuff?

I'll have to put in a request for xproto to be added to Termux repo, if it is truly needed.  xcb-proto is already there, but is something separate.

```
~/dev/app-foo $ pnpm add sharp
Packages: +70
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 70, reused 70, downloaded 0, added 0, done
node_modules/.pnpm/sharp@0.28.3/node_modules/sharp: Running install script, failed in 1.2s
.../sharp@0.28.3/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node insta
│ sharp: Detected globally-installed libvips v8.11.0
│ sharp: Building from source via node-gyp
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.1.0
│ gyp info using node@14.15.4 | android | arm64
│ gyp info find Python using Python version 3.9.6 found at "/data/data/com.termux/files/usr/bin/python3"
│ gyp info spawn /data/data/com.termux/files/usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/data/data/com.termux/files/home/dev/app-foo/node_modules/.pnpm/sharp@0.28.3/node_modules/sharp/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/14.15.4/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/14.15.4',
│ gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/14.15.4/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/dev/app-foo/node_modules/.pnpm/sharp@0.28.3/node_modules/sharp',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ Package xproto was not found in the pkg-config search path.
│ Perhaps you should add the directory containing `xproto.pc'
│ to the PKG_CONFIG_PATH environment variable
│ Package 'xproto', required by 'xau', not found
│ gyp: Call to 'PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags-only-I vips-cpp vips glib-2.0 | sed s\/-I//g' returned exit status 0 while in
│ gyp ERR! configure error
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/data/data/com.termux/files/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:353:16)
│ gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
│ gyp ERR! System Linux 4.19.113-21564965
│ gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /data/data/com.termux/files/home/dev/app-foo/node_modules/.pnpm/sharp@0.28.3/node_modules/sharp
│ gyp ERR! node -v v14.15.4
│ gyp ERR! node-gyp -v v8.1.0
│ gyp ERR! not ok
└─ Failed in 1.2s
 ERROR  Command failed with exit code 1.
~/dev/app-foo $
```

My system has an xproto.h file in /data/data/com.termux/files/usr/include/xcb/xproto.h but that is the only thing named xproto.  There doesn't seem to be any package named xproto in the Termux repo.  There is an xcb-proto.  Not sure if related.  I installed it and tried anyways.  It doesn't provide xproto.pc either, only /data/data/com.termux/files/usr/share/xcb/xproto.xml which seems unrelated.

Not that it makes any difference, because there is no xproto.pc anywhere on system, I did add the Termux specific location, which is where sharp should look on Termux, if such file existed.

```
~/dev/app-foo $ export PKG_CONFIG_PATH="/data/data/com.termux/files/usr/lib/pkgconfig"
~/dec/app-foo $ pnpm add sharp
...
same result, just different PKG_CONFIG_PATH env var
```

**Comment by Leif-W** [comment]
Solved it less than 5 minutes later, oops.  Well, this is a good documentation not for anyone else caught by the issue.

Termux has the `xproto.pc` in the `xorgproto` package, which is why I was not finding it with `pkg search xproto`.

In short, to use `sharp` on Termux:

```
pkg install libvips xorgproto
mkdir app-foo # if a new project
cd app-foo    # or use existing project
pnpm init -y  # use any package manager
pnpm add sharp
```

No need for explicit PKG_CONFIG_PATH fiddling.

**Comment by SimplyVoid** [comment]
> Solved it less than 5 minutes later, oops. Well, this is a good documentation for anyone else caught by the issue.
> 
> Termux has the `xproto.pc` in the `xorgproto` package, which is why I was not finding it with `pkg search xproto`.
> 
> In short, to use `sharp` on Termux:
> 
> ```
> pkg install libvips xorgproto
> mkdir app-foo # if a new project
> cd app-foo    # or use existing project
> pnpm init -y  # use any package manager
> pnpm add sharp
> ```
> 
> No need for explicit PKG_CONFIG_PATH fiddling.

i also needed to install `binutlis` manually to work and it worked
