### ISSUE TITLE
Google Cloud Functions - NPM install fails.

### ISSUE THREAD

**Issue by timhj** [lovell/sharp#2811]
Deploying some changes to a thumbnailer script that sharp uses (great script, btw - thanks!) and the npm build is now failing trying v0.28.3 (previously was using 0.18.1 and working, so not sure where the issue was introduced) 

GCF doesn't show the errors from the build itself but trying to run the thumbnailer script it errors:
> Provided module can't be loaded.
> Did you list all required modules in the package.json dependencies?
> Detailed stack trace: Error: Cannot find module 'sharp'
> ... package doesn't exist.

Google Cloud Functions: Tried with Node 10, 12 & 14

I saw a number of other issues on different chipsets, toolkits related to this so adding Google Cloud Functions into the mix. 

I'll go back through the issues to find an earlier version that should work and specify that release so my problem should be all good. Just letting you know the issue is breaking usage on GCF too.

**Comment by lovell** [comment]
Please provide more information, including answering the questions from the installation issue template.

Lots of people are successfully using sharp on Google Cloud Functions so it's likely there is something that needs updating or fixing in your build/deployment configuration.

**Comment by pietervdvn** [comment]
Hi,

I'm having a similar issue on Github actions. The full output can be found here: https://github.com/pietervdvn/MapComplete/runs/3170239620?check_suite_focus=true

(For reference:

```
 npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
npm ERR!    24 | #include <vips/vips8>
npm ERR!       |          ^~~~~~~~~~~~
npm ERR! compilation terminated
```

Machine info: 

```

Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210718.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210718.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210718.1
```

Someone of the team also had this on their local machine (a windows with WSL IIRC)

**Comment by lovell** [comment]
@pietervdvn Please open a new installation issue and answer all of the questions. https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&template=installation.md

**Comment by timhj** [comment]
@lovell  - Adding questionaire for completeness as I still haven't been able to get a build on GCF working. The GCF deployment still fails with the sharp module being 'missing' (my read is npm install difficulty). The last successful build was Dec 2020 (package.json fixed with 0.18.1 - Node 10). 
The build used to just work, has anything changed that would make a straight npm install not run anymore?

### package.json (the only build configuration available)
```
{
  "name": "crop-thumbnailer",
  "version": "0.1.3",
  "dependencies": {
    "sharp": "^0.28.3",
    "@google-cloud/storage" : ">=3.0.0",
    "mysql": ">=2.5.0"
  }
}
```

### Installation Issue Questionnaire

> Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes

> Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

It's all handled by GCF, I have to assume yes.

> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

These commands are not possible to run on the Google Cloud Platform, Google Cloud Functions Framework.

> If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

No, I've tried deploying ot GCF's Node 10, Node 12 and Node 14 environments all with same issue.

> If you are using npm v7, does the user running `npm install` own the directory it is run in?

N/A

> If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

N/A

> What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

It's not possible to see build logs, let alone verbose ones within GCF

> What is the output of running `npx envinfo --binaries --system`?

Again - It's not possible to shell to a GCF instance to to run these commands.

**Comment by lovell** [comment]
> It's not possible to see build logs, let alone verbose ones within GCF

https://cloud.google.com/functions/docs/building#accessing_your_build_image_logs

**Comment by timhj** [comment]
I went through those. It only shows errors with your code and not the
dependencies build. 🤷‍♂️

**Comment by timhj** [comment]
Disregard previous.

I tried though the console. Will try a command line deploy and report back
tomorrow.

**Comment by timhj** [comment]
@lovell  I can redeploy the last successful build from the command line, so here are the logs for trying to redeploy with Sharp 0.18.4 as a requirement.

### Build logs - Node10 Sharp 0.18.4 (last working deployment - no code change)
```
2021-08-05 11:14:10.957 - starting build "b688c464-7e35-486b-9b0a-b82b35303788"
2021-08-05 11:14:10.957 - FETCHSOURCE
2021-08-05 11:14:10.957 - Fetching storage object: gs://gcf-sources-299431218570-us-central1/DEV-crop_thumbnailer-16e73b41-2b80-4a3c-8806-74bb57638453/version-8/function-source.zip#1628126050136230
2021-08-05 11:14:16.240 - Copying gs://gcf-sources-299431218570-us-central1/DEV-crop_thumbnailer-16e73b41-2b80-4a3c-8806-74bb57638453/version-8/function-source.zip#1628126050136230...
2021-08-05 11:14:16.377 - / [0 files][ 0.0 B/ 3.4 KiB] / [1 files][ 3.4 KiB/ 3.4 KiB]
2021-08-05 11:14:16.377 - Operation completed over 1 objects/3.4 KiB.
2021-08-05 11:14:17.588 - Archive: /tmp/source-archive.zip
2021-08-05 11:14:17.588 - inflating: /workspace/index.js
2021-08-05 11:14:17.588 - inflating: /workspace/package.json
2021-08-05 11:14:17.588 - inflating: /workspace/testEvent.json
2021-08-05 11:14:17.874 - BUILD
2021-08-05 11:14:18.486 - Starting Step #0 - "prep"
2021-08-05 11:14:18.487 - Step #0 - "prep": Pulling image: us.gcr.io/fn-img/utilities/crane-shell:nodejs10_20210713_10_24_1_RC00
2021-08-05 11:14:19.522 - Step #0 - "prep": nodejs10_20210713_10_24_1_RC00: Pulling from fn-img/utilities/crane-shell
2021-08-05 11:14:19.601 - Step #0 - "prep": b49b96595fd4: Already exists
2021-08-05 11:14:19.615 - Step #0 - "prep": bb771d6dc9a1: Already exists
2021-08-05 11:14:19.625 - Step #0 - "prep": 82eb23873ec5: Pulling fs layer
2021-08-05 11:14:19.625 - Step #0 - "prep": 72164b581b02: Pulling fs layer
2021-08-05 11:14:19.625 - Step #0 - "prep": c15d52701efb: Pulling fs layer
2021-08-05 11:14:19.684 - Step #0 - "prep": 72164b581b02: Verifying Checksum
2021-08-05 11:14:19.684 - Step #0 - "prep": 72164b581b02: Download complete
2021-08-05 11:14:19.704 - Step #0 - "prep": 82eb23873ec5: Verifying Checksum
2021-08-05 11:14:19.704 - Step #0 - "prep": 82eb23873ec5: Download complete
2021-08-05 11:14:19.813 - Step #0 - "prep": c15d52701efb: Verifying Checksum
2021-08-05 11:14:19.813 - Step #0 - "prep": c15d52701efb: Download complete
2021-08-05 11:14:19.912 - Step #0 - "prep": 82eb23873ec5: Pull complete
2021-08-05 11:14:20.011 - Step #0 - "prep": 72164b581b02: Pull complete
2021-08-05 11:14:20.284 - Step #0 - "prep": c15d52701efb: Pull complete
2021-08-05 11:14:20.306 - Step #0 - "prep": Digest: sha256:746291589a530c825103f606a7fbe7633ba65fe573f614fe2f115892ecac48ad
2021-08-05 11:14:20.313 - Step #0 - "prep": Status: Downloaded newer image for us.gcr.io/fn-img/utilities/crane-shell:nodejs10_20210713_10_24_1_RC00
2021-08-05 11:14:20.319 - Step #0 - "prep": us.gcr.io/fn-img/utilities/crane-shell:nodejs10_20210713_10_24_1_RC00
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable BUILDER_OUTPUT to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_DEBUG to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_RUNTIME to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_LABEL_BUILDER_VERSION to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_LABEL_BUILDER_IMAGE to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_LABEL_RUN_IMAGE to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_FUNCTION_TARGET to buildpacks.
2021-08-05 11:14:21.221 - Step #0 - "prep": Passing build environment variable GOOGLE_FUNCTION_SIGNATURE_TYPE to buildpacks.
2021-08-05 11:14:21.404 - Finished Step #0 - "prep"
2021-08-05 11:14:21.404 - Starting Step #1 - "validate-images"
2021-08-05 11:14:21.406 - Step #1 - "validate-images": Already have image (with digest): us.gcr.io/fn-img/utilities/crane-shell:nodejs10_20210713_10_24_1_RC00
 2021-08-05 11:14:25.557 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:6ea402ebdaf85c8ad885027394d994bea275d806401c5dd50cace180cade1f2b
2021-08-05 11:14:25.561 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:9675bb9e968fd1192e15e32f26d77a09c4861425e6ccde828299dc16deee27ed
2021-08-05 11:14:25.565 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:d22b00816366056147e8f7c6b516c52b28c3c3a5cec23f648c2a4d3dd2f8792c
2021-08-05 11:14:25.587 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:f6909a737046ea5893451ee53868796bb489a0d556cf10608f1bddd34e91073d
2021-08-05 11:14:25.589 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:0533677bb37d0a93a1bc75adb94df8b68dece84f7415223d16cfc9bc346f5f94
2021-08-05 11:14:25.589 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:3e0b49ba1f68338d761c18dde71c71f07c15ae0da3dec74f3ba5d55d7e9c2e26
2021-08-05 11:14:25.601 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:928f56b671ac816f5194ab4656053ab3d8ae4e70a9db5be8cc6d1b9a44b63b30
2021-08-05 11:14:25.610 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:603dab334a4261a6ef71eba4aa37f6413566f2f5a5e21672bfb591ef4bb7ac5b
2021-08-05 11:14:25.617 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:00ab17d3df7c2d0714df265bbc519ea9fec79e220aee5c34c9d4e9eaa9e90e8b
2021-08-05 11:14:25.622 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:d0ed2b8c108fe7298f4b03fcbe1430e15abfd2ce104f7a350e5d7f8ec49b32f2
2021-08-05 11:14:25.624 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:18cee90eb87f2a77415eb5a15794935d13e3bd13b92042df56f3836d8a68b10a
2021-08-05 11:14:25.640 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:5a44e4f7b58d74fe6f92dd7028075c91191128d1e2e7f39846fe061a9a98836e
2021-08-05 11:14:25.715 - Step #2 - "pre-tag": 2021/08/05 01:14:25 existing blob: sha256:f10d184b98108935c6b514be86861053026e217186bd4d4100acd5fa67b38fc3
2021-08-05 11:14:25.961 - Step #2 - "pre-tag": 2021/08/05 01:14:25 us.gcr.io/searcheraggregator/gcf/us-central1/16e73b41-2b80-4a3c-8806-74bb57638453:DEV-crop_thumbnailer_version-8: digest: sha256:8a00c7376b9961686027ac63d4f1e9be2c9f61d8634e5278794beb8ac3af80af size: 5446
2021-08-05 11:14:26.149 - Finished Step #2 - "pre-tag"
2021-08-05 11:14:26.149 - Starting Step #3 - "build"
2021-08-05 11:14:26.150 - Step #3 - "build": Pulling image: us.gcr.io/fn-img/buildpacks/nodejs10/builder:nodejs10_20210713_10_24_1_RC00
2021-08-05 11:14:26.787 - Step #3 - "build": nodejs10_20210713_10_24_1_RC00: Pulling from fn-img/buildpacks/nodejs10/builder
2021-08-05 11:14:26.789 - Step #3 - "build": 228505c46125: Already exists
2021-08-05 11:14:26.799 - Step #3 - "build": 52b243a9211b: Already exists
2021-08-05 11:14:26.808 - Step #3 - "build": 3c2cba919283: Already exists
2021-08-05 11:14:26.817 - Step #3 - "build": 94b9159bf001: Already exists
2021-08-05 11:14:26.827 - Step #3 - "build": de3a1d1384e7: Already exists
2021-08-05 11:14:26.836 - Step #3 - "build": f48f5e846525: Already exists
2021-08-05 11:14:26.843 - Step #3 - "build": 56ae46af1768: Already exists
 2021-08-05 11:14:26.884 - Step #3 - "build": 1872f6afe650: Pulling fs layer
2021-08-05 11:14:26.884 - Step #3 - "build": 7d5f0d832abc: Pulling fs layer
2021-08-05 11:14:26.884 - Step #3 - "build": 7e8f029fa81d: Pulling fs layer
2021-08-05 11:14:26.884 - Step #3 - "build": 7b9ca1c3ab5b: Pulling fs layer
2021-08-05 11:14:26.884 - Step #3 - "build": a43ea245e86c: Pulling fs layer
2021-08-05 11:14:26.884 - Step #3 - "build": 4f4fb700ef54: Pulling fs layer
2021-08-05 11:14:26.884 - Step #3 - "build": c4bb98b50e02: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 918ecc66eae4: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": d74463ff2a9e: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 9645f1569810: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 96a4e2ef1369: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": ff1205b292fb: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 3dcec76d3627: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 6d43c0455dd6: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 06f428a8446f: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": df2a11ebcd38: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": cb30c9442e95: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": c3e0da70529e: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 176bb191af92: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 833850cf7cc5: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 1872f6afe650: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 7d5f0d832abc: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 7e8f029fa81d: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 7b9ca1c3ab5b: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": a43ea245e86c: Waiting
2021-08-05 11:14:26.884 - Step #3 - "build": 4f4fb700ef54: Waiting
 2021-08-05 11:14:27.916 - Step #3 - "build": 4f4fb700ef54: Download complete
2021-08-05 11:14:27.920 - Step #3 - "build": a43ea245e86c: Verifying Checksum
2021-08-05 11:14:27.920 - Step #3 - "build": a43ea245e86c: Download complete
2021-08-05 11:14:27.931 - Step #3 - "build": b01724cf3119: Pull complete
2021-08-05 11:14:29.849 - Step #3 - "build": c4bb98b50e02: Pull complete
2021-08-05 11:14:29.944 - Step #3 - "build": 918ecc66eae4: Pull complete
2021-08-05 11:14:30.133 - Step #3 - "build": d74463ff2a9e: Pull complete
2021-08-05 11:14:30.229 - Step #3 - "build": 9645f1569810: Pull complete
2021-08-05 11:14:30.329 - Step #3 - "build": 96a4e2ef1369: Pull complete
2021-08-05 11:14:30.422 - Step #3 - "build": ff1205b292fb: Pull complete
2021-08-05 11:14:30.552 - Step #3 - "build": 3dcec76d3627: Pull complete
2021-08-05 11:14:30.645 - Step #3 - "build": 6d43c0455dd6: Pull complete
2021-08-05 11:14:30.739 - Step #3 - "build": 06f428a8446f: Pull complete
2021-08-05 11:14:31.019 - Step #3 - "build": df2a11ebcd38: Pull complete
2021-08-05 11:14:31.223 - Step #3 - "build": cb30c9442e95: Pull complete
2021-08-05 11:14:31.408 - Step #3 - "build": c3e0da70529e: Pull complete
2021-08-05 11:14:31.601 - Step #3 - "build": 176bb191af92: Pull complete
2021-08-05 11:14:31.791 - Step #3 - "build": 833850cf7cc5: Pull complete
2021-08-05 11:14:31.976 - Step #3 - "build": 1872f6afe650: Pull complete
2021-08-05 11:14:32.176 - Step #3 - "build": 7d5f0d832abc: Pull complete
2021-08-05 11:14:32.366 - Step #3 - "build": 7e8f029fa81d: Pull complete
2021-08-05 11:14:32.463 - Step #3 - "build": 7b9ca1c3ab5b: Pull complete
2021-08-05 11:14:32.563 - Step #3 - "build": a43ea245e86c: Pull complete
2021-08-05 11:14:32.655 - Step #3 - "build": 4f4fb700ef54: Pull complete
2021-08-05 11:14:32.670 - Step #3 - "build": Digest: sha256:eae506c00b260304ed7ea698f485470d9a4e96bcd4ca5daa5b65c86f25d7f397
 2021-08-05 11:14:45.594 - Step #3 - "build": gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-08-05 11:14:45.594 - Step #3 - "build": gyp ERR! cwd /workspace/node_modules/sharp
2021-08-05 11:14:45.594 - Step #3 - "build": gyp ERR! node -v v10.24.1
2021-08-05 11:14:45.594 - Step #3 - "build": gyp ERR! node-gyp -v v5.1.0
2021-08-05 11:14:45.594 - Step #3 - "build": gyp ERR! not ok
2021-08-05 11:14:45.730 - Step #3 - "build": npm WARN crop-thumbnailer@0.0.2 No description
2021-08-05 11:14:45.731 - Step #3 - "build": npm WARN crop-thumbnailer@0.0.2 No repository field.
2021-08-05 11:14:45.734 - Step #3 - "build": npm WARN crop-thumbnailer@0.0.2 No license field.
2021-08-05 11:14:45.734 - Step #3 - "build":
2021-08-05 11:14:45.748 - Step #3 - "build": npm ERR! code ELIFECYCLE
2021-08-05 11:14:45.749 - Step #3 - "build": npm ERR! errno 1
2021-08-05 11:14:45.750 - Step #3 - "build": npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
2021-08-05 11:14:45.751 - Step #3 - "build": npm ERR! Exit status 1
2021-08-05 11:14:45.753 - Step #3 - "build": npm ERR!
2021-08-05 11:14:45.753 - Step #3 - "build": npm ERR! Failed at the sharp@0.18.4 install script.
2021-08-05 11:14:45.753 - Step #3 - "build": npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-08-05 11:14:45.766 - Step #3 - "build":
2021-08-05 11:14:45.766 - Step #3 - "build": npm ERR! A complete log of this run can be found in:
2021-08-05 11:14:45.766 - Step #3 - "build": npm ERR! /www-data-home/.npm/_logs/2021-08-05T01_14_45_759Z-debug.log
2021-08-05 11:14:45.774 - Step #3 - "build": Done "npm install --quiet (NODE_ENV=production)" (4.469620576s)
2021-08-05 11:14:45.775 - Step #3 - "build": Failure: (ID: 49341d49) > sharp@0.18.4 install /workspace/node_modules/sharp
2021-08-05 11:14:45.776 - Step #3 - "build": > node-gyp rebuild
2021-08-05 11:14:45.776 - Step #3 - "build":
2021-08-05 11:14:45.777 - Step #3 - "build": ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz status code 403
2021-08-05 11:14:45.778 - Step #3 - "build": gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! configure error 
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! stack Error: `gyp` failed with exit code: 1
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! stack at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! stack at ChildProcess.emit (events.js:198:13)
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! System Linux 5.4.0-1046-gcp
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! cwd /workspace/node_modules/sharp
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! node -v v10.24.1
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! node-gyp -v v5.1.0
2021-08-05 11:14:45.778 - Step #3 - "build": gyp ERR! not ok
2021-08-05 11:14:45.779 - Step #3 - "build": npm WARN crop-thumbnailer@0.0.2 No description
2021-08-05 11:14:45.779 - Step #3 - "build": npm WARN crop-thumbnailer@0.0.2 No repository field.
2021-08-05 11:14:45.779 - Step #3 - "build": npm WARN crop-thumbnailer@0.0.2 No license field.
2021-08-05 11:14:45.779 - Step #3 - "build":
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! code ELIFECYCLE
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! errno 1
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! Exit status 1
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR!
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! Failed at the sharp@0.18.4 install script.
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-08-05 11:14:45.779 - Step #3 - "build":
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! A complete log of this run can be found in:
2021-08-05 11:14:45.779 - Step #3 - "build": npm ERR! /www-data-home/.npm/_logs/2021-08-05T01_14_45_759Z-debug.log
2021-08-05 11:14:45.779 - Step #3 - "build": --------------------------------------------------------------------------------
2021-08-05 11:14:45.783 - Step #3 - "build": Running "mv -f /builder/outputs/output-5577006791947779410 /builder/outputs/output"
2021-08-05 11:14:45.784 - Step #3 - "build": Done "mv -f /builder/outputs/output-5577006791947779410 /builder/o..." (9.987915ms)
2021-08-05 11:14:45.786 - Step #3 - "build": ERROR: failed to build: exit status 1
2021-08-05 11:14:46.642 - Finished Step #3 - "build"
2021-08-05 11:14:46.642 - ERROR
2021-08-05 11:14:46.642 - ERROR: build step 3 "us.gcr.io/fn-img/buildpacks/nodejs10/builder:nodejs10_20210713_10_24_1_RC00" failed: step exited with non-zero status: 145
```

**Comment by lovell** [comment]
This installation log is for sharp v0.18.4 - please see #2574 and upgrade.

**Comment by timhj** [comment]
Yes, it's all I can deploy to get the logs without changing the build
pipeline. Same deployment issue occurs with 0.23.3

**Comment by timhj** [comment]
GCF just built the Node 10 function successfully sharp with v.0.28.3 as a dependency. Thanks for your patience.
