### ISSUE TITLE
Failed to install, Debian Buster, node 16.13.3, npm 8.1.0

### ISSUE THREAD

**Issue by lcherone** [lovell/sharp#2980]
Can't seem to install, looking through logs I can't seem to see what the cause is. Any suggestions?

Make version:

```
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
```

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)? YES

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime? YES

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? YES

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```
...<SNIP>
3366 timing build:link:node_modules/node-gyp/node_modules/semver Completed in 15ms
3367 timing build:link:node_modules/nuxt-build-optimisations/node_modules/semver Completed in 15ms
3368 timing build:link Completed in 19ms
3369 info run node-sass@5.0.0 install node_modules/node-sass node scripts/install.js
3370 info run sharp@0.23.4 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3371 info run node-sass@5.0.0 install { code: 0, signal: null }
3372 timing build:run:install:node_modules/node-sass Completed in 630ms
3373 info run sharp@0.23.4 install { code: 1, signal: null }
3374 timing reify:rollback:createSparse Completed in 1198ms
3375 timing reify:rollback:retireShallow Completed in 0ms
3376 timing command:install Completed in 15357ms
3377 verbose stack Error: command failed
3377 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3377 verbose stack     at ChildProcess.emit (node:events:390:28)
3377 verbose stack     at maybeClose (node:internal/child_process:1064:16)
3377 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3378 verbose pkgid sharp@0.23.4
3379 verbose cwd /var/www/html
3380 verbose Linux 5.4.0-90-generic
3381 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
3382 verbose node v16.13.0
3383 verbose npm  v8.1.0
3384 error code 1
3385 error path /var/www/html/node_modules/sharp
3386 error command failed
3387 error command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3388 error make: Entering directory '/var/www/html/node_modules/sharp/build'
3388 error   touch Release/obj.target/libvips-cpp.stamp
3388 error   g++ -o Release/obj.target/sharp/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/node/.cache/node-gyp/16.13.0/include/node -I/home/node/.cache/node-gyp/16.13.0/src -I/home/node/.cache/node-gyp/16.13.0/deps/openssl/config -I/home/node/.cache/node-gyp/16.13.0/deps/openssl/openssl/include -I/home/node/.cache/node-gyp/16.13.0/deps/uv/include -I/home/node/.cache/node-gyp/16.13.0/deps/zlib -I/home/node/.cache/node-gyp/16.13.0/deps/v8/include -I../../nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++14 -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c
3388 error make: Leaving directory '/var/www/html/node_modules/sharp/build'
3389 error info sharp Using cached /home/node/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
3389 error prebuild-install info begin Prebuild-install version 5.3.6
3389 error prebuild-install info install installing standalone, skipping download.
3389 error gyp info it worked if it ends with ok
3389 error gyp verb cli [
3389 error gyp verb cli   '/usr/local/bin/node',
3389 error gyp verb cli   '/var/www/html/node_modules/.bin/node-gyp',
3389 error gyp verb cli   'rebuild'
3389 error gyp verb cli ]
3389 error gyp info using node-gyp@7.1.2
3389 error gyp info using node@16.13.0 | linux | x64
3389 error gyp verb command rebuild []
3389 error gyp verb command clean []
3389 error gyp verb clean removing "build" directory
3389 error gyp verb command configure []
3389 error gyp verb find Python Python is not set from command line or npm configuration
3389 error gyp verb find Python Python is not set from environment variable PYTHON
3389 error gyp verb find Python checking if "python3" can be used
3389 error gyp verb find Python - executing "python3" to get executable path
3389 error gyp verb find Python - executable path is "/usr/bin/python3"
3389 error gyp verb find Python - executing "/usr/bin/python3" to get version
3389 error gyp verb find Python - version is "3.7.3"
3389 error gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
3389 error gyp verb get node dir no --target version specified, falling back to host node version: 16.13.0
3389 error gyp verb command install [ '16.13.0' ]
3389 error gyp verb install input version string "16.13.0"
3389 error gyp verb install installing version: 16.13.0
3389 error gyp verb install --ensure was passed, so won't reinstall if already installed
3389 error gyp verb install version is already installed, need to check "installVersion"
3389 error gyp verb got "installVersion" 9
3389 error gyp verb needs "installVersion" 9
3389 error gyp verb install version is good
3389 error gyp verb get node dir target node version installed: 16.13.0
3389 error gyp verb build dir attempting to create "build" dir: /var/www/html/node_modules/sharp/build
3389 error gyp verb build dir "build" dir needed to be created? /var/www/html/node_modules/sharp/build
3389 error gyp verb build/config.gypi creating config file
3389 error gyp verb build/config.gypi writing out config file: /var/www/html/node_modules/sharp/build/config.gypi
3389 error (node:5906) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
3389 error (Use `node --trace-deprecation ...` to show where the warning was created)
3389 error gyp verb config.gypi checking for gypi file: /var/www/html/node_modules/sharp/config.gypi
3389 error gyp verb common.gypi checking for gypi file: /var/www/html/node_modules/sharp/common.gypi
3389 error gyp verb gyp gyp format was not specified; forcing "make"
3389 error gyp info spawn /usr/bin/python3
3389 error gyp info spawn args [
3389 error gyp info spawn args   '/var/www/html/node_modules/node-gyp/gyp/gyp_main.py',
3389 error gyp info spawn args   'binding.gyp',
3389 error gyp info spawn args   '-f',
3389 error gyp info spawn args   'make',
3389 error gyp info spawn args   '-I',
3389 error gyp info spawn args   '/var/www/html/node_modules/sharp/build/config.gypi',
3389 error gyp info spawn args   '-I',
3389 error gyp info spawn args   '/var/www/html/node_modules/node-gyp/addon.gypi',
3389 error gyp info spawn args   '-I',
3389 error gyp info spawn args   '/home/node/.cache/node-gyp/16.13.0/include/node/common.gypi',
3389 error gyp info spawn args   '-Dlibrary=shared_library',
3389 error gyp info spawn args   '-Dvisibility=default',
3389 error gyp info spawn args   '-Dnode_root_dir=/home/node/.cache/node-gyp/16.13.0',
3389 error gyp info spawn args   '-Dnode_gyp_dir=/var/www/html/node_modules/node-gyp',
3389 error gyp info spawn args   '-Dnode_lib_file=/home/node/.cache/node-gyp/16.13.0/<(target_arch)/node.lib',
3389 error gyp info spawn args   '-Dmodule_root_dir=/var/www/html/node_modules/sharp',
3389 error gyp info spawn args   '-Dnode_engine=v8',
3389 error gyp info spawn args   '--depth=.',
3389 error gyp info spawn args   '--no-parallel',
3389 error gyp info spawn args   '--generator-output',
3389 error gyp info spawn args   'build',
3389 error gyp info spawn args   '-Goutput_dir=.'
3389 error gyp info spawn args ]
3389 error gyp verb command build []
3389 error gyp verb build type Release
3389 error gyp verb architecture x64
3389 error gyp verb node dev dir /home/node/.cache/node-gyp/16.13.0
3389 error gyp verb `which` succeeded for `make` /usr/bin/make
3389 error gyp info spawn make
3389 error gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
3389 error <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
3389 error <command-line>: note: this is the location of the previous definition
3389 error In file included from /home/node/.cache/node-gyp/16.13.0/include/node/v8.h:30,
3389 error                  from /home/node/.cache/node-gyp/16.13.0/include/node/node.h:63,
3389 error                  from ../src/common.cc:22:
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h: In function 'void v8::internal::PerformCastCheck(T*)':
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'
3389 error              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
3389 error                                       ^~~~~~~~~~~
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: note: suggested alternative: 'remove_cv'
3389 error              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
3389 error                                       ^~~~~~~~~~~
3389 error                                       remove_cv
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: note: suggested alternative: 'remove_cv'
3389 error              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
3389 error                                       ^~~~~~~~~~~
3389 error                                       remove_cv
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:50: error: template argument 2 is invalid
3389 error              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
3389 error                                                   ^
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:63: error: '::Perform' has not been declared
3389 error              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
3389 error                                                                ^~~~~~~
3389 error /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:63: note: suggested alternative: 'perror'
3389 error              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
3389 error                                                                ^~~~~~~
3389 error                                                                perror
3389 error make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
3389 error gyp ERR! build error
3389 error gyp ERR! stack Error: `make` failed with exit code: 2
3389 error gyp ERR! stack     at ChildProcess.onExit (/var/www/html/node_modules/node-gyp/lib/build.js:194:23)
3389 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
3389 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
3389 error gyp ERR! System Linux 5.4.0-90-generic
3389 error gyp ERR! command "/usr/local/bin/node" "/var/www/html/node_modules/.bin/node-gyp" "rebuild"
3389 error gyp ERR! cwd /var/www/html/node_modules/sharp
3389 error gyp ERR! node -v v16.13.0
3389 error gyp ERR! node-gyp -v v7.1.2
3389 error gyp ERR! not ok
3390 verbose exit 1

```

What is the output of running `npx envinfo --binaries --system`?

```
$ npx envinfo --binaries --system
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 6.88 GB / 15.58 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
```

Error:

```
npm ERR! code 1
npm ERR! path /var/www/html/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! make: Entering directory '/var/www/html/node_modules/sharp/build'
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! make: Leaving directory '/var/www/html/node_modules/sharp/build'
npm ERR! info sharp Using cached /home/node/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! (node:3660) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/var/www/html/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/www/html/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/www/html/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/node/.cache/node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/node/.cache/node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/var/www/html/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/node/.cache/node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/var/www/html/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
npm ERR! <command-line>: note: this is the location of the previous definition
npm ERR! In file included from /home/node/.cache/node-gyp/16.13.0/include/node/v8.h:30,
npm ERR!                  from /home/node/.cache/node-gyp/16.13.0/include/node/node.h:63,
npm ERR!                  from ../src/common.cc:22:
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h: In function 'void v8::internal::PerformCastCheck(T*)':
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                       ^~~~~~~~~~~
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: note: suggested alternative: 'remove_cv'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                       ^~~~~~~~~~~
npm ERR!                                       remove_cv
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:38: note: suggested alternative: 'remove_cv'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                       ^~~~~~~~~~~
npm ERR!                                       remove_cv
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:50: error: template argument 2 is invalid
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                   ^
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:63: error: '::Perform' has not been declared
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                                ^~~~~~~
npm ERR! /home/node/.cache/node-gyp/16.13.0/include/node/v8-internal.h:492:63: note: suggested alternative: 'perror'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                                ^~~~~~~
npm ERR!                                                                perror
npm ERR! make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/var/www/html/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.4.0-90-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/var/www/html/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /var/www/html/node_modules/sharp
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```

**Comment by lovell** [comment]
Please upgrade to the latest version (this log is from v0.23.4).

**Comment by lcherone** [comment]
Thanks, seems to have sorted it
