### ISSUE TITLE
Can we have platformAndArch string in error log?

### ISSUE THREAD

**Issue by sytolk** [lovell/sharp#2982]
What are you trying to achieve?

I mean this string: https://github.com/lovell/sharp/blob/master/lib/sharp.js#L3

If its have error here it's possible `platformAndArch` to be different from sharp-XXX.node in /build/Release/ but I dont know what is platformAndArch output 
```javascript
try {
  module.exports = require(`../build/Release/sharp-${platformAndArch}.node`);
} catch (err) {
```

This line miss me:
```javascript
} catch (err) {
  help.push('current platformAndArch: ' + platformAndArch);
  throw new Error(help.join('\n'));
}
```

**Comment by lovell** [comment]
The value should implicitly appear as part of the `err.message` already, e.g. if I delete the `build` directory and attempt to `require('sharp')` I see the following on Linux x64:
```
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
...
```
Is there a scenario where this isn't happening?

I'm happy to make this value explicit too, but want to make sure I understand the underlying problem first as there could be additional things we can output to help.

**Comment by sytolk** [comment]
I have packaged Electron App (with asar) and this error on Linux platform only (on Mac and Windows I dont have errors):
```
Tagspaces WS: /opt/TagSpaces/resources/app.asar/node_modules/sharp/lib/sharp.js:30
Tagspaces WS:   throw new Error(help.join('\n'));
Tagspaces WS:   ^
Tagspaces WS: Error: 
Tagspaces WS: Something went wrong installing the "sharp" module
Tagspaces WS: libvips-cpp.so.42: cannot open shared object file: No such file or directory
Tagspaces WS: Possible solutions:
Tagspaces WS: - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
Tagspaces WS: - Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
Tagspaces WS: - Consult the installation documentation: https://sharp.pixelplumbing.com/install
Tagspaces WS:     at Object.<anonymous> (/opt/TagSpaces/resources/app.asar/node_modules/sharp/lib/sharp.js:30:9)
Tagspaces WS:     at Module._compile (node:internal/modules/cjs/loader:1110:14)
Tagspaces WS:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
Tagspaces WS:     at Module.load (node:internal/modules/cjs/loader:982:32)
Tagspaces WS:     at Module._load (node:internal/modules/cjs/loader:823:12)
Tagspaces WS:     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
Tagspaces WS:     at Module.require (node:internal/modules/cjs/loader:1006:19)
Tagspaces WS:     at require (node:internal/modules/cjs/helpers:93:18)
Tagspaces WS:     at Object.<anonymous> (/opt/TagSpaces/resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
Tagspaces WS:     at Module._compile (node:internal/modules/cjs/loader:1110:14)
```
It appears that sharp-linux-x64.node is installed correctlly in asar archive 
![Screenshot_48](https://user-images.githubusercontent.com/1415463/142388419-30d884f7-754e-44f4-bf68-5c10fdd1af06.png)

maybe platformAndArch variable is different from `linux-x64` ??

**Comment by sytolk** [comment]
I found my issue: https://github.com/lovell/sharp/issues/2582
```
stanimir@debian:~/structmedia/tagspaces$ ldd node_modules/sharp/build/Release/sharp-linux-x64.node
        linux-vdso.so.1 (0x00007fff3bfed000)
        libvips-cpp.so.42 => /home/stanimir/structmedia/tagspaces/node_modules/sharp/build/Release/../.././vendor/8.11.3/linux-x64/lib/libvips-cpp.so.42 (0x00007f781ab89000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f781a807000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f781a503000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f781a2ec000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f781a0cf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7819d30000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f7819b19000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7819915000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f781bf42000)
```

**Comment by sytolk** [comment]
@lovell what about to change this line:
```javascript
 const help = ['', 'Something went wrong installing the "sharp" module for platform:' + platformAndArch, '', err.message, '', 'Possible solutions:'];
```

**Comment by lovell** [comment]
Added via commit https://github.com/lovell/sharp/commit/96992845ed25b74ab6ee1b82a9a1b443b86f6931 - this will be in v0.30.0

**Comment by lovell** [comment]
v0.30.0 now available with this feature.
