### ISSUE TITLE
The path containing special characters cannot be started

### ISSUE THREAD

**Issue by VisualSJ** [lovell/sharp#3001]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

yeah

What are the steps to reproduce?

Install the program in a special directory. Then try reuqire and you get an error:
\.publish\【# 58@测试 測試 ., ; & Ak%!{]\resources\app\node_modules\sharp\build\Release\sharp.node
![image](https://user-images.githubusercontent.com/7113508/144820186-54afc150-8975-48eb-9452-4dc00ca3d960.png)

name: 【# 58@测试 測試 ., ; & Ak%!{]

What is the expected behaviour?

Normal boot

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

What is the output of running `npx envinfo --binaries --system`?

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp`?

**Comment by earlybail** [comment]
I just got this via `yarn add sharp` as well, here's the verbose response:
```
› yarn add sharp --verbose
yarn add v1.9.4
verbose 0.211150689 Error: package.json: Name contains illegal characters
    at MessageError.ExtendableBuiltin (/Users/snidelywhiplash/.yarn/lib/cli.js:243:66)
    at new MessageError (/Users/snidelywhiplash/.yarn/lib/cli.js:272:123)
    at module.exports.exports.default (/Users/snidelywhiplash/.yarn/lib/cli.js:40316:13)
    at /Users/snidelywhiplash/.yarn/lib/cli.js:52283:51
    at Generator.next (<anonymous>)
    at step (/Users/snidelywhiplash/.yarn/lib/cli.js:92:30)
    at /Users/snidelywhiplash/.yarn/lib/cli.js:103:13
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by lovell** [comment]
@VisualSJ Were you able to make any progress with this? If you still require help, please can you provide the requested information.

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with the requested details if further help is required.
