### ISSUE TITLE
Tiling a 5GB TIF: RangeError [ERR_INVALID_OPT_VALUE]: The value "5479395327" is invalid for option "size"

### ISSUE THREAD

**Issue by beig** [lovell/sharp#3003]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
0.29.3

What are the steps to reproduce?

I am trying to tile a 5gb TIF from an S3 Bucket.
I recreated a working example locally, reading the file partially into a CombinedStream and piping it to sharp

Error:

```
RangeError [ERR_INVALID_OPT_VALUE]: The value "5479395327" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:386:3)
    at Function.concat (buffer.js:567:25)
    at Sharp._flattenBufferIn (E:\work\siteplan\siteplan-lambda\tiling\node_modules\sharp\lib\input.js:194:40)
    at Sharp.<anonymous> (E:\work\siteplan\siteplan-lambda\tiling\node_modules\sharp\lib\output.js:846:16)
    at Object.onceWrapper (events.js:421:28)
    at Sharp.emit (events.js:327:22)
    at Sharp.EventEmitter.emit (domain.js:467:12)
    at finish (internal/streams/writable.js:657:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_INVALID_OPT_VALUE'
}
```

What is the expected behaviour?

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```
    const sharpStream = sharp({
        limitInputPixels: false,
        sequentialRead: true
    });

    const partSize = 16000000;
    const combinedStream = CombinedStream.create();
    const contentLength = fs.statSync('test_file.tif').size;
    let currentByte = 0;

    while (currentByte <= contentLength) {
        const s1 = fs.createReadStream('test_file.tif', {
            start: currentByte,
            end: currentByte + partSize
        });
        currentByte += partSize + 1;
        combinedStream.append(s1);
    }

    combinedStream.pipe(sharpStream);

    await sharpStream.jpeg().tile({
        layout: 'google',
        size: 256
    }).toFile('output_folder');
```

**Comment by lovell** [comment]
You've probably hit the memory limit of Node.js. For huge inputs like this I recommend using the local filesystem and providing a path to sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
