### ISSUE TITLE
libIlmImf.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by binarykitchen** [lovell/sharp#304]
Because it fails every time with these versions and I am not sure if this ever has been tested yet.

Thanks for a confirmation

**Comment by binarykitchen** [comment]
For reference, these versions always produce this build error:

```
/home/michael-heuberger/.node-gyp/4.2.2/include/node/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
v8tools.target.mk:90: recipe for target 'Release/obj.target/v8tools/src/v8tools.o' failed
make: *** [Release/obj.target/v8tools/src/v8tools.o] Error 1
make: Leaving directory '/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/v8tools/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-18-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/v8tools
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:v8tools@0.2.2 v8tools@0.2.2 install: `node-gyp rebuild`
npm WARN install:v8tools@0.2.2 Exit status 1
```

**Comment by lovell** [comment]
Hi Michael, "npm WARN install:v8tools@0.2.2 Exit status 1" suggests that the `v8tools` module couldn't be installed.

What part of this error message led you to believe `sharp` might be at fault?

**Comment by binarykitchen** [comment]
Because when I try to run my app afterwards I get this error stack trace:

```
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libIlmImf.so.6: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/index.js:12:13)
...
```

**Comment by lovell** [comment]
`libIlmImf.so` is part of OpenEXR. My best guess is that you're using a version of libvips compiled with support for OpenEXR but the shared libraries upon which it depends are not available at runtime.

**Comment by binarykitchen** [comment]
@lovell thanks for explaining - can you give me a direction, any hints, how i can fix this? how i can rebuild libvips with the correct shared libraries at their expected locations?

**Comment by lovell** [comment]
Closing this question as it looks like we're making more progress at https://github.com/jcupitt/libvips/issues/350.

**Comment by binarykitchen** [comment]
yep, thanks so much for your great help

**Comment by binarykitchen** [comment]
@lovell arrrg, i just am experiencing the same issue over again while upgrading from ubuntu 14 to 16 on my server :(

```
$ vips -v
vips: error while loading shared libraries: libIlmImf.so.6: cannot open shared object file: No such file or directory
```

tried all the above, no luck
