### ISSUE TITLE
make: *** [../node-addon-api/nothing.target.mk:109: Release/obj.target/nothing/../node-addon-api/nothing.o] Error 127

### ISSUE THREAD

**Issue by alexander-milenko** [lovell/sharp#3063]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
**Yes**

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
**Yes**

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
**No**
```
bash-5.1# npm ls sharp
node-typescript-boilerplate@0.0.0 /usr/src/project
`-- (empty)

bash-5.1# npm view sharp dist-tags.latest
0.29.3
```

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
```
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:520:28)
npm verb stack     at maybeClose (node:internal/child_process:1090:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sharp@0.25.4
npm verb cwd /usr/src/project
npm verb Linux 4.19.130-boot2docker
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--ignore-scripts=false" "--verbose" "sharp"
npm verb node v17.4.0
npm verb npm  v8.3.1
npm ERR! code 1
npm ERR! path /usr/src/project/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! make: Entering directory '/usr/src/project/node_modules/sharp/build'
npm ERR! make: Leaving directory '/usr/src/project/node_modules/sharp/build'
npm ERR! info sharp Detected globally-installed libvips v8.12.1
npm ERR! info sharp Building from source via node-gyp
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.9.7"
npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 17.4.0
npm ERR! gyp verb command install [ '17.4.0' ]
npm ERR! gyp verb install input version string "17.4.0"
npm ERR! gyp verb install installing version: 17.4.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 17.4.0
npm ERR! gyp verb build dir attempting to create "build" dir: /usr/src/project/node_modules/sharp/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /usr/src/project/node_modules/sharp/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /usr/src/project/node_modules/sharp/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /usr/src/project/node_modules/sharp/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/src/project/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/17.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/17.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/17.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/src/project/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir /root/.cache/node-gyp/17.4.0
npm ERR! gyp verb `which` succeeded for `make` /usr/bin/make
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: printf: Operation not permitted
npm ERR! make: *** [../node-addon-api/nothing.target.mk:109: Release/obj.target/nothing/../node-addon-api/nothing.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 4.19.130-boot2docker
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/src/project/node_modules/sharp
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
```

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 6.95 GB / 7.78 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
This looks like https://github.com/lovell/sharp/issues/2810#issuecomment-886692938 which was a problem with Alpine Linux syscall permissions within Docker and unrelated to sharp.

**Comment by alexander-milenko** [comment]
@lovell 

Thanks for the advice, but
```
bash-5.1# scmp_sys_resolver faccessat2
439
```
That is means the `faccessat2` is supported.

**Comment by lovell** [comment]
> npm verb pkgid sharp@0.25.4

Please can you upgrade to the latest version, currently v0.29.3.

> npm ERR! info sharp Detected globally-installed libvips v8.12.1

Is your use of a globally-installed vips intentional? Prebuilt binaries are available and should "just work" without compilation.

If you're still having problems, please can you share a Dockerfile that allows someone else to reproduce.

**Comment by alexander-milenko** [comment]
I tried to reproduce the issue from scratch and remove `package.json` file at all

Dockerfile:
```
FROM node:current-alpine

RUN apk add --upgrade --no-cache \
    vips-dev fftw-dev gcc g++ make libc6-compat imagemagick bash pngcrush optipng=0.7.7-r0 file ffmpeg runc && \
    apk add --upgrade graphicsmagick ghostscript

RUN mkdir -p /usr/src/project/tmp
WORKDIR /usr/src/project
```

then (for testing reason) just open a container shell and `npm install sharp --verbose`

the error part of log I have [bump](https://pastebin.com/hcQ2UGGs)

**Comment by alexander-milenko** [comment]
Ok, solved.

I specified the tag for node from `node:current-alpine` to `node:17-alpine3.14`, and everything started to work. So, something wrong with the current alpine implementation.

**Comment by lovell** [comment]
I cannot reproduce this using the provided Dockerfile (Alpine 3.15) running the latest docker v20.10.12 on Ubuntu.

I note the log you've provided mentions boot2docker, which I believe has been unmaintained for a couple of years.

**Comment by alexander-milenko** [comment]
@lovell thank you for the comments, investigation and your time. 

I will try to find an accurate replacement for the boot2docker and back to you with accurate logs if needed.
