### ISSUE TITLE
EACCES: permission denied, mkdir '/root/.npm' on linux ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by moezbenrebah** [lovell/sharp#3064]
I'm under ubuntu 20.04 and I have node 14 and npm 7 installed on my machine, I tried to install sharp but I have always the same error occurred :
```shell
moez@moez:~/Desktop/project$ sudo npm i sharp --unsafe-perm
npm ERR! code 1
npm ERR! path /home/moez/Desktop/project/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Are you trying to install as a root or sudo user? Try again with the --unsafe-perm flag
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: EACCES: permission denied, mkdir '/root/.npm'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-31T17_39_17_805Z-debug.log
``` 
I also tried to change the permission in .npm, but still stuck. any idea will be appreciated

**Comment by lovell** [comment]
I highly recommend you avoid the use of `sudo` to install anything from npm.

If you're still having problems when using a non-root user, please provide answers to these questions (these were deleted from the issue template):

* If you are using npm v7, does the user running `npm install` own the directory it is run in?

* What is the complete output of running `npm install --verbose sharp`?

**Comment by moezbenrebah** [comment]
the entire output of "npm install --verbose sharp" is:
```bash
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose', 'sharp' ]
npm info using npm@7.24.2
npm info using node@v14.18.2
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 4ms
npm timing config:load:builtin Completed in 4ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/home/moez/Desktop/Go_ahead_travel/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/moez/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 2ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 18ms
npm timing npm:load:configload Completed in 18ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing config:load:flatten Completed in 6ms
npm timing npm:load:cleanupLog Completed in 4ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 41ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 1756ms
npm timing idealTree:userRequests Completed in 11ms
npm timing arborist:ctor Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 2614ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 582ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 868ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 876ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 955ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 1124ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 1452ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 3851ms (cache updated)
npm timing idealTree:#root Completed in 6504ms
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 579ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 964ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 1239ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 1336ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 1362ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 1415ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 1421ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 1454ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 1558ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 1583ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/npmlog 1675ms (cache revalidated)
npm timing idealTree:node_modules/sharp Completed in 1728ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/console-control-strings 331ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/are-we-there-yet 346ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/gauge 422ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/set-blocking 447ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install Completed in 485ms
npm timing idealTree:node_modules/expand-template Completed in 1ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/aproba 398ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/has-unicode 418ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/delegates 432ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 463ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/wide-align 472ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/string-width 478ms (cache revalidated)
npm timing idealTree:node_modules/npmlog Completed in 497ms
npm timing idealTree:node_modules/are-we-there-yet Completed in 4ms
npm timing idealTree:node_modules/console-control-strings Completed in 0ms
npm timing idealTree:node_modules/delegates Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/code-point-at 298ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 383ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 397ms (cache revalidated)
npm timing idealTree:node_modules/gauge Completed in 417ms
npm timing idealTree:node_modules/aproba Completed in 0ms
npm timing idealTree:node_modules/has-unicode Completed in 0ms
npm timing idealTree:node_modules/set-blocking Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 236ms (cache revalidated)
npm timing idealTree:node_modules/simple-get Completed in 247ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 284ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/bl 314ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 343ms (cache revalidated)
npm timing idealTree:node_modules/tar-fs Completed in 355ms
npm timing idealTree:node_modules/chownr Completed in 1ms
npm timing idealTree:node_modules/tar-stream Completed in 9ms
npm timing idealTree:node_modules/bl Completed in 2ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/wide-align Completed in 0ms
npm timing idealTree:node_modules/bl/node_modules/readable-stream Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/number-is-nan 1049ms (cache revalidated)
npm timing idealTree:node_modules/gauge/node_modules/string-width Completed in 1064ms
npm timing idealTree:node_modules/code-point-at Completed in 0ms
npm timing idealTree:node_modules/gauge/node_modules/is-fullwidth-code-point Completed in 4ms
npm timing idealTree:node_modules/number-is-nan Completed in 0ms
npm timing idealTree:node_modules/gauge/node_modules/strip-ansi Completed in 3ms
npm timing idealTree:node_modules/gauge/node_modules/ansi-regex Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 997ms (cache revalidated)
npm timing idealTree:node_modules/node-abi/node_modules/semver Completed in 1002ms
npm timing idealTree:node_modules/node-abi/node_modules/lru-cache Completed in 4ms
npm timing idealTree:node_modules/node-abi/node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/prebuild-install/node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/sharp/node_modules/color Completed in 0ms
npm timing idealTree:node_modules/sharp/node_modules/node-addon-api Completed in 0ms
npm timing idealTree:node_modules/sharp/node_modules/semver Completed in 4ms
npm timing idealTree:node_modules/sharp/node_modules/lru-cache Completed in 2ms
npm timing idealTree:node_modules/sharp/node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/simple-get/node_modules/decompress-response Completed in 6ms
npm timing idealTree:node_modules/simple-get/node_modules/mimic-response Completed in 1ms
npm timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
npm timing idealTree:buildDeps Completed in 12368ms
npm timing idealTree:fixDepFlags Completed in 18ms
npm timing idealTree Completed in 14195ms
npm timing reify:loadTrees Completed in 14198ms
npm timing reify:diffTrees Completed in 988ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 92ms
npm timing reify:loadBundles Completed in 0ms
npm verb reify failed optional dependency /home/moez/Desktop/Go_ahead_travel/node_modules/fsevents
npm verb reify failed optional dependency /home/moez/Desktop/Go_ahead_travel/node_modules/@parcel/watcher/node_modules/fsevents
npm timing reifyNode:node_modules/fsevents Completed in 16ms
npm timing reifyNode:node_modules/@parcel/watcher/node_modules/fsevents Completed in 16ms
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm http fetch POST 426 http://registry.npmjs.org/-/npm/v1/security/advisories/bulk 246ms
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm http fetch POST 426 http://registry.npmjs.org/-/npm/v1/security/audits/quick 802ms
npm verb audit error HttpErrorGeneral: 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
npm verb audit error     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb audit error     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm verb audit error     at async Map.[getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:337:21)
npm verb audit error     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:107:19)
npm verb audit error  HttpErrorGeneral: 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
npm verb audit error     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb audit error     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm verb audit error     at async Map.[getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:337:21)
npm verb audit error     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:107:19) {
npm verb audit error   headers: [Object: null prototype] {
npm verb audit error     date: [ 'Mon, 31 Jan 2022 19:37:41 GMT' ],
npm verb audit error     'content-type': [ 'text/plain' ],
npm verb audit error     'content-length': [ '271' ],
npm verb audit error     connection: [ 'keep-alive' ],
npm verb audit error     'npm-notice': [
npm verb audit error       'Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/'
npm verb audit error     ],
npm verb audit error     vary: [ 'Accept-Encoding' ],
npm verb audit error     server: [ 'cloudflare' ],
npm verb audit error     'cf-ray': [ '6d656560adda0f72-MXP' ],
npm verb audit error     'x-fetch-attempts': [ '1' ]
npm verb audit error   },
npm verb audit error   statusCode: 426,
npm verb audit error   code: 'E426',
npm verb audit error   method: 'POST',
npm verb audit error   uri: 'http://registry.npmjs.org/-/npm/v1/security/audits/quick',
npm verb audit error   body: <Buffer 42 65 67 69 6e 6e 69 6e 67 20 4f 63 74 6f 62 65 72 20 34 2c 20 32 30 32 31 2c 20 61 6c 6c 20 63 6f 6e 6e 65 63 74 69 6f 6e 73 20 74 6f 20 6e 70 6d 20 ... 221 more bytes>,
npm verb audit error   pkgid: undefined
npm verb audit error }
npm timing auditReport:getReport Completed in 1431ms
npm timing reify:audit Completed in 1431ms
npm timing reifyNode:node_modules/number-is-nan Completed in 1714ms
npm timing reifyNode:node_modules/code-point-at Completed in 1715ms
npm timing reifyNode:node_modules/chownr Completed in 1715ms
npm timing reifyNode:node_modules/wide-align Completed in 1715ms
npm timing reifyNode:node_modules/has-unicode Completed in 1716ms
npm timing reifyNode:node_modules/aproba Completed in 1717ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 1716ms
npm timing reifyNode:node_modules/gauge/node_modules/strip-ansi Completed in 1728ms
npm timing reifyNode:node_modules/gauge/node_modules/ansi-regex Completed in 1729ms
npm timing reifyNode:node_modules/fs-constants Completed in 1735ms
npm timing reifyNode:node_modules/set-blocking Completed in 1733ms
npm timing reifyNode:node_modules/simple-get/node_modules/mimic-response Completed in 1732ms
npm timing reifyNode:node_modules/sharp/node_modules/lru-cache Completed in 1733ms
npm timing reifyNode:node_modules/node-abi/node_modules/lru-cache Completed in 1739ms
npm timing reifyNode:node_modules/simple-get/node_modules/decompress-response Completed in 1738ms
npm timing reifyNode:node_modules/expand-template Completed in 1742ms
npm timing reifyNode:node_modules/sharp/node_modules/yallist Completed in 1741ms
npm timing reifyNode:node_modules/node-abi/node_modules/yallist Completed in 1747ms
npm timing reifyNode:node_modules/sharp/node_modules/color Completed in 1742ms
npm timing reifyNode:node_modules/simple-concat Completed in 1755ms
npm timing reifyNode:node_modules/npmlog Completed in 1753ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 1755ms
npm timing reifyNode:node_modules/delegates Completed in 1767ms
npm timing reifyNode:node_modules/tar-stream Completed in 1775ms
npm timing reifyNode:node_modules/simple-get Completed in 1772ms
npm timing reifyNode:node_modules/github-from-package Completed in 1797ms
npm timing reifyNode:node_modules/node-abi Completed in 1811ms
npm timing reifyNode:node_modules/gauge Completed in 1830ms
npm timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 1906ms
npm timing reifyNode:node_modules/bl/node_modules/readable-stream Completed in 1908ms
npm timing reifyNode:node_modules/tar-fs Completed in 1973ms
npm timing reifyNode:node_modules/sharp/node_modules/node-addon-api Completed in 1977ms
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.0.tgz 1208ms (cache miss)
npm timing reifyNode:node_modules/prebuild-install/node_modules/detect-libc Completed in 2020ms
npm timing reifyNode:node_modules/sharp/node_modules/semver Completed in 2023ms
npm timing reifyNode:node_modules/node-abi/node_modules/semver Completed in 2030ms
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install/-/prebuild-install-7.0.1.tgz 1342ms (cache miss)
npm timing reifyNode:node_modules/prebuild-install Completed in 2043ms
npm timing reifyNode:node_modules/sharp Completed in 2043ms
npm timing reify:rollback:createSparse Completed in 119ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 17520ms
npm verb stack TypeError: Cannot read property 'pickAlgorithm' of null
npm verb stack     at Integrity.match (/usr/lib/node_modules/npm/node_modules/ssri/index.js:234:24)
npm verb stack     at CachePolicy.satisfies (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/policy.js:113:49)
npm verb stack     at Function.find (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:172:25)
npm verb stack     at async cacheFetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:8:17)
npm verb stack     at async fetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:82:7)
npm verb cwd /home/moez/Desktop/Go_ahead_travel
npm verb Linux 5.13.0-27-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose" "sharp"
npm verb node v14.18.2
npm verb npm  v7.24.2
npm ERR! Cannot read property 'pickAlgorithm' of null
npm verb exit 1
npm timing npm Completed in 18740ms
npm verb unfinished npm timer reify 1643657845139
npm verb unfinished npm timer reify:unpack 1643657860480
npm verb unfinished npm timer reifyNode:node_modules/bl 1643657860482
npm verb unfinished npm timer reifyNode:node_modules/gauge/node_modules/is-fullwidth-code-point 1643657860485
npm verb unfinished npm timer reifyNode:node_modules/gauge/node_modules/string-width 1643657860485
npm verb unfinished npm timer reifyNode:node_modules/console-control-strings 1643657860485
npm verb unfinished npm timer reifyNode:node_modules/are-we-there-yet 1643657860486
npm verb unfinished npm timer reifyNode:node_modules/detect-libc 1643657860491
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moez/.npm/_logs/2022-01-31T19_37_42_679Z-debug.log
```

**Comment by moezbenrebah** [comment]
I find a solution for my problem by using these commands:
```bash
moez@moez:~/Desktop/project$ npm cache clear --force
npm WARN using --force Recommended protections disabled.
moez@moez:~/Desktop/project$ npm i sharp --unsafe-perm
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

added 43 packages in 25s

95 packages are looking for funding
  run `npm fund` for details
```
