### ISSUE TITLE
Vips preinstalled on Centos7 but crash on installation 

### ISSUE THREAD

**Issue by ytokan** [lovell/sharp#3073]
I 

can you help me

**System information**
`npx envinfo --binaries --system`

```
  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (2) x64 Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
    Memory: 370.19 MB / 3.70 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 14.18.1 - /bin/node
    Yarn: 1.22.11 - /opt/npm_modules/node_modules/.bin/yarn
    npm: 6.14.15 - /bin/npm
```

`npm install --unsafe-perm` crash 

**Vips**
```
vips -v
vips-8.12.1-Wed Nov 24 15:41:04 UTC 2021
```

```
pkg-config --modversion vips-cpp
Package vips-cpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips-cpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips-cpp' found
```

Dont find **vips-cpp.pc** file 

```
rpm -qa | grep vips
vips-tools-8.12.1-1.el7.remi.x86_64
vips-openslide-8.12.1-1.el7.remi.x86_64
vips-poppler-8.12.1-1.el7.remi.x86_64
vips-8.12.1-1.el7.remi.x86_64
```

sharp: Installation error: Prebuilt libvips 8.10.6 binaries are not yet available for linux-x64
sharp: Attempting to build from source via node-gyp but this may fail due to the above error

```
1557 verbose stack Error: sharp@0.28.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
1557 verbose stack Exit status 1
1557 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1557 verbose stack     at EventEmitter.emit (events.js:400:28)
1557 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1557 verbose stack     at ChildProcess.emit (events.js:400:28)
1557 verbose stack     at maybeClose (internal/child_process.js:1058:16)
1557 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
1558 verbose pkgid sharp@0.28.1
1559 verbose cwd /WEBS/site/docs/releases/back/20220126181707
1560 verbose Linux 3.10.0-1160.31.1.el7.x86_64
1561 verbose argv "/usr/bin/node" "/bin/npm" "install" "--verbose" "sharp"
1562 verbose node v14.18.1
1563 verbose npm  v6.14.15
1564 error code ELIFECYCLE
1565 error errno 1
1566 error sharp@0.28.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
1566 error Exit status 1
1567 error Failed at the sharp@0.28.1 install script.
1567 error This is probably not a problem with npm. There is likely additional logging output above.
1568 verbose exit [ 1, true ]
```

**Comment by ytokan** [comment]
**I add** 
`export PKG_CONFIG_PATH=/usr/lib64/`

**ls -la /usr/lib64/libvips-cpp***

```
lrwxrwxrwx 1 root root 22 Jan 21 09:02 /usr/lib64/libvips-cpp.so.42 -> libvips-cpp.so.42.14.1
-rwxr-xr-x 1 root root 233824 Nov 25 07:54 /usr/lib64/libvips-cpp.so.42.14.1
```

**Comment by lovell** [comment]
It looks like you're using Remi Collet's RPM repo. Did you install `vips-devel`?

**Comment by lovell** [comment]
@ytokan Were you able to make any progress with this?

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.
