### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by huangzongwang** [lovell/sharp#3092]
PS F:\test\videos6> npm ls -g sharp
C:\Users\Administrator\AppData\Roaming\npm
└── (empty)

PS F:\test\videos6> npm ls sharp
helpful-guidance-maintain-d2v1o@1.0.0 F:\test\videos6
└─┬ ffmpeg-concat@1.3.3
  └── sharp@0.24.1
Error: 
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\F:\test\videos6\node_modules\ffmpeg-concat\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (VM281 F:\test\videos6\node_modules\ffmpeg-concat\node_modules\sharp\lib\constructor.js:34)
    at Object.<anonymous> (VM281 F:\test\videos6\node_modules\ffmpeg-concat\node_modules\sharp\lib\constructor.js:276)
    at Module._compile (VM89 loader:1110)
    at Object.Module._extensions..js (VM89 loader:1140)
    at Module.load (VM89 loader:982)
    at Module._load (VM89 loader:823)
    at Function.c._load (VM108 asar_bundle:5)
    at Function.o._load (VM111 renderer_init:29)
    at Module.require (VM89 loader:1006)
    at require (VM92 helpers:93)

**Comment by lovell** [comment]
> sharp@0.24.1

Please upgrade to the latest v0.30.1

**Comment by huangzongwang** [comment]
> 0.30.1

 npm ls  sharp
helpful-guidance-maintain-d2v1o@1.0.0 F:\test\videos6
└─┬ ffmpeg-concat@1.3.3
  └── sharp@0.30.1

Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\F:\test\videos6\node_modules\ffmpeg-concat\node_modules\sharp\build\Release\sharp-win32-x64.node

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (F:\test\videos6\node_modules\ffmpeg-concat\node_modules\sharp\lib\sharp.js:31:9)
    at Object.<anonymous> (F:\test\videos6\node_modules\ffmpeg-concat\node_modules\sharp\lib\sharp.js:34:3)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:29:379)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
