### ISSUE TITLE
How to validate dimensions before extracting an image in nodejs ?

### ISSUE THREAD

**Issue by AsadJaved126** [lovell/sharp#3190]
OS: Windows 10
Node:v14.15.3
NPM: 6.14.9

Hi, We have developed a service to resize and extract the image.  We are having an issue while we give the **following parameters**  in the sample service call. 

x,y,width,heigth

http://localhost:8001/?x=100&y=300&width=700&height=1000&format=jpg&imagePath=https://bucketfleetlymaster-master.s3.us-west-2.amazonaws.com/public/JPEG_20210310_125807_.jpg&widthToDisplay=700&heightToDisplay=1000

This service work in most cases when we give the accurate parameters by using some cropping tool.

We have the following nodejs code, You may try with this code and this issue will be reproduced at your end then you may suggest us.
 

In Index.js file we call resize service like this !  
const express = require("express");
const app = express();
const cors = require("cors");
const sharp = require("sharp");
const resize = require('./resize');
app.use(express.json({ limit: "50mb" }));
app.use(cors());
app.use(
    express.urlencoded({
        extended: true,
    })
);

app.get('/', async(req, res) => {
    // Extract the query-parameter
    const xCoord = req.query.x;
    const yCoord = req.query.y;
    const widthString = req.query.width;
    const heightString = req.query.height;
    const format = req.query.format;
    const imageUrl = req.query.imagePath;
    const widthForDisplay = req.query.widthToDisplay;
    const heightForDisplay = req.query.heightToDisplay;
    // Parse to integer if possible
    let x, y, width, height, displayWidth, displayHeight;
    if (xCoord) {
        x = parseInt(xCoord)
    }
    if (yCoord) {
        y = parseInt(yCoord)
    }
    if (widthString) {
        width = parseInt(widthString)
    }
    if (heightString) {
        height = parseInt(heightString)
    }
    if (widthForDisplay) {
        displayWidth = parseInt(widthForDisplay);
    }
    if (heightForDisplay) {
        displayHeight = parseInt(heightForDisplay);
    }
    // Set the content-type of the response
    res.type(`image/${format || 'png'}`)
        //res.type(`png`)

    // Get the resized image
    const streamObject = await resize(imageUrl, x, y, format, width, height, displayWidth, displayHeight) /*.pipe(res)*/ ;
    streamObject.pipe(res);
    //res.pipe(streamObject);
})

--- resize.js

const express = require("express");
const app = express();
const fs = require('fs'),
    sharp = require("sharp"),
    axios = require("axios");
sharpStream = sharp({
    failOnError: false
});
module.exports = async function resize(path, x, y, format, width, height, displayWidth, displayHeight) {

    const imageResponse = await axios({ url: path, responseType: 'arraybuffer' })
    const buffer = Buffer.from(imageResponse.data, 'binary')
    const transform = await sharp(buffer);
    const metaDetail = await transform.metadata();
    //const sizeValidation = (metaDetail.height * metaDetail.width);
    const InputHeight = metaDetail.height;
    const InputWidth = metaDetail.width;

    const InputImageAspectRation = InputWidth / InputHeight;
[BadTextAreaError.txt](https://github.com/lovell/sharp/files/8480609/BadTextAreaError.txt)

    if (metaDetail.width > x && metaDetail.height > y) {
        const transformedImage = transform
            .toFormat(format)
            .extract({ left: x, top: y, width: width, height: height })
            .resize(displayWidth, displayHeight);
        return transformedImage;
    } else {
        return " Invalid dimension !";

    }

}

 --  But got an error : 

Error: extract_area: bad extract area

Emitted 'error' event on Sharp instance at:
    at Object.<anonymous> (E:\PB\photobook\serverside\node_modules\sharp\lib\output.js:1090:16)
    at Object.callbackTrampoline (internal/async_hooks.js:131:14)
[nodemon] app crashed - waiting for file changes before starting... 

[BadTextAreaError.txt](https://github.com/lovell/sharp/files/8480616/BadTextAreaError.txt)

Please suggest us to fix this issue.

**Comment by lovell** [comment]
Please provide a more minimal, standalone code sample, without other dependencies (no express, no axios etc.) and a sample image.
