### ISSUE TITLE
Core dumps with sharp 0.30.6 on AWS Graviton 2/3

### ISSUE THREAD

**Issue by asilvas-godaddy** [lovell/sharp#3257]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Linux 4.14 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (2) arm64 unknown
    Memory: 3.08 GB / 3.81 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    npm: 8.11.0 - /usr/bin/npm
```

### What are the steps to reproduce?

This is a segmentation fault (resulting in core dumps) in production, so unfortunately I do not (yet) have repro steps. Our system leverages clustering/forking, so we recently determined that we've been doing core dumps for months and didn't know it. So I don't yet know what version this started with. We've only seen the issue in production, on both Graviton 2 and Graviton 3 hardware. I'll update this issue as soon as I can figure out the best way to isolate to specific image+operations, but wanted to post these details in case the stack trace is of any use.

### What is the expected behaviour?

No core dumps.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

I'm still investigating but here's some details from a core dump (we have thousands of them) in case it's more obvious to you:

```
> gdb node core.14
Reading symbols from node...
[New LWP 2736]
[New LWP 21]
[New LWP 24]
[New LWP 26]
[New LWP 23]
[New LWP 43]
[New LWP 56]
[New LWP 53]
[New LWP 2752]
[New LWP 55]
[New LWP 54]
[New LWP 25]
[New LWP 2753]
[New LWP 2751]
[New LWP 14]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/node /src/node_modules/.bin/cservice ./lib/worker.js'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=281472328523984, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44      pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0xffff6227e0d0 (LWP 2736))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=281472328523984, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x0000ffff8196e394 in __pthread_kill_internal (signo=<optimized out>, threadid=<optimized out>) at pthread_kill.c:80
#2  0x0000ffff819291bc in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000ffff81915f70 in __GI_abort () at abort.c:79
#4  0x0000ffff819622f8 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0xffff81a44280 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x0000ffff8197891c in malloc_printerr (str=str@entry=0xffff81a3fba8 "malloc(): invalid size (unsorted)") at malloc.c:5543
#6  0x0000ffff8197b65c in _int_malloc (av=av@entry=0xffff3c000020, bytes=bytes@entry=14928) at malloc.c:3889
#7  0x0000ffff8197d450 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3566
#8  0x0000ffff624b6c94 in vips_tracked_malloc () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#9  0x0000ffff625cab50 in vips_buffer_new () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#10 0x0000ffff624be80c in vips_region_buffer () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#11 0x0000ffff6258a734 in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#12 0x0000ffff6258aa1c in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#13 0x0000ffff624be208 in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#14 0x0000ffff624bed90 in vips_region_fill () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#15 0x0000ffff624c83f0 in vips_region_prepare () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#16 0x0000ffff6258762c in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#17 0x0000ffff624be208 in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#18 0x0000ffff624bed90 in vips_region_fill () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#19 0x0000ffff624c83f0 in vips_region_prepare () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#20 0x0000ffff624b1d98 in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#21 0x0000ffff624bf49c in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#22 0x0000ffff624c8604 in vips_region_prepare_to () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#23 0x0000ffff624ca47c in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#24 0x0000ffff624cf37c in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#25 0x0000ffff624cf080 in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#26 0x0000ffff62d6dc14 in ?? () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#27 0x0000ffff62d6d39c in g_thread_proxy () from /src/node_modules/sharp/build/Release/../.././vendor/8.12.2/linux-arm64v8/lib/libvips-cpp.so.42
#28 0x0000ffff8196c69c in start_thread (arg=<optimized out>) at pthread_create.c:435
#29 0x0000ffff819d4d1c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```

### Please provide sample image(s) that help explain this problem

None yet.

**Comment by asilvas-godaddy** [comment]
I suspect this be an issue with libvips, but thought I'd post here first. If you prefer me posting the issue there let me know.

**Comment by lovell** [comment]
If you can narrow it down to palette-based PNG input, given it occurs on arm64, then this is likely to relate to #3225

**Comment by asilvas-godaddy** [comment]
I was able to repro on ARM only so I'll close this issue in favor of the original. 

  > malloc(): corrupted top size
  > Aborted (core dumped)
