### ISSUE TITLE
Dockerfile installation have been failed while yarn install with --modules-folder flag

### ISSUE THREAD

**Issue by igor-sitnikov** [lovell/sharp#3297]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

Dockerfile
```Dockerfile
FROM node:14.15.0 as builder
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn && yarn install --production --modules-folder ./modules
COPY tsconfig.build.json .
COPY tsconfig.json .
COPY config ./config
COPY src ./src
RUN yarn build

FROM node:14.15.0
WORKDIR /app
COPY --from=0 /app/modules /app/node_modules
COPY --from=0 /app/dist /app/
EXPOSE 80
CMD node src/main.js
```

Output:
```bash
error /app/modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /app/modules/sharp
Output:
sharp: Using cached /root/.npm/_libvips/libvips-8.12.2-linux-x64.tar.br
sharp: Integrity check passed for linux-x64
/bin/sh: 1: prebuild-install: not found
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.0 | linux | x64
gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v14.15.0/node-v14.15.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.15.0/node-v14.15.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.15.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.15.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/app/modules/sharp/build'
  CC(target) Release/obj.target/nothing/../../node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/../../node_modules/node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
../src/common.cc:24:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp-linux-x64.target.mk:139: recipe for target 'Release/obj.target/sharp-linux-x64/src/common.o' failed
make: *** [Release/obj.target/sharp-linux-x64/src/common.o] Error 1
make: Leaving directory '/app/modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-48-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/modules/sharp
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
The command '/bin/sh -c yarn && yarn install --production --modules-folder ./modules' returned a non-zero code: 1
script returned exit code 1
```

If I am using `yarn install` without `--modules-folder` flag it's all ok.

**Comment by lovell** [comment]
> /bin/sh: 1: prebuild-install: not found

`prebuild-install` is a declared dependency of `sharp`, so it looks like there is a problem (bug?) with `yarn` when used with the `--modules-folder` flag. Perhaps ask the yarn maintainers? You'll need to include more details such as the version of yarn etc.

**Comment by igor-sitnikov** [comment]
Yarn version 

> > /bin/sh: 1: prebuild-install: not found
> 
> `prebuild-install` is a declared dependency of `sharp`, so it looks like there is a problem (bug?) with `yarn` when used with the `--modules-folder` flag. Perhaps ask the yarn maintainers? You'll need to include more details such as the version of yarn etc.

Yarn version is 1.22.5 in this docker image of node

**Comment by lovell** [comment]
https://github.com/yarnpkg/yarn/issues/7467 appears to be related, and this is unlikely to be a problem with sharp itself.

If you want to use yarn, perhaps try the latest yarn v2 as it is well-maintained - see https://yarnpkg.com/getting-started/migration

**Comment by lovell** [comment]
Closing as this appears to be a bug in older versions of yarn, unrelated to sharp.
