### ISSUE TITLE
`npm install` fails on CentOS release 6.5

### ISSUE THREAD

**Issue by Lanfei** [lovell/sharp#342]
Here is the error log:

```shell
\
> sharp@0.12.2 install /home/me/sharp/node_modules/sharp
> node-gyp rebuild

ERROR: libc version 2.12 requires manual installation - please see http://sharp.dimens.io/en/stable/install/
gyp: Call to 'LDD_VERSION="ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
由 Roland McGrath 和 Ulrich Drepper 编写。" node -e "require('./binding').download_vips()"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.el6.centos.plus.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/me/sharp/node_modules/sharp
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-431.el6.centos.plus.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.12.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.12.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/sharp/npm-debug.log
```

**Comment by lovell** [comment]
> ERROR: libc version 2.12 requires manual installation - please see http://sharp.dimens.io/en/stable/install/

Centos 6 requires a manual installation of libvips - please read the "For older Linux-based operating systems..." section of http://sharp.dimens.io/en/stable/install/#linux

**Comment by helloqhx** [comment]
I have manually installed vips, but it still report this error: 
```
 ERROR: libc version 2.12 requires manual installation - please see http://sharp.dimens.io/en/stable/install/
gyp: Call to 'LDD_VERSION="ldd (GNU libc) 2.12
```

I am on Centos 6.5. 
Can anyone help?

**Comment by lovell** [comment]
@helloqhx Please open a new issue if you're still having problems after you have confirmed that libvips is correctly installed by running `pkg-config --modversion vips-cpp`.
