### ISSUE TITLE
Error in the installation of the package.

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [lovell/sharp#3498]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

```shell
> sharp@0.31.2 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

npm http fetch GET 200 https://registry.npmjs.org/ssri 1589ms (cache revalidated)
npm timing metavuln:packument:ssri Completed in 1592ms
npm timing metavuln:load:security-advisory:ssri:1068080 Completed in 0ms
npm timing metavuln:calculate:security-advisory:ssri:1068080 Completed in 1595ms
npm http fetch GET 200 https://registry.npmjs.org/eventsource 1692ms (cache revalidated)
npm timing metavuln:packument:eventsource Completed in 1697ms
npm timing metavuln:load:security-advisory:eventsource:1085188 Completed in 0ms
npm timing metavuln:calculate:security-advisory:eventsource:1085188 Completed in 1703ms
npm timing metavuln:cache:get:security-advisory:acorn-jsx:n6P77XUp00uEFW9RAIzmXCrN0gZ9n4lPjqtRlMUaALmndVEWV98n2KvUCqShGvLjV/hcmGtHzyFgXrGIUtT36g== Completed in 17ms
npm timing metavuln:cache:get:security-advisory:espree:r8JsGjYkaZwRuwRjChhj1fqHtV0PROzHTeNyFo8CdGV3D5VU0t9cqBShd+HIv+8+7o+U85Hq20evQxKmk5oDRw== Completed in 13ms
npm http fetch GET 200 https://registry.npmjs.org/espree 73ms (cache revalidated)
npm timing metavuln:packument:espree Completed in 81ms
npm timing metavuln:load:security-advisory:espree:oOSm3JTV9ocgAFf02dgmctzJ8gmQo7xZYv78kSRaIV+7fAMRpLITh82bvKDsSydGbeHvmiCI9FdfqERb4vnqYA== Completed in 2ms
npm timing metavuln:calculate:security-advisory:espree:oOSm3JTV9ocgAFf02dgmctzJ8gmQo7xZYv78kSRaIV+7fAMRpLITh82bvKDsSydGbeHvmiCI9FdfqERb4vnqYA== Completed in 92ms
npm http fetch GET 200 https://registry.npmjs.org/acorn-jsx 100ms (cache revalidated)
npm timing metavuln:packument:acorn-jsx Completed in 110ms
npm timing metavuln:load:security-advisory:acorn-jsx:oOSm3JTV9ocgAFf02dgmctzJ8gmQo7xZYv78kSRaIV+7fAMRpLITh82bvKDsSydGbeHvmiCI9FdfqERb4vnqYA== Completed in 0ms
npm timing metavuln:calculate:security-advisory:acorn-jsx:oOSm3JTV9ocgAFf02dgmctzJ8gmQo7xZYv78kSRaIV+7fAMRpLITh82bvKDsSydGbeHvmiCI9FdfqERb4vnqYA== Completed in 120ms
npm timing metavuln:cache:get:security-advisory:webpack:lFFfnwKbrZLJIaaNH0dzfm40Aeo9oLYvyqPB7PjDSkqMWTh2EtpMtF+/0XkFGD4lcCeYyBGRk6aCQTV+ALPqTA== Completed in 8ms
sharp: Using cached /home/codespace/.npm/_libvips/libvips-8.13.3-linux-x64.tar.br
npm http fetch GET 200 https://registry.npmjs.org/webpack 59ms (cache revalidated)
npm timing metavuln:packument:webpack Completed in 89ms
npm timing metavuln:load:security-advisory:webpack:C5dqjQQVkTKt6D4DBWU6CX16jcxaYMk6e19hUeK6VJoL8KvIkp4IdTsvHJHpYwsVd1PFKmfQ+UrZdXZypAiI0A== Completed in 8ms
npm timing metavuln:calculate:security-advisory:webpack:C5dqjQQVkTKt6D4DBWU6CX16jcxaYMk6e19hUeK6VJoL8KvIkp4IdTsvHJHpYwsVd1PFKmfQ+UrZdXZypAiI0A== Completed in 97ms
npm timing metavuln:cache:get:security-advisory:ajv-errors:777ONjR289I9nuULAxcJ3BaboHmHv3DOBVzOtLcTxg4TdcWJa430wUoE28EdYPZakpYGDiCNMAThLHq1QNsuLA== Completed in 39ms
npm timing metavuln:cache:get:security-advisory:ajv-keywords:AWwClhk57aFpWL4yPfw4ZZGo4g4tfLIayXCVWoDWbFgWs4h4tsL8RUdOldtt1cs6k70DDVwTkimFpzCHx8aSHA== Completed in 38ms
npm timing metavuln:cache:get:security-advisory:eslint:JGCV0/QgI95iHLqPsA6v2kEsQrgX9SkG0hceBukfivz1kLM1qGXhsPwTmxv25xbL0dB8oJEqGVw6gEikvKqlXQ== Completed in 37ms
npm timing metavuln:cache:get:security-advisory:har-validator:MjwYCkRQGrq5ph8MC+C4hOIcaimvkunLx7y9vPVysnVODTVnAETB67er8zum5wwT/y7Wo5NFagLdKaVsFzJyPg== Completed in 34ms
npm timing metavuln:cache:get:security-advisory:table:D87Ifua/Z0fG+uW0zWyDGH7GNL9AtGYBpBQ+RqFRh1ERmLXALpCKCfOv7Hj6OcbMig/FYK1RUyaeWg4jHM1N7A== Completed in 36ms
npm timing metavuln:cache:get:security-advisory:webpack:5Z2iNBex7P8yaZfJMW5OviKozRU9PoZ8dPJ1eBCRwAnT42c0w6BVJY5IBvNiKyN9yVpSmmgyiYesMXO1Z7OwHg== Completed in 35ms
npm timing metavuln:load:security-advisory:webpack:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 19ms
npm timing metavuln:calculate:security-advisory:webpack:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 57ms
npm timing metavuln:cache:get:security-advisory:schema-utils:k4yw95AS2dApSMpxXlHBkKmG9Tu+oZYOJgW2J8jEirlK3bawHNOuNnEx6mscwskJJilRE9pcjyBdVN0KcVNvww== Completed in 69ms
npm http fetch GET 200 https://registry.npmjs.org/ajv-keywords 164ms (cache revalidated)
npm timing metavuln:packument:ajv-keywords Completed in 171ms
npm timing metavuln:load:security-advisory:ajv-keywords:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 0ms
npm timing metavuln:calculate:security-advisory:ajv-keywords:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 175ms
npm http fetch GET 200 https://registry.npmjs.org/schema-utils 184ms (cache revalidated)
npm timing metavuln:packument:schema-utils Completed in 192ms
npm timing metavuln:load:security-advisory:schema-utils:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 1ms
npm timing metavuln:calculate:security-advisory:schema-utils:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 197ms
npm http fetch GET 200 https://registry.npmjs.org/eslint 209ms (cache revalidated)
npm timing metavuln:packument:eslint Completed in 225ms
npm timing metavuln:load:security-advisory:eslint:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 2ms
npm timing metavuln:calculate:security-advisory:eslint:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 231ms
npm http fetch GET 200 https://registry.npmjs.org/har-validator 231ms (cache revalidated)
npm timing metavuln:packument:har-validator Completed in 235ms
npm timing metavuln:load:security-advisory:har-validator:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 0ms
npm timing metavuln:calculate:security-advisory:har-validator:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 238ms
npm http fetch GET 200 https://registry.npmjs.org/table 252ms (cache revalidated)
npm timing metavuln:packument:table Completed in 256ms
npm timing metavuln:load:security-advisory:table:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 0ms
npm timing metavuln:calculate:security-advisory:table:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 260ms
sharp: Integrity check passed for linux-x64ming metavuln:calculate:security-advisory:table:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qg
prebuild-install info begin Prebuild-install version 5.3.3alculate:security-advisory:table:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qg
prebuild-install info install installing standalone, skipping download.
npm http fetch GET 200 https://registry.npmjs.org/ajv-errors 1055ms (cache revalidated)
npm timing metavuln:packument:ajv-errors Completed in 1060ms
npm timing metavuln:load:security-advisory:ajv-errors:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 0ms
npm timing metavuln:calculate:security-advisory:ajv-errors:pk6D4XR39ziIMbDEFZfKM7JcZugIUmmXoBl5ax9Osq1viKxIbFGIsZDu1fg+0cZd/qgMXwjim4M8umrkivlndw== Completed in 1070ms
npm timing metavuln:cache:get:security-advisory:strip-ansi:2brmEU/c99vXHahRtz/2fKlYidZKrcq1EXDS1prvgVVQ6iwinLx/zCpV8zYS7EDde98i0PP2mhdGTQNMNcd7+g== Completed in 10ms
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 80ms (cache revalidated)
npm timing metavuln:packument:strip-ansi Completed in 84ms
npm timing metavuln:load:security-advisory:strip-ansi:w6a0jOnF5wiMWlEmi/FuYMIAZRWIToivbLUvTJsuyRYnGkGzwzS3pGdZCiEvJihlOxs9BL+lznR6kNy9ZTohOw== Completed in 0ms
npm timing metavuln:calculate:security-advisory:strip-ansi:w6a0jOnF5wiMWlEmi/FuYMIAZRWIToivbLUvTJsuyRYnGkGzwzS3pGdZCiEvJihlOxs9BL+lznR6kNy9ZTohOw== Completed in 89ms
npm timing metavuln:cache:get:security-advisory:strip-ansi:Hr4YODCbKm36J/ta0pDEPr9PT2am+xMwq5ygT88nqHkVl1F4lktpA9BVmuQT/ZDidVK9GVsfr94HxfaansDQAQ== Completed in 8ms
npm timing metavuln:load:security-advisory:strip-ansi:nqxIQq/gRzJbkjHNgjQCIqFDZnRBBW1OOAgF+awVXjgfzro0Mdu/1M84naYPOI+7QWWgtO01zM+iLNpLWxwMng== Completed in 0ms
npm timing metavuln:calculate:security-advisory:strip-ansi:nqxIQq/gRzJbkjHNgjQCIqFDZnRBBW1OOAgF+awVXjgfzro0Mdu/1M84naYPOI+7QWWgtO01zM+iLNpLWxwMng== Completed in 11ms
npm timing metavuln:cache:get:security-advisory:strip-ansi:vgUumB0e0DcJV+OC5Aj3UrT0Kwuefjk/oqeoh8GE4hGuqPEcLYuxXXS+KXQGCpQMYNB/GL0qExfzmPytOobr3Q== Completed in 3ms
npm timing metavuln:load:security-advisory:strip-ansi:PEOPAeu7LCM6HibYOLdR6T/e+q6kjtFRlmyAVs/Z9xVJ0BImaWqsE9Z41mJmV6FqXkcQSTQlEX5SXaGfygCeBQ== Completed in 0ms
npm timing metavuln:calculate:security-advisory:strip-ansi:PEOPAeu7LCM6HibYOLdR6T/e+q6kjtFRlmyAVs/Z9xVJ0BImaWqsE9Z41mJmV6FqXkcQSTQlEX5SXaGfygCeBQ== Completed in 7ms
npm timing metavuln:cache:get:security-advisory:webpack-dev-server:zZOqqUVC+wwRYx8P2ap/S+vcwvryj2ycoDrLfX0pN+XRW7dL3V3yNgPfcoTnkzi5k0RxfeKayv8nny6AkliksQ== Completed in 33ms
npm timing metavuln:cache:get:security-advisory:webpack-hot-middleware:9pO6RrT/ldPvRPWsFl77k+rx+AkofjIONLHmt1ZR8OSDHW0ZHUHpgfNgSp4iOAraZPWM2w138AAauSPZn3SRTA== Completed in 35ms
npm http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 80ms (cache revalidated)
npm timing metavuln:packument:webpack-dev-server Completed in 90ms
npm timing metavuln:load:security-advisory:webpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1PPD2GuC74XInCX+tsVT4EvSLTx4PLfIfw== Completed in 1ms
npm timing metavuln:calculate:security-advisory:webpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1PPD2GuC74XInCX+tsVT4EvSLTx4PLfIfw== Completed in 93ms
gyp info it worked if it ends with okpt: timing metavuln:calculate:security-advisory:webpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1P
gyp verb cli [
gyp verb cli   '/usr/local/share/nvm/versions/node/v16.18.1/bin/node',
gyp verb cli   '/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@9.1.0
gyp info using node@16.18.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []typescript: timing metavuln:calculate:security-advisory:webpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1P
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/home/codespace/.python/current/bin/python3"bpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1P
gyp verb find Python - executing "/home/codespace/.python/current/bin/python3" to get version
gyp verb find Python - version is "3.10.4"iming metavuln:calculate:security-advisory:webpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1P
gyp info find Python using Python version 3.10.4 found at "/home/codespace/.python/current/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 16.18.1
gyp verb command install [ '16.18.1' ]
gyp verb install input version string "16.18.1" metavuln:calculate:security-advisory:webpack-dev-server:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1P
gyp verb install installing version: 16.18.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.18.1
gyp verb build dir attempting to create "build" dir: /workspaces/WTM-Algiers-Website/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb python symlink creating symlink to "/home/codespace/.python/current/bin/python3" at "/workspaces/WTM-Algiers-Website/node_modules/sharp/build/node_gyp_bins/python3"
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /workspaces/WTM-Algiers-Website/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /workspaces/WTM-Algiers-Website/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /workspaces/WTM-Algiers-Website/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /home/codespace/.python/current/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspaces/WTM-Algiers-Website/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/codespace/.cache/node-gyp/16.18.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/codespace/.cache/node-gyp/16.18.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/codespace/.cache/node-gyp/16.18.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspaces/WTM-Algiers-Website/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
npm http fetch GET 200 https://registry.npmjs.org/webpack-hot-middleware 1027ms (cache revalidated)
npm timing metavuln:packument:webpack-hot-middleware Completed in 1030ms
npm timing metavuln:load:security-advisory:webpack-hot-middleware:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1PPD2GuC74XInCX+tsVT4EvSLTx4PLfIfw== Completed in 1ms
npm timing metavuln:calculate:security-advisory:webpack-hot-middleware:ZpJdCL1EP0gL/UKZl98/nzVfS7Q0mplNG9BBEsBvNPwCiA7M0GPn1PPD2GuC74XInCX+tsVT4EvSLTx4PLfIfw== Completed in 1031ms
npm timing metavuln:cache:get:security-advisory:gh-pages:eJ/fWxerJUUtuDT5oZPwNJ2I6Kd4SInJshs9B6aP9yDRC/o5/hepVqeMfRvssrMV3IH3b2mnsCl/yztPQe6sJw== Completed in 7ms
npm timing metavuln:cache:get:security-advisory:gatsby-plugin-sharp:aqm3YIC7ad1PH9Q1BOelIEyqhsm8K4jpSgnU+/el+o2IPLi527zkz789TKxFfvKvJ+lj0gObnkV1qOrH0oNRPQ== Completed in 9ms
npm timing metavuln:cache:get:security-advisory:portfinder:Y6xe/dIHlyFosCYoYOjmUsrKu6LV4YfFeMpaB+as4xmY4shNVxLQGwt9svz99iJNQYrqa6ehIDPr44UYtoFvaw== Completed in 7ms
npm http fetch GET 200 https://registry.npmjs.org/gatsby-plugin-sharp 51ms (cache revalidated)
npm timing metavuln:packument:gatsby-plugin-sharp Completed in 70ms
npm timing metavuln:load:security-advisory:gatsby-plugin-sharp:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oIfGDsakqIO9PRUnXLBFUUgUDA== Completed in 14ms
npm timing metavuln:calculate:security-advisory:gatsby-plugin-sharp:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oIfGDsakqIO9PRUnXLBFUUgUDA== Completed in 88ms
npm http fetch GET 200 https://registry.npmjs.org/portfinder 118ms (cache revalidated)
npm timing metavuln:packument:portfinder Completed in 122ms
npm timing metavuln:load:security-advisory:portfinder:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oIfGDsakqIO9PRUnXLBFUUgUDA== Completed in 2ms
npm timing metavuln:calculate:security-advisory:portfinder:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oIfGDsakqIO9PRUnXLBFUUgUDA== Completed in 130ms
gyp verb command build []ify:typescript: timing metavuln:calculate:security-advisory:portfinder:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oI
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/codespace/.cache/node-gyp/16.18.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp verb bin symlinks adding symlinks (such as Python), at "/workspaces/WTM-Algiers-Website/node_modules/sharp/build/node_gyp_bins", to PATH
gyp info spawn make) ⠴ reify:typescript: timing metavuln:calculate:security-advisory:portfinder:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oI
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/workspaces/WTM-Algiers-Website/node_modules/sharp/build'
  cc -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/home/codespace/.cache/node-gyp/16.18.1/include/node -I/home/codespace/.cache/node-gyp/16.18.1/src -I/home/codespace/.cache/node-gyp/16.18.1/deps/openssl/config -I/home/codespace/.cache/node-gyp/16.18.1/deps/openssl/openssl/include -I/home/codespace/.cache/node-gyp/16.18.1/deps/uv/include -I/home/codespace/.cache/node-gyp/16.18.1/deps/zlib -I/home/codespace/.cache/node-gyp/16.18.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c
  rm -f Release/obj.target/../node-addon-api/nothing.a && ar crs Release/obj.target/../node-addon-api/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.o
  ln -f "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a" 2>/dev/null || (rm -rf "Release/nothing.a" && cp -af "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a")
  touch Release/obj.target/libvips-cpp.stamp
  g++ -o Release/obj.target/sharp-linux-x64/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp-linux-x64' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=7' '-DBUILDING_NODE_EXTENSION' -I/home/codespace/.cache/node-gyp/16.18.1/include/node -I/home/codespace/.cache/node-gyp/16.18.1/src -I/home/codespace/.cache/node-gyp/16.18.1/deps/openssl/config -I/home/codespace/.cache/node-gyp/16.18.1/deps/openssl/openssl/include -I/home/codespace/.cache/node-gyp/16.18.1/deps/uv/include -I/home/codespace/.cache/node-gyp/16.18.1/deps/zlib -I/home/codespace/.cache/node-gyp/16.18.1/deps/v8/include -I../../node-addon-api -I../vendor/8.13.3/linux-x64/include -I../vendor/8.13.3/linux-x64/include/glib-2.0 -I../vendor/8.13.3/linux-x64/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++14 -std=c++0x -fexceptions -Wall -Os -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp-linux-x64/src/common.o.d.raw   -c
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
   24 | #include <vips/vips8>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [sharp-linux-x64.target.mk:139: Release/obj.target/sharp-linux-x64/src/common.o] Error 1
make: Leaving directory '/workspaces/WTM-Algiers-Website/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 5.4.0-1094-azure
gyp ERR! command "/usr/local/share/nvm/versions/node/v16.18.1/bin/node" "/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /workspaces/WTM-Algiers-Website/node_modules/sharp
gyp ERR! node -v v16.18.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
npm info run sharp@0.31.2 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 98ms
npm timing reify:rollback:retireShallow Completed in 8ms
npm timing command:install Completed in 10935ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/share/nvm/versions/node/v16.18.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:513:28)
npm verb stack     at maybeClose (node:internal/child_process:1100:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm verb pkgid sharp@0.31.2
npm verb cwd /workspaces/WTM-Algiers-Website
npm verb Linux 5.4.0-1094-azure
npm verb node v16.18.1
npm verb npm  v8.19.2
npm ERR! code 1
npm ERR! path /workspaces/WTM-Algiers-Website/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm timing npm Completed in 11055ms
npm verb unfinished npm timer reify 1671288322127
npm verb unfinished npm timer reify:audit 1671288327737
npm verb unfinished npm timer auditReport:init 1671288328202
npm verb unfinished npm timer reify:build 1671288329744
npm verb unfinished npm timer build 1671288329746
npm verb unfinished npm timer build:deps 1671288329746
npm verb unfinished npm timer build:run:install 1671288329778
npm verb unfinished npm timer build:run:install:node_modules/sharp 1671288329778
npm verb unfinished npm timer metavuln:calculate:security-advisory:gh-pages:NoY+wHSsYG5BJzubpo0NM5+Am38MB0xXBYpP3OCsv9cT/J569BSmluVTaeA9oIfGDsakqIO9PRUnXLBFUUgUDA== 1671288332373
npm verb unfinished npm timer metavuln:packument:gh-pages 1671288332374
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2022-12-17T14_45_22_009Z-debug-0.log
```

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```shell
  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 2.28 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/nvm/current/bin/npm
```

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory? (The log provided above mentions dependencies unrelated to sharp so was unlikely to have been run in an otherwise empty directory.)

**Comment by lovell** [comment]
@AyushAgnihotri2025 Were you able to make any progress with this?

**Comment by AyushAgnihotri2025** [comment]
Yes, there was some conflicting packages so, removing them helped me out. Thanks a lot and sorry, I forgot to update the same here.
