### ISSUE TITLE
after install error  Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by 82318179** [lovell/sharp#3500]
App threw an error during load

Error:
Something went wrong installing the "sharp" module

Could not dynamically require "../build/Release/sharp-win32-x64.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at D:\Dev\\out\main\index.js:7424:11
    at Object.<anonymous> (D:\Dev\cbrowser_plus\out\main\index.js:7426:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at loadApplicationPackage (D:\Dev\\node_modules\.pnpm\registry.npmmirror.com+electron@21.3.1\node_modules\electron\dist\resources\default_app.asar\main.js:121:16)
    at Object.<anonymous> (D:\Dev\\node_modules\.pnpm\registry.npmmirror.com+electron@21.3.1\node_modules\electron\dist\resources\default_app.asar\main.js:233:9)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

**Comment by lovell** [comment]
Hello, it looks like you previously opened issue #3275, which ignored the issue template and then appeared to ignore my help.

This issue has also ignored/deleted the issue template. Please ensure you complete the information requested in issue templates, as doing so makes it much easier for volunteer maintainers of open source software to help you, as well as making sure neither your time nor mine is wasted.

In this case it looks like you're using rollup, and the error message you've provided says:

> Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

Have you tried doing what the error message suggests? A quick search suggests https://github.com/rollup/plugins/tree/master/packages/commonjs#dynamicrequiretargets is relevant here. Does adding sharp to the `dynamicRequireTargets` property work? If not, what else have you tried? Please provide as much information as possible e.g. I can also see reference to Electron and ASAR in here, so there are a lot of moving parts.

**Comment by lovell** [comment]
@82318179 Were you able to make any progress with this? If further help is required, please provide the requested information.

**Comment by lovell** [comment]
Closing as subsequent question #3533 suggests progress was made.
