### ISSUE TITLE
Issue with "npm install" on Gatsby project

### ISSUE THREAD

**Issue by sean-she** [lovell/sharp#3529]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
N/A

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?
Yes

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
N/A

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

```
npm verb cli /opt/homebrew/Cellar/node/19.4.0/bin/node /opt/homebrew/bin/npm
npm info using npm@9.2.0
npm info using node@v19.4.0
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/Users/seanshe/.npm/_logs/2023-01-15T08_47_26_254Z-
npm verb logfile /Users/seanshe/.npm/_logs/2023-01-15T08_47_26_254Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 32ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 175ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 177ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 177ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 179ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 290ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/minimist 32ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 34ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/rc 33ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 49ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 58ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 61ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/pump 64ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 67ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 101ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 105ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 115ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 115ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 124ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 117ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/once 119ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 127ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 215ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 229ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 38ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 43ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 45ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 43ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 41ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 45ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ini 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/wrappy 45ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yallist 43ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 194ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/inherits 50ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/bl 52ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 54ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 57ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer 44ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 44ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 56ms (cache revalidated)
npm info run sharp@0.31.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.31.3 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached /Users/seanshe/.npm/_libvips/libvips-8.13.3-darwin-arm64v8.tar.br
sharp: Integrity check passed for darwin-arm64v8rp@0.31.3 install node_modules/
prebuild-install info begin Prebuild-install version 7.1.1install node_modules/
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.31.3-napi-v7-darwin-arm64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/seanshe/.npm/_prebuilds/38f0e9-sharp-v0.31.3-napi-v7-darwin-arm64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /Users/seanshe/.npm/_prebuilds/38f0e9-sharp-v0.31.3-napi-v7-darwin-arm64.tar.gz
prebuild-install info unpack resolved to /Users/seanshe/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
prebuild-install info install Successfully installed prebuilt binary!
npm info run sharp@0.31.3 install { code: 0, signal: null }

added 45 packages in 4s

10 packages are looking for funding
  run `npm fund` for details
npm verb exit 0
npm info ok 
```

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 62.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  npmGlobalPackages:
    sharp: 0.31.3
```
## Context

Hello. I've recently cloned a project that my group is working on onto my device and I ran into this issue when running "npm i". I've looked through previous tickets relating to this error and tried the fixes. For example, I've tried deleting the tar.br file (previous post had tar.bg), installing vips via HomeBrew, but those didn't work for me. 

The error message after running "npm i":
```
npm ERR! code 1
npm ERR! path /Users/seanshe/Desktop/bdab_website/node_modules/gatsby-transformer-sharp/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-arm64v8.tar.br
npm ERR! ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for darwin-arm64v8
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.4.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/seanshe/Desktop/bdab_website/node_modules/gatsby-transformer-sharp/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/seanshe/Library/Caches/node-gyp/19.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/seanshe/Library/Caches/node-gyp/19.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/seanshe/Library/Caches/node-gyp/19.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/seanshe/Desktop/bdab_website/node_modules/gatsby-transformer-sharp/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.2.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.4.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/seanshe/Desktop/bdab_website/node_modules/gatsby-transformer-sharp/node_modules/sharp
npm ERR! gyp ERR! node -v v19.4.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanshe/.npm/_logs/2023-01-15T08_56_23_970Z-debug-0.log
```
The error seems to be in the "gatsby-transformer-sharp" module, so I tried running "npm update gatsby-transformer-sharp module" to see if anything would happen, and gave me this error:

```
npm ERR! code 1
npm ERR! path /Users/seanshe/Desktop/bdab_website/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-arm64v8.tar.br
npm ERR! ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for darwin-arm64v8
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.4.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/seanshe/Desktop/bdab_website/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/seanshe/Library/Caches/node-gyp/19.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/seanshe/Library/Caches/node-gyp/19.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/seanshe/Library/Caches/node-gyp/19.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/seanshe/Desktop/bdab_website/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.2.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.4.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/seanshe/Desktop/bdab_website/node_modules/sharp
npm ERR! gyp ERR! node -v v19.4.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanshe/.npm/_logs/2023-01-15T09_26_36_750Z-debug-0.log
```

<details>
<summary> Side "fix" that didn't work </summary>
One possible fix that was suggested to me was that I switch my node version to 14.15.0 (via nvm), in which I was able to get "npm i" to work, but ran into an issue when running "gatsby develop":
<br>
'darwin-x64' binaries cannot be used on the 'darwin-arm64v8' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'darwin-arm64v8' platform.
</details>

Any help is appreciated, thank you!

**Comment by lovell** [comment]
> npm ERR! ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for darwin-arm64v8
> npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error

As I said in #3525, please upgrade.

It looks like the version of `gatsby-transformer-sharp` you're using is out of date. It appears to be using an old version of sharp that does not support M1.

https://sharp.pixelplumbing.com/install#apple-m1

**Comment by sean-she** [comment]
Thanks for getting back to me.

This might be a dumb question, but what do you mean by upgrade? I've tried running the command `npm install --arch=arm64 --platform=darwin --libc=glibc sharp` which doesn't seem to fix my issue.

**Comment by lovell** [comment]
You'll need to ensure you're using a version of sharp that supports M1.

https://sharp.pixelplumbing.com/install#apple-m1

> Prebuilt sharp and libvips binaries have been provided for macOS on ARM64 since sharp v0.29.0.

Running `npm ls sharp` in the `/Users/seanshe/Desktop/bdab_website` directory will help highlight the dependency/ies that require upgrading, which you can do by editing the relevant `package.json` file and running `npm install` again.

For example, the most recent `gatsby-transformer-sharp` is v5.4.0, so please ensure you're using that version.

```sh
$ npm view gatsby-transformer-sharp dist-tags.latest
5.4.0
```

**Comment by sean-she** [comment]
I see. I got it working now. Thank you so much for your help!
