### ISSUE TITLE
Firebase Deploy => "Something went wrong installing the "sharp" module"

### ISSUE THREAD

**Issue by ohabash** [lovell/sharp#3607]
sharp: `^0.32.0`
npm: `v16.19.1`

I am making a Firebase cloud function with `sharp` as a dependency. I am unable to deploy due to build errors. Im sorry in advanced as i am see other threads about this problem but the documentation is a bit greek to me. so thanks for your patience. 

`firebase deploy` results in the following error 

```
Error: Error occurred while parsing your function triggers.

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-x64.node'
Require stack:
- /Users/omarhabash/Sites/habitat_commons_nx/functions/node_modules/sharp/lib/sharp.js
- /Users/omarhabash/Sites/habitat_commons_nx/functions/node_modules/sharp/lib/constructor.js
- /Users/omarhabash/Sites/habitat_commons_nx/functions/node_modules/sharp/lib/index.js
- /Users/omarhabash/Sites/habitat_commons_nx/functions/lib/index.js
- /Users/omarhabash/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/deploy/functions/runtimes/node/triggerParser.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/omarhabash/Sites/habitat_commons_nx/functions/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1890:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/omarhabash/Sites/habitat_commons_nx/functions/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1890:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by ohabash** [comment]
thank you for this answer. 

@lovell 

can you confirm that the part of the error `Require stack:` is written by sharp? 
the file paths point to my local machine. Would you expect those paths to be from a vm?

**Comment by ohabash** [comment]
I am seeking help from the firebase team. I wonder if you agree with my perception of the problem? Thank you.

https://github.com/firebase/firebase-functions/issues/1372

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

**Comment by ohabash** [comment]
If i 

```
❯ npm install --verbose --foreground-scripts sharp
npm verb cli /Users/omarhabash/.nvm/versions/node/v16.19.1/bin/node /Users/omarhabash/.nvm/versions/node/v16.19.1/bin/npm
npm info using npm@8.19.3
npm info using node@v16.19.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/Users/omarhabash/.nvm/versions/node/v16.19.1/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/Users/omarhabash/Sites/hc_functions/functions/.npmrc Completed in 0ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:/Users/omarhabash/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/omarhabash/.nvm/versions/node/v16.19.1/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 11ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm timing npm:load:setTitle Completed in 5ms
npm timing config:load:flatten Completed in 1ms
npm timing npm:load:display Completed in 4ms
npm verb logfile logs-max:10 dir:/Users/omarhabash/.npm/_logs
npm verb logfile /Users/omarhabash/.npm/_logs/2023-04-03T17_54_40_274Z-debug-0.log
npm timing npm:load:logFile Completed in 3ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 25ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 135ms
npm timing idealTree:userRequests Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 225ms (cache revalidated)
npm timing idealTree:#root Completed in 231ms
npm timing idealTree:node_modules/sharp Completed in 0ms
npm timing idealTree:buildDeps Completed in 231ms
npm timing idealTree:fixDepFlags Completed in 3ms
npm timing idealTree Completed in 374ms
npm timing reify:loadTrees Completed in 374ms
npm timing reify:diffTrees Completed in 12ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reify:unpack Completed in 0ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 0ms
npm timing build:deps Completed in 0ms
npm timing build Completed in 0ms
npm timing reify:build Completed in 1ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 38ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 221ms
npm timing auditReport:getReport Completed in 228ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 228ms
npm timing reify Completed in 620ms

up to date, audited 550 packages in 726ms

94 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 625ms
npm verb exit 0
npm timing npm Completed in 728ms
npm info ok 
```
