### ISSUE TITLE
what's the most memory efficient way to get metadata

### ISSUE THREAD

**Issue by joesong168** [lovell/sharp#3656]
## Question about an existing feature

I would like to get metadata for large image in memory restricted environment. I've tried to use buffer and stream which both consume large amount of memory. Is there a way to get metadata in sharp that is as efficient as vipsheader -a?

**Comment by lovell** [comment]
Image metadata is usually at the start of a file so you could try reading the first _N_ bytes and passing that into sharp. You'll need to experiment with the best value for _N_ as that will depend on your input.

**Comment by joesong168** [comment]
```
    function peek(stream: any, size: number, max: number) {
      return new Promise((resolve, reject) => {
        // const stream = fs.createReadStream(filePath, {
        //     encoding: encoding || 'utf8'
        // });

        let length = 0;
        let chunks: any = [];
        stream.on('readable', () => {
          let chunk;
          while (length < max && (chunk = stream.read(size)) !== null) {
            length += chunk.length;
            chunks.push(chunk);

            if ((length + size) >= max) {
              size = max - length;
            }
          }

          return resolve({
            length: length,
            chunks: chunks
          });
        });
      });
    }


    const result: any = await peek(stream, 1000000, 1000000)
    const buffer = result.chunks
```
Used above code but failed. Is there a general way to 'guess' the N?

[/aws/lambda/devcn-hdcompressAA33BBF2-HmdNF5cVF4sL] 8:28:24 AM 2023-05-04T00:28:24.527Z ded945a2-c162-407a-8707-cff2576c1b10    TRACE   Error: Unsupported input '' of type object when also providing options of type object
    at Sharp._createInputDescriptor (/opt/nodejs/node_modules/sharp/lib/input.js:75:11)
    at new Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:349:29)
    at Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:173:12)
    at Runtime.iLe [as handler] (/var/task/index.js:36:51563)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[/aws/lambda/devcn-hdcompressAA33BBF2-HmdNF5cVF4sL] 8:28:24 AM 2023-05-04T00:28:24.527Z ded945a2-c162-407a-8707-cff2576c1b10    INFO    Error: Unsupported input '' of type object when also providing options of type object
    at Sharp._createInputDescriptor (/opt/nodejs/node_modules/sharp/lib/input.js:75:11)
    at new Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:349:29)
    at Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:173:12)
    at Runtime.iLe [as handler] (/var/task/index.js:36:51563)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by joesong168** [comment]
```
Error: Input Buffer is empty
    at Sharp._createInputDescriptor (/opt/nodejs/node_modules/sharp/lib/input.js:51:13)
    at new Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:349:29)
    at Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:173:12)
    at Runtime.iLe [as handler] (/var/task/index.js:36:51601)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[/aws/lambda/devcn-hdcompressAA33BBF2-HmdNF5cVF4sL] 4:59:12 PM 2023-05-04T08:59:12.666Z a5b63f71-814c-4963-97fb-4c635db1cdbe    INFO    Error: Input Buffer is empty
    at Sharp._createInputDescriptor (/opt/nodejs/node_modules/sharp/lib/input.js:51:13)
    at new Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:349:29)
    at Sharp (/opt/nodejs/node_modules/sharp/lib/constructor.js:173:12)
    at Runtime.iLe [as handler] (/var/task/index.js:36:51601)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I changed according to your suggestion but it doesn't seem to work.

**Comment by joesong168** [comment]
```
    function peek(stream: any, size: number, max: number) {
      return new Promise((resolve, reject) => {
        // const stream = fs.createReadStream(filePath, {
        //     encoding: encoding || 'utf8'
        // });

        let length = 0;
        let chunks: any = [];
        stream.on('readable', () => {
          let chunk;
          while (length < max && (chunk = stream.read(size)) !== null) {
            length += chunk.length;
            chunks.push(chunk);

            if ((length + size) >= max) {
              size = max - length;
            }
          }
          return resolve({
            length: length,
            chunks: Buffer.concat(chunks)
          });
        });
      });
    }

    const result: any = await peek(stream, 1000, 1000)
    const buffer = result.chunks
```
I changed the code to this. It works! Thanks a lot for your suggestion.
