### ISSUE TITLE
fatal error: 'vips/vips8' file not found is back

### ISSUE THREAD

**Issue by shellscape** [lovell/sharp#3670]
The same issue as reported in #1882 seems to be back again. This is running in Ubuntu in a Github action with Node v18 and `pnpm@latest`

## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? n/a

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in? n/a

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

 WARN  Unsupported engine: wanted: {"node":"18.15.0"} (current: {"node":"v18.16.0","pnpm":"8.2.0"})
Scope: all 17 workspace projects
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +2386
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2386, reused 0, downloaded 0, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/runner/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 2386, reused 0, downloaded 55, added 49
Progress: resolved 2386, reused 0, downloaded 95, added 93
Progress: resolved 2386, reused 0, downloaded 170, added 205
Progress: resolved 2386, reused 0, downloaded 246, added 315
Progress: resolved 2386, reused 0, downloaded 336, added 405
Progress: resolved 2386, reused 0, downloaded 407, added 473
Progress: resolved 2386, reused 0, downloaded 503, added 574
Progress: resolved 2386, reused 0, downloaded 557, added 629
Progress: resolved 2386, reused 0, downloaded 625, added 695
Progress: resolved 2386, reused 0, downloaded 719, added 789
Progress: resolved 2386, reused 0, downloaded 747, added 820
Progress: resolved 2386, reused 0, downloaded 794, added 866
Progress: resolved 2386, reused 0, downloaded 864, added 941
Progress: resolved 2386, reused 0, downloaded 934, added 1004
Progress: resolved 2386, reused 0, downloaded 1007, added 1087
Progress: resolved 2386, reused 0, downloaded 1065, added 1150
Progress: resolved 2386, reused 0, downloaded 1107, added 1195
Progress: resolved 2386, reused 0, downloaded 1174, added 1264
Progress: resolved 2386, reused 0, downloaded 1249, added 1340
Progress: resolved 2386, reused 0, downloaded 1343, added 1435
Progress: resolved 2386, reused 0, downloaded 1410, added 1502
Progress: resolved 2386, reused 0, downloaded 1466, added 1561
Progress: resolved 2386, reused 0, downloaded 1482, added 1580
Progress: resolved 2386, reused 0, downloaded 1520, added 1621
Progress: resolved 2386, reused 0, downloaded 1555, added 1655
Progress: resolved 2386, reused 0, downloaded 1596, added 1695
Progress: resolved 2386, reused 0, downloaded 1621, added 1722
Progress: resolved 2386, reused 0, downloaded 1655, added 1754
Progress: resolved 2386, reused 0, downloaded 1719, added 1819
Progress: resolved 2386, reused 0, downloaded 1733, added 1833
Progress: resolved 2386, reused 0, downloaded 1784, added 1881
.../sharp@0.31.3/node_modules/sharp install: gyp http GET https://nodejs.org/download/release/v18.16.0/SHASUMS256.txt
.../sharp@0.31.3/node_modules/sharp install: gyp http 200 https://nodejs.org/download/release/v18.16.0/SHASUMS256.txt
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn /usr/bin/python3
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args [
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '/home/runner/.cache/node/corepack/pnpm/8.2.0/dist/node_modules/node-gyp/gyp/gyp_main.py',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   'binding.gyp',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-f',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   'make',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-I',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '/home/runner/work/<redacted>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp/build/config.gypi',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-I',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '/home/runner/.cache/node/corepack/pnpm/8.2.0/dist/node_modules/node-gyp/addon.gypi',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-I',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '/home/runner/.cache/node-gyp/18.16.0/include/node/common.gypi',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dlibrary=shared_library',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dvisibility=default',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dnode_root_dir=/home/runner/.cache/node-gyp/18.16.0',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dnode_gyp_dir=/home/runner/.cache/node/corepack/pnpm/8.2.0/dist/node_modules/node-gyp',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dnode_lib_file=/home/runner/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/<redacted>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Dnode_engine=v8',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '--depth=.',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '--no-parallel',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '--generator-output',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   'build',
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args   '-Goutput_dir=.'
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args ]
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn make
.../sharp@0.31.3/node_modules/sharp install: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
.../sharp@0.31.3/node_modules/sharp install: make: Entering directory '/home/runner/work/<redacted>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp/build'
.../sharp@0.31.3/node_modules/sharp install:   CC(target) Release/obj.target/nothing/../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.o
.../sharp@0.31.3/node_modules/sharp install: rm -f Release/obj.target/../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a Release/obj.target/../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a`
.../sharp@0.31.3/node_modules/sharp install: ar crs Release/obj.target/../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a @Release/obj.target/../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a.ar-file-list
.../sharp@0.31.3/node_modules/sharp install:   COPY Release/nothing.a
.../sharp@0.31.3/node_modules/sharp install:   TOUCH Release/obj.target/libvips-cpp.stamp
.../sharp@0.31.3/node_modules/sharp install:   CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
.../sharp@0.31.3/node_modules/sharp install: ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
.../sharp@0.31.3/node_modules/sharp install:    24 | #include <vips/vips8>
.../sharp@0.31.3/node_modules/sharp install:       |          ^~~~~~~~~~~~
.../sharp@0.31.3/node_modules/sharp install: compilation terminated.
.../sharp@0.31.3/node_modules/sharp install: make: *** [sharp-linux-x64.target.mk:139: Release/obj.target/sharp-linux-x64/src/common.o] Error 1
.../sharp@0.31.3/node_modules/sharp install: make: Leaving directory '/home/runner/work/<redacted>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp/build'
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! build error 
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! stack Error: `make` failed with exit code: 2
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! stack     at ChildProcess.onExit (/home/runner/.cache/node/corepack/pnpm/8.2.0/dist/node_modules/node-gyp/lib/build.js:203:23)
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! System Linux 5.15.0-1037-azure
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! command "/opt/hostedtoolcache/node/18.16.0/x64/bin/node" "/home/runner/.cache/node/corepack/pnpm/8.2.0/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! cwd /home/runner/work/<redacted>/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! node -v v18.16.0
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! node-gyp -v v9.3.1
.../sharp@0.31.3/node_modules/sharp install: gyp ERR! not ok 
.../sharp@0.31.3/node_modules/sharp install: Failed
 ELIFECYCLE  Command failed with exit code 1.

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

`envinfo` doesn't appear to work on Mac OS M2

**Comment by lovell** [comment]
* When you say "back again", what changed between a state of working and a state of not working?
* Do you only see this problem with the latest `pnpm`?
* Do previous versions of `pnpm` work?
* Does `npm` work?
* Does `yarn` work?
* What is the complete set of configuration you are using with `pnpm`?
* Does the latest sharp v0.32.2 exhibit the same behaviour (the log appears to be for v0.31.3)?

Please can you provide the complete output of running `pnpm add --loglevel=debug sharp` (or similar, I want to see as much information as possible, provide too much if you're unsure) when run in a brand new, empty directory.

**Comment by lovell** [comment]
@shellscape Were you able to make any progress with this?

**Comment by jshmllr** [comment]
I'm spinning up my [old site](https://github.com/jshmllr/jshmllr.github.io) and after running `npm install` I'm getting this error as well. 
Details below...👇

### Specs
M1 Macbook Pro · 14-inch, 2021
macOS: 13.3.1 (a) Ventura

### Package.json
_I've added the resolution just in case._

```package.json 
{
  "private": true,
  "name": "site",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "dev": "gatsby develop",
    "clean": "gatsby clean",
    "proxy": "netlify-cms-proxy-server",
    "deploy": "gatsby build && gh-pages -d public"
  },
  "dependencies": {
    "@narative/gatsby-theme-novela": "^0.*",
    "gatsby": "^2.13.41",
    "gatsby-plugin-google-analytics": "^2.3.19",
    "gatsby-plugin-manifest": "^2.2.4",
    "gatsby-remark-embed-video": "^2.0.1",
    "gatsby-remark-video": "^1.2.5",
    "netlify-cms-app": "^2.11.23",
    "netlify-cms-proxy-server": "^1.3.24",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "resolutions": {
    "sharp": "0.27.2"
  },  
  "devDependencies": {
    "gh-pages": "^3.1.0"
  }
}
```


```Error
npm ERR! code 1
npm ERR! path /Users/*/Projects/GitHub/*/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-arm64v8.tar.br
npm ERR! ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/*/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/*/Projects/GitHub/*/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/*/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/*/Library/Caches/node-gyp/16.20.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/*/Library/Caches/node-gyp/16.20.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/*/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/*/Library/Caches/node-gyp/16.20.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/*/Projects/GitHub/*/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/*/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/Users/*/.nvm/versions/node/v16.20.1/bin/node" "/Users/*/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/*/Projects/GitHub/*/node_modules/sharp
npm ERR! gyp ERR! node -v v16.20.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*/.npm/_logs/2023-07-05T13_44_20_075Z-debug-0.log
```

### Other Steps
- Installed VIPs globally
- Instructions from Chat-GPT
> The issue you're experiencing is due to some of your dependencies being deprecated or having vulnerabilities. The major issue is with the `sharp` package, which is a common problem on M1 Macs as it tries to download precompiled binaries for your platform (darwin-arm64v8), and when they're not available, it attempts to build from source code, which is failing.

Let's try to solve this step by step:

1. Update NPM to the latest version:

```bash
npm install -g npm
```

2. Clear NPM cache:

```bash
npm cache clean --force
```

3. Delete `node_modules` folder and `package-lock.json` file:

```bash
rm -rf node_modules package-lock.json
```

4. Reinstall the dependencies:

```bash
npm install
```

5. If the error persists, it's likely due to the `sharp` package. Try to install `sharp` directly using the `--platform` option to specify your platform:

```bash
npm install --platform=darwin sharp
```

6. If still facing the issue, you might need to install `libvips` manually using Homebrew:

```bash
brew install vips
```

7. If none of these steps work, you might need to consider using an older version of `sharp` that might not have the same issues. Add a `resolutions` field to your `package.json` to ensure that all packages that depend on `sharp` use the same version:

```json
"resolutions": {
  "sharp": "0.27.2"
}
```

Then run `npm install` again.

Remember, this is a known issue with `sharp` on M1 Macs, and the package maintainers are likely working on a fix. Check the [sharp GitHub repository](https://github.com/lovell/sharp) for updates.

As for the deprecated dependencies, you might need to update your project dependencies to the latest versions or find alternatives if they're no longer maintained. Be sure to check the documentation of each package for guidance on how to migrate to newer versions or alternatives.

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.
