### ISSUE TITLE
Cannot install sharp node v14.20.3

### ISSUE THREAD

**Issue by elsiosanchez** [lovell/sharp#3673]
this is the full output of running `npm install --verbose sharp`?

```
$ npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/elsio/.nvm/versions/node/v14.21.3/bin/node',
npm verb cli   '/home/elsio/.nvm/versions/node/v14.21.3/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.18
npm info using node@v14.21.3
npm verb npm-session f3fab3527cc8c9d9
npm http fetch GET 304 https://registry.npmjs.org/sharp 531ms (from cache)
npm timing stage:loadCurrentTree Completed in 2464ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 29ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 572ms
npm http fetch GET 304 https://registry.npmjs.org/semver 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 161ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 244ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 107ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 92ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/fsevents 2ms (from cache)
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 8414ms
npm timing stage:loadIdealTree Completed in 9562ms
npm timing stage:generateActionsToTake Completed in 95ms
npm verb correctMkdir /home/elsio/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/elsio/.npm/_locks/staging-9b04cf53ffcbf2dd.lock for /home/elsio/Escritorio/proxy-adempiere-api/node_modules/.staging
npm timing action:extract Completed in 44ms
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm verb unbuild rmStuff in /home/elsio/Escritorio/proxy-adempiere-api/node_modules/storefront-query-builder/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm verb unbuild rmStuff in /home/elsio/Escritorio/proxy-adempiere-api/node_modules/storefront-query-builder/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm verb unbuild rmStuff in /home/elsio/Escritorio/proxy-adempiere-api/node_modules/storefront-query-builder/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm verb unbuild rmStuff in /home/elsio/Escritorio/proxy-adempiere-api/node_modules/kue/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/elsio/Escritorio/proxy-adempiere-api/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm timing action:unbuild Completed in 7ms
npm timing action:remove Completed in 8ms
npm timing action:finalize Completed in 6ms
npm timing action:refresh-package-json Completed in 9ms
npm info lifecycle semver@5.7.1~preinstall: semver@5.7.1
npm info lifecycle node-abi@2.30.1~preinstall: node-abi@2.30.1
npm info lifecycle minipass@3.3.6~preinstall: minipass@3.3.6
npm info lifecycle fs-minipass@2.1.0~preinstall: fs-minipass@2.1.0
npm info lifecycle minizlib@2.1.2~preinstall: minizlib@2.1.2
npm info lifecycle prebuild-install@5.3.6~preinstall: prebuild-install@5.3.6
npm info lifecycle semver@6.3.0~preinstall: semver@6.3.0
npm info lifecycle tar@5.0.11~preinstall: tar@5.0.11
npm info lifecycle sharp@0.23.4~preinstall: sharp@0.23.4
npm timing action:preinstall Completed in 1ms
npm info linkStuff semver@5.7.1
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver' },
npm verb linkBins   '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/node-abi/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff node-abi@2.30.1
npm info linkStuff minipass@3.3.6
npm info linkStuff fs-minipass@2.1.0
npm info linkStuff minizlib@2.1.2
npm info linkStuff prebuild-install@5.3.6
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff semver@6.3.0
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff tar@5.0.11
npm info linkStuff sharp@0.23.4
npm timing action:build Completed in 4ms
npm info lifecycle semver@5.7.1~install: semver@5.7.1
npm info lifecycle node-abi@2.30.1~install: node-abi@2.30.1
npm info lifecycle minipass@3.3.6~install: minipass@3.3.6
npm info lifecycle fs-minipass@2.1.0~install: fs-minipass@2.1.0
npm info lifecycle minizlib@2.1.2~install: minizlib@2.1.2
npm info lifecycle prebuild-install@5.3.6~install: prebuild-install@5.3.6
npm info lifecycle semver@6.3.0~install: semver@6.3.0
npm info lifecycle tar@5.0.11~install: tar@5.0.11
npm info lifecycle sharp@0.23.4~install: sharp@0.23.4

> sharp@0.23.4 install /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.12.1
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/elsio/.nvm/versions/node/v14.21.3/bin/node',
gyp verb cli   '/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.1
gyp info using node@14.21.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.10.6"
gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 14.21.3
gyp verb command install [ '14.21.3' ]
gyp verb install input version string "14.21.3"
gyp verb install installing version: 14.21.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.21.3
gyp verb build dir attempting to create "build" dir: /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/elsio/.cache/node-gyp/14.21.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/elsio/.cache/node-gyp/14.21.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/elsio/.cache/node-gyp/14.21.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/elsio/.cache/node-gyp/14.21.3
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: se entra en el directorio '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/elsio/.cache/node-gyp/14.21.3/include/node -I/home/elsio/.cache/node-gyp/14.21.3/src -I/home/elsio/.cache/node-gyp/14.21.3/deps/openssl/config -I/home/elsio/.cache/node-gyp/14.21.3/deps/openssl/openssl/include -I/home/elsio/.cache/node-gyp/14.21.3/deps/uv/include -I/home/elsio/.cache/node-gyp/14.21.3/deps/zlib -I/home/elsio/.cache/node-gyp/14.21.3/deps/v8/include -I../../nan -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu/ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/orc-0.4 -I/usr/include/OpenEXR -I/usr/include/openjpeg-2.4 -I/usr/include/poppler/glib -I/usr/include/poppler -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/openslide -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
make: g++: No existe el archivo o el directorio
make: *** [sharp.target.mk:183: Release/obj.target/sharp/src/common.o] Error 127
make: se sale del directorio '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.15.0-72-generic
gyp ERR! command "/home/elsio/.nvm/versions/node/v14.21.3/bin/node" "/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm verb lifecycle sharp@0.23.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.23.4~install: PATH: /home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp/node_modules/.bin:/home/elsio/Escritorio/proxy-adempiere-api/node_modules/.bin:/home/elsio/.sdkman/candidates/gradle/current/bin:/home/elsio/.nvm/versions/node/v14.21.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle sharp@0.23.4~install: CWD: /home/elsio/Escritorio/proxy-adempiere-api/node_modules/sharp
npm info lifecycle sharp@0.23.4~install: Failed to exec install script
npm timing action:install Completed in 528ms
npm verb unlock done using /home/elsio/.npm/_locks/staging-9b04cf53ffcbf2dd.lock for /home/elsio/Escritorio/proxy-adempiere-api/node_modules/.staging
npm timing audit submit Completed in 652ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 667ms
npm timing audit body Completed in 16ms
npm timing stage:rollbackFailedOptional Completed in 18ms
npm timing stage:runTopLevelLifecycles Completed in 13246ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN enoent ENOENT: no such file or directory, open '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/conventional-changelog-writer/node_modules/read-pkg/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN enoent ENOENT: no such file or directory, open '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/conventional-commits-parser/node_modules/normalize-package-data/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN enoent ENOENT: no such file or directory, open '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/conventional-commits-parser/node_modules/read-pkg/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN enoent ENOENT: no such file or directory, open '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/conventional-changelog-writer/node_modules/read-pkg/node_modules/normalize-package-data/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN enoent ENOENT: no such file or directory, open '/home/elsio/Escritorio/proxy-adempiere-api/node_modules/conventional-commits-parser/node_modules/read-pkg/node_modules/normalize-package-data/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN @apollographql/apollo-tools@0.5.4 requires a peer of graphql@^14.2.1 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @apollographql/graphql-upload-8-fork@8.1.4 requires a peer of graphql@0.13.1 - 15 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-toolkit/common@0.10.4 requires a peer of graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@5.0.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-toolkit/file-loading@0.10.4 requires a peer of graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-toolkit/schema-merging@0.10.4 requires a peer of graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@5.0.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-cache-control@0.15.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-graphql@0.9.7 requires a peer of graphql@^14.2.1 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-link@1.2.14 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-link-http-common@0.2.16 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-core@2.26.1 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-types@0.10.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@4.0.8 requires a peer of graphql@^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-errors@2.5.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-express@2.25.2 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@4.0.8 requires a peer of graphql@^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-plugin-base@0.14.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-types@0.10.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-types@0.9.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.16.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-utilities@1.3.4 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.16.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-types@0.10.0 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@1.2.1 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tag@2.12.6 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN merge-graphql-schemas@1.7.8 requires a peer of graphql@^0.11.7 || ^0.13.0 || ^14.0.2 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-core@1.1.4 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN requestretry@4.1.2 requires a peer of request@2.*.* but none is installed. You must install peer dependencies yourself.
npm WARN subscriptions-transport-ws@0.9.19 requires a peer of graphql@>=0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN update-browserslist-db@1.0.11 requires a peer of browserslist@>= 4.21.0 but none is installed. You must install peer dependencies yourself.

npm verb stack Error: sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:400:28)
npm verb stack     at ChildProcess.<anonymous> (/home/elsio/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1088:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
npm verb pkgid sharp@0.23.4
npm verb cwd /home/elsio/Escritorio/proxy-adempiere-api
npm verb Linux 5.15.0-72-generic
npm verb argv "/home/elsio/.nvm/versions/node/v14.21.3/bin/node" "/home/elsio/.nvm/versions/node/v14.21.3/bin/npm" "install" "--verbose" "sharp"
npm verb node v14.21.3
npm verb npm  v6.14.18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 14300ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/elsio/.npm/_logs/2023-05-19T14_16_47_905Z-debug.log

```

**Comment by lovell** [comment]
It looks like you're using a globally-installed libvips, which means that sharp will be built from source and therefore requires a C++ compiler to be present.

> info sharp Detected globally-installed libvips v8.12.1
> info sharp Building from source via node-gyp
> ...
> make: g++: No existe el archivo o el directorio

https://sharp.pixelplumbing.com/install#building-from-source

In addition, I recommend you upgrade to the latest version of sharp as v0.23.4 is almost 4 years old.

**Comment by elsiosanchez** [comment]
Thank you very much install `g++` in the operating system and re-run `npm i sharp` and it worked

```shell
apt install -y g++
```
