### ISSUE TITLE
Asset Images rendering with Sharp but not Squoosh - File URL path must be absolute

### ISSUE THREAD

**Issue by nairsajeesh** [lovell/sharp#3733]
## Question about an existing feature

Using the default Squoosh to render image stored in assets/images folder throwing error during build

### What are you trying to achieve?

To use the Astro Asset feature to render webp image from a png image 

### When you searched for similar issues, what did you find that might be related?

I did not find any reference or solution on the internet - searched google as well as the current Issue list

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

`index.astro`
```
---
import { Image } from "astro:assets";
import test from "../assets/images/test.png";
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width" />
    <meta name="generator" content={Astro.generator} />
    <title>Astro</title>
  </head>
  <body>
    <h1>Astro</h1>
    <Image src={test} alt="test" />
  </body>
</html>

````
`astro.config.mjs`

```
import { defineConfig } from "astro/config";

export default defineConfig({
  experimental: {
    assets: true,
  },
});

```

### Error

```bash
 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+17ms)

 generating optimized images 
 error   File URL path must be absolute
  File:
    D:\Sajeesh\Projects\ibrastro\node_modules\astro\dist\assets\generate.js:51:41
  Code:
    50 |   const imageService = await getConfiguredImageService();
    > 51 |   const resultData = await imageService.transform(
         |                                         ^
      52 |     fileData,
      53 |     { ...options, src: originalImagePath },
      54 |     buildOpts.settings.config.image.service.config
  Stacktrace:
TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:399:5)
    at getPathFromURLWin32 (node:internal/url:1196:11)
    at fileURLToPath (node:internal/url:1226:22)
    at imageMetadata (file:///D:/Sajeesh/Projects/ibrastro/dist/chunks/astro.926f4805.mjs:3891:10)
    at getRotationForEXIF (file:///D:/Sajeesh/Projects/ibrastro/dist/chunks/astro.926f4805.mjs:14558:22)
    at Object.transform (file:///D:/Sajeesh/Projects/ibrastro/dist/chunks/astro.926f4805.mjs:14584:28)
    at generateImage (file:///D:/Sajeesh/Projects/ibrastro/node_modules/astro/dist/assets/generate.js:51:41)
    at async generateImage (file:///D:/Sajeesh/Projects/ibrastro/node_modules/astro/dist/core/build/generate.js:153:26)
    at async generatePages (file:///D:/Sajeesh/Projects/ibrastro/node_modules/astro/dist/core/build/generate.js:140:7)
    at async staticBuild (file:///D:/Sajeesh/Projects/ibrastro/node_modules/astro/dist/core/build/static-build.js:86:7)
```
# Solution - Used Sharp

Though I want to stick around with Squoosh being the default for Astro, I tried Sharp. Installed it, updated `astro.config.mjs` and everything is working fine. 

# Question

Where have I gone wrong. I followed many blogs and videos and no one had installed Sharp, yet they were able to work with the default setup.

**Comment by lovell** [comment]
Did you intend to ask this question at the https://github.com/withastro/astro repo?

**Comment by nairsajeesh** [comment]
Sorry posted in the wronge page
