### ISSUE TITLE
fatal error: 'vips/vips8' file not found

### ISSUE THREAD

**Issue by rooneyt** [lovell/sharp#3764]
macOS Ventura / non-ARM. I am using sharp in one of my projects. All has been well, but my system started acting up and needed to be replaced. After a fresh install of everything, I am running into this issue when I try to set up my dev environment. I added sharp to an empty directory and then when navigating into the node_modules/sharp folder and running node-gyp build, I am getting the following (which is the same error I am getting in my project):

`gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp-darwin-x64/src/common.o
../src/common.cc:13:10: **fatal error: 'vips/vips8' file not found**
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp-darwin-x64/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rooneyt/.nvm/versions/node/v20.5.1/lib/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 22.6.0
gyp ERR! command "/Users/rooneyt/.nvm/versions/node/v20.5.1/bin/node" "/Users/rooneyt/.nvm/versions/node/v20.5.1/bin/node-gyp" "build"
gyp ERR! cwd /Users/rooneyt/Documents/GitHub/lovell/node_modules/sharp
gyp ERR! node -v v20.5.1
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not okrooneyt`

## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli /Users/rooneyt/.nvm/versions/node/v20.5.1/bin/node /Users/rooneyt/.nvm/versions/node/v20.5.1/bin/npm
npm info using npm@9.8.1
npm info using node@v20.5.1
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/Users/rooneyt/.npm/_logs/2023-08-14T19_22_38_099Z-
npm verb logfile /Users/rooneyt/.npm/_logs/2023-08-14T19_22_38_099Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 284ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 31ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 59ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 93ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 96ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 100ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 102ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 107ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 408ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/minimist 190ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 191ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 195ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 195ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/pump 191ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 192ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 193ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/once 232ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 233ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 229ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 263ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 271ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 275ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 285ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 279ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/rc 282ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 286ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 70ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 73ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 71ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 99ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 47ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 47ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ini 65ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 64ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 68ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/wrappy 56ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yallist 51ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 60ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/b4a 117ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/streamx 149ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/fast-fifo 412ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/queue-tick 110ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 52ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/bl 53ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 53ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/inherits 60ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer 45ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 51ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 78ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 66ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 105ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/queue-tick/-/queue-tick-1.0.1.tgz 114ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/streamx/-/streamx-2.15.1.tgz 115ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/fast-fifo/-/fast-fifo-1.3.0.tgz 114ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs/-/tar-fs-3.0.4.tgz 112ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/b4a/-/b4a-1.6.4.tgz 116ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream/-/tar-stream-3.1.6.tgz 141ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.32.4.tgz 214ms (cache miss)
npm info run sharp@0.32.4 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.32.4 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.3/libvips-8.14.3-darwin-x64.tar.br
sharp: Integrity check passed for darwin-x64 sharp@0.32.4 install node_modules/
prebuild-install info begin Prebuild-install version 7.1.1install node_modules/
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.32.4-napi-v7-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/rooneyt/.npm/_prebuilds/0cc96c-sharp-v0.32.4-napi-v7-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.32.4/sharp-v0.32.4-napi-v7-darwin-x64.tar.gz
prebuild-install http 200 https://github.com/lovell/sharp/releases/download/v0.32.4/sharp-v0.32.4-napi-v7-darwin-x64.tar.gz
prebuild-install info downloading to @ /Users/rooneyt/.npm/_prebuilds/0cc96c-sharp-v0.32.4-napi-v7-darwin-x64.tar.gz.4584-5ccb21682f6b9.tmp
prebuild-install info renaming to @ /Users/rooneyt/.npm/_prebuilds/0cc96c-sharp-v0.32.4-napi-v7-darwin-x64.tar.gz
prebuild-install info unpacking @ /Users/rooneyt/.npm/_prebuilds/0cc96c-sharp-v0.32.4-napi-v7-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/rooneyt/Documents/GitHub/lovell/node_modules/sharp/build/Release/sharp-darwin-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm info run sharp@0.32.4 install { code: 0, signal: null }

added 51 packages in 6s

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

Need to install the following packages:
envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.04 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v20.5.1/bin/npm
  npmPackages:
    sharp: ^0.32.4 => 0.32.4

**Comment by lovell** [comment]
> when navigating into the node_modules/sharp folder and running node-gyp build, I am getting the following

You don't need to run `node-gyp` when using the prebuilt binaries.

It looks like the installation log you've provided was able to install sharp and its prebuilt binaries successfully:

> npm info run sharp@0.32.4 install { code: 0, signal: null }
> added 51 packages in 6s

**Comment by rooneyt** [comment]
I went ahead and removed sharp from my project and ran my dependency install and all was well. I then added sharp back, and during the add process, I get the same error...

`yarn add sharp
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/rooneyt/Documents/GitHub/project/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/rooneyt/Documents/GitHub/project/node_modules/sharp
Output:
sharp: Using cached /Users/rooneyt/.npm/_libvips/libvips-8.14.2-darwin-x64.tar.br
sharp: Integrity check passed for darwin-x64
prebuild-install warn install No prebuilt binaries found (target=7 runtime=napi arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | x64
gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/rooneyt/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rooneyt/Documents/GitHub/project/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rooneyt/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rooneyt/Library/Caches/node-gyp/16.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rooneyt/Library/Caches/node-gyp/16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/rooneyt/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/rooneyt/Library/Caches/node-gyp/16.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rooneyt/Documents/GitHub/project/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/sharp-darwin-x64/src/common.o
../src/common.cc:13:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp-darwin-x64/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rooneyt/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.6.0
gyp ERR! command "/Users/rooneyt/.nvm/versions/node/v16.14.2/bin/node" "/Users/rooneyt/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rooneyt/Documents/GitHub/project/node_modules/sharp
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok`

**Comment by lovell** [comment]
>  prebuild-install warn install No prebuilt binaries found (target=7 runtime=napi arch=x64 libc= platform=darwin)

This is unexpected. Are you sure you're using the latest version?

**Comment by rooneyt** [comment]
I thought I was, but apparently it was one or two back. Thanks for the fast responses. Appreciate it. All is well now.

**Comment by kmvan** [comment]
`pnpm add libvips` fixed.
