### ISSUE TITLE
Error: Cannot find module '../build/Release/sharp-*.node'

### ISSUE THREAD

**Issue by MariuzM** [lovell/sharp#3782]
I'm using turborepo and did not had issue before with Sharp but today i've deleted lock file and wanted to rebuild, usually i do this practice to check things but today Ive got this error 

```
server:dev: Error: Cannot find module '../build/Release/sharp-*.node'
server:dev: Require stack:
server:dev: - /Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/sharp.js
server:dev: - /Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/constructor.js
server:dev: - /Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/index.js
server:dev: - /Volumes/Media/p1/apps/server/src/routes/auth.ts
server:dev: - /Volumes/Media/p1/apps/server/src/app.ts
server:dev:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
server:dev:     at u.default._resolveFilename (/Volumes/Media/p1/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:1519)
server:dev:     at Module._load (node:internal/modules/cjs/loader:922:27)
server:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
server:dev:     at require (node:internal/modules/cjs/helpers:110:18)
server:dev:     at <anonymous> (/Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/sharp.js:10:28)
server:dev:     at Object.<anonymous> (/Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/sharp.js:38:1)
server:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
server:dev:     at Object.F (/Volumes/Media/p1/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
server:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32) {
server:dev:   code: 'MODULE_NOT_FOUND',
server:dev:   requireStack: [
server:dev:     '/Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/sharp.js',
server:dev:     '/Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/constructor.js',
server:dev:     '/Volumes/Media/p1/node_modules/.pnpm/sharp@0.32.5/node_modules/sharp/lib/index.js',
server:dev:     '/Volumes/Media/p1/apps/server/src/routes/auth.ts',
server:dev:     '/Volumes/Media/p1/apps/server/src/app.ts'
server:dev:   ]
server:dev: }
server:dev: 
server:dev: Node.js v18.17.0
```

**Comment by MariuzM** [comment]
But maybe this is not related to sharp i assumed this because `Error: Cannot find module '../build/Release/sharp-*.node'`

but looking at lock file i see changes

<img width="916" alt="image" src="https://github.com/lovell/sharp/assets/36937039/a4356a7f-c80c-41f4-b6c6-4c8373656edf">

**Comment by MariuzM** [comment]
Found here: https://github.com/esbuild-kit/core-utils/issues/47

**Comment by MariuzM** [comment]
I'm reopening because still thinking this could be sharp issue also when i dont use sharp i dont have this error

**Comment by lovell** [comment]
Does this relate to https://github.com/evanw/esbuild/issues/3353 ?

**Comment by MariuzM** [comment]
Yes thank you
