### ISSUE TITLE
Cloudflare Deployment Build Error

### ISSUE THREAD

**Issue by DeVoresyah** [lovell/sharp#3896]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0 and I am not using the "Plug'n'Play" linker
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [x] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies
before opening an issue.

### Cloudflare Build Settings
```
Build command: bun run build
Build output directory: /dist
Build system version: 2 (latest)
Root directory: /
Environment variables: None
```

### Error Log
```
2023-12-15T07:33:21.472815Z	Cloning repository...
2023-12-15T07:33:22.736409Z	From https://github.com/Cuan-sh/cuan-landing
2023-12-15T07:33:22.737926Z	 * branch            f969cdbb95f1e9e6c0a46a15f87589446a83e26b -> FETCH_HEAD
2023-12-15T07:33:22.738284Z	
2023-12-15T07:33:22.884326Z	HEAD is now at f969cdb fix: remove sharp
2023-12-15T07:33:22.884966Z	
2023-12-15T07:33:22.98129Z	
2023-12-15T07:33:23.011128Z	Success: Finished cloning repository files
2023-12-15T07:33:23.748422Z	Detected the following tools from environment: nodejs@16.20.2, bun@1.0.1
2023-12-15T07:33:23.749321Z	Installing nodejs 16.20.2
2023-12-15T07:33:23.832509Z	nodejs 16.20.2 is already installed
2023-12-15T07:33:24.404676Z	Installing project dependencies: bun install --frozen-lockfile
2023-12-15T07:33:24.666856Z	bun install v1.0.1 (31aec4eb)
2023-12-15T07:33:35.150443Z	 + @img/sharp-linux-x64@0.33.0
2023-12-15T07:33:35.150862Z	 + @builder.io/qwik@1.2.17
2023-12-15T07:33:35.151007Z	 + @builder.io/qwik-city@1.2.17
2023-12-15T07:33:35.151123Z	 + @storybook/addon-essentials@7.5.3
2023-12-15T07:33:35.151234Z	 + @storybook/addon-links@7.5.3
2023-12-15T07:33:35.151351Z	 + @storybook/blocks@7.5.3
2023-12-15T07:33:35.151464Z	 + @storybook/builder-vite@7.5.3
2023-12-15T07:33:35.151572Z	 + @storybook/html@7.5.3
2023-12-15T07:33:35.15169Z	 + @storybook/html-vite@7.5.3
2023-12-15T07:33:35.151798Z	 + @types/eslint@8.44.7
2023-12-15T07:33:35.151905Z	 + @types/node@20.9.0
2023-12-15T07:33:35.152019Z	 + @typescript-eslint/eslint-plugin@6.11.0
2023-12-15T07:33:35.152147Z	 + @typescript-eslint/parser@6.11.0
2023-12-15T07:33:35.152256Z	 + autoprefixer@10.4.16
2023-12-15T07:33:35.15237Z	 + eslint@8.53.0
2023-12-15T07:33:35.152508Z	 + eslint-plugin-qwik@1.2.17
2023-12-15T07:33:35.152648Z	 + postcss@8.4.31
2023-12-15T07:33:35.152765Z	 + prettier@3.1.0
2023-12-15T07:33:35.152875Z	 + prettier-plugin-tailwindcss@0.5.7
2023-12-15T07:33:35.153004Z	 + storybook@7.5.3
2023-12-15T07:33:35.153118Z	 + storybook-framework-qwik@0.2.4
2023-12-15T07:33:35.153227Z	 + tailwindcss@3.3.3
2023-12-15T07:33:35.153367Z	 + typescript@5.2.2
2023-12-15T07:33:35.153482Z	 + undici@5.27.2
2023-12-15T07:33:35.153606Z	 + vite@4.5.0
2023-12-15T07:33:35.153723Z	 + vite-tsconfig-paths@4.2.1
2023-12-15T07:33:35.153832Z	 + wrangler@3.20.0
2023-12-15T07:33:35.153953Z	 + @fontsource-variable/inter@5.0.15
2023-12-15T07:33:35.154068Z	 + @qwikest/icons@0.0.13
2023-12-15T07:33:35.154177Z	 + remixicon@3.5.0
2023-12-15T07:33:35.154291Z	
2023-12-15T07:33:35.154401Z	 1123 packages installed [10.49s]
2023-12-15T07:33:35.179559Z	Executing user command: bun run build
2023-12-15T07:33:35.480493Z	$ qwik build
2023-12-15T07:33:35.804543Z	
2023-12-15T07:33:35.805033Z	      ............
2023-12-15T07:33:35.805263Z	    .::: :--------:.
2023-12-15T07:33:35.805479Z	   .::::  .:-------:.
2023-12-15T07:33:35.805636Z	  .:::::.   .:-------.
2023-12-15T07:33:35.80584Z	  ::::::.     .:------.
2023-12-15T07:33:35.805988Z	 ::::::.        :-----:
2023-12-15T07:33:35.806195Z	 ::::::.       .:-----.
2023-12-15T07:33:35.806326Z	  :::::::.     .-----.
2023-12-15T07:33:35.806449Z	   ::::::::..   ---:.
2023-12-15T07:33:35.806651Z	    .:::::::::. :-:.
2023-12-15T07:33:35.806786Z	     ..::::::::::::
2023-12-15T07:33:35.806896Z	             ...::::
2023-12-15T07:33:35.807173Z	     
2023-12-15T07:33:35.807349Z	
2023-12-15T07:33:35.8075Z	
2023-12-15T07:33:35.807627Z	bun run build.types
2023-12-15T07:33:35.807756Z	bun run build.client
2023-12-15T07:33:35.807883Z	bun run build.server
2023-12-15T07:33:35.808001Z	bun run lint
2023-12-15T07:33:35.808135Z	
2023-12-15T07:33:35.817122Z	$ tsc --incremental --noEmit --pretty
2023-12-15T07:33:35.832806Z	$ vite build
2023-12-15T07:33:36.708088Z	�[31merror during build:
2023-12-15T07:33:36.708443Z	Error: 
2023-12-15T07:33:36.708578Z	Something went wrong installing the "sharp" module
2023-12-15T07:33:36.708735Z	
2023-12-15T07:33:36.708846Z	Cannot find module '../build/Release/sharp-linux-x64.node'
2023-12-15T07:33:36.708954Z	Require stack:
2023-12-15T07:33:36.709062Z	- /opt/buildhome/repo/node_modules/sharp/lib/sharp.js
2023-12-15T07:33:36.70917Z	- /opt/buildhome/repo/node_modules/sharp/lib/constructor.js
2023-12-15T07:33:36.709277Z	- /opt/buildhome/repo/node_modules/sharp/lib/index.js
2023-12-15T07:33:36.709386Z	
2023-12-15T07:33:36.709503Z	Possible solutions:
2023-12-15T07:33:36.70961Z	- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
2023-12-15T07:33:36.709732Z	- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
2023-12-15T07:33:36.709839Z	- Consult the installation documentation: https://sharp.pixelplumbing.com/install
2023-12-15T07:33:36.709951Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/sharp/lib/sharp.js:37:9)
2023-12-15T07:33:36.710058Z	    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2023-12-15T07:33:36.710172Z	    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2023-12-15T07:33:36.710286Z	    at Module.load (node:internal/modules/cjs/loader:1076:32)
2023-12-15T07:33:36.710398Z	    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2023-12-15T07:33:36.710516Z	    at Module.require (node:internal/modules/cjs/loader:1100:19)
2023-12-15T07:33:36.710632Z	    at require (node:internal/modules/cjs/helpers:119:18)
2023-12-15T07:33:36.71075Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/sharp/lib/constructor.js:11:1)
2023-12-15T07:33:36.713258Z	    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2023-12-15T07:33:36.713453Z	    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)�[39m
2023-12-15T07:33:36.734319Z	error: script "build.client" exited with code 1 (SIGHUP)
2023-12-15T07:33:36.742193Z	error: script "build" exited with code 1 (SIGHUP)
2023-12-15T07:33:36.744367Z	Failed: Error while executing user command. Exited with error code: 1
2023-12-15T07:33:39.331625Z	Failed: build command exited with code: 1
2023-12-15T07:33:40.213682Z	Failed: error occurred while running build command
```

**Comment by lovell** [comment]
Hi, you ticked the box that says "I am using the latest version..." but this error is from sharp v0.32.6 or earlier, which does not support Bun. Please upgrade.

**Comment by DeVoresyah** [comment]
<img width="393" alt="image" src="https://github.com/lovell/sharp/assets/8052370/095896c9-6813-41f4-bc70-77d0d95824e2">

**Comment by lovell** [comment]
The `@img/*` packages are `optionalDependencies` of `sharp` itself and provide platform-specific binaries - you do not need to add these to the dependencies of your own app (and nor should you, as these can and will conflict).

Use `npm ls sharp` to tell you where in your dependency tree the previous version of `sharp` is coming from (storybook maybe?).

**Comment by DeVoresyah** [comment]
<img width="507" alt="Screenshot 2023-12-15 at 16 02 58" src="https://github.com/lovell/sharp/assets/8052370/da41330b-fdaa-4342-8148-ab379691fd1e">
