### ISSUE TITLE
Install failure on Windows Server 2008

### ISSUE THREAD

**Issue by alexstanbury** [lovell/sharp#391]
Hi, I managed to get past a first error by installing Visual C++ 2008, but now I am getting the following error:

```
C:\xxx\node_modules\sharp>if no
t defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (no
de "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
VCBUILD : error : project file 'C:\xxx\node_modules\sharp\build\libvips-cpp.vcproj' was not found or not a va
lid project file. [C:\xxx\node
_modules\sharp\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xxx\node_module
s\sharp
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "sharp" "--msvs_version=2008"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.13.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xxx\npm-debug.l
og
```

Do you have any idea how I can resolve this please?

(I've replaced the full path with 'xxx' for brevity)

Thanks

**Comment by lovell** [comment]
Hello, I'm not sure Visual C++ 2008 will provide enough support for the features of C++11, as required for using native modules (like this) with Node v4+. This probably isn't the problem you're facing right now, but is likely to be the next wall you'll hit.

http://sharp.dimens.io/en/stable/install/#prerequisites

Are you able to try a more recent version, e.g. MSVC 2013+?

**Comment by alexstanbury** [comment]
I managed to get it working by uninstalling the 2008 stuff and then
installing the build tools as directed in this thread :
https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

Seems it's a massive problem for lots of people using plugins with a
node-gyp dependency.

Thanks for your help!

**Comment by lovell** [comment]
Thanks for the update, glad you got it working!
