### ISSUE TITLE
Make a dmg build with electron builder (Apple M2 Pro)

### ISSUE THREAD

**Issue by Sitaras** [lovell/sharp#3916]
### What are you trying to achieve?

I am trying to make a .dmg build with electron builder (Apple M2 Pro).
Furthermore, I am using yarn as a package manager; executing `yarn add sharp --ignore-engines` works normally in dev mode.
On the contrary, when I try to make a build, I'm getting the following attached error.

### Please provide samples that help explain this question

```
Uncaught Exception:
Error: Could not load the "sharp" module using the darwin-arm64 runtime
ERR_DLOPEN_FAILED: dlopen(/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/.1.0.0.IaklnF, 0x0001): Library not loaded: @rpath/libvips-cpp.42.dylib
Referenced from: <8F4E8BD8-BCBD-3E7C-B00E-0AB2DD4CBE85> /private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/.1.0.0.IaklnF
Reason: tried: '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../../sharp-libvips-darwin-arm64/1.0.0/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../node_modules/@img/sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../../node_modules/@img/sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../../../../@img-sharp-libvips-darwin-arm64-npm-1.0.0-b9c401f4b7/node_modules/@img/sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../../sharp-libvips-darwin-arm64/1.0.0/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../node_modules/@img/sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../../node_modules/@img/sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/private/var/folders/7l/kn1234cs0nngy87s25bq599w0000gp/T/../../../../../@img-sharp-libvips-darwin-arm64-npm-1.0.0-b9c401f4b7/node_modules/@img/sharp-libvips-darwin-arm64/lib/libvips-cpp.42.dylib' (no such file), '/Applications/awesome-tools.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libvips-cpp.42.dylib' (no such file), '/Applications/awesome-tools.app/Contents/Frameworks/libvips-cpp.42.dylib' (no such file), '/usr/local/lib/libvips-cpp.42.dylib' (no such file), '/usr/lib/libvips-cpp.42.dylib' (no such file, not in dyld cache)
Possible solutions:
- Ensure optional dependencies can be installed:
npm install --include=optional sharp
yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
npm install --os=darwin --cpu=arm64 sharp
npm install --force @img/sharp-darwin-arm64
- Consult the installation documentation:
See https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/Applications/awesome-tools.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:107:9)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/Applications/awesome-tools.app/Contents/Resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
```

### Appendix

- [package.json](https://github.com/lovell/sharp/files/13760592/package.json)

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/678#issuecomment-275956028

> I am using yarn as a package manager

Please ensure you're using at least yarn v3, ideally yarn v4, and definitely not yarn v1.

**Comment by Sitaras** [comment]
Thank u @lovell ! 🎄🎄🎄
I did a successful .dmg build.
I just added these two lines to the `build` JSON property:
```
"build": {
    "asar": true,
    "mac": {
      "asarUnpack": "node_modules/**/*.node"
    }
  }
```
