### ISSUE TITLE
Error while setting up sharp for AWS Lambda function development 

### ISSUE THREAD

**Issue by RonaldPM** [lovell/sharp#3919]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [x] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
START RequestId: 477d1e5e-db40-4a47-93dc-c45ab668da74 Version: $LATEST
2023-12-27T13:18:54.746Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n    npm install --force @img/sharp-linux-x64\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install","stack":["Error: Could not load the \"sharp\" module using the linux-x64 runtime","Possible solutions:","- Ensure optional dependencies can be installed:","    npm install --include=optional sharp","    yarn add sharp --ignore-engines","- Ensure your package manager supports multi-platform installation:","    See https://sharp.pixelplumbing.com/install#cross-platform","- Add platform-specific dependencies:","    npm install --os=linux --cpu=x64 sharp","    npm install --force @img/sharp-linux-x64","- Consult the installation documentation:","    See https://sharp.pixelplumbing.com/install","    at /var/task/index.js:270:44612","    at /var/task/index.js:1:263","    at /var/task/index.js:271:108","    at /var/task/index.js:1:263","    at /var/task/index.js:271:76797","    at /var/task/index.js:1:263","    at Object.<anonymous> (/var/task/index.js:290:21209)","    at Module._compile (node:internal/modules/cjs/loader:1256:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)","    at Module.load (node:internal/modules/cjs/loader:1119:32)"]}
27 Dec 2023 13:18:54,891 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2023-12-27T13:18:58.487Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n    npm install --force @img/sharp-linux-x64\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install","stack":["Error: Could not load the \"sharp\" module using the linux-x64 runtime","Possible solutions:","- Ensure optional dependencies can be installed:","    npm install --include=optional sharp","    yarn add sharp --ignore-engines","- Ensure your package manager supports multi-platform installation:","    See https://sharp.pixelplumbing.com/install#cross-platform","- Add platform-specific dependencies:","    npm install --os=linux --cpu=x64 sharp","    npm install --force @img/sharp-linux-x64","- Consult the installation documentation:","    See https://sharp.pixelplumbing.com/install","    at /var/task/index.js:270:44612","    at /var/task/index.js:1:263","    at /var/task/index.js:271:108","    at /var/task/index.js:1:263","    at /var/task/index.js:271:76797","    at /var/task/index.js:1:263","    at Object.<anonymous> (/var/task/index.js:290:21209)","    at Module._compile (node:internal/modules/cjs/loader:1256:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)","    at Module.load (node:internal/modules/cjs/loader:1119:32)"]}
END RequestId: 28297f58-1dca-4aa2-bca0-ad816ae9a6cd
REPORT RequestId: 28297f58-1dca-4aa2-bca0-ad816ae9a6cd	Init Duration: 0.83 ms	Duration: 7524.36 ms	Billed Duration: 7525 ms	Memory Size: 512 MB	Max Memory Used: 512 MB	


```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

```
usernamehere@katana empty % npm install --verbose --foreground-scripts sharp
npm verb cli /Users/usernamehere/.nvm/versions/node/v18.16.1/bin/node /Users/usernamehere/.nvm/versions/node/v18.16.1/bin/npm
npm info using npm@9.5.1
npm info using node@v18.16.1
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/Users/usernamehere/.npm/_logs/2023-12-27T13_20_04_052Z-
npm verb logfile /Users/usernamehere/.npm/_logs/2023-12-27T13_20_04_052Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 121ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 50ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 106ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 1038ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 1348ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 1347ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 1348ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 1353ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 1361ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 1369ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 1374ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 1404ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 1412ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 1415ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 1418ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 1423ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 1424ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 1472ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 1492ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 1878ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 2778ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 2780ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 3038ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 59ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 61ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 93ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-string 636ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tslib 40ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 34ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 35ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 38ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 40ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yallist 40ms (cache revalidated)
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sharp@0.33.1',
npm WARN EBADENGINE   required: { node: '^18.17.0 || ^20.3.0 || >=21.0.0', libvips: '>=8.15.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
npm WARN EBADENGINE }
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-win32-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-win32-ia32
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-wasm32
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@emnapi/runtime
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/tslib
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-linuxmusl-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-linuxmusl-arm64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-linux-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-linux-s390x
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-linux-arm64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-linux-arm
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-linux-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-linux-s390x
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-linux-arm64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-linux-arm
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-darwin-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-libvips-darwin-arm64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-darwin-x64
npm verb reify failed optional dependency /Users/usernamehere/workspace/empty/node_modules/@img/sharp-darwin-arm64
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.33.1.tgz 53ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi/runtime/-/runtime-0.44.0.tgz 712ms (cache miss)
npm info run sharp@0.33.1 install node_modules/sharp node install/check

> sharp@0.33.1 install
> node install/check

npm info run sharp@0.33.1 install { code: 0, signal: null }

added 11 packages in 6s

1 package is looking for funding
  run `npm fund` for details
npm verb exit 0
npm info ok 
```

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
username@katana empty % npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp
Need to install the following packages:
  envinfo@7.11.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 48.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.6.3 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
  npmPackages:
    sharp: ^0.33.1 => 0.33.1 
```

**Other info:**
I am running a Mac and developing an AWS Lambda application. I have also tried running `sam build --use-container` without any luck. I have also tried the [CrossPlatform options](https://pnpm.io/package_json#pnpmsupportedarchitectures) mentioned here for PNPM.

**Comment by RonaldPM** [comment]
Also note that when I try following  the step
`Ensure sharp is excluded from bundling via the [external ](https://esbuild.github.io/api/#external) configuration`

It gives me the following error during run
```
START RequestId: 807c3907-1d59-4e36-9525-a4c349816f51 Version: $LATEST
2023-12-27T13:43:38.911Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'sharp'","Require stack:","- /var/task/index.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}
27 Dec 2023 13:43:39,068 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=

```

**Comment by lovell** [comment]
> npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sharp@0.33.1',
npm WARN EBADENGINE   required: { node: '^18.17.0 || ^20.3.0 || >=21.0.0', libvips: '>=8.15.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
npm WARN EBADENGINE }

Please upgrade to a supported version of Node.js.

**Comment by RonaldPM** [comment]
I did try with 18.17.0 but doesn't seem to make a difference.

Here us the updated output of `npm install --verbose --foreground-scripts sharp` after the update

```
ronaldmathews@katana empty % npm install --verbose --foreground-scripts sharp
npm verb cli /Users/ronaldmathews/.nvm/versions/node/v18.17.0/bin/node /Users/ronaldmathews/.nvm/versions/node/v18.17.0/bin/npm
npm info using npm@9.6.7
npm info using node@v18.17.0
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/Users/ronaldmathews/.npm/_logs/2023-12-27T14_58_58_687Z-
npm verb logfile /Users/ronaldmathews/.npm/_logs/2023-12-27T14_58_58_687Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 7ms (cache hit)
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-win32-x64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-win32-ia32
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-wasm32
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@emnapi/runtime
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/tslib
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-linuxmusl-x64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-linuxmusl-arm64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-linux-x64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-linux-s390x
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-linux-arm64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-linux-arm
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-linux-x64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-linux-s390x
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-linux-arm64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-linux-arm
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-libvips-darwin-x64
npm verb reify failed optional dependency /Users/ronaldmathews/workspace/empty/node_modules/@img/sharp-darwin-x64
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 253ms

up to date, audited 14 packages in 379ms

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm verb exit 0
npm info ok 
```

**Comment by lovell** [comment]
> I am using pnpm

Have you ensured it is correctly configured to (a) install optional dependencies (b) with the relevant `supportedArchitectures` using (c) a node-linker strategy that supports AWS Lambda (watch out for lack of symlink support)?

**Comment by kearfy** [comment]
I am experiencing this same issue with AWS Amplify and NextJS 14. Node version is 18.18.x. I downgraded back to sharp@0.32.6 for the time being.

I am using `PNPM` and I tried both it's [supportedArchitectures](https://pnpm.io/package_json#pnpmsupportedarchitectures) config and I tried to add `--force @img/sharp-linux-x64` flag to the installation command.

Attaching a screenshot with logs for reference, in case it helps:
![Group 3](https://github.com/lovell/sharp/assets/17960250/fee36c65-166e-4281-9824-d1e7f9494f81)

**Comment by lovell** [comment]
@kearfy If this is Next.js "standalone mode" then you may have hit a known Vercel bug - please see https://github.com/vercel/nft/issues/371

**Comment by kearfy** [comment]
> @kearfy If this is Next.js "standalone mode" then you may have hit a known Vercel bug - please see https://github.com/vercel/nft/issues/371

Thanks! If I understand correctly, nft is used in the bundling process of NextJS? I see a lot of people mentioning issues there with deploying svelte/astro in combination with sharp to vercel aswell, though I am deploying to Amplify.

I'm not well read into this subject, apologies for any "dumb" questions! 😅

**Comment by lovell** [comment]
@RonaldPM Were you able to make any progress with this?

**Comment by noudadrichem** [comment]
@lovell I'm stumbling upon the same issue without using Vercel. I'm using AWS CDK with TypeScript where we I try to add 'sharp' to a layer dependency. I'm receiving the following error message:

```bash
{"errorType":"Error","errorMessage":"\nSomething went wrong installing the \"sharp\
"module\n\nCannot find module '../build/Release/sharp-linux-arm64v8.node'\nRequire stack:\n- 
/opt/nodejs/node_modules/sharp/lib/sharp.js\n- 
/opt/nodejs/node_modules/sharp/lib/constructor
```

**Comment by lovell** [comment]
@noudadrichem Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.

**Comment by noudadrichem** [comment]
Was able to fix it using a pre-build layer [from](https://github.com/pH200/sharp-layer?tab=readme-ov-file). Vamos to open source!

**Comment by RonaldPM** [comment]
> @RonaldPM Were you able to make any progress with this?

Hi @lovell, sorry for the late reply. We were not able to get it working on AWS Lambda even after spending a lot of time trying multiple workarounds (building sharp on a linux machine, copying binaries, using --use-container flag while building using AWS SAM etc.). Will try again in future and get back to you. Thanks.

**Comment by lovell** [comment]
@RonaldPM Thanks for the update, I'll close for now, but please feel free to re-open if you need help later.

For anyone else coming here and still needing help, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions.

**Comment by abuziyaada** [comment]
@noudadrichem  thanks. worked for me too
