### ISSUE TITLE
Error while running Jest tests: Could not load the "sharp" module using the win32-x64 runtime

### ISSUE THREAD

**Issue by ryanwalters** [lovell/sharp#3926]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
  ● Test suite failed to run

    Could not load the "sharp" module using the win32-x64 runtime
    Possible solutions:
    - Ensure optional dependencies can be installed:
        npm install --include=optional sharp
        yarn add sharp --ignore-engines
    - Ensure your package manager supports multi-platform installation:
        See https://sharp.pixelplumbing.com/install#cross-platform
    - Add platform-specific dependencies:
        npm install --os=win32 --cpu=x64 sharp
        npm install --force @img/sharp-win32-x64
    - Consult the installation documentation:
        See https://sharp.pixelplumbing.com/install

      at Object.<anonymous> (node_modules/sharp/lib/sharp.js:107:9)
      at Object.<anonymous> (node_modules/sharp/lib/constructor.js:10:1)
```

A few things that might be worth noting:
1. The project uses TypeScript.
2. When running serverless-offline locally, sharp appears to work as expected. I only see this error when running integration tests.
3. A similar error occurs in our CI environment (CircleCI): `Could not load the "sharp" module using the linux-x64 runtime`
4. `canvas` is not a dependency.
5. There is only one version of `sharp` installed.
   ```
   H:\Projects\project> npm ls sharp
   project@1.0.0 H:\Projects\project
   `-- sharp@0.33.1
   ```
6. Adding platform-specific dependencies did not work. e.g.
   ```
   npm install --os=win32 --cpu=x64 sharp
   npm install --force @img/sharp-win32-x64
   ```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

```
npm verb cli F:\Utils\nodejs\node.exe F:\Utils\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@10.2.3
npm info using node@v20.10.0
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:C:\Users\user\AppData\Local\npm-cache\_logs\2024-01-02T21_19_52_290Z-
npm verb logfile C:\Users\user\AppData\Local\npm-cache\_logs\2024-01-02T21_19_52_290Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 14ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 55ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 59ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 60ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 60ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 60ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 63ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 62ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 64ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 64ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 62ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 64ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 65ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 67ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 67ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 66ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tslib 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yallist 5ms (cache hit)
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-win32-ia32
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-wasm32
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@emnapi\runtime
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\tslib
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-linuxmusl-x64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-linuxmusl-arm64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-linux-x64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-linux-s390x
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-linux-arm64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-linux-arm
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-linux-x64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-linux-s390x
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-linux-arm64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-linux-arm
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-darwin-x64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-libvips-darwin-arm64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-darwin-x64
npm verb reify failed optional dependency H:\Projects\sharp-test\node_modules\@img\sharp-darwin-arm64
npm info run sharp@0.33.1 install node_modules/sharp node install/check

> sharp@0.33.1 install
> node install/check

npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 380ms
npm info run sharp@0.33.1 install { code: 0, signal: null }

added 12 packages, and audited 13 packages in 1s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm verb exit 0
npm info ok
```

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 25.37 GB / 47.93 GB
  Binaries:
    Node: 20.10.0 - F:\Utils\nodejs\node.EXE
    npm: 8.19.4 - H:\Projects\iris\node_modules\.bin\npm.CMD
  npmPackages:
    sharp: 0.33.1 => 0.33.1
```

**Comment by lovell** [comment]
It looks like you're using multiple platforms with npm - have you definitely ruled out https://github.com/npm/cli/issues/4828 ?

**Comment by puxiao** [comment]
@ryanwalters 

This is the solution:

```
npm install sharp
npm install --force @img/sharp-win32-x64
```

**Comment by metenev** [comment]
> @ryanwalters
> 
> This is the solution:
> 
> ```
> npm install sharp
> npm install --force @img/sharp-win32-x64
> ```

For yarn you should also add `--ignore-engines` option.

**Comment by lovell** [comment]
@puxiao Using `npm --force ...` is a workaround rather than a solution. If you're experiencing https://github.com/npm/cli/issues/4828 then it's really important to add your :+1: to that issue to help improve visibility and increase the chance of it getting fixed.

**Comment by ryanwalters** [comment]
> It looks like you're using multiple platforms with npm - have you definitely ruled out [npm/cli#4828](https://github.com/npm/cli/issues/4828) ?

After a bit more investigation, I do believe it is the same issue as npm/cli#4828. The good news is that I was able to come up with a command that appears to work in CI:
```bash
- run:
    name: Install dependencies
    command: |
      npm install --force --os=linux --cpu=x64 sharp
      npm install --force @img/sharp-linux-x64
```

Thanks!

**Comment by NoobMahbub** [comment]
1. Update your package manager

`  npm install -g npm@latest`

 2. Clear the cache

`  npm cache clean -f`

 3. Then Terminate batch job and run again 
 
` npm run dev `
 
 or 
 
` npm run start`
