### ISSUE TITLE
Getting module not found for sharp after installation

### ISSUE THREAD

**Issue by prashant03Dev** [lovell/sharp#3930]
STEPS FOLLOWED:

- Installed python 2.7 using cmd
  cmd: npm install --global windows-build-tools
  
- Deleted node_modules & dist from nestjs app using rimraf.
- again re-install using npm i 
-getting issue for sharp module

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (D:\radiansys\quince-fashion-api\node_modules\nestjs-multer-extended\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\radiansys\quince-fashion-api\node_modules\nestjs-multer-extended\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\radiansys\quince-fashion-api\node_modules\nestjs-multer-extended\dist\multer-sharp\multer-sharp.js:18:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    
  ----------------------------------------------------------------------------------------------------------------------------------------------
  
  Tried every possible solution for this error.But couldn't reach out,Suggest us the way to resolve.
  
  Thanks

**Comment by lovell** [comment]
It looks like you're using `nestjs-multer-extended`, which depends on an outdated and unsupported version of `sharp`.

https://github.com/jeffminsungkim/nestjs-multer-extended/blob/45c45f6b62c8c8719dbeb8ce2e0c688050ed242c/package.json#L54

You'll need to ask at the https://github.com/jeffminsungkim/nestjs-multer-extended repo. Perhaps you could submit a PR to update the version of sharp.

**Comment by prashant03Dev** [comment]
Hello Lovell,

I'm using  0.32.6 in my project,and it's working fine on mac machine,But when i run npm i command,and then start the app,it throws error,

Will it help by degrading the version for sharp?

Thanks

**Comment by lovell** [comment]
Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you require help with the latest v0.33.1.

**Comment by prashant03Dev** [comment]
Hello Lovell,

As we checked the version that you mentioned on your github link,After deleting node_modules and updated the sharp version to 0.26.0 works well,and the app runs.

Thanks
