### ISSUE TITLE
latest 0.33.2 causes Next.js build error on Vercel build  (RangeError: Maximum call stack size exceeded when collecting build traces)

### ISSUE THREAD

**Issue by Stewart86** [lovell/sharp#3949]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

Not Applicable. Running build on local works fine. Only when building on Vercel for deployment fails. 

### What are the steps to reproduce?

1. update sharp dependency of Next.js project from version 0.33.1 to 0.33.2
2. deploy to vercel
3. read error on deployment build log.

### What is the expected behaviour?

Vercel build run successfully.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Not Applicable.

### Please provide sample image(s) that help explain this problem

```bash
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
 ⚠ Using edge runtime on a page currently disables static generation for that page
   Generating static pages (0/46) ...

   Generating static pages (11/46) 

   Generating static pages (22/46) 

   Generating static pages (34/46) 

 ✓ Generating static pages (46/46) 
   Finalizing page optimization ...
   Collecting build traces ...
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at create (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18889)
    at create (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18918)
    at create (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18918)
    at parse.fastpaths (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18997)
    at picomatch.makeRe (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:21635)
    at picomatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
    at /vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
    at Array.map (<anonymous>)
    at picomatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3944

This is a problem with Vercel, please contact Vercel support.

**Comment by jgwiazdowski** [comment]
took me hours to realize what's causing it :|
