### ISSUE TITLE
0.33.2 breaks nextjs Vercel builds

### ISSUE THREAD

**Issue by tmaihoff** [lovell/sharp#3953]
## Possible bug

As title says.`npm run build` works fine on local machine but breaks on Vercel deployment with the following logging:

```log
Attention: Next.js now collects completely anonymous telemetry regarding usage.
--
13:24:10.939 | This information is used to shape Next.js' roadmap and prioritize features.
13:24:10.939 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
13:24:10.939 | https://nextjs.org/telemetry
13:24:10.939 |  
13:24:11.033 | ▲ Next.js 14.0.4
13:24:11.033 | - Environments: .env
13:24:11.033 | - Experiments (use at your own risk):
13:24:11.033 | · typedRoutes
13:24:11.033 |  
13:24:11.033 | Creating an optimized production build ...
13:24:23.011 | ✓ Compiled successfully
13:24:23.012 | Linting and checking validity of types ...
13:24:33.118 | Collecting page data ...
13:24:34.286 | Generating static pages (0/15) ...
13:24:34.662 | ⚠ Entire page /auth/signin deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /auth/signin
13:24:34.668 | Generating static pages (3/15)
13:24:34.968 | Generating static pages (7/15)
13:24:35.121 | Generating static pages (11/15)
13:24:35.208 | ✓ Generating static pages (15/15)
13:24:35.406 | Finalizing page optimization ...
13:24:35.406 | Collecting build traces ...
13:24:43.257 | RangeError: Maximum call stack size exceeded
13:24:43.258 | at parse (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:6313)
13:24:43.258 | at picomatch.makeRe (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
13:24:43.258 | at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
13:24:43.258 | at /vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
13:24:43.259 | at Array.map (<anonymous>)
13:24:43.259 | at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
13:24:43.259 | at micromatch.isMatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
13:24:43.259 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:245:48
13:24:43.259 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:75:9)
13:24:43.259 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
13:24:43.314 | Error: Command "npm run build" exited with 1

``` 

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

Using 0.33.2
- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### Workaround
Reverting to 0.33.1 fixes the issue.
`sharp: 0.33.1` without the `^`

#### Related Discussion
Opened by another user: https://github.com/orgs/vercel/discussions/5480

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3944
