### ISSUE TITLE
Upgrading sharp from `0.33.1` to `0.33.2` breaks Next.js build on Vercel

### ISSUE THREAD

**Issue by samuelcole** [lovell/sharp#3955]
After upgrading the sharp package, I was unable to deploy with the following error when "collecting build traces":

```
volunteer:build:    Collecting build traces ...
volunteer:build: RangeError: Maximum call stack size exceeded
volunteer:build:     at RegExp.exec (<anonymous>)
volunteer:build:     at create (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18889)
volunteer:build:     at create (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18918)
volunteer:build:     at parse.fastpaths (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18997)
volunteer:build:     at picomatch.makeRe (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:21635)
volunteer:build:     at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
volunteer:build:     at /vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
volunteer:build:     at Array.map (<anonymous>)
volunteer:build:     at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
volunteer:build:     at micromatch.isMatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
volunteer:build: ERROR: command finished with error: command (/vercel/path0/apps/volunteer) /vercel/.yarn/bin/yarn run build exited (1)
volunteer#build: command (/vercel/path0/apps/volunteer) /vercel/.yarn/bin/yarn run build exited (1)
```

My understanding is that Next.js is walking through `node_modules` to understand which files need to be included in the lambda runtime. Is there something in sharp, or its dependencies, that could have a really deep or recursive folder structure?

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3944
