### ISSUE TITLE
Very large 333333x333333 SVG input image will exceed 32767x32767 pixel limit when scaled to 250x250

### ISSUE THREAD

**Issue by natuan62** [lovell/sharp#3964]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 40.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 7.20.0 - ~/.config/yarn/global/node_modules/.bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
  npmPackages:
    sharp: ^0.33.2 => 0.33.2 ### What are the steps to reproduce?
```

```
(process:21376): GLib-GObject-CRITICAL **: 17:34:26.658: value "0.000750" of type 'gdouble' is invalid or out of range for property 'scale' of type 'gdouble'
/Users/..../node_modules/.pnpm/sharp@0.33.2/node_modules/sharp/lib/output.js:161
  const stack = Error();
                ^

Error: Input SVG image will exceed 32767x32767 pixel limit when scaled
    at Sharp.toBuffer (/Users/.../node_modules/.pnpm/sharp@0.33.2/node_modules/sharp/lib/output.js:161:17)
    at main (/Users/.../index.js:28:77)
```

### What is the expected behaviour?

- resize svg and convert to buffer work fine

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const main = async () => {
  const contentSvg = fs.readFileSync('./icon.svg', 'utf8');
  const svg = sharp(Buffer.from(contentSvg), {
    unlimited: true,
    limitInputPixels: false,
    failOn: 'none',
  });

  const meta = await svg.metadata();
  console.log('meta', meta);

  const { data: body, info: metadata } = await svg.clone().resize(250, 250).toBuffer({ resolveWithObject: true });
  fs.writeFileSync('./thumbnail.png', body);
};

main();
```
### Please provide sample image(s) that help explain this problem

```
icon.svg
<svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 333333 333333"
    shape-rendering="geometricPrecision"
    text-rendering="geometricPrecision"
    image-rendering="optimizeQuality"
    fill-rule="evenodd"
    clip-rule="evenodd"
>
    <defs>
        <linearGradient
            id="c"
            gradientUnits="userSpaceOnUse"
            x1="139644"
            y1="1216.54"
            x2="139644"
            y2="154838"
        >
            <stop
                offset="0"
                stop-color="#0ad778"
            />
            <stop
                offset="1"
                stop-color="#01ef75"
            />
        </linearGradient>
        <linearGradient
            id="a"
            gradientUnits="userSpaceOnUse"
            x1="131794"
            y1="175885"
            x2="131794"
            y2="314014"
        >
            <stop
                offset="0"
                stop-color="#fe3e4a"
            />
            <stop
                offset="1"
                stop-color="#e31f50"
            />
        </linearGradient>
        <linearGradient
            id="b"
            gradientUnits="userSpaceOnUse"
            x1="203724"
            y1="166762"
            x2="301448"
            y2="166762"
        >
            <stop
                offset="0"
                stop-color="#febe00"
            />
            <stop
                offset="1"
                stop-color="#ffd900"
            />
        </linearGradient>
        <linearGradient
            id="d"
            gradientUnits="userSpaceOnUse"
            x1="101563"
            y1="73139"
            x2="101563"
            y2="250453"
        >
            <stop
                offset="0"
                stop-color="#02c4ff"
            />
            <stop
                offset="1"
                stop-color="#01e2ff"
            />
        </linearGradient>
    </defs>
    <path
        d="M239294 224715L61656 327719c-5862 3400-8711 4828-15749 5612-1462 163-20263-7299-21614-7313l162266-169613 52735 68309v1z"
        fill="url(#a)"
    />
    <path
        d="M239323 108780l51810 29915c7151 4128 13345 7157 18724 13758 8759 10753 7617 23077-5003 33454-5577 4586-13106 8393-19403 12044l-46300 26791-52595-68339 52767-47624z"
        fill="url(#b)"
    />
    <path
        d="M39911 57c300-19 602-32 905-41 12993-368 19780 5461 30426 11735l168136 97065-52820 47588L39912 55v2z"
        fill="url(#c)"
    />
    <path
        d="M41278 518l145281 155887L24334 325975c-1040-1232-1950-2595-2736-4072-5033-9475-3621-24057-3621-34750V44552c0-7160-533-15777 646-23242C20279 10832 35301-2382 41277 519z"
        fill="url(#d)"
    />
</svg>
```

**Comment by lovell** [comment]
The dimensions in this example require a change to libvips as the scale factor is lower than the currently accepted minimum - please see https://github.com/libvips/libvips/pull/3827

A possible workaround is to use a very small `density`:
```js
sharp(input, { limitInputPixels: false, density: 1 }).resize( ...
```
