### ISSUE TITLE
Trying to resize images but getting pngload_buffer: libspng read error sometimes

### ISSUE THREAD

**Issue by jf7689** [lovell/sharp#3993]
Users upload an image file in an input tag. They can crop images client side so that the result is always a square base64 string png image and then I'm trying to resize them server side with sharp to always be 512x512 base64 string. I'm working with sveltekit and using sharp ^0.33.2, if that matters.

Code:
```
let parts = pfp.split(';');
let mimType = parts[0].split(':')[1];
let imageData = parts[1].split(',')[1];

let bufferImg = Buffer.from(imageData, "base64");
let resizeBuffer = await sharp(bufferImg).resize(512, 512).toBuffer();
let resizedImg = resizeBuffer.toString("base64");
```

At first I thought it might have to do with the uploaded image file size or dimensions being too large but that doesn't seem to be the case necessarily.

Images that didn't work:
![801](https://github.com/lovell/sharp/assets/54907558/698bb1e4-8e67-45c4-a664-47fcff3ade36)
![825](https://github.com/lovell/sharp/assets/54907558/a4f32ba9-93bd-4d7b-a800-e39cf1c44308)

**Comment by lovell** [comment]
Please provide a sample image that allows someone else to reproduce.

**Comment by lovell** [comment]
I note you've edited your post to include some images, which work for me. Please provide images and code that allows someone else to reproduce consistently. (My best guess would be that this relates to networking, or that there's a race condition in your code/logic not yet provided.)

**Comment by jf7689** [comment]
Thank you for responding. I"ll include the base64 string of the cropped images in text files and maybe they'll reproduce the issue.
[image1.txt](https://github.com/lovell/sharp/files/14299103/image1.txt)
[image2.txt](https://github.com/lovell/sharp/files/14299107/image2.txt)

```
import fs from "fs";
let imageData = fs.readFileSync("image1.txt", "utf8");
            
let bufferImg = Buffer.from(imageData, "base64");
let resizeBuffer = await sharp(bufferImg).resize(512, 512).toBuffer();
let resizedImg = resizeBuffer.toString("base64");
```

**Comment by lovell** [comment]
@jf7689 Were you able to make any progress with this? The files you provided are not valid base64.

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with valid base64-encoded images if further help is required.

**Comment by simonv3** [comment]
@lovell I'm getting a very similar error with this piece of code:

```
let newBuffer = await sharp(`path/to/file`)
              .rotate()
              .resize({ width: 1500, height: 1500 })
              .webp()
              .toBuffer();
```

With both of these files: 

![broken-png](https://github.com/lovell/sharp/assets/485583/df50385f-3452-413a-be10-c903a3b2224c)
![broken-2-png](https://github.com/lovell/sharp/assets/485583/ed6b650a-3ec5-4c89-b3ca-54dd67f3ebc1)

GIves this error:

```
{"stack":"Error: pngload: libspng read error\n    at Sharp.toBuffer (/var/www/api/node_modules/sharp/lib/output.js:161:17)\n    at /var/www/api/src/jobs/optimize-image.ts:121:16\n    at step (/var/www/api/src/jobs/optimize-image.ts:33:23)\n    at Object.next (/var/www/api/src/jobs/optimize-image.ts:14:53)\n    at /var/www/api/src/jobs/optimize-image.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/api/src/jobs/optimize-image.ts:4:12)\n    at /var/www/api/src/jobs/optimize-image.ts:84:12\n    at Array.map (<anonymous>)\n    at /var/www/api/src/jobs/optimize-image.ts:75:25\n    at Array.map (<anonymous>)\n    at /var/www/api/src/jobs/optimize-image.ts:64:8\n    at step (/var/www/api/src/jobs/optimize-image.ts:33:23)\n    at Object.next (/var/www/api/src/jobs/optimize-image.ts:14:53)\n    at fulfilled (/var/www/api/src/jobs/optimize-image.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"pngload: libspng read error"}
```

**Comment by lovell** [comment]
@simonv3 If you still require help, please open a new question issue and provide the images in a .zip file or similar to avoid GitHub manipulating or "fixing" them.

https://github.com/lovell/sharp/issues/new?assignees=&labels=question&projects=&template=question.md
