### ISSUE TITLE
node-gyp configure crashes

### ISSUE THREAD

**Issue by binarykitchen** [lovell/sharp#400]
I am trying to rebuild with debug mode but the configure command crashes with `
TypeError: Invalid Version: undefined`, see:

```
# michael-heuberger @ M1 in ~/binarykitchen/code/videomail.io/node_modules/sharp on git:staging x [18:45:26] 
$ node-gyp configure                                                                                    staging 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/michael-heuberger/.node-gyp/4.4.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/michael-heuberger/.node-gyp/4.4.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/semver/semver.js:279
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/semver/semver.js:279:11)
    at SemVer.compare (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/semver/semver.js:342:13)
    at compare (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/semver/semver.js:566:31)
    at Function.gte (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/semver/semver.js:615:10)
    at Object.module.exports.use_global_vips (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/binding.js:115:28)
    at [eval]:1:22
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:579:27
gyp: Call to 'GLOBAL_VIPS_VERSION="8.2.3" node -e "require('./binding').use_global_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-34-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by lovell** [comment]
Hello, what do you mean by "debug mode"? Is there a reason for running `node-gyp configure` instead of `npm install`? The former probably won't work as it relies on npm setting an environment variable (based on a value in [package.json](https://github.com/lovell/sharp/blob/master/package.json#L73)) to determine the minimum required version of libvips.

**Comment by binarykitchen** [comment]
@lovell i thought with `node-gyp configure` and `node-gyp rebuild --debug` i can see a better stack trace of the crash i mentioned in https://github.com/lovell/sharp/issues/401

hence i am after the ability to run sharp + libvips in debug mode

**Comment by lovell** [comment]
OK, doing so might improve the back trace if the crash is happening in sharp (rather than libvips or one of its dependencies).

Try:
```sh
npm_package_config_libvips=8.2.3 node-gyp rebuild --debug
```
Plus you'll need to locally modify "Release" to "Debug" [here](https://github.com/lovell/sharp/blob/master/index.js#L12).

**Comment by binarykitchen** [comment]
done that but no difference, no useful stack trace being produced. anyway, let's close this ticket and continue on the other one https://github.com/lovell/sharp/issues/401
