### ISSUE TITLE
Bun 1.1.1  Sharp 0.33.3  --  Error: Could not load the "sharp" module using the darwin-arm64 runtime

### ISSUE THREAD

**Issue by trevorfehrman** [lovell/sharp#4056]
Hi friends,

Trying to get Plaiceholder setup in my Next app for blur data urls but I am getting the error mentioned in the title.

I see other people have had problems similar to this but I couldn't find an example of it failing with my combination of versions and runtime.  I'm installing sharp with `bun add sharp`.

## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [ ] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [x] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [x] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
 ⨯ node_modules/sharp/lib/sharp.js (114:0) @ Object.<anonymous>
 ⨯ Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_sharp_a01c7e._.js:414:11)
    at [project]/node_modules/sharp/lib/sharp.js [app-rsc] (ecmascript) (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_sharp_a01c7e._.js:417:3)
    at instantiateModule (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at commonJsRequire (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:127:20)
    at Object.<anonymous> (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_sharp_a01c7e._.js:426:1)
    at [project]/node_modules/sharp/lib/constructor.js [app-rsc] (ecmascript) (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_sharp_a01c7e._.js:899:3)
    at instantiateModule (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at commonJsRequire (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:127:20)
    at Object.<anonymous> (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_sharp_a01c7e._.js:5499:15)
    at [project]/node_modules/sharp/lib/index.js [app-rsc] (ecmascript) (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_sharp_a01c7e._.js:5510:3)
    at instantiateModule (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at esmImport (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:113:20)
    at /Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_de9687._.js:13228:141
    at [project]/node_modules/plaiceholder/dist/plaiceholder.esm.js [app-rsc] (ecmascript) (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_de9687._.js:13489:3)
    at instantiateModule (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at esmImport (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:113:20)
    at /Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[root of the server]__940248._.js:872:163
    at [project]/components/search-table.tsx [app-rsc] (ecmascript) (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[root of the server]__940248._.js:1413:3)
    at instantiateModule (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at esmImport (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:113:20)
    at /Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[root of the server]__940248._.js:1482:134
    at [project]/app/search-movies/page.tsx [app-rsc] (ecmascript) (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[root of the server]__940248._.js:1504:3)
    at instantiateModule (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at esmImport (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[turbopack]_runtime.js:113:20)
    at Module.default (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/[root of the server]__940248._.js:1508:20)
    at tree.children.children.page (/Users/trevorfehrman/Documents/code/movie-night-v2/.next/server/chunks/node_modules_next_c2823b._.js:11407:196)
    at eB (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:401153)
    at /Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6514
    at /Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NoopTracer.startActiveSpan (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
    at ProxyTracer.startActiveSpan (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
    at /Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NextTracerImpl.trace (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at ru (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6395)
    at /Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:9085
    at Array.map (<anonymous>)
    at ru (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:8818)
    at async /Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:9079
    at async Promise.all (index 0)
    at async ru (/Users/trevorfehrman/Documents/code/movie-night-v2/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:8785) {
  digest: '1866502512',
  page: '/search-movies'
}
```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm install --verbose --foreground-scripts sharp
npm verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@9.8.1
npm info using node@v18.18.2
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/Users/trevorfehrman/.npm/_logs/2024-04-06T08_46_08_935Z-
npm verb logfile /Users/trevorfehrman/.npm/_logs/2024-04-06T08_46_08_935Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 114ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 37ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 61ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 79ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 94ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 94ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 93ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 94ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 95ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 95ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 95ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 97ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 96ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 97ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 96ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 97ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 96ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 110ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 109ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 126ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 129ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 129ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 130ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 27ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 42ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 64ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 254ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tslib 51ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 30ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 29ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 31ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 29ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yallist 24ms (cache revalidated)
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-win32-x64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-win32-ia32
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-wasm32
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@emnapi/runtime
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/tslib
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-linuxmusl-x64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-linuxmusl-arm64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-linux-x64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-linux-s390x
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-linux-arm64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-linux-arm
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-linux-x64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-linux-s390x
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-linux-arm64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-linux-arm
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-libvips-darwin-x64
npm verb reify failed optional dependency /Users/trevorfehrman/Documents/code/empty/node_modules/@img/sharp-darwin-x64
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.3.tgz 31ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-string/-/color-string-1.9.1.tgz 32ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz 33ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color/-/color-4.2.3.tgz 38ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz 43ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.33.3.tgz 42ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img/sharp-darwin-arm64/-/sharp-darwin-arm64-0.33.3.tgz 55ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi/runtime/-/runtime-1.1.1.tgz 71ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img/sharp-libvips-darwin-arm64/-/sharp-libvips-darwin-arm64-1.0.2.tgz 779ms (cache miss)
npm info run sharp@0.33.3 install node_modules/sharp node install/check

> sharp@0.33.3 install
> node install/check

npm info run sharp@0.33.3 install { code: 0, signal: null }

added 13 packages in 2s

3 packages are looking for funding
  run `npm fund` for details
npm verb exit 0
npm info ok

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.30 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    bun: 1.1.1 - ~/.bun/bin/bun
 ```

**Comment by lovell** [comment]
Bun supports `overrides` so you might be able to force-upgrade sharp to the latest version that way too - see https://bun.sh/docs/install/overrides
