### ISSUE TITLE
Support win on arm64

### ISSUE THREAD

**Issue by Daydreamer-riri** [lovell/sharp#4135]
### What are you trying to achieve?

Support win on arm64.

### Please provide sample image(s) that help explain this feature

I'm running into this issue:

```
C:\Users\Riri\workspace\riri\riri-me\node_modules\.pnpm\sharp@0.33.4\node_modules\sharp\lib\sharp.js:114
  throw new Error(help.join('\n'));
        ^

Error: Could not load the "sharp" module using the win32-arm64 runtime
Possible solutions:
- Manually install libvips >= 8.15.2
- Add experimental WebAssembly-based dependencies:
    npm install --cpu=wasm32 sharp
    npm install @img/sharp-wasm32
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\Riri\workspace\riri\riri-me\node_modules\.pnpm\sharp@0.33.4\node_modules\sharp\lib\sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Riri\workspace\riri\riri-me\node_modules\.pnpm\sharp@0.33.4\node_modules\sharp\lib\constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Riri\workspace\riri\riri-me\node_modules\.pnpm\sharp@0.33.4\node_modules\sharp\lib\index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async generatePage (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/core/build/generate.js:204:22)
    at async generatePages (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/core/build/generate.js:164:9)
    at async staticBuild (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/core/build/static-build.js:96:7)
    at async AstroBuilder.build (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/core/build/index.js:134:5)
    at async AstroBuilder.run (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/core/build/index.js:165:7)
    at async build (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/core/build/index.js:46:3)
    at async build (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/cli/build/index.js:20:3)
    at async runCommand (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/cli/index.js:141:7)
    at async cli (file:///C:/Users/Riri/workspace/riri/riri-me/node_modules/.pnpm/astro@4.5.8_sass@1.70.0_typescript@5.2.2/node_modules/astro/dist/cli/index.js:169:5)

Node.js v20.15.0
```

I guess it could be that Sharp doesn't support Win On Arm? Or is there another solution?

**Comment by lovell** [comment]
There's an existing issue for this at https://github.com/lovell/sharp-libvips/issues/238 - let's track it there.

In the meantime, you could try the WebAssembly binaries - https://sharp.pixelplumbing.com/install#webassembly
