### ISSUE TITLE
Unable to Deploy Sharp Library on AWS Lambda and Heroku (Using MacBook M1 for development)

### ISSUE THREAD

**Issue by ahtashamabbasse** [lovell/sharp#4162]
I'm experiencing the same issue with the Sharp library. I'm developing on a MacBook M1 and trying to use Sharp for image manipulation. When attempting to deploy it on AWS Lambda, I encountered problems. I added the following to my package.json:

```
"postinstall": "yarn add sharp --ignore-engines"
```
However, this results in an endless loop during installation. I've tried other solutions, but none have worked.

I then moved my deployment to Heroku but faced similar issues. I have limited access to specify the environment, and I don't have the necessary permissions to install Sharp via the shell.

Any assistance or guidance would be greatly appreciated.

## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version `v21.6.1`

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using yarn version 1.22.19

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

{
  "errorType": "Error",
  "errorMessage": "Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
  "trace": [
    "Error: Could not load the \"sharp\" module using the linux-x64 runtime",
    "Possible solutions:",
    "- Ensure optional dependencies can be installed:",
    "    npm install --include=optional sharp",
    "    yarn add sharp --ignore-engines",
    "- Ensure your package manager supports multi-platform installation:",
    "    See https://sharp.pixelplumbing.com/install#cross-platform",
    "- Add platform-specific dependencies:",
    "    npm install --os=linux --cpu=x64 sharp",
    "- Consult the installation documentation:",
    "    See https://sharp.pixelplumbing.com/install",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/sharp.js:114:9)",
    "    at Module._compile (node:internal/modules/cjs/loader:1364:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)",
    "    at Module.load (node:internal/modules/cjs/loader:1203:32)",
    "    at Module._load (node:internal/modules/cjs/loader:1019:12)",
    "    at Module.require (node:internal/modules/cjs/loader:1231:19)",
    "    at require (node:internal/modules/helpers:177:18)",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:1)",
    "    at Module._compile (node:internal/modules/cjs/loader:1364:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)"
  ]
}

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>
No Information as I'm running it on aws lambda
</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

<details>
No Information as I'm running it on aws lambda
</details>

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#aws-lambda ?

> The `node_modules` directory of the deployment package must include binaries for either the linux-x64 or linux-arm64 platforms depending on the chosen architecture. When building your deployment package on a machine that differs from the target architecture, see the cross-platform section to help decide which package manager is appropriate and how to configure it.

... and https://sharp.pixelplumbing.com/install#cross-platform ?

> yarn v3+
> Use the [supportedArchitectures](https://yarnpkg.com/configuration/yarnrc#supportedArchitectures) configuration.

If your package manager of choice is yarn, you'll need to upgrade to at least v3 to take advantage of this feature.

**Comment by lovell** [comment]
@ahtashamabbasse Were you able to make any progress with this?

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with more details if further help is required.

**Comment by ahtashamabbasse** [comment]
Thank you, @lovell, for the hint. I transitioned from Yarn to npm, and the issue was resolved..
