### ISSUE TITLE
Error: Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by nrozeboom** [lovell/sharp#4163]
I use Linux Mint 22 Cinnamon
Linux kernel: 6.8.0-35-generic

I installed "joplin" (an oneNote alternative).
When I run joplin I get the following error message:

joplin
/usr/local/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
  ^

**Error: Could not load the "sharp" module using the linux-x64 runtime**
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/local/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.1

npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp

  **System:
    OS: Linux 6.8 Linux Mint 22 (Wilma)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 54.71 GB / 62.20 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/bin/npm**

npm view sharp dist-tags.latest
**0.33.4**

I hope someone knows how to solve this issue
Many thanks in advance!

**Comment by lovell** [comment]
Please provide answers to the following questions that were ignored/deleted from the issue template.

## Possible install-time or require-time problem



- [ ] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ ] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?



- [ ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported package manager and installing optional dependencies?



- [ ] I am using npm >= 10.1.0 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

**Comment by rohit-nayak123** [comment]
@lovell 
> What is the complete output of running npm install --verbose --foreground-scripts sharp in an empty directory?

Well, here is my output please fix it

```cmd
#19 [package 6/7] RUN npm install --verbose --foreground-scripts sharp
#19 0.291 npm verbose cli /usr/local/bin/node /usr/local/bin/npm
#19 0.291 npm info using npm@10.8.2
#19 0.291 npm info using node@v18.20.4
#19 0.294 npm verbose title npm install sharp
#19 0.294 npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
#19 0.295 npm verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-07-17T12_57_31_249Z-
#19 0.296 npm verbose logfile /root/.npm/_logs/2024-07-17T12_57_31_249Z-debug-0.log
#19 0.707 npm http fetch GET 200 https://registry.npmjs.org/sharp 57ms (cache hit)
#19 0.777 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-win32-x64
#19 0.777 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-win32-ia32
#19 0.778 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-wasm32
#19 0.778 npm verbose reify failed optional dependency /app/node_modules/@emnapi/runtime
#19 0.778 npm verbose reify failed optional dependency /app/node_modules/tslib
#19 0.778 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-linuxmusl-arm64
#19 0.779 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-linux-s390x
#19 0.779 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-linux-arm64
#19 0.779 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-linux-arm
#19 0.780 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-libvips-linuxmusl-arm64
#19 0.780 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-libvips-linux-s390x
#19 0.780 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-libvips-linux-arm64
#19 0.780 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-libvips-linux-arm
#19 0.781 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-libvips-darwin-x64
#19 0.781 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-libvips-darwin-arm64
#19 0.781 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-darwin-x64
#19 0.781 npm verbose reify failed optional dependency /app/node_modules/@img/sharp-darwin-arm64
#19 0.901 npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk [157](https://github.com/rohit-nayak123/compresspics/actions/runs/9974640631/job/27562542863#step:5:158)ms
#19 0.918 npm http fetch GET 200 https://registry.npmjs.org/http-cache-semantics 14ms (cache hit)
#19 0.920 npm http fetch GET 200 https://registry.npmjs.org/got 16ms (cache hit)
#19 0.924 npm http fetch GET 200 https://registry.npmjs.org/semver-regex 19ms (cache hit)
#19 0.933 npm http fetch GET 200 https://registry.npmjs.org/download 7ms (cache hit)
#19 0.943 npm http fetch GET 200 https://registry.npmjs.org/cacheable-request 8ms (cache hit)
#19 0.949 npm http fetch GET 200 https://registry.npmjs.org/@img/sharp-linuxmusl-x64/-/sharp-linuxmusl-x64-0.33.4.tgz 164ms (cache miss)
#19 0.952 npm http fetch GET 200 https://registry.npmjs.org/find-versions 7ms (cache hit)
#19 0.961 npm http fetch GET 200 https://registry.npmjs.org/bin-wrapper 8ms (cache hit)
#19 0.962 npm http fetch GET 200 https://registry.npmjs.org/bin-build 8ms (cache hit)
#19 0.969 npm http fetch GET 200 https://registry.npmjs.org/bin-version 4ms (cache hit)
#19 0.974 npm http fetch GET 200 https://registry.npmjs.org/gifsicle 4ms (cache hit)
#19 0.980 npm http fetch GET 200 https://registry.npmjs.org/bin-version-check 4ms (cache hit)
#19 0.985 npm http fetch GET 200 https://registry.npmjs.org/imagemin-gifsicle 4ms (cache hit)
#19 1.133 npm http fetch GET 200 https://registry.npmjs.org/@img/sharp-libvips-linuxmusl-x64/-/sharp-libvips-linuxmusl-x64-1.0.2.tgz 348ms (cache miss)
```

**Comment by lovell** [comment]
@rohit-nayak123 Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.

**Comment by lovell** [comment]
@nrozeboom Closing due to inactivity. If you still require help, please provide answers to the questions in https://github.com/lovell/sharp/issues/4163#issuecomment-2231086531

**Comment by yannicksuc** [comment]
Same problem for me on Ubuntu 24.04 LTS when trying to start my node project... 
I have the latest version of sharp and Node.js v18.19.1.

**Comment by lovell** [comment]
@yannicksuc Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.
