### ISSUE TITLE
on mac, I build libvips with jxl support , but still jxlsave not found

### ISSUE THREAD

**Issue by i18nsite** [lovell/sharp#4272]
I use this install
```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
npm install --verbose --foreground-scripts sharp --build-from-source
```

```
/Users/z/git/flux/node_modules/sharp/lib/output.js:90
    const stack = Error();
                  ^

Error: VipsOperation: class "jxlsave" not found
    at Sharp.toFile (/Users/z/git/flux/node_modules/sharp/lib/output.js:90:19)
    at build (file:///Users/z/git/flux/title.coffee:220:6)
    at async file:///Users/z/git/flux/title.coffee:230:5
Thrown at:
    at toFile (/Users/z/git/flux/node_modules/sharp/lib/output.js:90:19)
    at build (file:///Users/z/git/flux/title.coffee:220:6)


Node.js v22.3.0
```

the libvips

```
❯ pkg-config --modversion vips-cpp           
8.17.0
❯ vips --vips-config
enable debug: false
enable deprecated: false
enable modules: false
enable cplusplus: true
enable RAD load/save: true
enable Analyze7 load: true
enable PPM load/save: true
enable GIF load: true
FFTs with fftw: false
SIMD support with libhwy: true
ICC profile support with lcms2: true
deflate compression with zlib: true
text rendering with pangocairo: true
font file support with fontconfig: true
EXIF metadata support with libexif: false
JPEG load/save with libjpeg: true
JXL load/save with libjxl: true (dynamic module: false)
JPEG2000 load/save with libopenjp2: true
PNG load/save with libpng: true
image quantisation with imagequant or quantizr: false
TIFF load/save with libtiff: false
image pyramid save with libarchive: false
HEIC/AVIF load/save with libheif: true (dynamic module: false)
WebP load/save with libwebp: true
PDF load with poppler-glib: true (dynamic module: false)
SVG load with librsvg-2.0: true
EXR load with OpenEXR: true
WSI load with OpenSlide: false (dynamic module: false)
Matlab load with Matio: false
NIfTI load/save with libnifti: false
FITS load/save with cfitsio: false
GIF save with cgif: false
Magick load/save with MagickCore: true (dynamic module: false)
❯ ./title.coffee
/Users/z/git/flux/node_modules/sharp/lib/output.js:90
    const stack = Error();
                  ^

Error: VipsOperation: class "jxlsave" not found
    at Sharp.toFile (/Users/z/git/flux/node_modules/sharp/lib/output.js:90:19)
    at build (file:///Users/z/git/flux/title.coffee:220:6)
    at async file:///Users/z/git/flux/title.coffee:230:5
Thrown at:
    at toFile (/Users/z/git/flux/node_modules/sharp/lib/output.js:90:1
```

install script

```
#!/usr/bin/env bash

DIR=$(realpath $0) && DIR=${DIR%/*}
cd $DIR
set -ex

cd /tmp
if [ ! -d "libvips" ]; then
  git clone --depth=1 https://github.com/libvips/libvips.git
  brew install cmake ninja meson pkg-config libjpeg libpng giflib jpeg-xl
fi

cd libvips

meson setup build-dir \
  --prefix=/usr/local \
  -Djpeg=enabled \
  -Dpng=enabled \
  --buildtype=release \
  -Dtiff=disabled \
  -Djpeg-xl=enabled \
  -Dintrospection=disabled \
  -Dmodules=disabled \
  -Ddeprecated=false --reconfigure

cd build-dir
ninja
sudo ninja install
cd $DIR

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
npm install --verbose --foreground-scripts sharp --build-from-source
```

log

```
+ cd /tmp
+ '[' '!' -d libvips ']'
+ cd libvips
+ meson setup build-dir --prefix=/usr/local -Djpeg=enabled -Dpng=enabled --buildtype=release -Dtiff=disabled -Djpeg-xl=enabled -Dintrospection=disabled --libdir=lib -Dmodules=disabled -Ddeprecated=false --reconfigure
The Meson build system
Version: 1.6.0
Source dir: /private/tmp/libvips
Build dir: /private/tmp/libvips/build-dir
Build type: native build
Project name: vips
Project version: 8.17.0
C compiler for the host machine: cc (clang 16.0.0 "Apple clang version 16.0.0 (clang-1600.0.26.4)")
C linker for the host machine: cc ld64 1115.7.3
C++ compiler for the host machine: c++ (clang 16.0.0 "Apple clang version 16.0.0 (clang-1600.0.26.4)")
C++ linker for the host machine: c++ ld64 1115.7.3
Host machine cpu family: aarch64
Host machine cpu: aarch64
Compiler for C supports arguments -Werror=pointer-arith: YES (cached)
Dependency glib-2.0 found: YES 2.82.2 (cached)
Dependency gio-2.0 found: YES 2.82.2 (cached)
Dependency gobject-2.0 found: YES 2.82.2 (cached)
Dependency gmodule-no-export-2.0 skipped: feature modules disabled
Dependency expat found: YES 2.5.0 (cached)
Dependency threads found: YES unknown (cached)
Library m found: YES
Compiler for C supports link arguments -Wl,-z,nodelete: NO (cached)
Compiler for C supports function attribute visibility:hidden: YES (cached)
Checking if "Has vector arithmetic" with dependency -lm compiles: YES (cached)
Checking if "Has signed constants in vector templates" with dependency -lm compiles: YES (cached)
Checking if "Has target_clones attribute" runs: DID NOT COMPILE
Checking for function "_aligned_malloc" : NO (cached)
Checking for function "posix_memalign" : YES (cached)
Checking for function "memalign" : NO (cached)
Checking for function "pthread_setattr_default_np" with dependency threads: NO (cached)
Dependency zlib found: YES 1.2.12 (cached)
Found pkg-config: YES (/opt/homebrew/bin/pkg-config) 2.3.0
Found CMake: /opt/homebrew/bin/cmake (3.31.0)
Run-time dependency libarchive found: NO (tried pkgconfig, framework and cmake)
Run-time dependency fftw3 found: NO (tried pkgconfig, framework and cmake)
Dependency MagickCore found: YES 7.1.1 (cached)
Checking for function "ImportImagePixels" with dependency MagickCore: YES (cached)
Checking for function "ImagesToBlob" with dependency MagickCore: YES (cached)
Run-time dependency cfitsio found: NO (tried pkgconfig, framework and cmake)
Run-time dependency imagequant found: NO (tried pkgconfig, framework and cmake)
Run-time dependency quantizr found: NO (tried pkgconfig, framework and cmake)
Run-time dependency libexif found: NO (tried pkgconfig, framework and cmake)
Dependency libjpeg found: YES 3.0.4 (cached)
Checking for function "jpeg_c_bool_param_supported" with dependency libjpeg: NO (cached)
Run-time dependency spng found: NO (tried pkgconfig, framework and cmake)
Run-time dependency libspng found: NO (tried pkgconfig, framework and cmake)
Dependency libpng found: YES 1.6.44 (cached)
Checking for function "png_set_chunk_malloc_max" with dependency libpng: YES (cached)
Dependency libwebp found: YES 1.4.0 (cached)
Dependency libwebpmux found: YES 1.4.0 (cached)
Dependency libwebpdemux found: YES 1.4.0 (cached)
Dependency pangocairo found: YES 1.54.0 (cached)
Dependency pangoft2 found: YES 1.54.0 (cached)
Dependency fontconfig found: YES 2.15.0 (cached)
Dependency libtiff-4 skipped: feature tiff disabled
Dependency librsvg-2.0 found: YES 2.58.4 (cached)
Dependency cairo found: YES 1.18.2 (cached)
Run-time dependency openslide found: NO (tried pkgconfig, framework and cmake)
Run-time dependency matio found: NO (tried pkgconfig, framework and cmake)
Dependency lcms2 found: YES 2.16 (cached)
Dependency OpenEXR found: YES 3.3.1 (cached)
Dependency libopenjp2 found: YES 2.5.2 (cached)
Dependency libhwy found: YES 1.2.0 (cached)
Run-time dependency pdfium found: NO (tried pkgconfig, framework and cmake)
Dependency libheif found: YES 1.19.2 (cached)
Checking for function "heif_image_handle_get_raw_color_profile" with dependency libheif: YES (cached)
Checking for function "heif_context_set_maximum_image_size_limit" with dependency libheif: YES (cached)
Checking whether type "struct heif_decoding_options" has member "convert_hdr_to_8bit" with dependency libheif: YES (cached)
Checking for function "heif_encoder_parameter_get_valid_integer_values" with dependency libheif: YES (cached)
Checking whether type "struct heif_encoding_options" has member "output_nclx_profile" with dependency libheif: YES (cached)
Dependency libjxl found: YES 0.11.0 (cached)
Dependency libjxl_threads found: YES 0.11.0 (cached)
Dependency poppler-glib found: YES 24.11.0 (cached)
Run-time dependency niftiio found: NO (tried pkgconfig)
Run-time dependency nifti found: NO (tried cmake)
Has header "sys/file.h" : YES (cached)
Has header "sys/param.h" : YES (cached)
Has header "sys/mman.h" : YES (cached)
Has header "unistd.h" : YES (cached)
Has header "io.h" : NO (cached)
Has header "direct.h" : NO (cached)
Checking for function "ngettext" : NO (cached)
Library intl found: NO
Configuring config.h using configuration
Program g-ir-scanner skipped: feature introspection disabled
Dependency glib-2.0 found: YES 2.82.2 (cached)
Program /opt/homebrew/Cellar/glib/2.82.2/bin/glib-mkenums found: YES (/opt/homebrew/Cellar/glib/2.82.2/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.82.2 (cached)
Program /opt/homebrew/Cellar/glib/2.82.2/bin/glib-mkenums found: YES (/opt/homebrew/Cellar/glib/2.82.2/bin/glib-mkenums)
Configuring version.h using configuration
Dependency glib-2.0 found: YES 2.82.2 (cached)
Program /opt/homebrew/Cellar/glib/2.82.2/bin/glib-genmarshal found: YES (/opt/homebrew/Cellar/glib/2.82.2/bin/glib-genmarshal)
Program msgfmt found: YES (/opt/homebrew/bin/msgfmt)
Program msginit found: YES (/opt/homebrew/bin/msginit)
Program msgmerge found: YES (/opt/homebrew/bin/msgmerge)
Program xgettext found: YES (/opt/homebrew/bin/xgettext)
Program python3 found: YES (/opt/homebrew/opt/python@3.13/bin/python3.13)
Configuring variables.sh using configuration
Build targets in project: 59  

vips 8.17.0  

  Dependencies
    glib-2.0                                      : 2.82.2
    gio-2.0                                       : 2.82.2
    gobject-2.0                                   : 2.82.2
    gmodule-no-export-2.0                         : unknown
    expat                                         : 2.5.0
    zlib                                          : 1.2.12
    MagickCore                                    : 7.1.1
    libjpeg                                       : 3.0.4
    libpng                                        : 1.6.44
    libwebp                                       : 1.4.0
    libwebpmux                                    : 1.4.0
    libwebpdemux                                  : 1.4.0
    pangocairo                                    : 1.54.0
    pangoft2                                      : 1.54.0
    fontconfig                                    : 2.15.0
    librsvg-2.0                                   : 2.58.4
    cairo                                         : 1.18.2
    lcms2                                         : 2.16
    OpenEXR                                       : 3.3.1
    libopenjp2                                    : 2.5.2
    libhwy                                        : 1.2.0
    libheif                                       : 1.19.2
    libjxl                                        : 0.11.0
    libjxl_threads                                : 0.11.0
    poppler-glib                                  : 24.11.0  

  Build options
    enable debug                                  : NO
    enable deprecated                             : NO
    enable modules                                : NO
    enable gtk-doc                                : NO
    enable doxygen                                : NO
    enable introspection                          : NO
    enable examples                               : YES
    enable cplusplus                              : YES
    enable RAD load/save                          : YES
    enable Analyze7 load                          : YES
    enable PPM load/save                          : YES
    enable GIF load                               : YES  

  Optional external packages
    FFTs with fftw                                : NO
    SIMD support with libhwy                      : YES
    ICC profile support with lcms2                : Cleaning... 0 files.
YES
    deflate compression with zlib                 : YES
    text rendering with pangocairo                : YES
    font file support with fontconfig             : YES
    EXIF metadata support with libexif            : NO  

  External image format libraries
    JPEG load/save with libjpeg                   : YES
    JXL load/save with libjxl                     : YES (dynamic module: NO)
    JPEG2000 load/save with libopenjp2            : YES
    PNG load/save with libpng                     : YES
    image quantisation with imagequant or quantizr: NO
    TIFF load/save with libtiff                   : NO
    image pyramid save with libarchive            : NO
    HEIC/AVIF load/save with libheif              : YES (dynamic module: NO)
    WebP load/save with libwebp                   : YES
    PDF load with poppler-glib                    : YES (dynamic module: NO)
    SVG load with librsvg-2.0                     : YES
    EXR load with OpenEXR                         : YES
    WSI load with OpenSlide                       : NO (dynamic module: NO)
    Matlab load with Matio                        : NO
    NIfTI load/save with libnifti                 : NO
    FITS load/save with cfitsio                   : NO
    GIF save with cgif                            : NO
    Magick load/save with MagickCore              : YES (dynamic module: NO)  

  User defined options
    buildtype                                     : release
    deprecated                                    : false
    introspection                                 : disabled
    jpeg                                          : enabled
    jpeg-xl                                       : enabled
    libdir                                        : lib
    modules                                       : disabled
    png                                           : enabled
    prefix                                        : /usr/local
    tiff                                          : disabled  

Found ninja-1.11.1.git.kitware.jobserver-1 at /Users/z/.local/share/mise/installs/python/3.12.7/bin/ninja
+ cd build-dir
+ ninja
ninja: no work to do.
+ sudo ninja install
[0/1] Installing files.
Installing libvips/include/vips/enumtypes.h to /usr/local/include/vips
Installing libvips/libvips.42.dylib to /usr/local/lib
Installing cplusplus/libvips-cpp.42.dylib to /usr/local/lib
Installing po/de/LC_MESSAGES/vips8.17.mo to /usr/local/share/locale/de/LC_MESSAGES
Installing po/en_GB/LC_MESSAGES/vips8.17.mo to /usr/local/share/locale/en_GB/LC_MESSAGES
Installing tools/vips to /usr/local/bin
Installing tools/vipsedit to /usr/local/bin
Installing tools/vipsthumbnail to /usr/local/bin
Installing tools/vipsheader to /usr/local/bin
Installing /private/tmp/libvips/libvips/include/vips/buf.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/connection.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/dbuf.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/debug.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/format.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/gate.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/generate.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/private.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/sbuf.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/semaphore.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/thread.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/threadpool.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/transform.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/util.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/vector.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/arithmetic.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/basic.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/colour.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/conversion.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/convolution.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/create.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/draw.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/error.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/foreign.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/freqfilt.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/header.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/histogram.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/image.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/interpolate.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/memory.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/morphology.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/mosaicing.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/object.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/operation.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/rect.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/region.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/resample.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/type.h to /usr/local/include/vips
Installing /private/tmp/libvips/libvips/include/vips/vips.h to /usr/local/include/vips
Installing /private/tmp/libvips/cplusplus/include/vips/VError8.h to /usr/local/include/vips
Installing /private/tmp/libvips/cplusplus/include/vips/VImage8.h to /usr/local/include/vips
Installing /private/tmp/libvips/cplusplus/include/vips/VInterpolate8.h to /usr/local/include/vips
Installing /private/tmp/libvips/cplusplus/include/vips/VRegion8.h to /usr/local/include/vips
Installing /private/tmp/libvips/cplusplus/include/vips/VConnection8.h to /usr/local/include/vips
Installing /private/tmp/libvips/cplusplus/include/vips/vips8 to /usr/local/include/vips
Installing /private/tmp/libvips/man/vipsedit.1 to /usr/local/share/man/man1
Installing /private/tmp/libvips/man/vipsheader.1 to /usr/local/share/man/man1
Installing /private/tmp/libvips/man/vips.1 to /usr/local/share/man/man1
Installing /private/tmp/libvips/man/vipsprofile.1 to /usr/local/share/man/man1
Installing /private/tmp/libvips/man/vipsthumbnail.1 to /usr/local/share/man/man1
Installing /private/tmp/libvips/build-dir/libvips/include/vips/version.h to /usr/local/include/vips
Installing /private/tmp/libvips/build-dir/meson-private/vips.pc to /usr/local/lib/pkgconfig
Installing /private/tmp/libvips/build-dir/meson-private/vips-cpp.pc to /usr/local/lib/pkgconfig
Installing /private/tmp/libvips/tools/vipsprofile to /usr/local/bin
Installing symlink pointing to libvips.42.dylib to /usr/local/lib/libvips.dylib
Installing symlink pointing to libvips-cpp.42.dylib to /usr/local/lib/libvips-cpp.dylib
+ cd /Users/z/git/flux
+ export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib:/usr/local/lib
+ LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib:/usr/local/lib
+ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:
+ PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:
+ npm install --verbose --foreground-scripts sharp --build-from-source
npm verbose cli /Users/z/.local/share/mise/installs/node/22.3.0/bin/node /Users/z/.local/share/mise/installs/node/22.3.0/lib/node_modules/npm/bin/npm-cli.js
npm info using npm@10.8.1
npm info using node@v22.3.0
npm verbose title npm install sharp
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp" "--build-from-source"
npm verbose logfile logs-max:10 dir:/Users/z/.npm/_logs/2024-11-17T20_10_08_634Z-
npm verbose logfile /Users/z/.npm/_logs/2024-11-17T20_10_08_634Z-debug-0.log
npm verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/tslib
npm http fetch GET 200 https://registry.npmjs.org/sharp 15ms (cache hit)
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-win32-x64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-win32-ia32
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-wasm32
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@emnapi/runtime
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/tslib
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-linuxmusl-x64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-linuxmusl-arm64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-linux-x64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-linux-s390x
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-linux-arm64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-linux-arm
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-linux-x64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-linux-s390x
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-linux-arm64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-linux-arm
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-libvips-darwin-x64
npm verbose reify failed optional dependency /Users/z/git/flux/node_modules/@img/sharp-darwin-x64
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 3545ms  

up to date, audited 163 packages in 4s  

25 packages are looking for funding
  run `npm fund` for details  

found 0 vulnerabilities
npm verbose cwd /Users/z/git/flux
npm verbose os Darwin 23.6.0
npm verbose node v22.3.0
npm verbose npm  v10.8.1
npm verbose exit 0
npm info ok
  
```.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#building-from-source

What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

**Comment by i18nsite** [comment]
```
npm verbose cli /Users/z/.local/share/mise/installs/node/22.3.0/bin/node /Users/z/.local/share/mise/installs/node/22.3.0/lib/node_modules/npm/bin/npm-cli.js
npm info using npm@10.8.1
npm info using node@v22.3.0
npm verbose title npm install sharp
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verbose logfile logs-max:10 dir:/Users/z/.npm/_logs/2024-11-18T02_43_25_517Z-
npm verbose logfile /Users/z/.npm/_logs/2024-11-18T02_43_25_517Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 14ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tslib 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 1ms (cache hit)
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-win32-x64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-win32-ia32
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-wasm32
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@emnapi/runtime
npm verbose reify failed optional dependency /private/tmp/test/node_modules/tslib
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-linuxmusl-x64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-linuxmusl-arm64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-linux-x64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-linux-s390x
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-linux-arm64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-linux-arm
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-linux-x64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-linux-s390x
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-linux-arm64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-linux-arm
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-libvips-darwin-x64
npm verbose reify failed optional dependency /private/tmp/test/node_modules/@img/sharp-darwin-x64
npm info run sharp@0.33.5 install node_modules/sharp node install/check

> sharp@0.33.5 install
> node install/check

sharp: Detected globally-installed libvips v8.17.0
sharp: Attempting to build from source via node-gyp
sharp: Please add node-addon-api to your dependencies
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 960ms
npm info run sharp@0.33.5 install { code: 0, signal: null }

added 11 packages, and audited 12 packages in 4s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm verbose cwd /private/tmp/test
npm verbose os Darwin 23.6.0
npm verbose node v22.3.0
npm verbose npm  v10.8.1
npm verbose exit 0
npm info ok
```

```

/private/tmp/test/node_modules/sharp/lib/output.js:163
  const stack = Error();
                ^

Error: VipsOperation: class "jxlsave_buffer" not found
    at Sharp.toBuffer (/private/tmp/test/node_modules/sharp/lib/output.js:163:17)
    at file:///private/tmp/test/test.js:9:53
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5)

Node.js v22.3.0
```

**Comment by lovell** [comment]
Thank you, the salient part of the output you've provided is:

> sharp: Detected globally-installed libvips v8.17.0
> sharp: Attempting to build from source via node-gyp
> sharp: Please add node-addon-api to your dependencies

Please see https://sharp.pixelplumbing.com/install#building-from-source for the complete list of dependencies you will need to provide in order to build sharp from source.

**Comment by i18nsite** [comment]
fixed , thanks


  export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
  export SHARP_FORCE_GLOBAL_LIBVIPS=1
  npm install --verbose --foreground-scripts --save node-addon-api node-gyp sharp --build-from-source
