### ISSUE TITLE
Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by Ararat-Bakaryan** [lovell/sharp#4278]
#### Description
When running the application, encountering a fatal error preventing the Sharp module from loading on Linux x64 platform. The error occurs in the main process and appears to be related to dynamic module loading configuration in Rollup.

#### Error Message
```
Error: Could not load the "sharp" module using the linux-x64 runtime
```

Multiple failed require attempts:
- `../src/build/Release/sharp-linux-x64.node`
- `../src/build/Release/sharp-wasm32.node`
- `@img/sharp-linux-x64/sharp.node`
- `@img/sharp-wasm32/sharp.node`

#### Environment
- **Platform**: Linux x64
- **Application**: electron-unique
- **Location**: `/usr/lib/electron-uniq/resources/app.asar/.vite/build/main.js`

Additional warning observed:
```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

#### Attempted Solutions
None yet, but Sharp's documentation suggests:
1. Installing optional dependencies:
   ```bash
   npm install --include=optional sharp
   ```
2. Using platform-specific installation:
   ```bash
   npm install --os=linux --cpu=x64 sharp
   ```

**Comment by Ararat-Bakaryan** [comment]
After building the app using electron-forge and vite-plugin, I am getting this issue when launching the app, please help resolve the problem!

**Comment by jigyar2001** [comment]
I have the same problem, too. How can I solve the problem?

**Comment by lovell** [comment]
> building the app using electron-forge and vite-plugin

https://github.com/lovell/sharp/blob/hat/docs/install.md#electron
https://github.com/lovell/sharp/blob/hat/docs/install.md#vite

**Comment by Narek02161** [comment]
> > building the app using electron-forge and vite-plugin
> 
> https://github.com/lovell/sharp/blob/hat/docs/install.md#electron https://github.com/lovell/sharp/blob/hat/docs/install.md#vite

I followed the instructions and now I get this: Error: Could not load the "sharp" module using the linux-x64 runtime

**Comment by Narek02161** [comment]
## Full log

```
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/lib/dolphin-uniq/resources/app.asar/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/lib/dolphin-uniq/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
```

**Comment by Narek02161** [comment]
Using official electron-forge documentation for configuration: https://www.electronforge.io/config/plugins/vite

**Comment by jigyar2001** [comment]
> > building the app using electron-forge and vite-plugin
> 
> https://github.com/lovell/sharp/blob/hat/docs/install.md#electron https://github.com/lovell/sharp/blob/hat/docs/install.md#vite

I followed the instructions and now I get this: Error: Could not load the "sharp" module using the linux-x64 runtime

**Comment by jigyar2001** [comment]
> > > building the app using electron-forge and vite-plugin
> > 
> > 
> > https://github.com/lovell/sharp/blob/hat/docs/install.md#electron https://github.com/lovell/sharp/blob/hat/docs/install.md#vite
> 
> I followed the instructions and now I get this: Error: Could not load the "sharp" module using the linux-x64 runtime

**Full log**

Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/lib/electron-uniq/resources/app.asar/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/lib/electron-uniq/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)

**Comment by jigyar2001** [comment]
**Full log**

Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/lib/electron-uniq/resources/app.asar/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/lib/electron-uniq/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)

**Comment by jigyar2001** [comment]
Using official electron-forge documentation for configuration: https://www.electronforge.io/config/plugins/vite

**Comment by Ararat-Bakaryan** [comment]
Hi @lovell thanks for the quick reply! Unfortunately the problem remains do you have any suggestions?

**Comment by lovell** [comment]
If you're using electron-forge, watch out for https://github.com/electron/forge/issues/1250

If you're still having problems, please provide a minimal, complete, standalone repo that allows someone else to reproduce.

**Comment by Ararat-Bakaryan** [comment]
@lovell Thank you very much for your answer, I have already changed the build to electron-builder and everything is working.
