### ISSUE TITLE
Error: Image input not supported, even though i am giving image/jpeg file

### ISSUE THREAD

**Issue by Saurabh9678** [lovell/sharp#4285]
### What are you trying to achieve?
I am trying to implement sharp on my backend system, when i want to create thumbnail for images [jpeg, jpg,png]
I will be attaching the code section below, i have used mime-type to verify my file, mime lookup gives value of image/jpeg
and the file exist for sure. but still its giving me image input not supported, what is the possible issue?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
 
                    await sharp(filePath).resize(200, 200).toFile(thumbnailPath,(err,info)=>{
                        if(err){
                            console.log("Error in generating thumbnail",err);
                        }else{
                            console.log("Thumbnail generated successfully",info);
                            thumbnailgenerated = true;
                             }
                        }
                    );

**Comment by Saurabh9678** [comment]
![Uploading Screenshot 2024-11-26 at 7.12.20 PM.png…]()

**Comment by Saurabh9678** [comment]
Error in generating thumbnail Error: Input file contains unsupported image format
    at Sharp.toFile (/Users/saurabh/Desktop/daakia-backend-nodejs/node_modules/sharp/lib/output.js:90:19)
    at uploadChatAttachmentFileToAzure (/Users/saurabh/Desktop/daakia-backend-nodejs/middlewares/uploadToAzure.js:153:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Middleware_Common_Object.<anonymous> (/Users/saurabh/Desktop/daakia-backend-nodejs/middlewares/uploadToAzure.js:233:30)
    
    
    this is the error i am getting, what are the possible reasons?
and how to debug?

**Comment by QAtestingin** [comment]
Facing same issue.

**Comment by lovell** [comment]
> uploadChatAttachmentFileToAzure

Please ensure there are no networking-related errors or race conditions in your code. If you're still having problems, please provide a sample image that allows someone else to consistently reproduce.

**Comment by lovell** [comment]
@Saurabh9678 Were you able to make any progress with this? If you still require help, please provide the requested information.

**Comment by lovell** [comment]
Closing due to inactivity but please feel free to reopen with the requested details if further help is required.
