### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by geobalas** [lovell/sharp#468]
I am getting a "Module version mismatch" error when I am starting the server.
I tried removing sharp from node_modules, and re-adding it, but nothing changed. Also I tried npm rebuild.

node 6.2.1
npm 3.9.5
sharp 0.15.0

The error:

module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path_to_project/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path_to_project/controller.js:4:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path_to_project/app.js:54:15)
    at Module._compile (module.js:413:34)

**Comment by lovell** [comment]
Hello, the "module version mismatch" error usually occurs when `npm install` was run using a different version of node than that used at runtime.

**Comment by geobalas** [comment]
That is correct, it was my fault. I ran it using the same version of node as when it was installed and I got no errors. Thank you!

**Comment by idw111** [comment]
Do I have to reinstall sharp if I change my node version?
Thank you.

**Comment by lovell** [comment]
@idw111 When the major version of node is chaged, `npm install` is required to ensure all native modules (not just sharp) are compiled against the correct ABI - see https://nodejs.org/en/download/releases/#ref-1
