### ISSUE TITLE
libglib-2.0 not defined with link time references

### ISSUE THREAD

**Issue by Chrisponch** [lovell/sharp#493]
Hi! 
I was building a backup node server to work paralell to the production branch, later is working perfectly 
and when I try to start the local server this error show up 
I'm using ubuntu 14.04, sharp 2.15.8 & 4.4.7

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /var/repo/ponch-api/node_modules/sharp/build/Release/../../lib/libgio-2.0.so.0: symbol g_option_group_unref, version libglib-2.0.so.0 not defined in file libglib-2.0.so.0 with link time reference
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/repo/ponch-api/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/repo/ponch-api/server/controllers/site.js:10:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/repo/ponch-api/server/api/routes/user.js:6:22)
    at Module._compile (module.js:409:26)
```
Hope you can help me with this 
[sharp-ver-log.txt](https://github.com/lovell/sharp/files/348828/sharp-ver-log.txt)

**Comment by lovell** [comment]
Hello, does `ponch-api` also depend on `node-canvas`? If so, please see #371 for various suggestions.

**Comment by Chrisponch** [comment]
Hi lovell, i was able to get it working, I just did the pre-install process, the error stop and everything seems to work fine.

```
# WARNING: This script is deprecated. You probably don't need to run it. Please read above.
curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
```

thanks!

**Comment by lovell** [comment]
The **deprecated** preinstall script will globally install libvips and its dependencies, so both `sharp` and `canvas` end up using the same `glib` version. You should probably work out how to do this with your own environment rather than relying on calling a script that is no longer maintained - although feel free to copy the salient parts of it :)
