### ISSUE TITLE
Node-gyp fails on Ubuntu

### ISSUE THREAD

**Issue by herkyl** [lovell/sharp#527]
I'm trying to install Sharp on Ubuntu 14.04. Node v6.2.2.

I get this error:

```
Error: not found: make
...
Failed at the sharp@0.15.1 install script 'node-gyp rebuild'
```

I have tried adding `--unsafe-perm` but that didn't help.

Here is the log:

```
➜  api git:(master) sudo npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@3.9.5
npm info using node@v6.2.2
npm verb request uri https://registry.npmjs.org/sharp
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:03 PM
npm verb request id 2423c33d220e05b3
npm verb etag "E6OIRD6131WMUIUH5LYXTBW64"
npm http request GET https://registry.npmjs.org/sharp
npm http 304 https://registry.npmjs.org/sharp
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:03 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"E6OIRD6131WMUIUH5LYXTBW64"',
npm verb headers   age: '168',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-atl6230-ATL',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1469469183.603741,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/sharp from cache
npm verb get saving sharp to /home/app/.npm/registry.npmjs.org/sharp/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb cache add spec sharp@^0.15.1
npm verb addNamed ">=0.15.1 <0.16.0" is a valid semver range for sharp
npm verb addNameRange registry:https://registry.npmjs.org/sharp not in flight; fetching
npm verb get https://registry.npmjs.org/sharp not expired, no request
npm verb addNamed "0.15.1" is a plain semver version for sharp
npm verb afterAdd /home/app/.npm/sharp/0.15.1/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/sharp/0.15.1/package/package.json written
npm verb request uri https://registry.npmjs.org/color
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "7M55ZF3DZ22IU7IWLYGPR9A14"
npm http request GET https://registry.npmjs.org/color
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "2E1V908MEG33STFNV1760SLVP"
npm http request GET https://registry.npmjs.org/nan
npm verb request uri https://registry.npmjs.org/semver
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "4JWD7E8YC630VDRV5KTAN4J0Q"
npm http request GET https://registry.npmjs.org/semver
npm verb request uri https://registry.npmjs.org/request
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "8FB05PIQR4Q5W8KXYHG1UFYLD"
npm http request GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/color
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"7M55ZF3DZ22IU7IWLYGPR9A14"',
npm verb headers   age: '297',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-atl6230-ATL',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1469469184.411030,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/color from cache
npm verb get saving color to /home/app/.npm/registry.npmjs.org/color/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb cache add spec color@^0.11.3
npm verb addNamed ">=0.11.3 <0.12.0" is a valid semver range for color
npm verb addNameRange registry:https://registry.npmjs.org/color not in flight; fetching
npm http 304 https://registry.npmjs.org/nan
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"2E1V908MEG33STFNV1760SLVP"',
npm verb headers   age: '254',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2133-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '5',
npm verb headers   'x-timer': 'S1469469184.444478,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /home/app/.npm/registry.npmjs.org/nan/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm http 304 https://registry.npmjs.org/semver
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"4JWD7E8YC630VDRV5KTAN4J0Q"',
npm verb headers   age: '300',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2645-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '10',
npm verb headers   'x-timer': 'S1469469184.455516,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/semver from cache
npm verb get saving semver to /home/app/.npm/registry.npmjs.org/semver/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm http 304 https://registry.npmjs.org/request
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"8FB05PIQR4Q5W8KXYHG1UFYLD"',
npm verb headers   age: '59',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2623-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1469469184.458036,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/request from cache
npm verb get saving request to /home/app/.npm/registry.npmjs.org/request/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb get https://registry.npmjs.org/color not expired, no request
npm verb addNamed "0.11.3" is a plain semver version for color
npm verb cache add spec nan@^2.4.0
npm verb addNamed ">=2.4.0 <3.0.0" is a valid semver range for nan
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb cache add spec semver@^5.2.0
npm verb addNamed ">=5.2.0 <6.0.0" is a valid semver range for semver
npm verb addNameRange registry:https://registry.npmjs.org/semver not in flight; fetching
npm verb cache add spec request@^2.73.0
npm verb addNamed ">=2.73.0 <3.0.0" is a valid semver range for request
npm verb addNameRange registry:https://registry.npmjs.org/request not in flight; fetching
npm verb afterAdd /home/app/.npm/color/0.11.3/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb get https://registry.npmjs.org/nan not expired, no request
npm verb addNamed "2.4.0" is a plain semver version for nan
npm verb get https://registry.npmjs.org/semver not expired, no request
npm verb addNamed "5.3.0" is a plain semver version for semver
npm verb get https://registry.npmjs.org/request not expired, no request
npm verb addNamed "2.74.0" is a plain semver version for request
npm verb afterAdd /home/app/.npm/color/0.11.3/package/package.json written
npm verb afterAdd /home/app/.npm/nan/2.4.0/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/request/2.74.0/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/semver/5.3.0/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/nan/2.4.0/package/package.json written
npm verb afterAdd /home/app/.npm/request/2.74.0/package/package.json written
npm verb afterAdd /home/app/.npm/semver/5.3.0/package/package.json written
npm verb request uri https://registry.npmjs.org/clone
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "90QASS0T33UPPO253JZ799622"
npm http request GET https://registry.npmjs.org/clone
npm verb request uri https://registry.npmjs.org/color-convert
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "93P4AUJLHETWWM2OHSIR6BDFK"
npm http request GET https://registry.npmjs.org/color-convert
npm verb request uri https://registry.npmjs.org/color-string
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "4LQ4H8ANU0KIESMY9BMG9A0NY"
npm http request GET https://registry.npmjs.org/color-string
npm http 304 https://registry.npmjs.org/color-convert
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"93P4AUJLHETWWM2OHSIR6BDFK"',
npm verb headers   age: '172',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2133-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1469469184.759120,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/color-convert from cache
npm verb get saving color-convert to /home/app/.npm/registry.npmjs.org/color-convert/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm http 304 https://registry.npmjs.org/color-string
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"4LQ4H8ANU0KIESMY9BMG9A0NY"',
npm verb headers   age: '7',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2645-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1469469184.758980,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/color-string from cache
npm verb get saving color-string to /home/app/.npm/registry.npmjs.org/color-string/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm http 304 https://registry.npmjs.org/clone
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"90QASS0T33UPPO253JZ799622"',
npm verb headers   age: '128',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-atl6230-ATL',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1469469184.769476,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/clone from cache
npm verb get saving clone to /home/app/.npm/registry.npmjs.org/clone/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb cache add spec color-convert@^1.3.0
npm verb addNamed ">=1.3.0 <2.0.0" is a valid semver range for color-convert
npm verb addNameRange registry:https://registry.npmjs.org/color-convert not in flight; fetching
npm verb cache add spec color-string@^0.3.0
npm verb addNamed ">=0.3.0 <0.4.0" is a valid semver range for color-string
npm verb addNameRange registry:https://registry.npmjs.org/color-string not in flight; fetching
npm verb cache add spec clone@^1.0.2
npm verb addNamed ">=1.0.2 <2.0.0" is a valid semver range for clone
npm verb addNameRange registry:https://registry.npmjs.org/clone not in flight; fetching
npm verb get https://registry.npmjs.org/color-convert not expired, no request
npm verb addNamed "1.3.1" is a plain semver version for color-convert
npm verb get https://registry.npmjs.org/color-string not expired, no request
npm verb addNamed "0.3.0" is a plain semver version for color-string
npm verb get https://registry.npmjs.org/clone not expired, no request
npm verb addNamed "1.0.2" is a plain semver version for clone
npm verb afterAdd /home/app/.npm/color-convert/1.3.1/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/color-string/0.3.0/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/clone/1.0.2/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/color-convert/1.3.1/package/package.json written
npm verb afterAdd /home/app/.npm/color-string/0.3.0/package/package.json written
npm verb afterAdd /home/app/.npm/clone/1.0.2/package/package.json written
npm verb request uri https://registry.npmjs.org/color-name
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:04 PM
npm verb etag "9XAYPUAP978784IWZSSO4BOH6"
npm http request GET https://registry.npmjs.org/color-name
npm http 304 https://registry.npmjs.org/color-name
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:04 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"9XAYPUAP978784IWZSSO4BOH6"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2623-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1469469184.935489,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/color-name from cache
npm verb get saving color-name to /home/app/.npm/registry.npmjs.org/color-name/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb cache add spec color-name@^1.0.0
npm verb addNamed ">=1.0.0 <2.0.0" is a valid semver range for color-name
npm verb addNameRange registry:https://registry.npmjs.org/color-name not in flight; fetching
npm verb get https://registry.npmjs.org/color-name not expired, no request
npm verb addNamed "1.1.1" is a plain semver version for color-name
npm verb afterAdd /home/app/.npm/color-name/1.1.1/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/color-name/1.1.1/package/package.json written
npm verb request uri https://registry.npmjs.org/tough-cookie
npm verb request no auth needed
npm info attempt registry request try #1 at 1:53:05 PM
npm verb etag "EWMR67V8Y6CMLDH7G88TR6SIB"
npm http request GET https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/tough-cookie
npm verb headers { date: 'Mon, 25 Jul 2016 17:53:05 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"EWMR67V8Y6CMLDH7G88TR6SIB"',
npm verb headers   age: '194',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2133-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '4',
npm verb headers   'x-timer': 'S1469469185.028576,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/tough-cookie from cache
npm verb get saving tough-cookie to /home/app/.npm/registry.npmjs.org/tough-cookie/.cache.json
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb cache add spec tough-cookie@~2.3.0
npm verb addNamed ">=2.3.0 <2.4.0" is a valid semver range for tough-cookie
npm verb addNameRange registry:https://registry.npmjs.org/tough-cookie not in flight; fetching
npm verb get https://registry.npmjs.org/tough-cookie not expired, no request
npm verb addNamed "2.3.0" is a plain semver version for tough-cookie
npm verb afterAdd /home/app/.npm/tough-cookie/2.3.0/package/package.json not in flight; writing
npm verb correctMkdir /home/app/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/app/.npm/tough-cookie/2.3.0/package/package.json written
npm verb correctMkdir /home/app/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/app/.npm/_locks/staging-302d375d1cc73f48.lock for /home/app/api/node_modules/.staging
npm verb unbuild node_modules/.staging/clone-afcec25e
npm verb unbuild node_modules/.staging/color-convert-be55926e
npm verb unbuild node_modules/.staging/color-name-3621b6c3
npm verb unbuild node_modules/.staging/color-string-9a369deb
npm verb unbuild node_modules/.staging/color-aad0c55f
npm verb unbuild node_modules/.staging/nan-9f562cce
npm verb unbuild node_modules/.staging/tough-cookie-784f361f
npm verb unbuild node_modules/.staging/request-7bdfb2d3
npm verb unbuild node_modules/.staging/sharp-180a923b
npm verb unbuild node_modules/.staging/semver-bb5a4b86
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/clone-afcec25e
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-convert-be55926e
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-name-3621b6c3
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-string-9a369deb
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-aad0c55f
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/nan-9f562cce
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/tough-cookie-784f361f
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/request-7bdfb2d3
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/sharp-180a923b
npm verb tar unpack /home/app/.npm/clone/1.0.2/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/clone-afcec25e
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/clone-afcec25e
npm verb tar unpack /home/app/.npm/color-convert/1.3.1/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/color-convert-be55926e
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-convert-be55926e
npm verb tar unpack /home/app/.npm/color-name/1.1.1/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/color-name-3621b6c3
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-name-3621b6c3
npm verb tar unpack /home/app/.npm/color-string/0.3.0/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/color-string-9a369deb
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-string-9a369deb
npm verb tar unpack /home/app/.npm/color/0.11.3/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/color-aad0c55f
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-aad0c55f
npm verb tar unpack /home/app/.npm/nan/2.4.0/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/nan-9f562cce
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/nan-9f562cce
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/semver-bb5a4b86
npm verb tar unpack /home/app/.npm/tough-cookie/2.3.0/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/tough-cookie-784f361f
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/tough-cookie-784f361f
npm verb tar unpack /home/app/.npm/request/2.74.0/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/request-7bdfb2d3
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/request-7bdfb2d3
npm verb tar unpack /home/app/.npm/sharp/0.15.1/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/sharp-180a923b
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/sharp-180a923b
npm verb tar unpack /home/app/.npm/semver/5.3.0/package.tgz
npm verb tar unpacking to /home/app/api/node_modules/.staging/semver-bb5a4b86
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/semver-bb5a4b86
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-name-3621b6c3/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-aad0c55f/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-string-9a369deb/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/semver-bb5a4b86/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/color-convert-be55926e/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/clone-afcec25e/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/tough-cookie-784f361f/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/request-7bdfb2d3/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/nan-9f562cce/node_modules
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/.staging/sharp-180a923b/node_modules
npm info lifecycle clone@1.0.2~preinstall: clone@1.0.2
npm info lifecycle color-convert@1.3.1~preinstall: color-convert@1.3.1
npm info lifecycle color-name@1.1.1~preinstall: color-name@1.1.1
npm info lifecycle color-string@0.3.0~preinstall: color-string@0.3.0
npm info lifecycle color@0.11.3~preinstall: color@0.11.3
npm info lifecycle nan@2.4.0~preinstall: nan@2.4.0
npm info lifecycle semver@5.3.0~preinstall: semver@5.3.0
npm info lifecycle tough-cookie@2.3.0~preinstall: tough-cookie@2.3.0
npm info lifecycle request@2.74.0~preinstall: request@2.74.0
npm info lifecycle sharp@0.15.1~preinstall: sharp@0.15.1
npm info linkStuff clone@1.0.2
npm verb linkBins clone@1.0.2
npm verb linkMans clone@1.0.2
npm info linkStuff color-convert@1.3.1
npm verb linkBins color-convert@1.3.1
npm verb linkMans color-convert@1.3.1
npm info linkStuff color-name@1.1.1
npm verb linkBins color-name@1.1.1
npm verb linkMans color-name@1.1.1
npm info linkStuff color-string@0.3.0
npm verb linkBins color-string@0.3.0
npm verb linkMans color-string@0.3.0
npm info linkStuff color@0.11.3
npm verb linkBins color@0.11.3
npm verb linkMans color@0.11.3
npm info linkStuff nan@2.4.0
npm verb linkBins nan@2.4.0
npm verb linkMans nan@2.4.0
npm info linkStuff semver@5.3.0
npm verb linkBins semver@5.3.0
npm verb link bins [ { semver: './bin/semver' },
npm verb link bins   '/home/app/api/node_modules/sharp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans semver@5.3.0
npm verb gentlyRm don't care about contents; nuking /home/app/api/node_modules/sharp/node_modules/.bin/semver
npm info linkStuff tough-cookie@2.3.0
npm verb linkBins tough-cookie@2.3.0
npm verb linkMans tough-cookie@2.3.0
npm info linkStuff request@2.74.0
npm verb linkBins request@2.74.0
npm verb linkMans request@2.74.0
npm info linkStuff sharp@0.15.1
npm verb linkBins sharp@0.15.1
npm verb linkMans sharp@0.15.1
npm info lifecycle clone@1.0.2~install: clone@1.0.2
npm info lifecycle color-convert@1.3.1~install: color-convert@1.3.1
npm info lifecycle color-name@1.1.1~install: color-name@1.1.1
npm info lifecycle color-string@0.3.0~install: color-string@0.3.0
npm info lifecycle color@0.11.3~install: color@0.11.3
npm info lifecycle nan@2.4.0~install: nan@2.4.0
npm info lifecycle semver@5.3.0~install: semver@5.3.0
npm info lifecycle tough-cookie@2.3.0~install: tough-cookie@2.3.0
npm info lifecycle request@2.74.0~install: request@2.74.0
npm info lifecycle sharp@0.15.1~install: sharp@0.15.1

> sharp@0.15.1 install /home/app/api/node_modules/sharp
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/nodejs',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.3.1
gyp info using node@6.2.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.2.2
gyp verb command install [ '6.2.2' ]
gyp verb install input version string "6.2.2"
gyp verb install installing version: 6.2.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.2.2
gyp verb build dir attempting to create "build" dir: /home/app/api/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/app/api/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/app/api/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/app/api/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/app/api/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/app/api/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/app/.node-gyp/6.2.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/app/.node-gyp/6.2.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/app/api/node_modules/sharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/app/.node-gyp/6.2.2
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Linux 4.4.0-28-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/app/api/node_modules/sharp
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm verb lifecycle sharp@0.15.1~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.15.1~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/app/api/node_modules/sharp/node_modules/.bin:/home/app/api/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.15.1~install: CWD: /home/app/api/node_modules/sharp
npm info lifecycle sharp@0.15.1~install: Failed to exec install script
npm verb unlock done using /home/app/.npm/_locks/staging-302d375d1cc73f48.lock for /home/app/api/node_modules/.staging
npm verb stack Error: sharp@0.15.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid sharp@0.15.1
npm verb cwd /home/app/api
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--verbose" "sharp"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.15.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.15.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/app/api/npm-debug.log
```

**Comment by herkyl** [comment]
I was missing build essentials.

`sudo apt-get install build-essential`
