### ISSUE TITLE
node-gpy install error

### ISSUE THREAD

**Issue by natural-law** [lovell/sharp#551]
I have this issue when I try to install sharp package:
```
> npm install sharp --verbose
...
gyp verb get node dir target node version installed: 6.4.0
gyp verb build dir attempting to create "build" dir: /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/cocos2d-x/.node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cocos2d-x/.node/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cocos2d-x/.node-gyp/6.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/cocos2d-x/.node-gyp/6.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/cocos2d-x/.node/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Although Homebrew has added initial recognition of 10.11, it is unsupported.
You may encounter breakage or other failure and there is no guarantee
Homebrew can resolve those issues until El Capitan is stable.

gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/cocos2d-x/.node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/cocos2d-x/.node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm verb lifecycle sharp@0.16.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.16.0~install: PATH: /Users/cocos2d-x/.node/lib/node_modules/npm/bin/node-gyp-bin:/Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp/node_modules/.bin:/Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/.bin:/Applications/Cocos/Cocos2d-x:/Users/cocos2d-x/.node/bin:/Users/cocos2d-x/MyWork/cocos2d-x/cocos2d-x/templates:/Applications/Cocos/frameworks:/usr/local/bin:/Users/cocos2d-x/MyWork/cocos2d-x/cocos2d-x/tools/cocos2d-console/bin:/Users/cocos2d-x/MyWork/android/sdk/tools:/Users/cocos2d-x/MyWork/android/sdk/platform-tools:/Users/cocos2d-x/MyWork/android/sdk:/Users/cocos2d-x/MyWork/android/android-ndk-r10c:/Users/cocos2d-x/MyWork/tools/repo-tools:/Users/cocos2d-x/MyWork/tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin:/Users/cocos2d-x/MyWork/tizen-sdk/tools/ide/bin
npm verb lifecycle sharp@0.16.0~install: CWD: /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/sharp
npm info lifecycle sharp@0.16.0~install: Failed to exec install script
npm verb unlock done using /Users/cocos2d-x/.npm/_locks/staging-d3233f4567d35fae.lock for /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/.staging
custom-protocol@1.0.0 /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol
└── bcrypt@0.8.7  extraneous

npm WARN custom-protocol@1.0.0 No description
npm WARN custom-protocol@1.0.0 No repository field.
npm WARN custom-protocol@1.0.0 No license field.
npm verb stack Error: sharp@0.16.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/cocos2d-x/.node/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/cocos2d-x/.node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid sharp@0.16.0
npm verb cwd /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/cocos2d-x/.node/bin/npm" "install" "sharp" "--verbose"
npm ERR! node v6.4.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.16.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/npm-debug.log
```

Also I found [this issue](https://github.com/lovell/sharp/issues/163). And I've test installing `bcrypt`. It's all right. The log is:
```
(node:83066) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> bcrypt@0.8.7 install /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
custom-protocol@1.0.0 /Users/cocos2d-x/MyWork/cocos-creator-repos/cocos-creator-stable/editor-framework/example-apps/custom-protocol
└── bcrypt@0.8.7  extraneous
```

Could you please give me some help? Thanks very much!

**Comment by voidstarfire** [comment]
Have the exact same issue; have been Googling for about 5 hours today trying to resolve the issue.

So far no good.

**Comment by teaspoon** [comment]
Any solution to the above error?

**Comment by lovell** [comment]
@natural-law Please try `xcode-select --install` and/or `brew update && brew upgrade`

@voidstarfire The salient part of the *different* error you are experiencing is `g++: internal compiler error: Killed (program cc1plus)`, which looks like possible memory exhaustion. Running `dmesg` after the failure will confirm/deny this.

**Comment by voidstarfire** [comment]
I'm running with 2GB's free on the server.
I decided to go with GM as it just worked off the bat with NPM install & now it's in production so I can't have any more input sorry.

**Comment by natural-law** [comment]
> Please try xcode-select --install and/or brew update && brew upgrade

@lovell Thanks for your reply! I just tried your suggestion, but it's not work. I've solved the problem by **Uninstall Homebrew**. Maybe it's a compatibility problem of Homebrew on Mac OX 10.11.

After all, thanks for your help!

**Comment by lovell** [comment]
@natural-law Great to hear you got it working, thanks for the update.

@teaspoon Were you able to make any progress?

**Comment by thatcort** [comment]
I also get a node-gyp build error and am unable to install.

I'm running Windows 10 64-bit with windows-build-tools installed.

```
>npm install sharp --save

> sharp@0.16.0 install C:\Users\brian\Dropbox\projects\sketchGit\express\node_modules\sharp
> node-gyp rebuild


C:\Users\brian\Dropbox\projects\sketchGit\express\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\brian\AppData\Roaming\nvm\v6.5.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.c
C:\Users\brian\AppData\Roaming\nvm\v6.5.0\node_modules\npm\node_modules\node-gy
p\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefiniti
on; different type modifiers [C:\Users\brian\Dropbox\projects\sketchGit\express
\node_modules\sharp\build\libvips-cpp.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\brian\AppData\Roaming\nvm\v6.5.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\brian\\AppData\\Roaming\\nvm\\v6.5.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\brian\Dropbox\projects\sketchGit\express\node_modules\sharp
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp" "--save"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.16.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\brian\Dropbox\projects\sketchGit\express\npm-debug.log
```

Any suggestions for how to fix this?

**Comment by lovell** [comment]
@thatcort `npm -g install npm@latest` - see https://github.com/nodejs/node-gyp/issues/972
