### ISSUE TITLE
Won't install (because of dependency build error ?) under Mac OS X (10.11.6) using node v6.8.1

### ISSUE THREAD

**Issue by Jan0707** [lovell/sharp#604]
```
npm install --save sharp --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   'sharp',
npm verb cli   '--verbose' ]
npm info using npm@3.10.8
npm info using node@v6.8.1
npm verb request uri https://registry.npmjs.org/sharp
npm verb request no auth needed
npm info attempt registry request try #1 at 16:57:40
npm verb request id 2234d63b5e92d166
npm verb etag "85JNEOK8I1H0JKN9VUGJYSVSO"
npm http request GET https://registry.npmjs.org/sharp
npm http 304 https://registry.npmjs.org/sharp
npm verb headers { date: 'Sun, 16 Oct 2016 14:57:42 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"85JNEOK8I1H0JKN9VUGJYSVSO"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-fra1236-FRA',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1476629862.950576,VS0,VE106',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/sharp from cache
npm verb get saving sharp to /Users/jangregortriebel/.npm/registry.npmjs.org/sharp/.cache.json
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb cache add spec sharp
npm verb addNamed "latest" is being treated as a dist-tag for sharp
npm info addNameTag [ 'sharp', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/sharp not in flight; fetching
npm verb get https://registry.npmjs.org/sharp not expired, no request
npm verb addNamed "0.16.1" is a plain semver version for sharp
npm verb afterAdd /Users/jangregortriebel/.npm/sharp/0.16.1/package/package.json not in flight; writing
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/jangregortriebel/.npm/sharp/0.16.1/package/package.json written
npm verb request uri https://registry.npmjs.org/color
npm verb request no auth needed
npm info attempt registry request try #1 at 16:57:44
npm verb etag "A5PSLGYHQ31D8JUZUY6NZ7PZ6"
npm http request GET https://registry.npmjs.org/color
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 16:57:44
npm verb etag "1YJEPM5V4XH0MZT0HV3B8R9BB"
npm http request GET https://registry.npmjs.org/nan
npm verb request uri https://registry.npmjs.org/bluebird
npm verb request no auth needed
npm info attempt registry request try #1 at 16:57:44
npm verb etag "D2W27RRRKU4N4YK4UN61LP0OG"
npm http request GET https://registry.npmjs.org/bluebird
npm verb request uri https://registry.npmjs.org/semver
npm verb request no auth needed
npm info attempt registry request try #1 at 16:57:44
npm verb etag "4FOCBW9AO6QXP00NXYDE4LR4Z"
npm http request GET https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/nan
npm verb headers { date: 'Sun, 16 Oct 2016 14:57:44 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"1YJEPM5V4XH0MZT0HV3B8R9BB"',
npm verb headers   age: '231',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-fra1231-FRA',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '4',
npm verb headers   'x-timer': 'S1476629864.979246,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /Users/jangregortriebel/.npm/registry.npmjs.org/nan/.cache.json
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm http 304 https://registry.npmjs.org/bluebird
npm verb headers { date: 'Sun, 16 Oct 2016 14:57:44 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"D2W27RRRKU4N4YK4UN61LP0OG"',
npm verb headers   age: '293',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-fra1230-FRA',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '5',
npm verb headers   'x-timer': 'S1476629864.990077,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/bluebird from cache
npm verb get saving bluebird to /Users/jangregortriebel/.npm/registry.npmjs.org/bluebird/.cache.json
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm http 304 https://registry.npmjs.org/semver
npm verb headers { date: 'Sun, 16 Oct 2016 14:57:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"4FOCBW9AO6QXP00NXYDE4LR4Z"',
npm verb headers   age: '126',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-fra1231-FRA',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1476629865.005408,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/semver from cache
npm verb get saving semver to /Users/jangregortriebel/.npm/registry.npmjs.org/semver/.cache.json
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb cache add spec nan@^2.4.0
npm verb addNamed ">=2.4.0 <3.0.0" is a valid semver range for nan
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb cache add spec semver@^5.3.0
npm verb addNamed ">=5.3.0 <6.0.0" is a valid semver range for semver
npm verb addNameRange registry:https://registry.npmjs.org/semver not in flight; fetching
npm verb cache add spec bluebird@^3.4.6
npm verb addNamed ">=3.4.6 <4.0.0" is a valid semver range for bluebird
npm verb addNameRange registry:https://registry.npmjs.org/bluebird not in flight; fetching
npm verb get https://registry.npmjs.org/semver not expired, no request
npm verb addNamed "5.3.0" is a plain semver version for semver
npm verb get https://registry.npmjs.org/nan not expired, no request
npm verb addNamed "2.4.0" is a plain semver version for nan
npm verb get https://registry.npmjs.org/bluebird not expired, no request
npm verb addNamed "3.4.6" is a plain semver version for bluebird
npm verb afterAdd /Users/jangregortriebel/.npm/nan/2.4.0/package/package.json not in flight; writing
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/jangregortriebel/.npm/semver/5.3.0/package/package.json not in flight; writing
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/jangregortriebel/.npm/bluebird/3.4.6/package/package.json not in flight; writing
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/jangregortriebel/.npm/nan/2.4.0/package/package.json written
npm verb afterAdd /Users/jangregortriebel/.npm/bluebird/3.4.6/package/package.json written
npm verb afterAdd /Users/jangregortriebel/.npm/semver/5.3.0/package/package.json written
npm http 304 https://registry.npmjs.org/color
npm verb headers { date: 'Sun, 16 Oct 2016 14:57:44 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"A5PSLGYHQ31D8JUZUY6NZ7PZ6"',
npm verb headers   age: '137',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-fra1236-FRA',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1476629864.261211,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/color from cache
npm verb get saving color to /Users/jangregortriebel/.npm/registry.npmjs.org/color/.cache.json
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb cache add spec color@^0.11.3
npm verb addNamed ">=0.11.3 <0.12.0" is a valid semver range for color
npm verb addNameRange registry:https://registry.npmjs.org/color not in flight; fetching
npm verb get https://registry.npmjs.org/color not expired, no request
npm verb addNamed "0.11.3" is a plain semver version for color
npm verb afterAdd /Users/jangregortriebel/.npm/color/0.11.3/package/package.json not in flight; writing
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/jangregortriebel/.npm/color/0.11.3/package/package.json written
npm verb request uri https://registry.npmjs.org/color-convert
npm verb request no auth needed
npm info attempt registry request try #1 at 16:57:45
npm verb etag "5MITL66SF4YPVNA59FY90UW2L"
npm http request GET https://registry.npmjs.org/color-convert
npm http 304 https://registry.npmjs.org/color-convert
npm verb headers { date: 'Sun, 16 Oct 2016 14:57:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"5MITL66SF4YPVNA59FY90UW2L"',
npm verb headers   age: '290',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-fra1231-FRA',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1476629865.754066,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/color-convert from cache
npm verb get saving color-convert to /Users/jangregortriebel/.npm/registry.npmjs.org/color-convert/.cache.json
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb cache add spec color-convert@^1.3.0
npm verb addNamed ">=1.3.0 <2.0.0" is a valid semver range for color-convert
npm verb addNameRange registry:https://registry.npmjs.org/color-convert not in flight; fetching
npm verb get https://registry.npmjs.org/color-convert not expired, no request
npm verb addNamed "1.5.0" is a plain semver version for color-convert
npm verb afterAdd /Users/jangregortriebel/.npm/color-convert/1.5.0/package/package.json not in flight; writing
npm verb correctMkdir /Users/jangregortriebel/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/jangregortriebel/.npm/color-convert/1.5.0/package/package.json written
npm verb correctMkdir /Users/jangregortriebel/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/jangregortriebel/.npm/_locks/staging-27d8d7c6a5cb57a7.lock for /Users/jangregortriebel/Projects/assag/node_modules/.staging
npm verb unbuild node_modules/.staging/color-convert-090c91b8
npm verb unbuild node_modules/.staging/nan-23411156
npm verb unbuild node_modules/.staging/bluebird-1e152755
npm verb unbuild node_modules/.staging/color-952f06ca
npm verb unbuild node_modules/.staging/sharp-2d5b5790
npm verb unbuild node_modules/.staging/semver-59fb8dfd
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-convert-090c91b8
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/nan-23411156
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/bluebird-1e152755
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-952f06ca
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/sharp-2d5b5790
npm verb tar unpack /Users/jangregortriebel/.npm/color-convert/1.5.0/package.tgz
npm verb tar unpacking to /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-convert-090c91b8
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-convert-090c91b8
npm verb tar unpack /Users/jangregortriebel/.npm/nan/2.4.0/package.tgz
npm verb tar unpacking to /Users/jangregortriebel/Projects/assag/node_modules/.staging/nan-23411156
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/nan-23411156
npm verb tar unpack /Users/jangregortriebel/.npm/bluebird/3.4.6/package.tgz
npm verb tar unpacking to /Users/jangregortriebel/Projects/assag/node_modules/.staging/bluebird-1e152755
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/bluebird-1e152755
npm verb tar unpack /Users/jangregortriebel/.npm/color/0.11.3/package.tgz
npm verb tar unpacking to /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-952f06ca
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-952f06ca
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/semver-59fb8dfd
npm verb tar unpack /Users/jangregortriebel/.npm/sharp/0.16.1/package.tgz
npm verb tar unpacking to /Users/jangregortriebel/Projects/assag/node_modules/.staging/sharp-2d5b5790
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/sharp-2d5b5790
npm verb tar unpack /Users/jangregortriebel/.npm/semver/5.3.0/package.tgz
npm verb tar unpacking to /Users/jangregortriebel/Projects/assag/node_modules/.staging/semver-59fb8dfd
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/semver-59fb8dfd
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-952f06ca/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/semver-59fb8dfd/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/color-convert-090c91b8/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/sharp-2d5b5790/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/nan-23411156/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/.staging/bluebird-1e152755/node_modules
npm info lifecycle color-convert@1.5.0~preinstall: color-convert@1.5.0
npm info lifecycle nan@2.4.0~preinstall: nan@2.4.0
npm info lifecycle bluebird@3.4.6~preinstall: bluebird@3.4.6
npm info lifecycle color@0.11.3~preinstall: color@0.11.3
npm info lifecycle semver@5.3.0~preinstall: semver@5.3.0
npm info lifecycle sharp@0.16.1~preinstall: sharp@0.16.1
npm info linkStuff color-convert@1.5.0
npm verb linkBins color-convert@1.5.0
npm verb linkMans color-convert@1.5.0
npm info linkStuff nan@2.4.0
npm verb linkBins nan@2.4.0
npm verb linkMans nan@2.4.0
npm info linkStuff bluebird@3.4.6
npm verb linkBins bluebird@3.4.6
npm verb linkMans bluebird@3.4.6
npm info linkStuff color@0.11.3
npm verb linkBins color@0.11.3
npm verb linkMans color@0.11.3
npm info linkStuff semver@5.3.0
npm verb linkBins semver@5.3.0
npm verb link bins [ { semver: './bin/semver' },
npm verb link bins   '/Users/jangregortriebel/Projects/assag/node_modules/sharp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans semver@5.3.0
npm verb gentlyRm don't care about contents; nuking /Users/jangregortriebel/Projects/assag/node_modules/sharp/node_modules/.bin/semver
npm info linkStuff sharp@0.16.1
npm verb linkBins sharp@0.16.1
npm verb linkMans sharp@0.16.1
npm info lifecycle color-convert@1.5.0~install: color-convert@1.5.0
npm info lifecycle nan@2.4.0~install: nan@2.4.0
npm info lifecycle bluebird@3.4.6~install: bluebird@3.4.6
npm info lifecycle color@0.11.3~install: color@0.11.3
npm info lifecycle semver@5.3.0~install: semver@5.3.0
npm info lifecycle sharp@0.16.1~install: sharp@0.16.1

> sharp@0.16.1 install /Users/jangregortriebel/Projects/assag/node_modules/sharp
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.8.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.8.1
gyp verb command install [ '6.8.1' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'block-stream'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:469:15)
gyp ERR! stack     at Function.Module._load (module.js:417:25)
gyp ERR! stack     at Module.require (module.js:497:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/entry-writer.js:7:19)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jangregortriebel/Projects/assag/node_modules/sharp
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm verb lifecycle sharp@0.16.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.16.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jangregortriebel/Projects/assag/node_modules/sharp/node_modules/.bin:/Users/jangregortriebel/Projects/assag/node_modules/.bin:/Users/jangregortriebel/.swiftenv/shims:/Users/jangregortriebel/.swiftenv/bin:/Users/jangregortriebel/.composer/vendor/bin:/Applications/MAMP/bin/php/php5.6.10/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Tomb:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Volumes/SecureNifty/Go/bin
npm verb lifecycle sharp@0.16.1~install: CWD: /Users/jangregortriebel/Projects/assag/node_modules/sharp
npm info lifecycle sharp@0.16.1~install: Failed to exec install script
npm verb unlock done using /Users/jangregortriebel/.npm/_locks/staging-27d8d7c6a5cb57a7.lock for /Users/jangregortriebel/Projects/assag/node_modules/.staging
npm WARN AssAg@0.1.0 No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN AssAg@0.1.0 No license field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb stack Error: sharp@0.16.1 install: `node-gyp rebuild`
npm verb stack Exit status 7
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid sharp@0.16.1
npm verb cwd /Users/jangregortriebel/Projects/assag
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "sharp" "--verbose"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sharp@0.16.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jangregortriebel/Projects/assag/npm-debug.log
```

**Comment by lovell** [comment]
Hello, this looks like a local environment problem with the installation of npm on this machine rather than a problem specific to this module.
```
gyp ERR! stack Error: Cannot find module 'block-stream'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:469:15)
gyp ERR! stack     at Function.Module._load (module.js:417:25)
gyp ERR! stack     at Module.require (module.js:497:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/entry-writer.js:7:19)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jangregortriebel/Projects/assag/node_modules/sharp
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
```
Re-installing `npm` will probably fix this, perhaps via something like `npm install -g npm`

**Comment by Jan0707** [comment]
Wow, thanks @lovell ! Reinstalling npm did the trick. Now I feel bad for opening the issue here...
