### ISSUE TITLE
node-gyp rebuild error on macOS and Linux docker

### ISSUE THREAD

**Issue by HawkinsZhao** [lovell/sharp#611]
Hello guys, I got a weird error.

``` 
> sharp@0.16.2 install /Users/hawkins/Desktop/4-m/docker/4mdevstudio/4mdevstudio/node_modules/sharp
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  TOUCH Release/obj.target/libvips-cpp.stamp
/Users/hawkins/Desktop/4-m/docker/4mdevstudio/4mdevstudio/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/hawkins/Desktop/4-m/docker/4mdevstudio/4mdevstudio/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/libvips-cpp.stamp] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hawkins/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/hawkins/.nvm/versions/node/v6.5.0/bin/node" "/Users/hawkins/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hawkins/Desktop/4-m/docker/4mdevstudio/4mdevstudio/node_modules/sharp
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN node-js-getting-started@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/hawkins/.nvm/versions/node/v6.5.0/bin/node" "/Users/hawkins/.nvm/versions/node/v6.5.0/bin/npm" "install" "sharp"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hawkins/Desktop/4-m/docker/4mdevstudio/4mdevstudio/npm-debug.log
```

Is that something wrong with sharp or touch?

**Comment by lovell** [comment]
It's a problem with the `touch` module; there are lots of examples of this https://github.com/search?l=JavaScript&q=touch+%22syntax+error+near+unexpected+token%22&type=Issues&utf8=%E2%9C%93

https://github.com/node-inspector/node-inspector/issues/760
https://github.com/kelektiv/node.bcrypt.js/issues/367
https://github.com/nodejs/node-gyp/issues/795
https://github.com/websockets/bufferutil/issues/29
