### ISSUE TITLE
win10 64 build  error!

### ISSUE THREAD

**Issue by hpze2000** [lovell/sharp#635]
Environment setup and configuration:
`npm install -g windows-build-tools`

```
> sharp@0.16.2 install E:\nodejs\test\node_modules\sharp
> node-gyp rebuild


E:\nodejs\test\node_modules\sharp>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): error C2664: 'char *strpbrk(char *const ,
const char *const )': cannot convert argument 1 from 'const char *' to 'char *const ' (compiling source file D:\Program
 Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): note: Conversion loses qualifiers (comp
  iling source file D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc)
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): error C2664: 'char *strpbrk(char *const ,
const char *const )': cannot convert argument 1 from 'const char *' to 'char *const ' (compiling source file ..\src\lib
vips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxproj]
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): note: Conversion loses qualifiers (comp
  iling source file ..\src\libvips\cplusplus\VInterpolate.cpp)
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): error C2664: 'char *strpbrk(char *const ,
const char *const )': cannot convert argument 1 from 'const char *' to 'char *const ' (compiling source file ..\src\lib
vips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxproj]
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): note: Conversion loses qualifiers (comp
  iling source file ..\src\libvips\cplusplus\VError.cpp)
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): error C2664: 'char *strpbrk(char *const ,
const char *const )': cannot convert argument 1 from 'const char *' to 'char *const ' (compiling source file ..\src\lib
vips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxproj]
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): note: Conversion loses qualifiers (comp
  iling source file ..\src\libvips\cplusplus\VImage.cpp)
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(20): error C2039: 'strcmp': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(20): error C2039: 'strcmp': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(20): error C2039: 'strcmp': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(20): error C2873: 'strcmp': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules
\sharp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(20): error C2873: 'strcmp': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp
\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(20): error C2873: 'strcmp': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp
\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(21): error C2039: 'strcspn': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sha
rp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(21): error C2039: 'strcspn': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(21): error C2039: 'strcspn': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(21): error C2873: 'strcspn': symbol cannot be us
ed in a using-declaration (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_module
s\sharp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(21): error C2873: 'strcspn': symbol cannot be us
ed in a using-declaration (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(21): error C2873: 'strcspn': symbol cannot be us
ed in a using-declaration (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(22): error C2039: 'strlen': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(22): error C2039: 'strlen': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(22): error C2039: 'strlen': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(22): error C2873: 'strlen': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules
\sharp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(22): error C2873: 'strlen': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp
\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(22): error C2873: 'strlen': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp
\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(23): error C2039: 'strncmp': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sha
rp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(23): error C2039: 'strncmp': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(23): error C2039: 'strncmp': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(23): error C2873: 'strncmp': symbol cannot be us
ed in a using-declaration (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_module
s\sharp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(23): error C2873: 'strncmp': symbol cannot be us
ed in a using-declaration (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(23): error C2873: 'strncmp': symbol cannot be us
ed in a using-declaration (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(24): error C2039: 'strspn': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(24): error C2039: 'strspn': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(24): error C2039: 'strspn': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(24): error C2873: 'strspn': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules
\sharp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(24): error C2873: 'strspn': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp
\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstring(24): error C2873: 'strspn': symbol cannot be use
d in a using-declaration (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp
\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(524): error C2039: 'strlen': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\shar
p\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(524): error C2039: 'strlen': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(524): error C2039: 'strlen': is not a member of '
`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\buil
d\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(524): error C3861: 'strlen': identifier not found
 (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp
.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(524): error C3861: 'strlen': identifier not found
 (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxpr
oj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(524): error C3861: 'strlen': identifier not found
 (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxpr
oj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(508): error C2039: 'strcmp': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(508): error C2039: 'strcmp': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(508): error C2039: 'strcmp': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sha
rp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(508): error C3861: 'strcmp': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxp
roj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(508): error C3861: 'strcmp': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxp
roj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(508): error C3861: 'strcmp': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cp
p.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(748): error C2039: 'strlen': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(748): error C3861: 'strlen': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxp
roj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(748): error C2039: 'strlen': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(748): error C2039: 'strlen': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sha
rp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(748): error C3861: 'strlen': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxp
roj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(748): error C3861: 'strlen': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cp
p.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(787): error C2039: 'strlen': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(787): error C2039: 'strlen': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sha
rp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(787): error C2039: 'strlen': is not a member of
'`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bui
ld\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(787): error C3861: 'strlen': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxp
roj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(787): error C3861: 'strlen': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cp
p.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(787): error C3861: 'strlen': identifier not foun
d (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcxp
roj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1693): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1693): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1693): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1693): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1693): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sh
arp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1693): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-c
pp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1794): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1794): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1794): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1794): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sh
arp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1794): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1794): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-c
pp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1927): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1927): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1927): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1927): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1927): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sh
arp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(1927): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-c
pp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(2028): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(2028): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VImage.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(2028): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\bu
ild\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(2028): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VError.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-cpp.vcx
proj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(2028): error C2039: 'strlen': is not a member of
 '`global namespace'' (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sh
arp\build\libvips-cpp.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(2028): error C3861: 'strlen': identifier not fou
nd (compiling source file ..\src\libvips\cplusplus\VInterpolate.cpp) [E:\nodejs\test\node_modules\sharp\build\libvips-c
pp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `F:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\nodejs\test\node_modules\sharp
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'E:\nodejs\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "sharp"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodejs\test\npm-debug.log
```

**Comment by lovell** [comment]
The first error looks odd (and it very likely to be the cause of the remaining, cascading errors):

> D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string.h(444): error C2664: 'char *strpbrk(char *const , const char *const )': cannot convert argument 1 from 'const char *' to 'char *const ' (compiling source file D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc)

This suggests Visual Studio cannot compile its own `string.h` header file. This problem is probably a local environment thing rather than specific to sharp.

Does running `npm install --build-from-source bcrypt` fail in a similar manner?

**Comment by lovell** [comment]
@hpze2000 Have you been able to make any progress with this?

**Comment by lovell** [comment]
Closing due to inactivity. Feel free to re-open if help is still required.
