### ISSUE TITLE
32-bit Ubuntu 16.04: "undefined symbol" when loading sharp.node

### ISSUE THREAD

**Issue by sebastien-mignot** [lovell/sharp#649]
Hi,
When I try to require("sharp"), I get the following error : 

```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/sebastien/git/backend/node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZN4vips6VImageixEi
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sebastien/git/backend/node_modules/sharp/index.js:12:13)
```

We are many developpers on the same project, many of which on the same OS as me (ubuntu 16.04), with the same node version (6.6) for everyone. So this is likely to be an annoying configuration bug...

This happens even when I put a simple test.js in my project that only does the require, and run it in command line with node executable. (else it's done in our server that runs with forever)

I saw here https://github.com/lovell/sharp/issues/188 that it could come from a build done with a different version that the one on which it's executed. But I cleaned all the installed versions (I'm using 'n'), removed the -g install of node-gyp (npm remove -g node-gyp), deleted all the node_modules, and made npm install in the project again. It didn't work. I did then a npm rebuild (for good mesure, since re-installing all the modules already did that...), and no more luck.

No luck finding anything on google on this error either.

Any help would be welcome !

**Comment by sebastien-mignot** [comment]
(and I even try after this to install the lastest node 7.2.1 (via n too), and re-did every steps described above, and it didn't work either.

**Comment by lovell** [comment]
Bonsoir, do you have (or have you had) libvips installed on the machine that is failing? What does the following output?

```sh
ldd /home/sebastien/git/backend/node_modules/sharp/build/Release/sharp.node
```

**Comment by sebastien-mignot** [comment]
@lovell Thank's for your help.
Yes, I forgot to say, but I installed libvips, and also the -dev package to be sure to have everything.

Here is the output you asked for : 
```
~/git/backend (master) $ ldd /home/sebastien/git/backend/node_modules/sharp/build/Release/sharp.node
	linux-gate.so.1 =>  (0xb777f000)
	libvips-cpp.so.42 => /usr/lib/i386-linux-gnu/libvips-cpp.so.42 (0xb76fe000)
	libvips.so.42 => /usr/lib/i386-linux-gnu/libvips.so.42 (0xb7359000)
	libgobject-2.0.so.0 => /usr/lib/i386-linux-gnu/libgobject-2.0.so.0 (0xb72f9000)
	libglib-2.0.so.0 => /lib/i386-linux-gnu/libglib-2.0.so.0 (0xb71d0000)
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xb7059000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb7004000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb6fe7000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb6e30000)
	libMagickCore-6.Q16.so.2 => /usr/lib/i386-linux-gnu/libMagickCore-6.Q16.so.2 (0xb6b38000)
	libpng12.so.0 => /lib/i386-linux-gnu/libpng12.so.0 (0xb6b0d000)
	libtiff.so.5 => /usr/lib/i386-linux-gnu/libtiff.so.5 (0xb6a93000)
	libjpeg.so.8 => /usr/lib/i386-linux-gnu/libjpeg.so.8 (0xb6a34000)
	libgmodule-2.0.so.0 => /usr/lib/i386-linux-gnu/libgmodule-2.0.so.0 (0xb6a2e000)
	libpangoft2-1.0.so.0 => /usr/lib/i386-linux-gnu/libpangoft2-1.0.so.0 (0xb6a16000)
	libpango-1.0.so.0 => /usr/lib/i386-linux-gnu/libpango-1.0.so.0 (0xb69c5000)
	libgsf-1.so.114 => /usr/lib/i386-linux-gnu/libgsf-1.so.114 (0xb6979000)
	libxml2.so.2 => /usr/lib/i386-linux-gnu/libxml2.so.2 (0xb679c000)
	libfftw3.so.3 => /usr/lib/i386-linux-gnu/libfftw3.so.3 (0xb65bb000)
	liborc-0.4.so.0 => /usr/lib/i386-linux-gnu/liborc-0.4.so.0 (0xb6528000)
	liblcms2.so.2 => /usr/lib/i386-linux-gnu/liblcms2.so.2 (0xb64c8000)
	libIlmImf-2_2.so.22 => /usr/lib/i386-linux-gnu/libIlmImf-2_2.so.22 (0xb61fa000)
	libopenslide.so.0 => /usr/lib/i386-linux-gnu/libopenslide.so.0 (0xb61ad000)
	libcfitsio.so.2 => /usr/lib/i386-linux-gnu/libcfitsio.so.2 (0xb5fae000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb5f91000)
	libwebp.so.5 => /usr/lib/i386-linux-gnu/libwebp.so.5 (0xb5f2d000)
	libmatio.so.2 => /usr/lib/i386-linux-gnu/libmatio.so.2 (0xb5eea000)
	libexif.so.12 => /usr/lib/i386-linux-gnu/libexif.so.12 (0xb5eb0000)
	libffi.so.6 => /usr/lib/i386-linux-gnu/libffi.so.6 (0xb5ea6000)
	libpcre.so.3 => /lib/i386-linux-gnu/libpcre.so.3 (0xb5e31000)
	/lib/ld-linux.so.2 (0x80035000)
	liblqr-1.so.0 => /usr/lib/i386-linux-gnu/liblqr-1.so.0 (0xb5e1c000)
	libfontconfig.so.1 => /usr/lib/i386-linux-gnu/libfontconfig.so.1 (0xb5dd3000)
	libfreetype.so.6 => /usr/lib/i386-linux-gnu/libfreetype.so.6 (0xb5d23000)
	libXext.so.6 => /usr/lib/i386-linux-gnu/libXext.so.6 (0xb5d0d000)
	libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xb5bc2000)
	libbz2.so.1.0 => /lib/i386-linux-gnu/libbz2.so.1.0 (0xb5bb0000)
	libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb5b95000)
	libltdl.so.7 => /usr/lib/i386-linux-gnu/libltdl.so.7 (0xb5b89000)
	libgomp.so.1 => /usr/lib/i386-linux-gnu/libgomp.so.1 (0xb5b64000)
	liblzma.so.5 => /lib/i386-linux-gnu/liblzma.so.5 (0xb5b3e000)
	libjbig.so.0 => /usr/lib/i386-linux-gnu/libjbig.so.0 (0xb5b2f000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb5b2a000)
	libharfbuzz.so.0 => /usr/lib/i386-linux-gnu/libharfbuzz.so.0 (0xb5ac6000)
	libthai.so.0 => /usr/lib/i386-linux-gnu/libthai.so.0 (0xb5aba000)
	libgio-2.0.so.0 => /usr/lib/i386-linux-gnu/libgio-2.0.so.0 (0xb58f1000)
	libicuuc.so.55 => /usr/lib/i386-linux-gnu/libicuuc.so.55 (0xb575b000)
	libHalf.so.12 => /usr/lib/i386-linux-gnu/libHalf.so.12 (0xb5717000)
	libIex-2_2.so.12 => /usr/lib/i386-linux-gnu/libIex-2_2.so.12 (0xb56fd000)
	libIlmThread-2_2.so.12 => /usr/lib/i386-linux-gnu/libIlmThread-2_2.so.12 (0xb56f5000)
	libcairo.so.2 => /usr/lib/i386-linux-gnu/libcairo.so.2 (0xb55b4000)
	libsqlite3.so.0 => /usr/lib/i386-linux-gnu/libsqlite3.so.0 (0xb54d3000)
	libopenjpeg.so.5 => /usr/lib/i386-linux-gnu/libopenjpeg.so.5 (0xb54ad000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/i386-linux-gnu/libgdk_pixbuf-2.0.so.0 (0xb5484000)
	libhdf5_serial.so.10 => /usr/lib/i386-linux-gnu/libhdf5_serial.so.10 (0xb518d000)
	libexpat.so.1 => /lib/i386-linux-gnu/libexpat.so.1 (0xb5163000)
	libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xb513d000)
	libgraphite2.so.3 => /usr/lib/i386-linux-gnu/libgraphite2.so.3 (0xb5116000)
	libdatrie.so.1 => /usr/lib/i386-linux-gnu/libdatrie.so.1 (0xb510b000)
	libselinux.so.1 => /lib/i386-linux-gnu/libselinux.so.1 (0xb50e5000)
	libresolv.so.2 => /lib/i386-linux-gnu/libresolv.so.2 (0xb50cc000)
	libicudata.so.55 => /usr/lib/i386-linux-gnu/libicudata.so.55 (0xb3814000)
	libpixman-1.so.0 => /usr/lib/i386-linux-gnu/libpixman-1.so.0 (0xb3764000)
	libxcb-shm.so.0 => /usr/lib/i386-linux-gnu/libxcb-shm.so.0 (0xb375f000)
	libxcb-render.so.0 => /usr/lib/i386-linux-gnu/libxcb-render.so.0 (0xb3754000)
	libXrender.so.1 => /usr/lib/i386-linux-gnu/libXrender.so.1 (0xb3748000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb373f000)
	libsz.so.2 => /usr/lib/i386-linux-gnu/libsz.so.2 (0xb373b000)
	libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xb3736000)
	libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xb372f000)
	libaec.so.0 => /usr/lib/i386-linux-gnu/libaec.so.0 (0xb3725000)
~/git/backend (master) $
```

**Comment by lovell** [comment]
`i386-linux-gnu` suggests this is 32-bit machine. Is that correct?

**Comment by sebastien-mignot** [comment]
@lovell Yes it is. It's a rather old machine (6 years), but with a fairly recent ubuntu install.

**Comment by lovell** [comment]
Ubuntu 16.04 provides [libvips-dev](http://packages.ubuntu.com/xenial/libvips-dev) v8.2.2 so you're currently limited to sharp [v0.13.x](http://sharp.dimens.io/en/stable/changelog/#v013-mind) or earlier.

For 32-bit Ubuntu 16.04, I'd suggest removing the prepackaged libvips via apt-get and installing a more recent libvips [from source](https://github.com/jcupitt/libvips#building-libvips-from-a-source-tarball).

**Comment by sebastien-mignot** [comment]
@lovell I installed the last version of libvips from your source, and it worked perfectly !
Thank's a lot for your help.

**Comment by unski11ed** [comment]
I have a smilar problem when launching on 32bit Cent6. I have compiled libvips from the tarball but i think i have some dependencies missing.

Error upon launch:
 ````
Error: /root/app/build/node_modules/sharp/build/Release/sharp.node: undefined s$
mbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoI$
S_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE      
    at Error (native)                                                           
    at Object.Module._extensions..node (module.js:434:18)                       
    at Module.load (module.js:343:32)                                           
    at Function.Module._load (module.js:300:12)                                 
    at Module.require (module.js:353:17)                                        
    at require (internal/module.js:12:17)                                       
    at Object.<anonymous> (/root/app/build/node_modules/sharp/lib/constructor.j$
:9:15)                                                                          
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
````
Output of  `ldd ./app/build/node_modules/sharp/build/Release/sharp.node`:
````
        linux-gate.so.1 =>  (0xb77d4000)                                        
        libvips-cpp.so.42 => /usr/local/lib/libvips-cpp.so.42 (0xb7761000)      
        libvips.so.42 => /usr/local/lib/libvips.so.42 (0xb73dc000)              
        libgobject-2.0.so.0 => /lib/libgobject-2.0.so.0 (0xb738f000)            
        libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xb738a000)            
        librt.so.1 => /lib/librt.so.1 (0xb7380000) 
        libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xb7263000)          [4/1991]
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb7178000)                  
        libm.so.6 => /lib/libm.so.6 (0xb714e000)                                
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb7130000)                        
        libpthread.so.0 => /lib/libpthread.so.0 (0xb7115000)                    
        libc.so.6 => /lib/libc.so.6 (0xb6f7d000)
        libz.so.1 => /lib/libz.so.1 (0xb6f69000)
        libpng12.so.0 => /usr/lib/libpng12.so.0 (0xb6f41000)
        libtiff.so.3 => /usr/lib/libtiff.so.3 (0xb6edf000)
        libjpeg.so.62 => /usr/lib/libjpeg.so.62 (0xb6e88000)
        libgmodule-2.0.so.0 => /lib/libgmodule-2.0.so.0 (0xb6e84000)
        libexpat.so.1 => /lib/libexpat.so.1 (0xb6e5b000)
        liblcms.so.1 => /usr/lib/liblcms.so.1 (0xb6e21000)
        libgif.so.4 => /usr/lib/libgif.so.4 (0xb6e18000)
        libexif.so.12 => /usr/lib/libexif.so.12 (0xb6ddf000)
        /lib/ld-linux.so.2 (0xb77d5000)
        libdl.so.2 => /lib/libdl.so.2 (0xb6dd9000)
        libSM.so.6 => /usr/lib/libSM.so.6 (0xb6dd1000)
        libICE.so.6 => /usr/lib/libICE.so.6 (0xb6db7000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0xb6c7d000)
        libuuid.so.1 => /lib/libuuid.so.1 (0xb6c78000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0xb6c4f000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0xb6c4c000)
````

Any suggestions what am I missing here?

**Comment by lovell** [comment]
@unski11ed `_ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoI$
S_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE` is a (mangled) symbol from Node itself. Perhaps you ran `npm install` on one version of Node and are using another version at runtime? Please open a new issue if you still need help.
