### ISSUE TITLE
Installing with --no-bin-links still creates a sym link

### ISSUE THREAD

**Issue by alexturpin** [lovell/sharp#670]
Hey guys,

I develop on a Linux VM on a Windows host using Vagrant and VirtualBox. Because of a known bug in VirtualBox, symlinks do not work in shared folders. I've tried many workarounds but have resigned myself to not using symlinks. A lot of npm modules of course produce symlinks when installed, particularly to binaries, and I have used the `--no-bin-links` flag to prevent that with great success in the past. Unfortunately, it doesn't seem to be working with sharp. Here is the log output:

```
vagrant@vagrant-app:~/srv/myproject$ npm install --save-dev --no-bin-links sharp

> sharp@0.17.0 install /srv/myproject/node_modules/sharp
> node-gyp rebuild

ERROR: EPROTO: protocol error, symlink 'libpng16/pngconf.h' -> '/srv/myproject/node_modules/sharp/vendor/include/pngconf.h'
gyp: Call to 'LDD_VERSION="ldd (Ubuntu GLIBC 2.23-0ubuntu3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/myproject/node_modules/sharp
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "--no-bin-links" "sharp"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/myproject/npm-debug.log
vagrant@vagrant-app:~/srv/myproject$
```

I understand that the particularities of this project may make what I am asking impossible, but is there any chance that it could install without creating symlinks / respect the `--no-bin-links` flag?

Thanks a lot!

**Comment by lovell** [comment]
Hello, these symlinks are part of the pre-compiled binary tarball containing libvips and its dependencies.

In your case, I'd suggest installing these from source:

http://sharp.dimens.io/en/stable/install/#linux
https://github.com/jcupitt/libvips#building-libvips-from-a-source-tarball

**Comment by alexturpin** [comment]
Thanks!

**Comment by IAkumaI** [comment]
@alexturpin Hi. Did you found any workaround?

**Comment by alexturpin** [comment]
@IAkumaI I believe I didn't end up using Sharp in the end unfortunately

**Comment by IAkumaI** [comment]
Finally, I found solution. Just enable symlinks for shared folders in virtualbox.
I used this answer: https://stackoverflow.com/a/28674584/2026687 and it works.
