### ISSUE TITLE
Cant remove file after transform

### ISSUE THREAD

**Issue by terbooter** [lovell/sharp#693]
My environment
Win 7,  node v6.3.0, npm 4.1.2

Sample code 
```js
let sharp = require("sharp");
let fs = require("fs");

let fromPath = "c:\\unsorted-photos\\P1300375.JPG";
let toPath = "c:\\photos\\2017\\2017_01_30\\P1300375.JPG";

sharp(fromPath)
    .resize(1600)
    .withMetadata()
    .toFile(toPath, (error, info) => {
        if (error) {
            console.log(error);
        } else {
            fs.unlinkSync(fromPath);
        }
    });
```

Got error
```
$ node test.js
vips warning: VipsJpeg: bad exif meta "exif-ifd3-GPSVersionID"
fs.js:1089
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EBUSY: resource busy or locked, unlink 'c:\unsorted-photos\P1300375.JPG'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at sharp.resize.withMetadata.toFile (C:\Work\sort-photos\test.js:14:16)
```
Packages versions are
```
$ npm list
sort-photos@1.0.0 C:\Work\sort-photos
+-- exif@0.6.0
| `-- debug@2.6.0
|   `-- ms@0.7.2
+-- filehound@1.13.0
| +-- bluebird@3.4.7
| +-- lodash@4.17.4
| +-- minimatch@3.0.3
| | `-- brace-expansion@1.1.6
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| `-- unit-compare@1.0.1
+-- mkdirp@0.5.1
| `-- minimist@0.0.8
+-- moment@2.17.1
`-- sharp@0.17.0
  +-- caw@2.0.0
  | +-- get-proxy@1.1.0
  | | `-- rc@1.1.6
  | |   +-- deep-extend@0.4.1
  | |   +-- ini@1.3.4
  | |   +-- minimist@1.2.0
  | |   `-- strip-json-comments@1.0.4
  | `-- tunnel-agent@0.4.3
  +-- color@1.0.3
  | +-- color-convert@1.8.2
  | | `-- color-name@1.1.1
  | `-- color-string@1.4.0
  |   `-- simple-swizzle@0.2.2
  |     `-- is-arrayish@0.3.1
  +-- got@6.7.1
  | +-- create-error-class@3.0.2
  | | `-- capture-stack-trace@1.0.0
  | +-- duplexer3@0.1.4
  | +-- get-stream@3.0.0
  | +-- is-redirect@1.0.0
  | +-- is-retry-allowed@1.1.0
  | +-- is-stream@1.1.0
  | +-- lowercase-keys@1.0.0
  | +-- safe-buffer@5.0.1
  | +-- timed-out@4.0.0
  | +-- unzip-response@2.0.1
  | `-- url-parse-lax@1.0.0
  |   `-- prepend-http@1.0.4
  +-- nan@2.5.0
  +-- semver@5.3.0
  `-- tar@2.2.1
    +-- block-stream@0.0.9
    +-- fstream@1.0.10
    | +-- graceful-fs@4.1.11
    | `-- rimraf@2.5.4
    |   `-- glob@7.1.1
    |     +-- fs.realpath@1.0.0
    |     +-- inflight@1.0.6
    |     | `-- wrappy@1.0.2
    |     +-- once@1.4.0
    |     `-- path-is-absolute@1.0.1
    `-- inherits@2.0.3
```

How can I remove file after transform?

**Comment by lovell** [comment]
Please see #346, #447

**Comment by terbooter** [comment]
Thanks!
```
sharp.cache(false);
```
Solved the problem for me

**Comment by toan12a** [comment]
> Thanks!
> 
> ```
> sharp.cache(false);
> ```
> 
> Solved the problem for me

Help me, where is the "sharp.cache(false);"
