### ISSUE TITLE
Module version mismatch. Expected 47, got 48.

### ISSUE THREAD

**Issue by alanweissman** [lovell/sharp#733]
Thanks for the help - I've seen this issue with other npm libs but haven't been able to resolve by switching around node versions etc. I have tried 6.0-7.7.2. Sharp runs great on my local machine but I get this error every time on AWS instance. 

Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:444:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ec2-user/projects/resizer/node_modules/sharp/lib/constructor.js:8:15)
    at Module._compile (module.js:417:34)
    at Object.Module._extensions..js (module.js:426:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ec2-user/projects/resizer/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:417:34)
    at Object.Module._extensions..js (module.js:426:10)

**Comment by lovell** [comment]
Hello, did you see #468?

**Comment by alanweissman** [comment]
Thanks Lovell my mistake for the dupe I searched earlier but didn't see #468. Appreciate the help!

**Comment by DroidGar** [comment]
same problem to me, npm install doesnt solve the problem, any help?

**Comment by alanweissman** [comment]
Using 'n' and not 'nvm' I was able to update my AWS machine to node 7.6.0, rm -rf node_modules, npm cache clean, npm cache clear, npm install. Make sure node version in /usr/local/bin matches version on command line. Good luck!

**Comment by DroidGar** [comment]
I resolve it by installing 'n', my mistake was install twice node.js to keep same version use command: n 'node_x.x.x' this way you select witch node u want to use (Use the same version of runing node). and problem resolved.

**Comment by lovell** [comment]
Glad to hear you both managed to get the correct version of node installed and working.
