### ISSUE TITLE
npm install --save sharp fails

### ISSUE THREAD

**Issue by jaspersorrio** [lovell/sharp#744]
Same as issue #551
Not able to fix even after following all instructions.
```
Jaspers-MacBook-Pro:yosei-website jasper$ npm install --save sharp

> sharp@0.16.2 install /Users/jasper/Sites/yosei-website/node_modules/sharp
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Unknown option: n
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jasper/.nvm/versions/node/v7.7.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/jasper/.nvm/versions/node/v7.7.4/bin/node" "/Users/jasper/.nvm/versions/node/v7.7.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jasper/Sites/yosei-website/node_modules/sharp
gyp ERR! node -v v7.7.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
npm WARN mpi-website@1.0.0 No description
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jasper/.npm/_logs/2017-03
```

**Comment by jaspersorrio** [comment]
Solved after uninstalling homebrew

**Comment by lovell** [comment]
Glad you got it sorted. I've not seen this error before but as you say, it looks like a corrupt homebrew installation specific to one machine. (When homebrew is installed, sharp uses it as part of a search for a globally-installed libvips, if any.)
