### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 47

### ISSUE THREAD

**Issue by sanmish16** [lovell/sharp#750]
I am geting this error after updating node fro. 5.0.0 to 6.10.0

npm version is 3.10.10

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sandeep/Bluewings/bluewings-pro/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ()
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by xiongjiabin** [comment]
rm node_modules and npm install fixed the problem for me.

**Comment by lovell** [comment]
Please see #468 #733 #740
