### ISSUE TITLE
Unable to install sharp module in ubuntu 32

### ISSUE THREAD

**Issue by bhargavkonkathi** [lovell/sharp#759]
> sharp@0.16.2 install /home/bharagavkonkathi/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server/node_
modules/sharp
> node-gyp rebuild

ERROR: Intel Architecture 32-bit systems require manual installation - please see http://sharp.dimens.io/en/s
table/install/
gyp: Call to 'LDD_VERSION="ldd (Ubuntu EGLIBC 2.19-0ubuntu6) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit
status 1 while in binding.gyp. while trying to load binding.gyp

gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
" "rebuild"
gyp ERR! cwd /home/bharagavkonkathi/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server/node_modules/sh
arp
gyp ERR! node -v v7.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN mocha-mongodb@0.1.2 requires a peer of mocha@* but none was installed.
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by lovell** [comment]
Hello, did you see http://sharp.dimens.io/en/stable/install/#linux ?

> For 32-bit Intel CPUs and older Linux-based operating systems such as Centos 6, it is recommended to install a system-wide installation of libvips from source:
> https://github.com/jcupitt/libvips#building-libvips-from-a-source-tarball

**Comment by bhargavkonkathi** [comment]
Hello lovell, 
I looked into following URL [http://sharp.dimens.io/en/stable/install/#linux](http://sharp.dimens.io/en/stable/install/#linux) but no luck so far. I installed all dependencies that are mentioned in http://sharp.dimens.io/en/stable/install/#linux page. Still i got following errors as follows 

` sharp@0.17.3 install /home/bharagavkonkathi/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/home/bharagavkonkathi/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:20:0:
/home/bharagavkonkathi/.node-gyp/7.7.0/include/node/node.h:44:33: fatal error: tracing/trace_event.h: No such file or directory
 #include "tracing/trace_event.h"
                                 ^
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory `/home/bharagavkonkathi/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bharagavkonkathi/node_modules/sharp
gyp ERR! node -v v7.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/bharagavkonkathi/package.json'
npm WARN bharagavkonkathi No description
npm WARN bharagavkonkathi No repository field.
npm WARN bharagavkonkathi No README data
npm WARN bharagavkonkathi No license field.
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:


`

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/753#issuecomment-291519068

**Comment by bhargavkonkathi** [comment]
Thank you lovell for your comment, I upgraded to latest node version i.e 7.9.0 and npm 4.2.0. Then using `npm install sharp` command I successfully installed sharp module. Following is the output 

`bharagavkonkathi@SDN-256:~/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server$ npm install sharp

> sharp@0.17.3 install /home/bharagavkonkathi/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/home/bharagavkonkathi/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
make: Leaving directory `/home/bharagavkonkathi/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server/node_modules/sharp/build'
/home/bharagavkonkathi/DayUsers/Bhargav/Official/projects/Git/Dymitry/bwt/server
`-- sharp@0.17.3 
  `-- nan@2.6.2 
`

Please Let me know If I installed proper sharp module based on my output. But When I try to upload images which have proper  image format i.e jpeg or jpg , I'm getting following warning and image is not uploading to mentioned path. I don't see any image uploaded to required path. Please suggest where i'm going wrong. Thanks, Bhargav

```
(node:11309) DeprecationWarning: quality: use jpeg({ quality: ... }), webp({ quality: ... }) and/or tiff({ quality:
... }) instead
(node:11309) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Input buffer contains unsupported image format
```

**Comment by lovell** [comment]
Installation looks good. Are you able to share a sample of code that fails?

**Comment by lovell** [comment]
Closing due to inactivity, but please do re-open with a code sample if further help is required.
