### ISSUE TITLE
Get image width and height from stream

### ISSUE THREAD

**Issue by Znarkus** [lovell/sharp#776]
Hi! Thanks for an excellent module!

I'm trying to read image width and height from a stream, but nothing happens.
In the code below nothing is printed to console.
If I remove `.pipe(metaReader)` the response is printed etc.

What am I missing?

```
    const request = require('request')
    const sharp = require('sharp')

    let image

    const metaReader = sharp()
      .on('info', info => {
        image = info
      })
      .on('error', err => {
        console.log(err)
      })

    request
      .get('https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMjM2NTgwNl5BMl5BanBnXkFtZTgwMTUzOTUwMjI@._V1_SX1777_CR0,0,1777,999_AL_.jpg')
      .pipe(metaReader)
      .on('response', function(response) {
        console.log(response) // 200
      })
      .on('error', err => {
        console.log(err)
      })
      .on('end', () => {
        console.log('end')
      })
```

**Comment by lovell** [comment]
Hello, it looks like you're attempting to register the `on` handlers with `sharp` rather than `request`.

Perhaps try the following (untested):

```javascript
    request
      .get('https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMjM2NTgwNl5BMl5BanBnXkFtZTgwMTUzOTUwMjI@._V1_SX1777_CR0,0,1777,999_AL_.jpg')
      .on('response', function(response) {
        console.log(response) // 200
      })
      .on('error', err => {
        console.log(err)
      })
      .on('end', () => {
        console.log('end')
      })
      .pipe(metaReader)
```

**Comment by Znarkus** [comment]
Thanks for the response! Changed the code to this:

```
const request = require('request')
const sharp = require('sharp')

const metaReader = sharp()
  .on('info', info => {
    console.log(info)
  })
  .on('error', err => {
    console.log(err)
  })

request
  .get('https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMjM2NTgwNl5BMl5BanBnXkFtZTgwMTUzOTUwMjI@._V1_SX1777_CR0,0,1777,999_AL_.jpg')
  .on('error', err => {
    console.log(err)
  })
  .on('end', () => {
    console.log('end')
  })
  .pipe(metaReader)
```

Now `end` is printed, but nothing else.

**Comment by lovell** [comment]
You'll need to tell `metaReader` what to do. If you're expecting metadata about the input image then try something like (untested):
```javascript
const metaReader = sharp()
  .metadata()
  .then(info => {
    console.log(info)
  })
  .catch(err => {
    console.log(err)
  })
```

**Comment by Znarkus** [comment]
```
const request = require('request')
const sharp = require('sharp')

const metaReader = sharp()
  .metadata()
  .then(info => {
    console.log(info)
  })

request
  .get('https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMjM2NTgwNl5BMl5BanBnXkFtZTgwMTUzOTUwMjI@._V1_SX1777_CR0,0,1777,999_AL_.jpg')
  .on('error', err => {
    console.log(err)
  })
  .on('end', () => {
    console.log('end')
  })
  .pipe(metaReader)
```

```
$ node test.js
stream.js:45
  dest.on('drain', ondrain);
       ^

TypeError: dest.on is not a function
    at Request.Stream.pipe (stream.js:45:8)
    at Request.pipe (node_modules/request/request.js:1412:34)
```

Sharp is returning a Promise in this instance. 

This issue is not a big problem for me, if can drop it if you'd like.

**Comment by lovell** [comment]
Try:
```javascript
const metaReader = sharp()

metaReader
  .metadata()
  .then(info => {
    console.log(info)
  })
```

**Comment by Znarkus** [comment]
That worked, thanks.

```
end
{ format: 'jpeg',
  width: 1777,
  height: 999,
  space: 'srgb',
  channels: 3,
  hasProfile: false,
  hasAlpha: false }
```

Does Sharp need to download the full image to read dimensions? Or just the first bytes?

**Comment by lovell** [comment]
Sorry, missed your question (too many GH notifications)... you should be able to get away with passing a truncated Buffer with only the header to read image dimensions, but watch out for things like large ICC profiles that can be part of the header. Hope this helps.

**Comment by Znarkus** [comment]
Thanks for excellent support and your time!

**Comment by tomonsoejang** [comment]
@lovell I am trying to upload an image and get the image dimension in Nodejs. How can I assign values of the image dimension to a variable?

```
const metaReader = sharp()
metaReader
  .metadata()
  .then(info => {
    console.log(info)
  })
let metainfo = stream.pipe(metaReader)
```
