### ISSUE TITLE
Problem installing on Windows 10

### ISSUE THREAD

**Issue by luixal** [lovell/sharp#817]
Hi,

When trying to install this module on Windows 10, after installing Python 2.7.x (v3 seems no to be supported) it throws another error about MSBUILD version:

```javascript
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
MSBUILD : error MSB4132: No se reconoce la versión de herramientas "2.0". Las versiones de herramientas disponibles son
 "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\laperez.ACSSYC\AppData\Roaming\nvm\v4.6.2\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\laperez.ACSSYC\\AppData\\Roaming\\nvm\\v4.6.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\laperez.ACSSYC\dev\scripts\node_modules\sharp
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "sharp"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\laperez.ACSSYC\dev\scripts\export-to-word2\npm-debug.log
```

Here's the log file: [npm-debug-log.txt](https://github.com/lovell/sharp/files/1021377/npm-debug-log.txt)

**Comment by lovell** [comment]
Did you see #789?

**Comment by lovell** [comment]
@luixal Have you been able to make any progress with this?

**Comment by luixal** [comment]
Finally went in other direction, but as for comments, it seemed to work installing the windows compilation tools.
