### ISSUE TITLE
ETIMEDOUT install failed on macOS 10.12, nodejs version:7.10.0

### ISSUE THREAD

**Issue by aircloud** [lovell/sharp#827]
install failed, and the console information:

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ETIMEDOUT
gyp ERR! stack     at exports._errnoException (util.js:1050:11)
gyp ERR! stack     at TLSWrap.onread (net.js:582:26)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hh/2017spring/mynpm/img-resize/node_modules/sharp
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN img-resize@0.1.1 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install" "sharp" "--save"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hh/.npm/_logs/2017-05-27T11_55_30_106Z-debug.log
```

Thanks.

**Comment by lovell** [comment]
sharp attempts to download libvips and its dependencies at `npm install` time. The "Error: read ETIMEDOUT" message suggests there is a (temporary) network or firewall connection problem trying to connect to `dl.bintray.com` via HTTPS.
