### ISSUE TITLE
sharp installation returns msg "Failed at the sharp@0.18.1 install script 'node-gyp rebuild'" on Windows7

### ISSUE THREAD

**Issue by SentinelWarren** [lovell/sharp#842]
Hello!
I am getting the following error when trying to install `sharp` on windows 7.
I tried install module `minimatch` & `node-gyp` which installed just fine, but when i tried installing sharp again,the errors still persist.
I have `MSBUILD v2017` `node v6.11.0` & `npm v3.10.10` installed.

```
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.11.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python" in the PATH
gyp verb `which` succeeded C:\Python27\python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned:
 "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.11.0
gyp verb command install [ '6.11.0' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'minimatch'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:469:15)
gyp ERR! stack     at Function.Module._load (module.js:417:25)
gyp ERR! stack     at Module.require (module.js:497:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:
23:17)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\BnB Company\Documents\Projects\SentinelWarren.me\node_modules\sharp
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm verb lifecycle sharp@0.18.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.18.1~install: CWD: C:\Users\BnB Company\Documents\Projects\SentinelWarren.me\node_modules\sha
rp
npm info lifecycle sharp@0.18.1~install: Failed to exec install script
npm verb unlock done using C:\Users\BnB Company\AppData\Roaming\npm-cache\_locks\staging-76fc980bec6e2cf9.lock for C:\Us
ers\BnB Company\Documents\Projects\SentinelWarren.me\node_modules\.staging
npm verb stack Error: sharp@0.18.1 install: `node-gyp rebuild`
npm verb stack Exit status 7
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:891:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid sharp@0.18.1
npm verb cwd C:\Users\BnB Company\Documents\Projects\SentinelWarren.me
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "--verbose" "sharp"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.18.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sharp@0.18.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
```

**Comment by lovell** [comment]
The salient part of the error is `gyp ERR! stack Error: Cannot find module 'minimatch'` when running node-gyp, usually caused by an out of date or incomplete global installation of node-gyp.

It's a common problem, unrelated to sharp, and you should find a solution amongst these:
https://github.com/search?q=%22Cannot+find+module+%27minimatch%27%22&type=Issues&utf8=%E2%9C%93
