### ISSUE TITLE
Vagrant, sudo/root: node-gyp rebuild fails with EACCES

### ISSUE THREAD

**Issue by nanom1t** [lovell/sharp#858]
Hi, I can't install sharp package for my app. I have Node.js v6.11.0, gcc 5.4.0, node-gyp 3.6.2. Also I'm using Vagrant. I can install all other packages, but not sharp. It seems that something wrong with permissions, but I don't know how to fix this issue. Please help me.
```
user@node3-vm:/vagrant$ sudo npm i sharp
> sharp@0.18.1 install /vagrant/node_modules/sharp
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/vagrant/node_modules/sharp/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.4.0-51-generic
gyp ERR! command "/home/user/.nvm/versions/node/v6.11.0/bin/node" "/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/node_modules/sharp
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/user/.nvm/versions/node/v6.11.0/bin/node" "/home/user/.nvm/versions/node/v6.11.0/bin/npm" "i" "sharp"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.18.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```
npm-debug.log:
```
...
3189 silly lifecycle tar@3.1.5~install: no script for install, continuing
3190 silly install sharp@0.18.1 /vagrant/node_modules/.staging/sharp-9f6bc15c
3191 info lifecycle sharp@0.18.1~install: sharp@0.18.1
3192 verbose lifecycle sharp@0.18.1~install: unsafe-perm in lifecycle false
3193 verbose lifecycle sharp@0.18.1~install: PATH: /home/user/.nvm/versions/node/v6.11.0/lib/node_modules/npm/bin/node-gyp-bin:/vagrant/node_modules/sharp/node_modules/.bin:/vagrant/node_modules/.bin:/home/user/.nvm/versions/node/v6.11.0/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
3194 verbose lifecycle sharp@0.18.1~install: CWD: /vagrant/node_modules/sharp
3195 silly lifecycle sharp@0.18.1~install: Args: [ '-c', 'node-gyp rebuild' ]
3196 silly lifecycle sharp@0.18.1~install: Returned: code: 1  signal: null
3197 info lifecycle sharp@0.18.1~install: Failed to exec install script
3198 verbose unlock done using /home/user/.npm/_locks/staging-db29c5a769436947.lock for /vagrant/node_modules/.staging
3199 silly rollbackFailedOptional Starting
3200 silly rollbackFailedOptional Finishing
3201 silly runTopLevelLifecycles Finishing
3202 silly install printInstalled
3203 verbose stack Error: sharp@0.18.1 install: `node-gyp rebuild`
3203 verbose stack Exit status 1
3203 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
3203 verbose stack     at emitTwo (events.js:106:13)
3203 verbose stack     at EventEmitter.emit (events.js:191:7)
3203 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
3203 verbose stack     at emitTwo (events.js:106:13)
3203 verbose stack     at ChildProcess.emit (events.js:191:7)
3203 verbose stack     at maybeClose (internal/child_process.js:891:16)
3203 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
3204 verbose pkgid sharp@0.18.1
3205 verbose cwd /vagrant
3206 error Linux 4.4.0-51-generic
3207 error argv "/home/user/.nvm/versions/node/v6.11.0/bin/node" "/home/user/.nvm/versions/node/v6.11.0/bin/npm" "i" "sharp"
3208 error node v6.11.0
3209 error npm  v3.10.10
3210 error code ELIFECYCLE
3211 error sharp@0.18.1 install: `node-gyp rebuild`
3211 error Exit status 1
3212 error Failed at the sharp@0.18.1 install script 'node-gyp rebuild'.
3212 error Make sure you have the latest version of node.js and npm installed.
3212 error If you do, this is most likely a problem with the sharp package,
3212 error not with npm itself.
3212 error Tell the author that this fails on your system:
3212 error     node-gyp rebuild
3212 error You can get information on how to open an issue for this project with:
3212 error     npm bugs sharp
3212 error Or if that isn't available, you can get their info via:
3212 error     npm owner ls sharp
3212 error There is likely additional logging output above.
3213 verbose exit [ 1, true ]
```
Thanks.

**Comment by nanom1t** [comment]
I've tried to do the same steps from root user. Now I'm getting next error:
```
root@node3-vm:/vagrant# npm i
> sharp@0.18.1 install /vagrant/node_modules/sharp
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/root/.nvm/versions/node/v6.11.0/bin/node" "/root/.nvm/versions/node/v6.11.0/bin/npm" "i"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sharp@0.18.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sharp@0.18.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by lovell** [comment]
Hello, npm's `--unsafe-perm` flag usually "solves" most file permission problems when using sudo/root.
https://docs.npmjs.com/misc/config#unsafe-perm

**Comment by nanom1t** [comment]
Thanks for your response. It is working with `--unsafe-perm` flag now. Is this flag good for security on my production server or should I use it only for Vagrant?

**Comment by lovell** [comment]
Glad to hear you got this working. I strongly recommend you do not use this flag on a production system. Avoid the use of root as much as possible.

**Comment by hsribei** [comment]
Hi! I'm also getting the same problem. Tried running with `--unsafe-perm` but it didn't help.

I'm running node v8.4.0, trying to install sharp@0.18.4.

I'm running without sudo because I used sudo once with npm and it made a mess, had to reinstall everything from scratch. Is `sudo` absolutely necessary here? Thank you!

**Comment by lovell** [comment]
@hsribei Are you using Vagrant?

**Comment by hsribei** [comment]
No, sorry if this is the wrong issue. I'm getting the no permission error on a normal install on macOS. 

I start a blank npm project with `mkdir` and `npm init`, then run `npm install --save sharp` and I see this error:

```
$ npm install --save sharp

> sharp@0.18.4 install /Users/hsribei/tmp/testsharp/node_modules/sharp
> node-gyp rebuild

sh: /usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: Permission denied
npm WARN testsharp@1.0.0 No description
npm WARN testsharp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hsribei/.npm/_logs/2017-09-20T18_41_00_055Z-debug.log
```

**Comment by lovell** [comment]
The `/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: Permission denied` message suggests your local npm/node-gyp installation is broken and the "I used sudo once with npm and it made a mess" comment could well be the reason. This is unlikely to be a problem specific to sharp.

**Comment by lovell** [comment]
@hsribei But good luck sorting this!
