### ISSUE TITLE
Error installing on Windows 10: Error: Cannot find module 'caw'

### ISSUE THREAD

**Issue by normmcgarry** [lovell/sharp#871]
When installing on Windows 10, and the current version of Node 8.7.1 (64-bit), I get the follow error:

```
> sharp@0.17.3 install S:\Repositories\site\node_modules\sharp
> node-gyp rebuild


S:\Repositories\site\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\User\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:487
    throw err;
    ^

Error: Cannot find module 'caw'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (S:\Repositories\Hook\hookllc\site-2017\site\node_modules\sharp\binding.js:8:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

Any ideas?

**Comment by lovell** [comment]
Hello, the `caw` module is listed as [a dependency](https://github.com/lovell/sharp/blob/master/package.json#L70). Perhaps there was a temporary network problem. Please can you provide the output of `npm install --verbose sharp`.

**Comment by lovell** [comment]
@normmcgarry Is this problem still occurring?

**Comment by lovell** [comment]
Closing due to inactivity, please reopen if this problem is still occurring.
