### ISSUE TITLE
Sharp install fails \sharp\build\libvips-cpp.vcxproj" (default targets) -- FAILED.

### ISSUE THREAD

**Issue by sattaman** [lovell/sharp#878]
I've installed python 2.7, windows-build-tools, im on latest node, any pointers as to why it isn't working or what else I can try?

```

> sharp@0.18.2 install C:\VSO Agent Geoff\_work\151\s\node_modules\sharp
> node-gyp rebuild


C:\VSO Agent Geoff\_work\151\s\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 24/07/2017 17:16:03.
Project "C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\binding.sln" (1) is building "C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\libvips-cpp.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\libvips-cpp\".
  Creating directory "Release\obj\libvips-cpp\libvips-cpp.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\libvips-cpp\libvips-cpp.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /I"C:\Users\tom.sanderson\.node-gyp\6.11.1\include\node" /I"C:\Users\tom.sanderson\.node-gyp\6.11.1\src" /I"C:\Users\tom.sanderson\.node-gyp\6.11.1\deps\uv\include" /I"C:\Users\tom.sanderson\.node-gyp\6.11.1\deps\v8\include" /I..\vendor\include /I"..\vendor\include\glib-2.0" /I"..\vendor\lib\glib-2.0\include" /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D "NODE_GYP_MODULE_NAME=libvips-cpp" /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D VIPS_CPLUSPLUS_EXPORTS /D _ALLOW_KEYWORD_MACROS /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\libvips-cpp\\" /Fd"Release\obj\libvips-cpp\vc140.pdb" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /errorReport:queue /MP ..\src\libvips\cplusplus\VError.cpp ..\src\libvips\cplusplus\VInterpolate.cpp ..\src\libvips\cplusplus\VImage.cpp "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\libvips-cpp.vcxproj]
Done Building Project "C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\libvips-cpp.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\binding.sln" (default target) (1) ->
"C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\libvips-cpp.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\VSO Agent Geoff\_work\151\s\node_modules\sharp\build\libvips-cpp.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.86
```

**Comment by lovell** [comment]
Hello, the appearance of the `C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe` path suggests you've got an (old?) installation of Visual Studio 2012 on the same machine that is conflicting with the more recent tooling installed via `windows-build-tools`. Perhaps either uninstall this older version if no longer required or remove any reference to it from `PATH`.

**Comment by lovell** [comment]
@sattaman Were you able to make any progress with this?

**Comment by odahcam** [comment]
I'm using VS2015 and got almost the same error: 

```bash
$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > mocha-webpack@0.7.0" has incorrect peer dependency "webpack@^1.12.13 || ^2.1.0-beta.15".
[4/4] Building fresh packages...
[1/3] ⠂ sharp: not ok
[2/3] ⠂ phantomjs-prebuilt: Done. Phantomjs binary available at C:\Users\67390\Projects\odahcam\zxing-ts\node_m
[3/3] ⠂ uglifyjs-webpack-plugin
[-/3] ⠂ waiting...
error C:\Users\67390\Projects\odahcam\zxing-ts\node_modules\sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\67390\Projects\odahcam\zxing-ts\node_modules\sharp
Output:
C:\Users\67390\Projects\odahcam\zxing-ts\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.3.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\67390\\Projects\\odahcam\\zxing-ts\\node_modules\\sharp\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\67390\\.node-gyp\\8.3.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\67390\\.node-gyp\\8.3.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\67390\\.node-gyp\\8.3.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\67390\\Projects\\odahcam\\zxing-ts\\node_modules\\sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\67390\\Projects\\odahcam\\zxing-ts\\node_modules\\sharp\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". O sistema n�o pode encontrar o arquivo especificado. [C:\Users\67390\Projects\odahcam\zxing-ts\node_modules\sharp\build\libvips-cpp.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\67390\Projects\odahcam\zxing-ts\node_modules\sharp
```
