### ISSUE TITLE
Bintray binaries give 403 forbidden error

### ISSUE THREAD

**Issue by Kansuler** [lovell/sharp#965]
While running npm install --verbose sharp I get 403 forbidden error. It seems like all of the binaries are forbidden: `http://dl.bintray.com/lovell/sharp/`
<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@5.4.2
npm info using node@v8.4.0
npm verb npm-session ff512b8b99d62133
npm http fetch GET 304 https://registry.npmjs.org/sharp 152ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 32ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 86ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 85ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 86ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 28ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 25ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 29ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 29ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fsevents 31ms (from cache)
npm verb correctMkdir /home/kansuler/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/kansuler/.npm/_locks/staging-a0aca838516dc7a5.lock for /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/.staging
npm info lifecycle chownr@1.0.1~preinstall: chownr@1.0.1
npm info lifecycle has-symbol-support-x@1.4.0~preinstall: has-symbol-support-x@1.4.0
npm info lifecycle has-to-string-tag-x@1.4.0~preinstall: has-to-string-tag-x@1.4.0
npm info lifecycle color-string@1.5.2~preinstall: color-string@1.5.2
npm info lifecycle yallist@3.0.2~preinstall: yallist@3.0.2
npm info lifecycle simple-concat@1.0.0~preinstall: simple-concat@1.0.0
npm info lifecycle detect-libc@0.2.0~preinstall: detect-libc@0.2.0
npm info lifecycle color@2.0.0~preinstall: color@2.0.0
npm info lifecycle tar@3.2.1~preinstall: tar@3.2.1
npm info lifecycle simple-get@2.7.0~preinstall: simple-get@2.7.0
npm info lifecycle sharp@0.18.4~preinstall: sharp@0.18.4
npm info linkStuff chownr@1.0.1
npm verb linkBins chownr@1.0.1
npm verb linkMans chownr@1.0.1
npm info linkStuff has-symbol-support-x@1.4.0
npm verb linkBins has-symbol-support-x@1.4.0
npm verb linkMans has-symbol-support-x@1.4.0
npm info linkStuff has-to-string-tag-x@1.4.0
npm verb linkBins has-to-string-tag-x@1.4.0
npm verb linkMans has-to-string-tag-x@1.4.0
npm info linkStuff color-string@1.5.2
npm verb linkBins color-string@1.5.2
npm verb linkMans color-string@1.5.2
npm info linkStuff yallist@3.0.2
npm verb linkBins yallist@3.0.2
npm verb linkMans yallist@3.0.2
npm info linkStuff simple-concat@1.0.0
npm verb linkBins simple-concat@1.0.0
npm verb linkMans simple-concat@1.0.0
npm info linkStuff detect-libc@0.2.0
npm verb linkBins detect-libc@0.2.0
npm verb linkBins [ { 'detect-libc': './bin/detect-libc.js' },
npm verb linkBins   '/home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/.bin',
npm verb linkBins   false ]
npm verb linkMans detect-libc@0.2.0
npm info linkStuff color@2.0.0
npm verb linkBins color@2.0.0
npm verb linkMans color@2.0.0
npm info linkStuff tar@3.2.1
npm verb linkBins tar@3.2.1
npm verb linkMans tar@3.2.1
npm info linkStuff simple-get@2.7.0
npm verb linkBins simple-get@2.7.0
npm verb linkMans simple-get@2.7.0
npm info linkStuff sharp@0.18.4
npm verb linkBins sharp@0.18.4
npm verb linkMans sharp@0.18.4
npm info lifecycle chownr@1.0.1~install: chownr@1.0.1
npm info lifecycle has-symbol-support-x@1.4.0~install: has-symbol-support-x@1.4.0
npm info lifecycle has-to-string-tag-x@1.4.0~install: has-to-string-tag-x@1.4.0
npm info lifecycle color-string@1.5.2~install: color-string@1.5.2
npm info lifecycle yallist@3.0.2~install: yallist@3.0.2
npm info lifecycle simple-concat@1.0.0~install: simple-concat@1.0.0
npm info lifecycle detect-libc@0.2.0~install: detect-libc@0.2.0
npm info lifecycle color@2.0.0~install: color@2.0.0
npm info lifecycle tar@3.2.1~install: tar@3.2.1
npm info lifecycle simple-get@2.7.0~install: simple-get@2.7.0
npm info lifecycle sharp@0.18.4~install: sharp@0.18.4

> sharp@0.18.4 install /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.4.0
gyp verb command install [ '8.4.0' ]
gyp verb install input version string "8.4.0"
gyp verb install installing version: 8.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.4.0
gyp verb build dir attempting to create "build" dir: /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kansuler/.node-gyp/8.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/kansuler/.node-gyp/8.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/kansuler/.node-gyp/8.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz status code 403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm verb lifecycle sharp@0.18.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.18.4~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp/node_modules/.bin:/home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/kansuler/.golibs/bin:/home/kansuler/Workspace/bin:/snap/bin:/usr/local/go/bin:/home/kansuler/.golibs/bin:/usr/local/go/bin:/home/kansuler/.golibs/bin
npm verb lifecycle sharp@0.18.4~install: CWD: /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/sharp
npm info lifecycle sharp@0.18.4~install: Failed to exec install script
npm verb unlock done using /home/kansuler/.npm/_locks/staging-a0aca838516dc7a5.lock for /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017/node_modules/.staging
npm WARN eslint-config-esnext@1.6.0 requires a peer of babel-eslint@~6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-esnext@1.6.0 requires a peer of eslint@~3.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-esnext@1.6.0 requires a peer of eslint-plugin-import@~1.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-node@1.6.0 requires a peer of eslint@~3.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN vcs-sitecore-template-vue@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.18.4 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:927:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid sharp@0.18.4
npm verb cwd /home/kansuler/Workspace/src/bitbucket.org/fbinhouse/volvia-edm-form-q3-2017
npm verb Linux 4.10.0-35-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
npm verb node v8.4.0
npm verb npm  v5.4.2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kansuler/.npm/_logs/2017-09-29T13_52_23_259Z-debug.log
```
</details>

**Comment by Kansuler** [comment]
Duplicate: https://github.com/lovell/sharp/issues/964
