### ISSUE TITLE
No access to libvips-8.5.5-linux-x64.tar.gz file

### ISSUE THREAD

**Issue by angfal** [lovell/sharp#966]
Hi everyone,
Sharp module doesn't build now. I receive the next error. Could you check, please?
```
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz status code 403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/go/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by angfal** [comment]
I going to close it as a duplicate
