### ISSUE TITLE
libvips-8.5.5-darwin-x64.tar.gz - 403 error

### ISSUE THREAD

**Issue by theorise** [lovell/sharp#969]
I am having problems installing this package as a dependency. I get the same error there as I did when running `npm install --verbose sharp`:

```
gyp info spawn args   '-Goutput_dir=.' ]
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-darwin-x64.tar.gz status code 403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/admin/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/admin/.nvm/versions/node/v8.4.0/bin/node" "/Users/admin/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/Sites/test-gatsby/node_modules/sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by DSchau** [comment]
@theorise seems like `https://dl.bintray.com/lovell/sharp/libvips-8.5.5-darwin-x64.tar.gz` might be down or misconfigured? This is _probably_ not an issue with sharp, but who knows! 🤷‍♂️

**Comment by lovell** [comment]
Please see #964
